goreleaser/goreleaser

config/config.go
config/config_test.go
main.go

- tried to make the code more idiomatic and split it in more functions.
- added more tests and remove an unused function

Improve config code

---

glide.lock
glide.yaml
main.go

improved main.go

---

config/config.go
config/config_test.go

added changelog

---

.travis.yml
config/config.go
config/config_test.go
config/git/tag_test.go
pipeline/brew/brew.go
pipeline/compress/compress.go
pipeline/release/release_test.go

gometalinter on CI

---

CODE_OF_CONDUCT.md
README.md

added code of conduct

---

.travis.yml
config/config_test.go
main.go
pipeline/compress/compress.go
pipeline/release/release.go

refs #28 and #29 
not sure this is the right way to fix the `defer x.Close()` issues... I'm basically ignoring the possible errors..

added errcheck

---

CONTRIBUTING.md
README.md

Add a CONTRIBUTING.md doc

---

README.md

I'm not sure if the installation and usage notes I've added are correct, but they worked for me and were missing from the readme.

Installation and usage notes

---

config/config.go
config/config_test.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/compress/compress.go
pipeline/compress/tar/tar.go
pipeline/compress/zip/zip.go
pipeline/release/release.go

Added zip archiving support!
I didn't make a "zip for windows" approach, instead I make it configurable to deliver all packages as zip or tar.gz.
Should fix #45

Zip archiving support

---

README.md
config/config.go
pipeline/build/build.go

customize ldflags

---

pipeline/brew/brew.go

improved create/update formulae logic

---

README.md
config/config.go
pipeline/brew/brew.go

create brew formulae in a subfolder

---

pipeline/release/release.go

update or create release

---

README.md

Might be helpful for anyone new to Homebrew taps.

Link help for creating a Homebrew tap.

---

config/config.go
goreleaser.example.yml
pipeline/brew/brew.go
pipeline/brew/brew_test.go

added brew dependencies support

---

main.go

fixed name on --help

---

pipeline/build/build.go

simplified env for build

---

README.md
config/config.go
pipeline/build/build.go

add support for pre and post hooks on build pipe
closes #13

added hooks support

---

README.md

Link to Slack channel.

---

README.md

We cannot include code here since there are too many different scenarios. A note has to be enough. Closes #92.

Mention single run for CI

---

pipeline/fpm/fpm.go

concurrency fix

---

.travis.yml
pipeline/source/source.go

git status if fail

---

Makefile

make fmt faster

---

README.md
config/config.go
goreleaser.yml
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/fpm/fpm.go

adds conflicts_with for fpm and brew

---

README.md
config/config.go
pipeline/build/build.go

support for custom build flags

---

clients/github.go
context/context.go
glide.lock
glide.yaml
pipeline/brew/brew.go
pipeline/release/release.go

Bump GitHub

---

README.md

fixed readme to download the binary instead of using go get

---

README.md
pipeline/defaults/defaults.go
pipeline/defaults/defaults_test.go

changing default main from main.go to .

---

main.go

closes #135 #134 #132 
Basically, the `--skip-release` flag allows to only build and archive, skipping validations and the upload to github and others.

allow skipping release processes

---

main.go

refs https://github.com/goreleaser/goreleaser/pull/136#issuecomment-284532299

skip the git log/diff as well

---

README.md
config/config.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/defaults/defaults.go
pipeline/defaults/defaults_test.go

Add custom install script with multiple commands support for homebrew formulas

homebrew: add custom install command

---

Makefile

Check https://github.com/dominikh/go-tools/issues/63 for details

increased gometalinter deadline

---

pipeline/build/build.go
pipeline/build/build_test.go

closes https://github.com/goreleaser/goreleaser/issues/142

skip invalid builds

---

Makefile

fixed Makefile source files

---

clients/client.go
clients/client_test.go
clients/github.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/release/release.go
pipeline/release/release_test.go

client interface

---

main.go

refs https://github.com/goreleaser/goreleaser/issues/155

added file and f alias for config

---

main.go
pipeline/build/ldflags.go

fixed ldflags time format

---

context/context.go
context/context_test.go
pipeline/archive/archive.go
pipeline/fpm/fpm.go
pipeline/release/release.go
pipeline/release/release_test.go

refs https://github.com/goreleaser/goreleaser/issues/162

fixed old TODO: artifact list on context

---

client/client.go
client/client_test.go
client/github.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/release/release.go
pipeline/release/release_test.go

All other packages are in the singular form, I guess it makes sense for this one to be singular too.

singularized clients package

---

main.go

fixed config validation

---

context/context.go
main.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/env/env.go
pipeline/env/env_test.go
pipeline/git/git.go
pipeline/git/git_test.go
pipeline/release/release.go
pipeline/release/release_test.go

skip release and skip validations as separated flags

---

pipeline/build/build.go

With many GOOS OARCH combos, the CPU gets glowing.

Reduce the number of concurrent builds

---

pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/env/env.go
pipeline/git/git.go
pipeline/release/release.go

logging the reasons why a pipe is being skipped

---

Makefile

Just spotted a typo and GitHub interface makes such a contribution too easy :)

Fix typo in Makefile comment

---

config/config.go
pipeline/brew/brew.go
pipeline/build/name.go
pipeline/defaults/defaults.go

removed deprecated code

---

README.md
pipeline/build/build.go
pipeline/build/valid_os.go
pipeline/build/valid_os_test.go

refs https://github.com/goreleaser/goreleaser/issues/191
cc/ @bep

removed invalid builds and improved tests

---

README.md
client/github.go
config/config.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go

allowing draft releases

---

.gitignore
.travis.yml
Makefile
README.md
cmd/goreleaser/main.go

switching to codecov

---

pipeline/git/git.go
pipeline/git/git_test.go

fixed first release log

---

README.md
pipeline/build/name.go
pipeline/build/name_test.go

fixed name_template version vs tag issue

---

README.md
config/config.go
pipeline/build/build.go
pipeline/build/build_test.go
pipeline/build/name.go
pipeline/build/name_test.go
pipeline/build/target.go
pipeline/defaults/defaults.go

closes https://github.com/goreleaser/goreleaser/issues/36

added goarch option to build section

---

README.md

Which can lead to some hard-to-debug issues ...
See https://github.com/spf13/hugo/issues/3382

Fix ldflags key name in README

---

README.md
pipeline/build/ldflags.go
pipeline/build/ldflags_test.go

refs https://github.com/goreleaser/goreleaser/pull/223#discussion_r114083461

fixed ldflags tag vs version confusion

---

config/config.go
config/config_test.go

Even added test cases.  No changes to existing functionality.

Add LoadReader function to prevent clients from having to deal with YAML

---

README.md
config/config.go
goreleaser.yml
pipeline/build/build.go
pipeline/build/build_test.go

so users can set custom environment variables :)
Also set CGO_ENABLED=0 for #225

custom env support

---

config/config.go
config/config_test.go

improved config package test coverage

---

README.md
goreleaser.yml
pipeline/defaults/defaults.go
pipeline/defaults/defaults_test.go

check discussion on #236
closes #236

breaking: do not default to uname values

---

README.md
goreleaser.yml
pipeline/build/name_test.go
pipeline/defaults/defaults.go

added version to default name_template

---

README.md

@client9, does this clear things up?

Mention in docs to push the new tag.

---

.travis.yml

Update .travis.yml to use golang 1.8.3

Update .travis.yml to use golang 1.8.3

---

README.md

typo, and fix for travis-ci instructions

---

Gopkg.lock
Gopkg.toml

fixed dep warning

---

pipeline/fpm/fpm.go

Add missing loop variable capture

---

Gopkg.lock
context/context.go
context/context_test.go
goreleaserlib/goreleaser.go
goreleaserlib/goreleaser_test.go
internal/client/github.go
main.go
pipeline/archive/archive.go
pipeline/brew/brew.go
pipeline/build/build.go
pipeline/build/target.go
pipeline/checksums/checksums.go
pipeline/env/env.go
pipeline/fpm/fpm.go
pipeline/git/git.go
pipeline/release/release.go

It now looks like this:
What do you guys think?
ref #263

Added debug and improved logs

---

internal/client/github.go

I created a github account called @goreleaserbot and thought it would be nice to use it to publish formulas et al.
What do you guys think?
Ex: https://github.com/caarlos0/homebrew-tap/blob/master/Formula/test.rb

using a valid email to publish formulas

---

pipeline/release/body.go
pipeline/release/body_test.go

fixed template

---

pipeline/release/release.go

closes https://github.com/goreleaser/goreleaser/issues/279

throttling file uploads

---

context/context.go
goreleaserlib/goreleaser.go
main.go
pipeline/cleandist/dist.go
pipeline/cleandist/dist_test.go

rm dist feature

---

context/context.go
context/context_test.go
pipeline/archive/archive.go
pipeline/archive/archive_test.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/build/build.go
pipeline/build/build_test.go
pipeline/fpm/fpm.go
pipeline/fpm/fpm_test.go

WIP: fixing fpm on multiple naked binaries releases

---

config/config.go
context/context.go
goreleaserlib/goreleaser.go
goreleaserlib/goreleaser_test.go
main.go
pipeline/build/build.go
pipeline/build/build_test.go
pipeline/release/release.go
pipeline/release/release_test.go

allow configuring parallelism via flag

---

.goreleaser.yml
README.md
config/config.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go

homebrew test support

---

pipeline/git/errors.go
pipeline/git/git.go

just cleaning up the main file a bit

moved errors to another file

---

goreleaserlib/goreleaser_test.go
internal/testlib/git.go
internal/testlib/git_test.go
internal/testlib/mktemp.go
internal/testlib/mktemp_test.go
pipeline/archive/archive_test.go
pipeline/git/git_test.go

there are a few repeated blocks of test code across several packages, this meant to decrease that.

Created a testlib

---

.goreleaser.yml
.travis.yml
config/config.go
goreleaserlib/goreleaser.go
pipeline/snapcraft/snapcraft.go
pipeline/snapcraft/snapcraft_test.go

Snapcraft is the new universal and secure package being developed by Ubuntu. It allows upstream developers to push their software to all Linux distros on their own schedule, without intermediaries, and with automatic updates.
https://snapcraft.io/

add the snapcraft pipeline

---

context/context.go

fix for windows

---

README.md

Add the documentation about the snapcraft pipeline

---

pipeline/fpm/fpm.go

This change fixes an error you'll receive if you try building an RPM package on OSX and installing it on linux:
```
rpm is intended for a different operating system
```
From `fpm -h`, you'll see:
```
--rpm-os OS                   (rpm only) The operating system to target this rpm for. You want to set this to 'linux' if you are using fpm on OS X, for example
```
There's probably a more generic way of doing this, but for this use case the patch will work well.

fix RPM cross-compiling (OSX => amazonlinux/CentOS)

---

.goreleaser.yml
.travis.yml
CONTRIBUTING.md
pipeline/fpm/fpm.go
pipeline/fpm/fpm_test.go

it fails on my macOS box, let's try on a linux :)

building rpm packages as well

---

goreleaserlib/goreleaser.go
goreleaserlib/goreleaser_test.go

also accept .yaml files

---

.goreleaser.yml
README.md
config/config.go
internal/name/name.go
internal/name/name_test.go
pipeline/checksums/checksums.go
pipeline/checksums/checksums_test.go
pipeline/defaults/defaults.go

checksums name template support

---

pipeline/archive/archive.go

I recently ran into an issue where one of the glob patterns in my `.goreleaser.yml` file didn't result an any existing files and therefore caused the archive step to fail. Sadly, the error message only said that a file didn't exist but not what file and in what step.
With this PR I've added a couple of more verbose error messages that should help debug these issues in the future :)

Print a more verbose error message if archiving fails

---

docs/000-introduction.md
docs/100-fpm.md
docs/110-snapcraft.md
docs/140-ci.md

fixed links and formatting

---

.goreleaser.yml
.travis.yml
Dockerfile
config/config.go
config/config_test.go
config/testdata/invalid_config.yml
goreleaserlib/goreleaser.go
pipeline/defaults/defaults.go
pipeline/defaults/defaults_test.go
pipeline/docker/docker.go
pipeline/docker/docker_test.go
pipeline/docker/testdata/Dockerfile
pipeline/pipe.go
pipeline/pipe_test.go

------
So, this is not complete yet because I want to make sure the API is good enough first.
What I thought:
```yaml
dockers:
- goos: linux
goarch: amd64
goarm: ''
dockerfile: Dockerfile
image: goreleaser/goreleaser
```
- have several docker images (for different platforms or not)
- write their own dockerfiles
User can define multiple dockerfiles anywhere in the project, the dockerfile for the specific binary and platform is copied into the respective dist folder and `docker build` is run from that folder.
Yeap, that simple.
- templating in the image name (e.g.: `user/image:{{.Tag }}_blah`)
- deal with image names when its a snapshot
- a way to also tag and push latest (eg: `latest: true` in the config)
- docs (after the feature is complete)
- release goreleaser with docker as well
- set …

draft: Docker integration

---

pipeline/docker/docker.go
pipeline/docker/docker_test.go

just a small change that fixes things ;D

fixed docker version name when snapshots

---

config/config.go
docs/130-docker.md
pipeline/docker/docker.go
pipeline/docker/docker_test.go

if latest is set, goreleaser will also tag and push the `user/image:latest` tag :)

also supporting latest docker tag

---

Makefile
checksum/checksum.go
internal/name/name_test.go
pipeline/defaults/defaults.go
pipeline/docker/docker.go
pipeline/fpm/fpm.go
pipeline/snapcraft/snapcraft.go
pipeline/snapcraft/snapcraft_test.go

enabled all linters, fixed everything that came up

enabled more linters and fixed them

---

.goreleaser.yml
context/context.go
context/context_test.go
goreleaserlib/goreleaser.go
pipeline/docker/docker.go
pipeline/release/body.go
pipeline/release/body_test.go
pipeline/release/testdata/release1.txt
pipeline/release/testdata/release2.txt

add the docker images into the release description :)

adding docker images into the release notes

---

pipeline/docker/docker.go

docker push latest

---

config/config.go
docs/130-docker.md
pipeline/docker/docker.go

allows extra copies in the docker image

---

docs/010-quick-start.md

docs/010-quick-start: fix spelling

---

.travis.yml
checksum/checksum_test.go
config/config_test.go
context/context_test.go
goreleaserlib/goreleaser_test.go
internal/archiveformat/format_test.go
internal/buildtarget/buildtarget_test.go
internal/buildtarget/targets_test.go
internal/git/git_test.go
internal/name/name_test.go
internal/testlib/git.go
internal/testlib/mktemp.go
internal/testlib/mktemp_test.go
pipeline/archive/archive_test.go
pipeline/brew/brew_test.go
pipeline/build/build_test.go
pipeline/build/ldflags_test.go
pipeline/checksums/checksums_test.go
pipeline/cleandist/dist_test.go
pipeline/defaults/defaults_test.go
pipeline/defaults/remote_test.go
pipeline/docker/docker.go
pipeline/docker/docker_test.go
pipeline/env/env_test.go
pipeline/fpm/fpm_test.go
pipeline/git/git_test.go
pipeline/pipe_test.go
pipeline/release/body_test.go
pipeline/release/release_test.go
pipeline/snapcraft/snapcraft_test.go

I disabled this one day because it was timing out on travis... time to try it again... I guess

Lint on build

---

Makefile

---
since go 1.9, `./...` skips vendored deps.

chore: updated makefile for go 1.9

---

goreleaserlib/goreleaser.go

Improved the previous log by changing the field notes to file and also
adding a new a debug log with the actual contents of the file.
Refs #385

chore: Improved custom release notes logs

---

docs/150-github-enterprise.md

docs: typo in config filename 

---

docs/000-introduction.md

It is unclear how to get going with Goreleaser, this might help some new folks.

docs: Add examples for installation

---

config/config.go
docs/115-release.md
internal/client/github.go
internal/name/name.go
internal/name/name_test.go
pipeline/defaults/defaults.go

To be clearly honest, `make ci` doesn't totally pass, as there are errors since my fork is not in the `goreleaser` org. 
I have also manually tested this by releasing live code both with and without the feature.
Fixes #392

Add custom release title feature

---

pipeline/fpm/fpm.go

This shall helps in the cases fpm is failing for an unknown reason.
refs #333

chore: passing down --debug to fpm

---

pipeline/brew/brew_test.go
pipeline/brew/template.go
pipeline/brew/testdata/run_pipe.rb
pipeline/brew/testdata/test.rb

They were being inlined, generating an invalid receipt.
closes #416

fix: dependencies and conflicts on brew tap

---

.goreleaser.yml
config/config.go
docs/130-docker.md
pipeline/docker/docker.go
pipeline/docker/docker_test.go

Allow to template docker tags.
Closes #433

 feat: allow templates on docker tags

---

Makefile

Making the static task commit and push
the changes

chore: make static pushes repo as well

---

.travis.yml
Makefile

This should re-build and push the docs on every release. Let's see how it works out :)
closes #378

chore: automating docs deployment

---

.github/stale.yml

It's the configuration for the stale probot.
https://github.com/probot/stale

chore: create stale.yml

---

context/context.go
context/context_test.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/release/body.go
pipeline/release/body_test.go
pipeline/release/testdata/release1.txt

- Added homebrew taps
- Docker pull commands instead of list of docker imgs

feat: improved release notes

---

pipeline/snapshot/snapshot.go

typo: misspeled word on package docs

---

docs/120-homebrew.md

The old "taps" URL 404s out; I've updated to the new URL.

docs: Fixed broken homebrew link

---

docs/060-archive.md
pipeline/build/build_test.go
pipeline/build/name.go

cherry-picked from #449 so we can make multiple releases of this.

Name template

---

goreleaserlib/goreleaser.go
main.go
pipeline/defaults/defaults.go

- Added paddings
- Added total time taken by the release
Example output:
fixes #441

style: improved goreleaser output

---

docs/075-sign.md

docs: fix sign docs

---

pipeline/archive/archive.go
pipeline/archive/archive_test.go

fix: default archive name

---

pipeline/checksums/checksums.go
pipeline/checksums/checksums_test.go

fix: paralelism on checksums pipe

---

docs/075-sign.md
docs/110-snapcraft.md
docs/115-release.md
docs/125-artifactory.md
docs/140-ci.md

Fix 6 typos in the markdown docs.

fix typos in documentation

---

internal/nametemplate/name.go
internal/nametemplate/name_test.go

Also added a deprecation warning and tests,
Closes #476

fix: re-added .Binary to supported fields

---

internal/artifact/artifact.go
pipeline/docker/docker.go
pipeline/docker/docker_test.go

feat: docker in parallel

---

pipeline/docker/docker.go
pipeline/docker/docker_test.go
pipeline/docker/testdata/Dockerfile.bad

Docker: improved test

---

pipeline/fpm/fpm.go
pipeline/fpm/fpm_test.go

fix: use gnu-tar on macOS

---

internal/client/name.go
internal/filenametemplate/template.go
internal/filenametemplate/template_test.go
pipeline/build/ldflags.go
pipeline/build/ldflags_test.go
pipeline/checksums/checksums_test.go
pipeline/checksums/name.go
pipeline/docker/docker.go
pipeline/docker/docker_test.go

fix: break if env not available

---

config/config.go
docs/120-homebrew.md
internal/testlib/skip.go
pipeline/artifactory/artifactory.go
pipeline/artifactory/artifactory_test.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/piper.go
pipeline/release/release.go

feat: skip formula upload

---

Gopkg.lock
Gopkg.toml
goreleaserlib/goreleaser.go
main.go

fix: colors on windows

---

config/config.go
docs/120-homebrew.md
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/brew/template.go
pipeline/brew/testdata/run_pipe_download_strategy.rb.golden

feat: support download strategy on brew

---

README.md

readme: OpenCollective

---

config/config.go
docs/130-docker.md
pipeline/docker/docker.go
pipeline/docker/docker_test.go

Multiple docker tags

---

pipeline/docker/docker.go

feat: added deprecation warnings

---

config/config.go
config/config_test.go
config/testdata/anchor.yaml
config/testdata/invalid_config.yml

I had poorly re-implemented yaml's `UnmarshalStrict` method, don't know why.
Just replaced a bunch of hacky stuff with the right thing.
and as a side effect we can now also use anchors on the configs again 🐝

Simplified config

---

internal/git/git.go
internal/git/git_test.go

fix: git: if exit is 0, ignore stderr

---

pipeline/release/body.go

Fail as fast as possible.
(yup, I managed to break the template...)

fix: Compile template at startup

---

.travis.yml

chore: fix ci

---

Gopkg.lock
Gopkg.toml
config/config.go
docs/020-environment.md
pipeline/defaults/defaults.go
pipeline/env/env.go
pipeline/env/env_test.go

feat: load github token from file

---

.goreleaser.yml
config/config.go
docs/000-introduction.md
docs/122-scoop.md
goreleaserlib/goreleaser.go
pipeline/defaults/defaults.go
pipeline/scoop/scoop.go
pipeline/scoop/scoop_test.go

Finished the Scoop.sh manifest generator for Windows releases!
See #387

Scoop.sh App Manifest

---

pipeline/docker/docker.go

fix: do not print ctx in docker pipe when on debug

---

pipeline/artifactory/artifactory.go
pipeline/artifactory/artifactory_test.go

fix: artifactory should upload linux archives as well

---

pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/defaults/defaults.go
pipeline/defaults/defaults_test.go
pipeline/scoop/scoop.go
pipeline/scoop/scoop_test.go

fix: global default for github download url

---

pipeline/scoop/scoop.go
pipeline/scoop/scoop_test.go
pipeline/scoop/testdata/test_buildmanifest.json.golden

refactor: improved scoop pipe code

---

internal/client/github.go
pipeline/archive/archive.go
pipeline/docker/docker_test.go
pipeline/scoop/scoop_test.go
pipeline/snapcraft/snapcraft.go

style: removed elses, improved test code

---

.travis.yml
pipeline/artifactory/artifactory_test.go

chore: compile with go1.10

---

docs/990-deprecations.md
internal/deprecate/deprecate.go
internal/deprecate/deprecate_test.go
pipeline/build/build.go
pipeline/docker/docker.go
pipeline/fpm/fpm.go

fix: better deprecation notices

---

pipeline/nfpm/nfpm.go

fix: closing targz file

---

pipeline/nfpm/nfpm.go
pipeline/nfpm/nfpm_test.go

fix: nfpm multiple binaries in the same archive

---

Gopkg.lock
Gopkg.toml
config/config.go
pipeline/nfpm/nfpm.go
pipeline/nfpm/nfpm_test.go

feat: nfpm: support config files

---

.goreleaser.yml
Gopkg.lock
Gopkg.toml
config/config.go
docs/100-nfpm.md
pipeline/nfpm/nfpm.go
pipeline/nfpm/nfpm_test.go

feat: bump nfpm and recommends rpm

---

pipeline/changelog/changelog.go

closes #571 
couldn't think of a way to write unit tests for this though :/
anyway, when we migrate to go-git this would not be a problem anymore :)

fix: git log without colors

---

pipeline/release/remote.go
pipeline/release/remote_test.go

or github enterprise...
closes https://github.com/goreleaser/goreleaser/issues/570

fix: guess git repo from url with custom ssh configs

---

Makefile
pipeline/release/release_test.go

chore: enabling -race -failfast and -coverpkg

---

internal/git/git.go
internal/git/git_test.go
pipeline/artifactory/artifactory_test.go
pipeline/git/errors.go
pipeline/git/git.go
pipeline/git/git_test.go
pipeline/release/release.go
pipeline/release/release_test.go
pipeline/release/remote.go

Snapshot release without a git repo

---

context/context.go
main.go
main_test.go
pipeline/artifactory/artifactory.go
pipeline/artifactory/artifactory_test.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/docker/docker.go
pipeline/docker/docker_test.go
pipeline/env/env.go
pipeline/env/env_test.go
pipeline/piper.go
pipeline/release/release.go
pipeline/release/release_test.go
pipeline/scoop/scoop.go
pipeline/scoop/scoop_test.go

feat: --skip-publish is back

---

pipeline/git/git.go
pipeline/git/git_test.go

fix: running goreleaser against repo with no commits

---

pipeline/scoop/scoop.go
pipeline/scoop/scoop_test.go
pipeline/scoop/testdata/test_buildmanifest.json.golden

fix: scoop download url

---

context/context.go
main.go
pipeline/git/git.go
pipeline/git/git_test.go
pipeline/piper.go

feat: --skip-validate is back

---

internal/client/client.go
internal/client/github.go
pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/release/release_test.go
pipeline/scoop/scoop.go
pipeline/scoop/scoop_test.go

WIP: change commit msg for brew and scoop

---

Gopkg.lock
Gopkg.toml
main.go
main_test.go

I like the way kingpin works better (not that urfave/cli is bad or anything).
I'm also using kingpin in most of my other projects, so I though it would be nice to use the same thing all over.
Maybe this makes the code easier to test as well, let's see.

chore: replacing cli with kingpin

---

config/config.go
docs/130-docker.md
pipeline/docker/docker.go
pipeline/docker/docker_test.go

feat: skip_push on docker to match draft releases

---

Gopkg.lock
Gopkg.toml
docs/100-linux-packages.md
docs/123-release.md
pipeline/nfpm/nfpm_test.go

feat: updated nfpm to glob support

---

docs/140-ci.md

docs: fix insecure pipe to bash

---

.github/PULL_REQUEST_TEMPLATE.md
docs/050-build.md
internal/builders/golang/build.go
internal/builders/golang/build_test.go
internal/client/name.go

fix: added time func to ldflags template

---

Gopkg.lock
Gopkg.toml

bump: deps update

---

Gopkg.lock
Gopkg.toml
pipeline/nfpm/nfpm.go

just to make goreleaser go get-able again
no new features are actually being used yet.
refs #646

chore: update nfpm

---

docs/100-linux-packages.md

fix: typo in docs

---

config/config.go
docs/123-release.md
pipeline/release/release.go
pipeline/release/release_test.go

feat: allow to disable the release pipe

---

docs/130-docker.md
pipeline/docker/docker.go
pipeline/docker/docker_test.go

feat: added Commit to docker name_template

---

CONTRIBUTING.md
Makefile
www/content/introduction.md

just fixes the `go get` usage.

docs: improve docs

---

config/config.go
pipeline/snapcraft/snapcraft.go
pipeline/snapcraft/snapcraft_test.go
www/content/linux-packages.md

feat: add args to snapcraft commands

---

Gopkg.lock

bump: deps

---

pipeline/brew/brew.go
pipeline/brew/brew_test.go
pipeline/brew/testdata/binary_overriden.rb.golden

Fix the brew pipe ignoring format_overrides.
The pipe was just ignoring the config altogether. 
closes #720

Brew: consider format override

---

Gopkg.lock
pipeline/archive/archive_test.go

closes https://github.com/goreleaser/goreleaser/issues/734

fix: folders inside zips

---

pipeline/s3/s3.go
pipeline/s3/s3_test.go

refs https://github.com/goreleaser/goreleaser/issues/737

fix: s3: honor skip upload

---

www/content/ci.md

If applied, this commit will correct the documentation for CircleCI.

docs: Correct CircleCI Example.

---

internal/pipeline/docker/docker.go
internal/pipeline/docker/docker_test.go

fix: multiple docker instances with the same extra files

---

internal/pipeline/git/errors.go
internal/pipeline/git/git.go
internal/pipeline/git/git_test.go

fix: check if git is present in path

---

scripts/entrypoint.sh

It seems entrypoint script is slightly incorrect :( sorry for that, my mistake. I always forget bash syntax...
refs https://github.com/goreleaser/goreleaser/issues/783

fix: entrypoint

---

internal/http/http.go

chore: add debug to http put

---

.goreleaser.yml
.travis.yml
Makefile
internal/artifact/artifact.go

bump: Go 1.11

---

internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go
pkg/config/config.go

feat: scoop: accept name/project name

---

www/content/ci.md

Add instructions for running goreleaser in Google CloudBuild.
See also issue #432.

Add instructions for using with Google CloudBuild.

---

www/content/build.md
www/content/hooks.md

docs: improve docs on go modules usage

---

.travis.yml

docs can get "too updated", misleading the users :/

docs: deploy on tags only

---

internal/pipe/publish/publish.go
internal/pipe/publish/publish_test.go
internal/pipeline/pipeline.go

refs https://github.com/goreleaser/goreleaser/issues/827

refactor: added publish pipe

---

internal/pipe/brew/brew.go
internal/pipe/publish/publish.go
internal/pipe/publish/publish_test.go
internal/pipe/scoop/scoop.go
internal/pipeline/pipeline.go
main.go

refactor: moved brew and scoop to publish pipe

---

internal/pipe/artifactory/artifactory.go
internal/pipe/artifactory/artifactory_test.go
internal/pipe/publish/publish.go
internal/pipeline/pipeline.go

refactor: artifactory: pipe -> publisher

---

internal/pipe/defaults/defaults.go
pkg/defaults/defaults.go

refs https://github.com/goreleaser/godownloader/issues/81

chore: move defaulter to pkg, so godownloader can use it

---

internal/deprecate/deprecate_test.go
internal/deprecate/testdata/output.txt.golden
main.go

hopefully this enabled colors on travis output again...

fix: colored output on travis

---

www/content/ci.md

docs: Adding Semaphore CI to GoReleaser documentation

---

internal/pipe/release/release.go
internal/pipe/release/release_test.go

fix: defaults when release is disabled

---

internal/builders/golang/build.go
internal/builders/golang/targets.go
internal/http/http.go
internal/pipe/artifactory/artifactory.go
internal/pipe/changelog/changelog.go
internal/pipe/git/git.go
internal/pipe/publish/publish.go
internal/pipe/put/put.go
internal/pipe/release/body.go
internal/pipeline/pipeline.go
main.go
pkg/build/build.go
pkg/defaults/defaults.go

fixed some new linter issues...

fix: linter fixes

---

internal/pipe/archive/archive.go

fix: archives with windows paths

---

internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go

fix: do not allow several archives with the same name

---

internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go

fix: uniq files inside archive

---

internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go
pkg/config/config.go
www/content/archive.md

feat: support custom wrap directory

---

internal/http/http_test.go

clean: removed unused method

---

.goreleaser.yml

refs https://github.com/goreleaser/goreleaser/pull/881

feat: also build/publish docker w/ cgo image

---

www/content/ci.md

Fix package name required for snap pipe in documentation.

docs(ci): change snapcraft package with snapd

---

Dockerfile
Dockerfile.cgo
internal/pipe/docker/docker.go
www/content/docker.md

fix: improvements on docker extra_files

---

internal/artifact/artifact.go
internal/artifact/artifact_test.go
internal/builders/golang/build.go
internal/builders/golang/build_test.go
internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go
internal/pipe/docker/docker.go
internal/pipe/docker/docker_test.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go

refs https://github.com/goreleaser/goreleaser/issues/705

feat: back-reference build artifacts from archive artifact

---

www/content/build.md

Replace deprecated .Commit var with .ShortCommit

Replace deprecated .Commit var with .ShortCommit

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go
www/content/build.md

feat: template on flags

---

internal/pipe/docker/docker.go
internal/pipe/docker/docker_test.go
www/content/docker.md

feat: support templates on docker.binaries

---

internal/pipe/s3/s3.go
internal/pipe/s3/s3_test.go
www/content/s3.md

This PR allow user to use custom value for S3 Bucket name

feat: allow s3 bucket name customization

---

internal/pipe/git/git.go

not really needed but wouldn't hurt

fix: suppress diffs on git show

---

www/content/ci.md

Updating the link to Semaphore documentation on handling secrets.

docs(ci): Updating the link to Semaphore docs

---

.github/main.workflow

i always delete the branches and its mostly failing anyway

clean: remove workflow

---

internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go

fix: custom changelog and changelog.skip

---

scripts/entrypoint.sh
www/content/actions.md

It allow publishing taps from github actions

Allow brew with github actions (#982)

---

internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
pkg/config/config.go
www/content/snapcraft.md

feat: added Plugs attribute to snapcraft.Metadata

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go
internal/pipe/before/before.go
internal/pipe/build/build.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
pkg/context/context.go

this should fix #985 
also stopped messing with env in several places, tried to organize it a little bit

fix: all envs allowed on build template

---

internal/pipe/sign/sign.go
internal/pipe/sign/sign_test.go

The signature Path was assumed to be at the root of dist without
taking into account the target of the original artifact. This made the
upload of signature fails with file not found errors.
The signature Name was the actual signature filename and didn't take
into account the target and would lead to conflicts when flattening
the paths for upload. This change derives the Name from the original
artifact Name instead.
Fix the Path and Name of Signature artifacts
The current version does not work when uploading multiple signatures for the same build with multiple goarch/goos:
- The Path is incorrect and points to `dist/filename.sig` instead of `dist/target/filename.sig`
```
⨯ release failed after 42.20s error=GitHub Releases: failed to publish artifacts: failed to upload aws-dump.asc after 10 …
```

Fix signature path and upload

---

internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
pkg/config/config.go
www/content/snapcraft.md

Hi there!
I've added the base key to the snapcraft pipe.

feat: add base key to snapcraft

---

.goreleaser.yml
internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
pkg/config/config.go
www/content/deprecations.md
www/content/nfpm.md

part of #705 
adding multiple nfpm support

feat: multiple nfpm

---

internal/ids/ids.go
internal/ids/ids_test.go
internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go
internal/pipe/build/build.go
internal/pipe/build/build_test.go
internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
pkg/config/config.go
www/content/nfpm.md

- small pkg to validate ids
- add id field to nfpm

refactor: id validations

---

www/content/ci.md

Added a GitLab CI specific chapter to the Continuous Integration docs.
If applied, this commit will solve issue #1022.

docs: Document GitLab CI

---

internal/pipe/nfpm/nfpm.go
internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
pkg/config/config.go
www/content/deprecations.md
www/content/snapcraft.md

part of #705
adding multiple snapcrafts support

feat: multiple snapcraft

---

internal/builders/golang/build.go
internal/pipe/build/build_test.go
main.go
main_test.go
www/content/build.md

refs https://github.com/Homebrew/homebrew-core/pull/40045

feat: improved version command

---

internal/linux/arch.go
internal/linux/arch_test.go
internal/pipe/snapcraft/snapcraft_test.go

closes https://github.com/goreleaser/goreleaser/issues/1026

fix: armhf on arm v6

---

internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
pkg/config/config.go
www/content/snapcraft.md

fix: nfpm id

---

internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go

fix: wrap snapcraft command in TrimSpace

---

www/content/ci.md

I added documentation on how to use goreleaser in Codefresh CI/CD. No code was changed.
I found existing instructions for other CI services in the docs and added Codefresh in the list.
Here is the full example on Codefresh docs. 
https://codefresh.io/docs/docs/learn-by-example/golang/goreleaser/

Added Codefresh instructions

---

CONTRIBUTING.md

Fixes small typos in contributing doc.

docs: correct typos in contrib doc

---

internal/pipe/build/build.go
internal/pipe/build/build_test.go

dumb mistake, refs https://github.com/gohugoio/hugo/pull/6021
thanks @bep for reporting

fix: build with same binary name

---

internal/http/http.go
internal/pipe/blob/blob.go
internal/pipe/blob/blob_test.go
internal/pipe/blob/openbucket.go
internal/pipe/blob/util.go
internal/pipe/s3/s3.go
internal/pipe/s3/s3_test.go
pkg/config/config.go
www/content/blob.md
www/content/deprecations.md
www/content/s3.md

refs https://github.com/goreleaser/goreleaser/issues/705

 feat: id filter on s3/blob pipes

---

internal/pipe/brew/template.go
internal/pipe/brew/testdata/custom_download_strategy.rb.golden
internal/pipe/brew/testdata/custom_require.rb.golden

fix: generate valid brew formula

---

www/content/tutorials.md

This commit will help users of GoReleaser to understand how to cross compile using CGO.

Add Cross compile with CGO and GoReleaser

---

internal/pipe/build/build.go
internal/pipe/build/build_test.go
internal/pipe/defaults/defaults_test.go

fix: non-templateable field as default build.id

---

go.mod
go.sum
pkg/config/config.go
www/content/nfpm.md

https://github.com/goreleaser/nfpm/releases/tag/v0.12.0

feat: update nfpm

---

www/content/ci.md

Current formatting is not in yml format so it looks a bit ugly.

docs: Improve formatting of drone section in CI guides

---

internal/client/client.go

If applied, this commit will fix #1073

Fixed token required if release is disabled

---

README.md

Fix opencollective links in README

---

internal/pipe/brew/template.go
internal/pipe/brew/testdata/custom_block.rb.golden
internal/pipe/brew/testdata/custom_download_strategy.rb.golden
internal/pipe/brew/testdata/custom_require.rb.golden
internal/pipe/brew/testdata/default.rb.golden
internal/pipe/brew/testdata/github_enterprise_url.rb.golden
internal/pipe/brew/testdata/test.rb.golden

fix brew trying to bottle the formula when it can't detect command line tools.
closes #1078

fix: set bottle unneeded

---

internal/pipe/snapcraft/snapcraft.go

feat(snap): allow previous in review process

---

internal/pipe/sign/sign.go
internal/pipe/sign/sign_test.go
pkg/config/config.go
www/content/deprecations.md
www/content/sign.md

add support to multiple `sign` instructions.
closes #1087
cc/ @joemiller @magiconair

feat: multiple sign

---

.github/ISSUE_TEMPLATE/Bug_report.md
main.go
main_test.go
www/content/deprecations.md

so users can easily check their config files for errors / deprecations.

feat: add goreleaser check

---

pkg/config/config.go

config file was not being closed...

fix: close config file

---

.goreleaser.yml
Makefile

This reverts commit a10c5525bcb74ac10c0ba7a0d4e326bc39c23330.
it was failing on travis a few days ago... lets see how it goes now.

Revert "ci: remove gocenter for now"

---

www/content/ci.md

docs: clarify shallow clone behavior

---

internal/pipe/blob/blob_test.go
internal/pipe/docker/docker_test.go
internal/pipe/s3/awssession_test.go

Hi there!
I've removed some unused code.

clean: remove unused code

---

internal/pipe/build/build_test.go
internal/pipe/sign/sign_test.go

Hi there!
I've added additional error handling for 2 tests.

test: add error handling

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go

Hi there!
After these changes, an artifact fields will become available to flags.
Close #1115

fix: artifact fields not available to flags

---

www/content/actions.md

Documentation will reflect new GitHub YAML syntax.
Resolves: #1124

docs: Update GitHub actions with new YAML syntax

---

www/content/actions.md

Fixes #1149 (see [goreleaser-action](https://github.com/goreleaser/goreleaser-action))

docs: Use GoReleaser Action

---

internal/builders/golang/build_test.go
internal/builders/golang/targets.go
internal/builders/golang/targets_test.go
internal/pipe/build/build.go
internal/pipe/build/build_test.go

adds JS WASM build target.
closes #1017

feat: wasm support

---

go.mod
go.sum
internal/client/github.go
internal/pipe/semver/semver.go
pkg/context/context.go

will auto close a bunch of other prs

chore(deps): bump all

---

internal/client/github_test.go

right now it has no tests... adding a few..

test: increase github client test coverage

---

www/content/actions.md

docs: use v1 as recommended by GitHub

---

Makefile

fix: locale on tests

---

internal/pipe/release/release.go
internal/pipe/release/release_test.go
pkg/config/config.go
www/content/release.md

* add `ids: string[]` to release configuration
* add support for filtering artifacts by id within the release pipe
Closes #1202

feat(release): add artifact filter (by id) to release pipe

---

www/content/install.md

Add instructions for installing using shell script
Fixes #1197

docs: add instructions for installing using shell script

---

www/content/tutorials.md

Add new post of using goreleaser + GitHub Actions.
[Go Release Automation with goreleaser + GitHub Actions | Toshimaru’s Blog](https://blog.toshima.ru/2019/10/20/go-release-automation-with-goreleaser.html)
Hope this helps ❗️

docs: Add goreleaser + GitHub Actions blog post

---

go.mod
go.sum

fix: update nfpm

---

go.mod
go.sum

chore(deps): cleanup go.mod file

---

internal/pipe/nfpm/nfpm.go

chore: fixed spelling

---

www/content/actions.md

New input for this action: `workdir`

docs: Update GitHub Actions page

---

www/content/sign.md

refs #1227
cc/ @joemiller @mitchellh if you want to add/change anything :)

docs: signing with mitchellh/gon

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
pkg/config/config.go
pkg/config/config_test.go
www/content/deprecations.md

singular nfpm was removed in favor of its plural form.

feat: remove deprecated nfpm

---

internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
pkg/config/config.go
www/content/deprecations.md

removed deprecated snapcraft config in favor of its plural form.

feat: remove singular snapcraft config

---

www/content/templates.md

docs: fix typo

---

www/content/actions.md

refs https://github.com/goreleaser/goreleaser-action/issues/61#issuecomment-569286582

docs: run only on new tag note on github actions

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go
internal/pipe/defaults/defaults_test.go
pkg/config/config.go
www/content/deprecations.md

feat: remove deprecated brew config

---

internal/artifact/artifact.go
internal/artifact/artifact_test.go
internal/linux/arch.go
internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go
internal/pipe/nfpm/nfpm.go
internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
www/content/archive.md
www/content/nfpm.md
www/content/snapcraft.md
www/content/templates.md

closes https://github.com/goreleaser/goreleaser/issues/1329
still need to add more tests

wip: fix gomips

---

www/content/ci.md

Fix typos that referenced GitHub.
Move config to job level. Users can extract elements to global config if
necessary, but since the snippet has no other jobs the use of global
config added confusion.
Disable shallow clones to fix changelogs.
Update use of GitLab image registry to use the USER/PASSWORD vars and
clarify that they are automatically set on jobs running on GitLab
instances with the image registry enabled.
Document use of `only` to not release every commit (optionally).
Format nested docker goreleaser command multi-line.
Document purpose of GITLAB_TOKEN.

docs: improve GitLab CI documentation

---

.travis.yml
CONTRIBUTING.md
Dockerfile
Dockerfile.cgo
Makefile
go.mod
go.sum
internal/client/github_test.go
internal/pipe/artifactory/artifactory_test.go
internal/pipe/upload/upload_test.go
main_test.go
www/content/actions.md
www/content/ci.md

Upgrade builds, docker images, examples and tests from go 1.13 to 1.14.

feat: upgrade to go 1.14

---

internal/builders/golang/targets.go
internal/builders/golang/targets_test.go

feat: support freebsd/arm64 and openbsd/arm64

---

internal/middleware/logging.go
internal/pipe/artifactory/artifactory.go
internal/pipe/before/before.go
internal/pipe/blob/blob.go
internal/pipe/docker/docker.go
internal/pipe/nfpm/nfpm.go
internal/pipe/release/release.go
internal/pipe/scoop/scoop.go
internal/pipe/semver/semver.go
internal/pipe/snapcraft/snapcraft.go
internal/pipe/upload/upload.go

making it a bit less aggressive by remove the `strings.ToUpper` and improved some titles.

feat: improve output a bit

---

internal/pipe/env/env.go
internal/pipe/env/env_test.go
pkg/defaults/defaults.go

fix: default evn tokenfiles

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
www/content/templates.md

feat: allow to use Release and Epoch on nfpm name template

---

go.mod
go.sum
internal/client/client.go
internal/pipe/release/release.go

make it simpler and depending on one less library.

refactor: simplify retries

---

www/content/homebrew.md

docs: Use "brews" plural form in documentation

---

.goreleaser.yml
internal/builders/golang/build.go
internal/builders/golang/build_test.go
internal/pipe/build/build_test.go

we were setting the untemplated `build.binary` field in the `extra.binary` field, which caused things to fail.
closes #1462
refs https://github.com/goreleaser/goreleaser/discussions/1461

fix: builds.binary template

---

internal/pipe/blob/blob.go
internal/pipe/blob/upload.go

refs https://github.com/goreleaser/goreleaser/pull/1474

fix: blob data race

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go

Previously `goreleaser --snapshot` (also used here in Travis CI) would fail if no token was provided, because Homebrew requires a token type for figuring out how to construct the download URLs.
This patch makes GitHub the default token type, which is in line with how releases work now.
```
• homebrew tap formula
• token type                type=
⨯ release failed after 42.51s error=homebrew tap formula: failed to publish artifacts: token type not implemented for brew pipe
```
```
• homebrew tap formula
• token type                type=
• writing                   formula=dist/goreleaser.rb
• pipe skipped              error=publishing is disabled
```
--- 
I'm assuming this fix still retains the spirit of https://github.com/goreleaser/goreleaser/pull/1425 and allows inspection of formula …

fix(pipe/brew): Default to GitHub

---

www/content/scoop.md

This fixes inaccurate installation instructions for Scoop.

docs: Fix Scoop installation instructions

---

www/content/actions.md

Ref. https://github.com/goreleaser/goreleaser-action/releases/tag/v2.0.0

docs: GoReleaser Action v2

---

www/content/actions.md

docs: Use template for signs.args in GitHub Action doc

---

.github/workflows/gosum.yml

Our first GitHub Action :rocket:

feat: Add go.sum verification workflow

---

README.md

docs: Use GitHub Action badge

---

.github/workflows/docs.yml
.github/workflows/htmltest.yml
www/htmltest.yml

chore(ci): htmltest workflow

---

www/docs/customization/templates.md
www/docs/overrides/main.html

some more docs improvements...

docs: some other improvements

---

.github/workflows/build.yml

need to use the correct token...

fix(ci): use GH_PAT to release

---

www/docs/ci/jenkins.md
www/mkdocs.yml

This is how to release using Jenkins pipeline

docs: added docs for Jenkins pipeline

---

.github/workflows/build.yml

release log was empty, needed to input it manually.
reason: missing unshallow step :)

fix(ci): unshallow history

---

www/docs/customization/build.md

docs: fix grammar

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go

fix: windows filenames

---

.goreleaser.yml
internal/pipe/brew/brew_test.go
internal/pipe/brew/template.go
internal/pipe/brew/testdata/binary_overridden.rb.golden
internal/pipe/brew/testdata/custom_block.rb.golden
internal/pipe/brew/testdata/custom_download_strategy.rb.golden
internal/pipe/brew/testdata/custom_require.rb.golden
internal/pipe/brew/testdata/default.rb.golden
internal/pipe/brew/testdata/default_gitlab.rb.golden
internal/pipe/brew/testdata/github_enterprise_url.rb.golden
internal/pipe/brew/testdata/gitlab_enterprise_url.rb.golden
internal/pipe/brew/testdata/multiple_armv5.rb.golden
internal/pipe/brew/testdata/multiple_armv6.rb.golden
internal/pipe/brew/testdata/multiple_armv7.rb.golden
pkg/config/config.go
www/docs/customization/homebrew.md

feat: add support brew dependency types

---

pkg/config/config.go
pkg/config/config_homebrew_dependency_test.go

refs #1554
not sure if there's a better way to do this... if there is, I'm all ears :)

fix: brew dependency: string or struct

---

.github/workflows/build.yml

Ref. actions/virtual-environments#922

fix(ci): Remove workaround for invalid cross-device link

---

go.mod
go.sum
internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go

upgraded and removed now unused field.

chore(deps): bump github.com/goreleaser/nfpm from 1.2.1 to 1.3.0

---

www/docs/ci/actions.md

docs: Fix link to "sign"

---

.github/workflows/gosum.yml

so it matches dependabot's commit msgs.

chore(ci): change auto go mod tidy commit msg

---

internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go
internal/pipe/changelog/testdata/changes-templated.md
internal/pipe/changelog/testdata/release-footer-templated.md
internal/pipe/changelog/testdata/release-header-templated.md

feat: Add support for templated release notes, header and footer

---

.gitignore
Makefile
scripts/get-releases.sh

refs https://github.com/goreleaser/goreleaser-action/pull/213#discussion_r436909494

docs: generate static/releases.json

---

.gitignore
Makefile

broke things on #1594
refs https://github.com/goreleaser/goreleaser-action/pull/213#pullrequestreview-426505497

docs: fix vercel deploy

---

www/docs/customization/build.md

docs: Documentation to include simple multiple binary example

---

.github/workflows/build.yml
www/docs/ci/actions.md

closes https://github.com/goreleaser/goreleaser/pull/1608
refs https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches

docs: unshallow action

---

www/docs/ci/actions.md

document the semver range feature of the github-action.

docs: action version semver range

---

go.mod
go.sum

fixes #1636
refs https://github.com/goreleaser/nfpm/pull/152

fix: update nfpm to v1.3.2

---

go.mod
go.sum
internal/client/gitea_test.go

chore(deps): bump code.gitea.io/sdk/gitea from v0.12.0 to v0.12.1

---

www/docs/ci/cirrus.md
www/mkdocs.yml

Document how to configure GoReleaser on Cirrus CI.

docs: configuring with Cirrus CI

---

internal/pipe/snapcraft/snapcraft.go

different approach to #1678 (and its PR #1679): we don't need to copy the completer for each binary, so we can just move that loop to outside of the binaries loop..

refactor: avoid copying the completer multiple times

---

internal/pipe/before/before.go
internal/pipe/before/before_test.go
internal/pipe/before/testdata/foo.sh

fix: better handle before hooks errors

---

internal/pipe/build/build.go
internal/pipe/build/build_test.go
internal/tmpl/tmpl.go
pkg/build/build.go

I was looking for that, and saw the ticket. Figured, I'd try to add it and it seems to work. :)
I'm parsing the relevant values from "target", everything else seemed not feasible. And I didn't want to muck around in env unless necessary.
Resolves: #1518

feat: make goos and goarch available in hooks

---

www/docs/customization/bintray.md

docs: update bintray instructions

---

scripts/entrypoint.sh

feat: log into Github package registry with token

---

go.mod
go.sum

fix: windows shellwords

---

internal/pipe/build/build.go
internal/pipe/build/build_test.go

feat: log build hooks

---

Dockerfile

**If applied, this commit will...**
Update the docker base image to use Go 1.15
Some users may require Go 1.15 features.

feat: update to Go 1.15 image

---

.github/workflows/build.yml
.github/workflows/gosum.yml
.goreleaser.yml
CONTRIBUTING.md
Dockerfile
Dockerfile.cgo
cmd/util_test.go
go.mod
internal/builders/golang/build_test.go
internal/builders/golang/targets.go
internal/builders/golang/targets_test.go
www/docs/ci/actions.md
www/docs/ci/circle.md
www/docs/ci/codefresh.md

use the latest and greatest :)

feat: use go 1.15

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go
internal/pipe/pipe.go
internal/pipe/pipe_test.go

closes #1719
my initial idea, happy to hear any feedback.
(names are probably bad, couldn't think on good ones)

fix(brew) create file if skip is set

---

internal/pipe/checksums/checksums.go
internal/pipe/checksums/checksums_test.go
pkg/config/config.go
www/docs/customization/checksum.md

feat: allow to disable checksum pipe

---

www/docs/customization/templates.md

Fix minor doco typo
typo
`this fields are always available:`
to:
`these fields are always available:`

typo: `this` to `these`

---

internal/artifact/artifact.go
internal/artifact/artifact_test.go

fix: typo in artifact checksum error message

---

.github/workflows/build.yml
.goreleaser.yml
scripts/entrypoint.sh

feat: support ghcr.io

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go

fix: do not default goos/goarch/goarm if targets is provided

---

internal/pipe/git/git.go

closes #1793
is this what you meant @crazy-max?

refactor: use git tag --points-at

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go
internal/pipe/brew/template.go
internal/pipe/brew/testdata/test.rb.golden
pkg/config/config.go

feat(brew): post_install

---

go.mod
go.sum
internal/client/gitea.go
internal/client/gitea_test.go

<details>
<summary>Changelog</summary>
<br>
<b>BREAKING</b><br>
* Check Gitea Version Requirement (#419)<br>
* All Function return http responce (#416)<br>
* Remove opts from ListPullReviewComments (#411)<br>
* Use enum AccessMode for OrgTeam and Collaborator functions (#408)<br>
* CreateOrgOption rename UserName to Name (#386)<br>
* EditMilestoneOption also use StateType (#350)<br>
* Refactor RepoSearch to be easy usable (#346)<br>
<b>FEATURES</b><br>
* Milestone Functions accept name to identify (#418)<br>
* Make http requests with context (#417)<br>
* Add GetGlobalAttachmentSettings (#414)<br>
* Add GetArchive (#413)<br>
* Add GetRepoLanguages + TESTs (#412)<br>
* Add CreateBranch (#407)<br>
* Add Admin CronTask functions (#406)<br>
* Add GetGlobalAPISettings Function (#404)<br>
* Add …

chore(deps): bump code.gitea.io/sdk/gitea from v0.12.1 to v0.13.0

---

www/docs/cookbooks/cgo-and-crosscompiling.md
www/docs/limitations/cgo.md
www/mkdocs.yml

Updating docs with CGO and cross-compiling how to.
Follow up to [conversation](https://gophers.slack.com/archives/C3T1JU24B/p1600905690004300)

docs: how to cross-compile Go with CGO

---

go.mod
go.sum
internal/client/gitea.go
internal/client/gitea_test.go

follow up of  #1806
close #1827

chore(deps): bump code.gitea.io/sdk/gitea from v0.12.1 to v0.13.1

---

internal/pipe/snapcraft/snapcraft_test.go

refactor: use require on snapcraft tests

---

www/docs/customization/archive.md

closes https://github.com/goreleaser/goreleaser/issues/1821

docs: improve archive docs

---

www/docs/customization/release.md

docs: gitlab subgroups

---

internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
pkg/config/config.go
www/docs/customization/snapcraft.md

feat: snap restart-condition

---

internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go

This might be a breaking change for some, but I think its an error they haven't noticed (nor they users), so its probably OK to fail.
closes #1780

fix: break the release if archive has different binary counts for each platform

---

internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go
pkg/config/config.go
www/docs/customization/archive.md

closes #1855
refs 229c8f54a51a8b25313a752016983c44e47e0214 #1841  #1780

feat: allow to disable archive binary count check

---

internal/pipe/snapcraft/snapcraft_test.go

This pull-request fixes the snapcraft tests. This closes #1843 .
Note: Before merging the questions in https://github.com/goreleaser/goreleaser/issues/1843#issuecomment-711442004 should be resolved.

tests: fix snapcraft tests

---

www/docs/customization/nfpm.md

Hi,
a tiny improvement that adds apk package to the list of the supported packages in the docs

docs: added apk package

---

www/docs/tutorials.md

Hello. 
This is my article about using GitHub Action with GoReleaser on Dev.to:
https://dev.to/koddr/github-action-for-release-your-go-projects-as-fast-and-easily-as-possible-20a2

docs: add new tutorial

---

go.mod
go.sum
internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
pkg/config/config.go
www/docs/customization/nfpm.md
www/docs/deprecations.md

feat: ugprade nfpm

---

www/docs/customization/docker_manifest.md

Improves docs on multi-platform docker images.
refs https://github.com/goreleaser/goreleaser/discussions/1967

docs: improve docker_manifest examples

---

internal/pipe/docker/docker.go
internal/pipe/docker/docker_test.go

fix(docker): handle empty docker images

---

.goreleaser.yml
Dockerfile

make the docker image work better for local builds (no need to pass extra build-args).

chore(ci): improve dockerfile/manifest

---

internal/pipe/docker/manifest.go

refs #1977
seems like running it sequentially fixes the push issues...

fix: manifest with no parallelism

---

.goreleaser.yml

install fish, bash and zsh completions on the linux packages :)

feat: install completions on linux packages

---

cmd/build.go
cmd/release.go

closes https://github.com/goreleaser/goreleaser/issues/2013

feat: use num cpu as default parallelism

---

www/docs/customization/bintray.md

docs: fix typo in bintray.md

---

www/docs/intro.md

docs: fix minor typo in intro.md

---

www/docs/customization/templates.md

minor grammar tweak

---

www/docs/cookbooks/blog-posts.md
www/docs/limitations/cgo.md
www/mkdocs.yml

also moved some files around a bit.

docs: clarify cgo a bit

---

internal/builders/golang/build.go
internal/builders/golang/targets.go
internal/builders/golang/targets_test.go

ignore darwin/arm64 if its go 1.15...
I don't really like this... but maybe its better leaving this here for a month or so than dealing with support...
refs #2066

fix: try not to break if run on go1.15

---

.github/workflows/build.yml
.goreleaser.yml
Makefile
cmd/testdata/good.yml
internal/static/config.go
www/docs/customization/build.md
www/docs/customization/env.md
www/docs/customization/hooks.md

fix(ci): go mod tidy

---

cmd/init.go
cmd/init_test.go

either create a `.gitignore` or append to an existing `.gitignore` the `dist/` folder so its where it needs to be :)

feat: init: add dist to gitignore

---

.github/workflows/build.yml

refs https://github.com/goreleaser/goreleaser/issues/1715

fix(ci): snap tests

---

www/docs/customization/templates.md

docs: fix typo in templates.md

---

internal/linux/arch.go
internal/linux/arch_test.go

closes https://github.com/goreleaser/goreleaser/issues/2125

fix: properly translate mips arch

---

internal/pipe/gomod/gomod.go
internal/pipe/gomod/gomod_test.go
internal/pipeline/pipeline.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
pkg/context/context.go
www/docs/customization/templates.md

closes https://github.com/goreleaser/goreleaser/issues/1688

feat: allow to use ModulePath on templates

---

www/docs/customization/homebrew.md

Update the documentation for the homebrew customization section.
There was no easy way to know that this feature even existed in goreleaser I had to search through issues.
Issue: #2137

docs: added documentation for post_install step in homebrew section

---

internal/pipe/git/errors.go
internal/pipe/git/git.go
internal/pipe/git/git_test.go

closes https://github.com/goreleaser/goreleaser/issues/2134

feat: fail on shallow clone

---

internal/builders/golang/build_test.go
internal/builders/golang/targets.go
internal/builders/golang/targets_test.go

closes https://github.com/goreleaser/goreleaser/issues/2143

fix: build windows/arm

---

www/docs/overrides/home.html
www/mkdocs.yml

- Add support for dark mode in documentation (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle)
- Use instant navigation to increase page performance

docs: tune performance and theming of documentation

---

.goreleaser.yml
internal/middleware/error.go
internal/middleware/error_test.go
internal/middleware/logging.go
internal/pipe/artifactory/artifactory.go
internal/pipe/blob/blob.go
internal/pipe/brew/brew.go
internal/pipe/changelog/changelog.go
internal/pipe/checksums/checksums.go
internal/pipe/checksums/checksums_test.go
internal/pipe/custompublishers/custompublishers.go
internal/pipe/docker/docker.go
internal/pipe/gomod/gomod.go
internal/pipe/milestone/milestone.go
internal/pipe/pipe.go
internal/pipe/pipe_test.go
internal/pipe/release/release.go
internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go
internal/pipe/snapshot/snapshot.go
internal/pipe/sourcearchive/source.go
internal/pipe/upload/upload.go
www/docs/customization/gomod.md

no need to show a warning when skipping a pipe because it is disabled...

fix: improve output a bit

---

go.mod
go.sum
internal/client/github.go
pkg/config/config.go
www/docs/customization/release.md

closes https://github.com/goreleaser/goreleaser/issues/2161

feat: create discussions from releases

---

internal/pipe/gomod/gomod.go

should really close that reader...

fix: fd leak on gomod pipe

---

internal/artifact/artifact_test.go
internal/client/gitea_test.go
internal/http/http_test.go
internal/pipe/archive/archive_test.go
internal/pipe/artifactory/artifactory_test.go
internal/pipe/brew/brew_test.go
internal/pipe/checksums/checksums_test.go
internal/pipe/dist/dist_test.go
internal/pipe/docker/docker_test.go
internal/pipe/env/env_test.go
internal/pipe/git/git_test.go
internal/pipe/nfpm/nfpm_test.go
internal/pipe/release/release_test.go
internal/pipe/snapcraft/snapcraft_test.go
internal/pipe/upload/upload_test.go
pkg/archive/archive_test.go
pkg/archive/gzip/gzip_test.go
pkg/archive/targz/targz_test.go
pkg/archive/tarxz/tarxz_test.go
pkg/archive/zip/zip_test.go
pkg/config/config_test.go

fix a bunch of file descriptor leaks on tests.
found most of them while trying to make tests pass on windows, which complains about them...

fix: several fd leaks (on tests)

---

www/docs/customization/docker.md

Fixed a typo in docker.md
Fixing a typo in the docs

docs: fixes typo in docker.md

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/lock.yml
.github/workflows/misspell.yml

Follow-up dependabot/dependabot-core#3704

fix(ci): pin actions to major

---

cmd/check.go
cmd/check_test.go
www/docs/cmd/goreleaser_check.md

feat: check -q

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go

Reverts goreleaser/goreleaser#2193
closes #2203

fix: revert "fix: skip releasing to brew when skipping publishing"

---

internal/pipe/sign/sign.go
internal/pipe/sign/sign_test.go
www/docs/customization/sign.md

refs #1802
allow more options on `artifacts`.

feat: fine grained sign

---

internal/pipe/sign/sign.go
internal/pipe/sign/sign_test.go
internal/pipe/sign/testdata/README.md
www/docs/customization/sign.md

feat: allow to template signs[].signature 

---

cmd/release.go
cmd/release_test.go
internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go
pkg/context/context.go
www/docs/cmd/goreleaser_release.md

closes https://github.com/goreleaser/goreleaser/issues/2196

feat: template release notes

---

internal/pipe/env/env.go
internal/pipe/env/env_test.go
www/docs/customization/env.md

feat: env template support 

---

www/docs/ci/actions.md
www/docs/cmd/goreleaser_release.md
www/docs/customization/hooks.md
www/docs/customization/includes.md
www/docs/customization/monorepo.md
www/docs/customization/release.md
www/docs/customization/templates.md
www/docs/install.md
www/docs/overrides/home.html
www/docs/pro.md
www/docs/sponsors.md
www/mkdocs.yml

docs: goreleaser-pro

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go
internal/pipe/brew/template.go
internal/pipe/brew/testdata/custom_block.rb.golden
internal/pipe/brew/testdata/custom_download_strategy.rb.golden
internal/pipe/brew/testdata/custom_require.rb.golden
internal/pipe/brew/testdata/default.rb.golden
internal/pipe/brew/testdata/default_gitlab.rb.golden
internal/pipe/brew/testdata/foo_is_bar.rb.golden
internal/pipe/brew/testdata/multiple_armv5.rb.golden
internal/pipe/brew/testdata/multiple_armv6.rb.golden
internal/pipe/brew/testdata/multiple_armv7.rb.golden
internal/pipe/brew/testdata/test.rb.golden
internal/pipe/brew/testdata/test_linux_only.rb.golden

closes https://github.com/goreleaser/goreleaser/issues/2159
would be amazing if someone can help testing this 🙏

fix: improve brew formula

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go
pkg/config/config.go
www/docs/customization/build.md

feat: build tags

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
www/docs/customization/homebrew.md
www/docs/customization/nfpm.md

allow to template more fields in the nfpm pipe...

feat(nfpm): template homepage and description

---

internal/exec/exec.go
internal/exec/exec_mock.go
internal/exec/exec_test.go
www/docs/customization/hooks.md
www/docs/customization/publishers.md

closes https://github.com/goreleaser/goreleaser/issues/2201

fix(publishers): inherit some system variables

---

.github/workflows/build.yml
cmd/release.go
cmd/release_test.go
internal/pipe/git/git.go
www/docs/cmd/goreleaser_release.md

feat: --auto-snapshot on dirty git tree

---

internal/pipe/docker/docker_test.go
internal/pipe/docker/manifest.go
pkg/config/config.go
www/docs/customization/docker.md
www/docs/customization/docker_manifest.md

feat: docker_manifests.skip_push

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
pkg/config/config.go
www/docs/customization/nfpm.md

Binds the NFPM APK support for pre/post upgrade scripts to goreleaser customization.

feat(nfpm): add support for APK pre/post upgrade scripts

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
pkg/config/config.go
www/docs/deprecations.md

remove options deprecated for more than 6 months

feat: remove some nfpm deprecated options

---

www/docs/customization/docker_manifest.md

Align docs with [deprecation notice](https://goreleaser.com/deprecations/#dockeruse_buildx).

docs: update use buildx syntax

---

internal/pipe/blob/blob_minio_test.go
internal/pipe/blob/upload.go

add tests to #2373 
closes #2373

fix: upload gcs blobs to bucket root

---

internal/git/config.go
internal/git/config_test.go

fix: prevent panic on invalid git remote url

---

.goreleaser.yml
go.mod
go.sum
internal/pipe/announce/announce.go
internal/pipe/reddit/reddit.go
internal/pipe/reddit/reddit_test.go
pkg/config/config.go
pkg/defaults/defaults.go
www/docs/customization/announce.md

add Reddit support to the Announces, and fix #2424 
to add Reddit support
https://www.reddit.com/r/test/comments/pbtik1/goreleaser_v1123_was_just_released_get_it_while/
https://github.com/developer-guy/goreleaser/runs/3429508179?check_suite_focus=true

feat: announce: reddit

---

www/docs/ci/gitlab.md

fix #2427 
to link related pages in order to provide a better UX.

style(ci): enhance Gitlab documentation

---

www/docs/install.md

to be merged only after the next release
refs https://github.com/goreleaser/goreleaser/commit/c100de32a3b63668c469d2c95acefafaf107584a

docs: update check instructions

---

internal/static/config.go

Update the default config template.

fix: link in example config to https

---

www/docs/ci/actions.md

Follow-up goreleaser/goreleaser-action#302

docs: ghaction-import-gpg v4

---

go.mod
go.sum
internal/pipe/announce/announce.go
internal/pipe/discord/discord.go
internal/pipe/discord/discord_test.go
pkg/config/config.go
pkg/defaults/defaults.go
www/docs/customization/announce.md
www/htmltest.yml

Fix #2477 
To have Discord as additonal announce channel.

feat: announce: discord

---

go.mod
go.sum
internal/pipe/announce/announce.go
internal/pipe/teams/teams.go
internal/pipe/teams/teams_test.go
pkg/config/config.go
pkg/defaults/defaults.go
www/docs/customization/announce.md
www/htmltest.yml

Signed-off-by: Engin Diri engin.diri@mail.schwarz
Fix #2481 
MS Teams as new announcer for all things enterprise 😄 
Test Announcement:

feat: announce: teams

---

internal/git/config.go
internal/git/config_test.go
internal/pipe/milestone/milestone_test.go
internal/pipe/release/release_test.go
internal/testlib/git.go

Co-authored-with: Erkan Zileli <erkan.zileli@trendyol.com>
Co-authored-with: Furkan Türkal <furkan.turkal@trendyol.com>
to use the correct remote name of the current branch #2486
...

feat: use correct remote name of the current branch

---

.github/workflows/build.yml
internal/pipe/docker/api_docker.go
internal/pipe/docker/docker.go
internal/pipe/docker/docker_test.go

Signed-off-by: Erkan Zileli <erkan.zileli@trendyol.com>
Co-authored-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
fixes #2491

fix(buildpacks): add if check when copying Dockerfile

---

scripts/entrypoint.sh

Signed-off-by: Artur Troian <troian.ap@gmail.com>

fix: run goreleaser via exec to handle ctrl+c

---

vercel.json
www/htmltest.yml

closes https://github.com/goreleaser/goreleaser/issues/2519

docs: fix trailing slashes

---

internal/artifact/artifact.go
internal/artifact/artifact_test.go
internal/golden/golden.go
internal/pipe/gofish/doc.go
internal/pipe/gofish/food_template.go
internal/pipe/gofish/gofish.go
internal/pipe/gofish/gofish_test.go
internal/pipe/gofish/testdata/TestFullFood.lua.golden
internal/pipe/gofish/testdata/TestFullFoodLinuxOnly.lua.golden
internal/pipe/gofish/testdata/TestFullFoodWindowsOnly.lua.golden
internal/pipe/gofish/testdata/TestFullPipe/default.lua.golden
internal/pipe/gofish/testdata/TestFullPipe/default_gitlab.lua.golden
internal/pipe/gofish/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.lua.golden
internal/pipe/gofish/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.lua.golden
internal/pipe/gofish/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.lua.golden
internal/pipe/gofish/testdata/TestRunPipeNameTemplate.lua.golden
internal/pipe/publish/publish.go
internal/pipeline/pipeline.go
pkg/config/config.go
pkg/defaults/defaults.go
www/docs/customization/gofish.md
www/htmltest.yml
www/mkdocs.yml

This PR adds the support for [GoFish](https://gofi.sh/). I recently wanted to publish my minectl project to GoFish, and while checking for open issues for GoFish support i stumbeled over this #2420.
So I created the GoFish integration.
I hope its okay. 😄

feat: publish: GoFish integration

---

internal/pipe/announce/announce.go
internal/pipe/mattermost/mattermost.go
internal/pipe/mattermost/mattermost_test.go
pkg/config/config.go
pkg/defaults/defaults.go
www/docs/customization/announce/mattermost.md

Add mattermost to the announcements 
Test Announcement:

feat: announce: mattermost

---

www/docs/overrides/home.html
www/docs/quick-start.md

Fix some commands and enhance documents on the webpage.

feat: some little fixes on the webpage

---

internal/pipe/blob/blob.go
internal/pipe/blob/blob_minio_test.go
internal/pipe/blob/blob_test.go
internal/pipe/blob/upload.go

speed up blob minio tests consirable.

test: speed up minio tests

---

.goreleaser.yml

Follow-up goreleaser/goreleaser-action#308

feat: publish arm v7 variant

---

USERS.md

docs: add USERS.md to track users of goreleaser

---

internal/pipe/discord/discord.go
internal/pipe/mattermost/mattermost.go
internal/pipe/reddit/reddit.go
internal/pipe/slack/slack.go
internal/pipe/smtp/smtp.go
internal/pipe/teams/teams.go
internal/pipe/telegram/telegram.go
internal/pipe/twitter/twitter.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
www/docs/customization/announce/discord.md
www/docs/customization/announce/index.md
www/docs/customization/announce/mattermost.md
www/docs/customization/announce/reddit.md
www/docs/customization/announce/slack.md
www/docs/customization/announce/smtp.md
www/docs/customization/announce/teams.md
www/docs/customization/announce/telegram.md
www/docs/customization/announce/twitter.md
www/docs/customization/templates.md

Fixes #2622
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
Co-authored-by: Batuhan <batuhan.apaydin@trendyol.com>
Co-authored-by: Erkan <erkan.zileli@trendyol.com>
...
...
...

fix: remove .git suffix by default from announcers

---

www/docs/users.md

Adds [Compose Generator](https://github.com/compose-generator/compose-generator) to the list of users. It drastically increases the build, deployment and release flow for us.
All the best for this awesome project. Way underrated imho ;)

docs: Add Compose Generator to list of users

---

www/docs/ci/azurepipelines.md

doc: add GoReleaser Extensions for Azure DevOps to docs

---

.goreleaser.yml

Fixes: #2635 
cc: @developer-guy @Dentrax

feat(ci): add cosign public key to releases

---

internal/client/client.go
internal/client/github.go
internal/client/github_test.go
internal/client/mock.go
internal/client/testdata/github/releasenotes.json
internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go
www/docs/customization/changelog.md

feat: support github release notes

---

internal/client/client.go
internal/client/client_test.go
internal/client/github.go

fix: [Bug]: changelog is too long

---

internal/artifact/artifact.go
internal/artifact/artifact_test.go
internal/exec/exec.go
internal/exec/exec_test.go
internal/http/http.go
internal/http/http_test.go
internal/pipe/blob/blob_minio_test.go
internal/pipe/blob/upload.go
internal/pipe/env/env.go
internal/pipe/release/release.go
internal/pipe/release/release_test.go
internal/pipe/sign/sign.go
internal/pipe/sign/sign_docker_test.go
internal/pipe/sign/sign_test.go
pkg/config/config.go
pkg/context/context.go
pkg/context/context_test.go
www/docs/customization/docker_sign.md
www/docs/customization/sign.md

feat: sign with env and output certificate

---

.github/workflows/build.yml
go.mod
go.sum
pkg/config/config.go
www/docs/customization/nfpm.md
www/docs/deprecations.md

- update nfpm
- test package on main

feat: update nfpm to 2.9.2

---

www/docs/static/schema.json

- schema: add env to the sign schema
/assign @caarlos0

fix: add env to the sign schema

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go

feat: allow to template main

---

scripts/vercel/build.sh
www/docs/install.md

replace `__VERSION__` with the actual git tag on install instructions, so we can give better instructions :)

docs: fix version in docs

---

USERS.md

Fleet's `.goreleaser.yml`: https://github.com/fleetdm/fleet/blob/main/.goreleaser.yml

docs: Add Fleet to USERS.md

---

internal/extrafiles/extra_files.go
internal/extrafiles/extra_files_test.go
internal/pipe/blob/upload.go
internal/pipe/checksums/checksums.go
internal/pipe/release/release.go
www/docs/customization/blob.md
www/docs/customization/checksum.md
www/docs/customization/release.md

feat: template on extra_files

---

internal/pipe/checksums/checksums.go
internal/pipe/checksums/checksums_test.go

fix: checksum extra_files when no builds

---

.golangci.yml
internal/pipe/krew/krew.go
internal/pipe/snapcraft/snapcraft.go
pkg/config/config.go

closes #2688
added some validations as well, but seems like it doesn't get missing keys (https://github.com/ldez/tagliatelle/issues/6)

fix: jsonschema field names

---

internal/pipe/docker/api.go
internal/pipe/docker/api_buildpack.go
internal/pipe/docker/api_docker.go
internal/pipe/docker/docker.go
internal/pipe/docker/docker_test.go

Fixes #2585 
Tasks:
@developer-guy @caarlos0 this is working but I'm not sure if it's the best approach, please fell free to comment and ask for changes.
Signed-off-by: pedro.lopez.mareque@gmail.com

Adding top level environment variables within env section in docker section

---

internal/client/gitea.go
internal/client/github.go
internal/client/gitlab.go
internal/client/release_notes.go
internal/client/release_notes_test.go
pkg/config/config.go
www/docs/customization/release.md
www/docs/static/schema.json

feat: allow to customize release notes update behavior

---

internal/git/git.go
internal/pipe/git/git_test.go
internal/testlib/git.go

it seems this is not really used...

refactor: remove unused git.RunEnv

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go
www/docs/errors/no-main.md
www/mkdocs.yml

refs https://github.com/goreleaser/goreleaser-action/issues/317

feat: no main error page

---

internal/pipe/release/body.go
internal/pipe/release/body_test.go
internal/pipe/release/testdata/TestDescribeBody.golden
internal/pipe/release/testdata/TestDescribeBodyWithHeaderAndFooter.golden

Rationale is in #2707, just opening it here fwiw
closes #2707

feat: remove docker images from changelog

---

www/docs/customization/docker_sign.md
www/docs/customization/sign.md

Update documentation for the signing part using cosign using the updated flags

update documentation for signing when using cosign

---

internal/pipe/sign/sign_docker.go
internal/pipe/sign/sign_docker_test.go

fix: double-dash cosign flags

---

.github/workflows/milestone.yml

copied from sigstore... auto-assign milestone to merged PRs :)

chore(ci): auto-assign milestone

---

cmd/init.go

chore: rename yml to yaml in init command

---

internal/pipe/env/env.go
internal/pipe/env/env_test.go
www/docs/errors/multiple-tokens.md
www/mkdocs.yml

- improve error message
- adds an error page detailing how to fix it
resolves #2732

feat: improve multiple tokens error

---

.github/dependabot.yml
.github/workflows/milestone.yml

- actions dep updates should use `chore` as scope
- update github-script version and code

chore(deps): update milestone and dependabot config

---

.github/workflows/codeql.yml

improve scorecard scores, hopefully.

chore(ci): run codeql analysis

---

internal/pipe/scoop/scoop_test.go

test: improve scoop tests

---

.github/workflows/build.yml

chore(ci): use download syft action

---

internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go
pkg/config/config.go
www/docs/customization/changelog.md

fix: do not group changelog when using github-native

---

internal/pipe/artifacts/artifacts.go
internal/pipe/artifacts/artifacts_test.go

fix: artifacts.json should be 0644 instead of 0600

---

USERS.md

Add prestd on users file

---

internal/pipe/defaults/defaults.go

feat: less logs for defaults

---

go.mod
go.sum
internal/client/github.go

just because I saw its outdated :)

feat(deps): update go-github to v41

---

internal/pipe/docker/docker.go
internal/pipe/docker/docker_test.go
www/docs/customization/docker.md

feat: allow to template dockerfile

---

internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go

also refactored implementation and added more tests
refs #2802

fix: do not filter and sort github-native changelog

---

internal/client/gitlab.go
internal/client/gitlab_test.go

refs #2745
- avoid one duplicated if
- added some tests for package registry

refactor: improve gitlab cli a bit

---

go.mod
go.sum
internal/pipe/reddit/reddit.go

closes https://github.com/goreleaser/goreleaser/issues/2822
see https://github.com/vartanbeno/go-reddit/issues/26
not much I can do besides this

fix: go install and go-reddit

---

internal/client/gitea.go

fix: linter issues after gotea update

---

.gitignore
.goreleaser.yaml
cmd/docs.go
cmd/man.go
cmd/root.go
go.mod
go.sum
scripts/manpages.sh

generate and distribute goreleaser's man page using the awesome mango by @muesli 🙏

feat: manpages

---

www/docs/how-it-works.md

... update the `www/docs/how-it-works.md` file with different grammar in first sentence and format with `prettier www/docs/how-it-works.md --write --prose-wrap always --parser markdown`
...
...

chore: update grammar in markdown

---

internal/pipe/aur/aur.go
internal/pipe/aur/aur_test.go
internal/pipe/aur/testdata/TestFullPipe/default-gitlab.pkgbuild.golden
internal/pipe/aur/testdata/TestFullPipe/default-gitlab.srcinfo.golden
internal/pipe/aur/testdata/TestFullPipe/default.pkgbuild.golden
internal/pipe/aur/testdata/TestFullPipe/default.srcinfo.golden
internal/pipe/aur/testdata/TestFullPipe/with-more-opts.pkgbuild.golden
internal/pipe/aur/testdata/TestFullPipe/with-more-opts.srcinfo.golden

fixes aur pkgbuilds, versions should be numbers only.

fix(aur): version must be numbers only

---

www/docs/customization/nfpm.md

Example on documentation of extended description to be compliant with Debian packaging.

Two line "extended" description

---

Dockerfile

This adds gpg to the Docker image for signing of Artifacts (see https://github.com/goreleaser/goreleaser/issues/2904 )

feat: add gpg to Docker image for signing of artifacts

---

Dockerfile

update from v1.4.1 to v1.5.1  cc/ @cpanato

feat: update docker image's cosign

---

www/docs/customization/homebrew.md

This commit is a simple correction to the new style of Homebrew generate formulas based on a recent formula this tool generated for one of my projects. After checking the documentation, I found the README had not yet been updated.
This change is to bring the documentation inline with what the output of a Homebrew generated formula will look like.

fix: Homebrew README example formula

---

internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
www/docs/customization/templates.md

this adds `grep` and `reverseGrep` template functions, which should help dealing with text.  
refs #2920

feat: add filter and reverseFilter template functions

---

internal/pipe/aur/aur.go
internal/pipe/aur/aur_test.go

make sure it has the right permissions and improve error messages  
refs https://github.com/goreleaser/goreleaser-action/issues/326

fiX: improve aur key handling

---

go.mod
go.sum

upgrade from v2.13.0 to v2.14.0

feat(deps): upgrade nfpm to v2.14.0

---

go.mod
go.sum
internal/client/github.go

Signed-off-by: Carlos A Becker <caarlos0@gmail.com>

feat: update go-github to v43

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go
internal/pipe/brew/template.go
internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
internal/pipe/brew/testdata/TestFullPipe/valid_tap_templates.rb.golden
pkg/config/config.go
www/docs/customization/homebrew.md

closes https://github.com/goreleaser/goreleaser/issues/2970

feat: brew service block

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go
internal/pipe/brew/template.go
internal/pipe/brew/testdata/TestFullFormulae.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
internal/pipe/brew/testdata/TestFullPipe/valid_tap_templates.rb.golden

properly indent brews.post_install block, and also fix indent on newly added brews.service block.  closes #2980

fix: brew.post_install indent

---

.github/workflows/build.yml
CONTRIBUTING.md
Dockerfile
cmd/util_test.go
go.mod
go.sum
internal/builders/buildtarget/targets_test.go
internal/builders/golang/build_test.go
internal/pipe/before/before_test.go
internal/pipe/docker/docker_test.go
internal/pipe/gomod/gomod_proxy_test.go
www/docs/ci/actions.md
www/docs/ci/azurepipelines.md
www/docs/ci/circle.md
www/docs/ci/codefresh.md
www/docs/contributing.md

feat: upgrade to go 1.18

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/generate.yml
.github/workflows/lint.yml
internal/pipe/sbom/sbom.go
internal/pipe/sbom/sbom_test.go
internal/tmpl/tmpl.go
pkg/context/context.go

moved more workflows to go 1.18, switched some code to strings.Cut

feat: more go 1.18

---

go.mod
go.sum

feat: update nfpm to v2.15.0

---

www/docs/scm/gitlab.md

Just a simple spelling fix
Fix a simple typo
Typo/Spelling issue
N/A

Typo in gitlab.md

---

go.mod
internal/pipe/effectiveconfig/config.go
internal/pipe/krew/krew.go
internal/pipe/krew/testdata/TestFullManifest.yaml
internal/pipe/krew/testdata/TestFullPipe/default.yaml
internal/pipe/krew/testdata/TestFullPipe/default_gitlab.yaml
internal/pipe/krew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.yaml
internal/pipe/krew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.yaml
internal/pipe/krew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.yaml
internal/pipe/krew/testdata/TestRunPipeNameTemplate.yaml
internal/pipe/krew/testdata/TestRunPipeUniversalBinary.yaml
internal/pipe/krew/testdata/TestRunPipeUniversalBinaryNotReplacing.yaml
internal/pipe/krew/testdata/TestSimple.yaml
internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
internal/yaml/yaml.go
internal/yaml/yaml_test.go
pkg/config/config.go
pkg/config/config_archive_files_test.go
pkg/config/config_array_test.go
pkg/config/config_build_hook_test.go

* fixes #3005 
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>
...
...
...

feat(yaml): upgraded from yaml.v2 to yaml.v3

---

internal/pipe/universalbinary/universalbinary.go
internal/pipe/universalbinary/universalbinary_test.go

Ensure the new ID is set, and add a test to prevent the bug from happening again.  closes #3027

fix: use universal binary id

---

internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go

refactor: improve scoop tests

---

Dockerfile

Pinned dependencies reduce several security risks:
They ensure that checking and deployment are all done with the same software, reducing deployment risks, simplifying debugging, and enabling reproducibility.
They can help mitigate compromised dependencies from undermining the security of the project (in the case where you've evaluated.
https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies

Updated docker file - Pined by SHA

---

.github/workflows/build.yml

switch back to main krew as my PR was recently released.

fix(ci): dont use krew fork

---

internal/pipe/docker/docker_test.go

Port 5000 is used by MacOS Monterey for Airplay Receiver by default.
https://developer.apple.com/forums/thread/682332

Change test docker registry port numbers

---

Dockerfile

feat: adds openssh-client to docker images

---

www/docs/cookbooks/using-jfrog-cli-to-publish-to-artifactory.md
www/docs/customization/snapshots.md
www/docs/errors/resource-not-accessible-by-integration.md
www/docs/pro.md
www/htmltest.yml

- help and docs github subdomains are giving 403
- fixed actual broken link

docs: fix several htmltest issues

---

internal/client/github.go

find existing draft release by list all releases
otherwise it don't update exiting draft release, but create a duplicated one.
Closes: #3072

fix: update existing release drafts

---

www/docs/overrides/home.html

update homepage documentations
to tell people about new features supported in goreleaser such as sbom
...

docs(website): add SBOM section, update Docker as container

---

go.mod
go.sum
internal/client/github.go

feat: update go-github from v44 to v45

---

www/docs/ci/actions.md
www/docs/cookbooks/release-a-library.md
www/docs/customization/env.md
www/docs/customization/monorepo.md
www/docs/customization/nightlies.md
www/docs/customization/verifiable_builds.md
www/docs/quick-start.md
www/docs/scm/github.md
www/docs/scm/gitlab.md
www/mkdocs.yml

This is a set of minor docs improvements.
I'm experimenting with goreleaser to see if I can use it with [DDEV](https://github.com/drud/ddev). I think I can. But I read through the (outstanding) docs a couple of times and thought that I could make some contributions as a native English speaker. There were a few phrases and usages that were not expected standard English. You can keep or not keep anything you like of course.

[docs] Miscellaneous usage improvements

---

pkg/config/config.go
www/docs/static/schema.json

fix: wrap_in_directory type

---

cmd/schema.go
cmd/schema_test.go
go.mod
go.sum
pkg/config/config.go
www/docs/static/schema.json

alecthomas' moved it to this new owner.

feat: update jsonschema library

---

.github/gitleaks.toml
.github/workflows/gitleaks.yml

updates and fixes gitleaks workflow

fix(ci): gitleaks license

---

cmd/build.go
cmd/release.go
cmd/root.go
internal/artifact/artifact.go
internal/artifact/artifact_test.go
internal/artifact/testdata/TestMarshalJSON.json.golden
internal/pipe/metadata/metadata.go
internal/pipe/metadata/testdata/TestRun/artifacts.json.golden
pkg/context/context.go

some small refactories to make it easy to add new feature 👀

refactory: make easier to manage merges with pro

---

cmd/build.go
cmd/release.go
internal/pipe/before/before.go
internal/pipe/before/before_test.go
internal/pipe/docker/docker_test.go
pkg/context/context.go

this would allow to skip global before hooks

feat: added --skip-before flag

---

www/docs/customization/archive.md

Typo in archive.md

---

internal/pipe/blob/upload.go

fix: blob upload eating errors

---

.github/workflows/build.yml
scripts/test.sh

properly handle errors and be less verbose as well.

chore(ci): improve tparse output

---

www/docs/customization/aur.md

TYPO from copy-pasta in AUR section.

Fix mistaken mention of homebrew in AUR section

---

www/docs/customization/nfpm.md
www/docs/customization/release.md

Fix a few small typos in the docs.

docs: fix typos

---

www/docs/ci/actions.md

docs: update wrong permission key

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go
internal/pipe/build/build_test.go
pkg/config/config.go
www/docs/customization/build.md

feat: allow to override env for a target

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go

I some how had coded this while dreaming, I think... I was 100% sure I done it... and couldn't find it anywhere... so I wrote it again.
Sorry for the horrendous bug, last week was crazy and I lost track of some things.
closes #3230
refs #3119
refs #3201

fix: build env overrides

---

Dockerfile

feat(deps): update cosign to 1.10.0

---

www/docs/customization/aur.md

This is a good way to skip publish on a test account, for example
...
...
...

Note that AUR publish is skipped if aur git url is empty

---

scripts/entrypoint.sh

feat: login into gitlab registry

---

go.mod
go.sum
internal/client/github.go

feat(deps): update github to v46

---

.github/workflows/grype.yml
.grype.yaml

it fails on some symlinks with no targets that are using for testing.

fix: grype ignore testdata

---

.github/workflows/gitleaks.yml
.github/workflows/grype.yml
.gitleaks.toml

fix: run gitleaks and grype on prs

---

internal/semerrgroup/sem.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
...
...
...

chore: remove duplicate word in comments

---

www/docs/intro.md

fix: insert missing word

---

.github/workflows/build.yml

chore(ci): govulncheck

---

.goreleaser.yaml

https://fishshell.com/docs/current/completions.html#where-to-put-completions

fix: fish completions path on nfpm

---

www/docs/install.md

Cross-ref: https://github.com/fluxcd/source-controller/issues/899

fix: add COSIGN_EXPERIMENTAL=1 for verify-blob

---

Dockerfile

fix(deps): update cosign to v1.12.1

---

USERS.md

docs: add trendyol.com to users

---

USERS.md

This counts for my hacktoberfest contribution right?

Add Gitleaks.io to list of users

---

USERS.md

docs: Add Ayedo to Users.md

---

.github/workflows/fig.yml

feat: fig integration

---

internal/pipe/aur/aur.go
internal/pipe/aur/aur_test.go
internal/pipe/aur/testdata/TestFullAur.golden
internal/pipe/aur/tmpl.go
pkg/config/config.go
www/docs/customization/aur.md

feat: aur backup

---

internal/pipe/blob/blob_test.go
internal/pipe/blob/upload.go
www/docs/customization/blob.md

feat: more templateable fields for blobs

---

internal/pipe/publish/publish.go

closes https://github.com/goreleaser/goreleaser/discussions/3472

fix: change publishers order a bit

---

go.mod
go.sum
internal/client/github.go

fix(deps): update to go-github v48

---

go.mod
go.sum

fix: unknown revision when installing with go install

---

www/docs/ci/woodpecker.md
www/mkdocs.yml

This PR adds [woodpecker](https://woodpecker-ci.org) to the CI docs.

feat: add woodpecker ci

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/fig.yml
.github/workflows/generate.yml
.github/workflows/lint.yml
.github/workflows/release.yml
www/docs/ci/actions.md

feat: update to go 1.19.3

---

internal/client/config.go
internal/client/config_test.go
internal/pipe/brew/brew.go
internal/pipe/krew/krew.go
internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go
www/docs/customization/homebrew.md
www/docs/customization/krew.md
www/docs/customization/scoop.md

closes #3508
- adds template support for krew and scoop repo refs
- template branch on reporef on brew as well

fix: allow to template scoop/brew/krew repo ref

---

www/docs/contributing.md

Update contributing doc to include Syft
Help contributors prevent errors with `task test`

docs: add Syft to contributing docs

---

www/docs/errors/dirty.md

Fixes wording in the docs page about Git being in a dirty state.
The goal is to improve the end-user reading of the instructions.
...

chore(docs): Fix wording

---

internal/pipe/artifactory/artifactory.go
internal/pipe/artifactory/artifactory_test.go

fix: improve artifactory error handling

---

USERS.md

[Mercure](https://mercure.rocks), an open solution for real-time communications designed to be fast, reliable and battery-efficient is a proud user of GoReleaser.

Add Mercure to users

---

internal/pipe/docker/docker.go
internal/pipe/docker/docker_test.go
www/docs/customization/docker.md

fix: set dockers.goarm to 6 by default

---

.github/workflows/release.yml
.goreleaser.yaml

actually announce goreleaser releases to mastodon as well :)

chore: announce goreleaser releases to mastodon

---

www/docs/pro.md

achives -> archives
...
...
...

chore: fix typo in pro docs

---

.github/workflows/lock.yml

Update lock task due to breaking changes 
https://github.com/dessant/lock-threads/blob/master/CHANGELOG.md#changelog
Updated the properties
...

feat: update lock task parameter due to braking change

---

www/docs/ci/actions.md
www/docs/cookbooks/override-image-name.md
www/docs/errors/resource-not-accessible-by-integration.md

Using the new version (v4) everywhere.

docs: update github-action documentation

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/docs.yml
.github/workflows/fig.yml
.github/workflows/generate.yml
.github/workflows/lint.yml
.github/workflows/release.yml
www/docs/ci/actions.md

feat(deps): build with go 1.19.4

---

go.mod
go.sum
internal/pipe/blob/blob_minio_test.go
internal/pipe/docker/docker_test.go
internal/testlib/docker.go

using ory/dockertest to simplify integration tests

feat: improving minio and docker tests

---

internal/pipe/env/env.go

this just helps debugging issues like #3661

fix: log which token will be used

---

cmd/release.go
internal/client/mock.go
internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go
internal/pipe/git/git.go
internal/pipe/git/git_test.go
pkg/context/context.go

fix: native changeloger without previous tag

---

internal/pipe/changelog/changelog.go

revert a bit of the changes made in #3668 to improve mergeability with pro.

fix: improve changelog a bit

---

Taskfile.yml
scripts/vercel/build.sh
scripts/vercel/install.sh
vercel.json

merge after 48h to ensure DNS is propagated.
before merging, delete site on vercel.com
refs https://github.com/goreleaser/goreleaser/issues/3502

docs: remove vercel

---

internal/pipe/telegram/telegram.go
internal/pipe/telegram/telegram_test.go
pkg/config/config.go
www/docs/customization/announce/telegram.md

feat: allow to template telegram.chat_id

---

internal/pipe/gomod/gomod_proxy.go
internal/pipe/gomod/gomod_proxy_test.go

Thanks for the suggestions @mvdan!
refs https://github.com/goreleaser/goreleaser/issues/3624

refactor: improve go mod proxy usage

---

internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
www/docs/customization/snapcraft.md

refs https://github.com/charmbracelet/meta/commit/d73320559b8ea7eafe53e09f4322c3ee0ee9d2a8

feat: allow to template snaps.grade

---

internal/pipe/env/env.go
internal/pipe/env/env_test.go
internal/pipe/publish/publish_test.go
internal/pipe/release/release.go
internal/pipe/release/release_test.go
internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go
pkg/config/config.go
www/docs/customization/release.md

closes https://github.com/goreleaser/goreleaser/issues/3705

feat: allow to template release.disable and releaser.skip_upload

---

internal/middleware/skip/skip.go
internal/middleware/skip/skip_test.go
internal/pipe/announce/announce.go
internal/pipe/announce/announce_test.go
internal/pipe/env/env.go
internal/pipe/env/env_test.go
internal/pipe/release/release.go
internal/pipe/release/release_test.go
internal/pipe/scoop/scoop.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go

this tries to unify the way we check for bools coming from templates... there's a bunch more places to refactor though.

refactor: improve tmpls that eval to a bool

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/docs.yml
.github/workflows/fig.yml
.github/workflows/generate.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.golangci.yaml
CONTRIBUTING.md
Dockerfile
cmd/util_test.go
go.mod
internal/pipe/gomod/gomod_proxy_test.go
internal/pipe/ko/testdata/app/go.mod
internal/pipe/sign/sign_test.go
www/docs/ci/actions.md
www/docs/ci/azurepipelines.md
www/docs/ci/circle.md
www/docs/ci/codefresh.md
www/docs/contributing.md

build: use go1.20 

---

www/docs/customization/snapcraft.md

update snapcraft doc supported interfaces ref link

docs: update ref links

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go

fix: nfpm replacements deprecation

---

internal/pipe/scoop/scoop.go
pkg/config/config.go
www/docs/customization/scoop.md
www/docs/static/schema.json

feat: scoop depends

---

internal/gio/copy.go

fix: convert to forward slashes inside gio.Copy

---

internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go

fix: meta archives make the other archives be ignored

---

go.mod
go.sum
internal/pipe/discord/discord.go
internal/pipe/linkedin/linkedin.go
internal/pipe/mastodon/mastodon.go
internal/pipe/mattermost/mattermost.go
internal/pipe/opencollective/opencollective.go
internal/pipe/reddit/reddit.go
internal/pipe/slack/slack.go
internal/pipe/smtp/smtp.go
internal/pipe/teams/teams.go
internal/pipe/telegram/telegram.go
internal/pipe/twitter/twitter.go
internal/pipe/webhook/webhook.go

feat(deps): update env to v7

---

internal/pipe/smtp/smtp.go
internal/pipe/smtp/smtp_test.go
www/docs/customization/announce/smtp.md

it was forcing to provide the same information as env and yaml.
this should fix it.

fix: smtp mixup of env and yaml opts

---

www/docs/errors/release-upload.md

Hello, I found a number error in the document when I consulted the document, so I propose a pr to fix it

typo: document number error

---

pkg/context/context.go

this is not being used, so... let's delete

fix: remove unused field

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
www/docs/customization/templates.md

feat: ConventionalExtension on nFPM

---

.goreleaser.yaml
internal/pipe/sign/sign_docker.go
internal/pipe/sign/sign_docker_test.go
www/docs/customization/docker_sign.md
www/docs/customization/sign.md
www/docs/install.md
www/docs/static/run

cosign v2 update!
- need to use `--yes` to auto-approve prompts
cc/ @cpanato anything else I'm missing?

feat: cosign update

---

internal/artifact/artifact_test.go
internal/builders/golang/build_test.go
internal/pipe/artifactory/artifactory_test.go
internal/pipe/aur/aur_test.go
internal/pipe/changelog/changelog_test.go
internal/pipe/checksums/checksums_test.go
internal/pipe/metadata/metadata_test.go
internal/pipe/nfpm/nfpm_test.go
internal/pipe/sign/sign_test.go
internal/pipe/upload/upload_test.go

using `errors.Is` everywhere, as file not found errors have different messages on different OSes.

test: improve file not found checkings

---

internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
www/docs/customization/templates.md

feat: add base template function

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/docs.yml
.github/workflows/fig.yml
.github/workflows/generate.yml
.github/workflows/lint.yml
.github/workflows/release.yml
Dockerfile
www/docs/ci/actions.md

new vuln in town https://pkg.go.dev/vuln/GO-2023-1621

fix(GO-2023-1621): update from go 1.20.1 to 1.20.2

---

www/docs/customization/archive.md
www/docs/customization/builds.md

closes #3844
closes #3843 
closes #3862

docs: add note about binary archives

---

internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
www/docs/customization/templates.md

This will allow more customized templates using dates!

feat: .Now template variable

---

go.mod
go.sum

feat(deps): bump github.com/caarlos0/log from v0.2.1 to v0.2.2

---

internal/pipe/scoop/scoop.go
pkg/config/config.go
www/docs/customization/scoop.md
www/docs/static/schema.json

close: https://github.com/goreleaser/goreleaser/issues/3845

feat: scoop shortcuts

---

internal/pipe/blob/blob.go
internal/pipe/blob/blob_minio_test.go
pkg/config/config.go
www/docs/customization/blob.md
www/docs/static/schema.json

Allows to template-disable specific blob configurations.
Closes #3883

feat: blobs.disable

---

internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go

all other pipes don't, not sure why scoop was doing it.
closes #3887

fix: do not skip scoop on draft releases

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go

similar to #3894, but for homebrew

fix: improve brew no archive error

---

www/docs/install.md
www/docs/static/run

updated to the cosign v2
cc/ @cpanato

docs: fix install's cosign steps

---

internal/pipe/krew/krew.go
internal/pipe/krew/krew_test.go
internal/pipe/krew/testdata/TestRunPipePullRequest.yaml
www/docs/customization/krew.md

feat: allow to pr krew plugin manifests

---

internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go
internal/pipe/scoop/testdata/TestRunPipePullRequest.json.golden
www/docs/customization/scoop.md

follow up of https://github.com/goreleaser/goreleaser/pull/3903

feat: allow to pr scoop manifests

---

internal/pipe/docker/docker.go
internal/pipe/docker/docker_test.go

refs https://github.com/goreleaser/goreleaser/pull/3940#issuecomment-1507149519

fix: improve docker error handling

---

internal/builders/golang/build.go

fix: build should output more debug info

---

internal/pipe/env/env.go
pkg/config/config.go
www/docs/errors/multiple-tokens.md
www/docs/static/schema.json

As a follow-up to #3910, this adds `force_token` to the config.

feat: add force_token to config

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
www/docs/customization/nfpm.md

closes https://github.com/goreleaser/goreleaser/issues/3956

feat: allow to template nfpms.package_name 

---

.github/workflows/build.yml
.goreleaser.yaml
internal/pipe/upx/upx.go
internal/pipe/upx/upx_test.go
internal/pipeline/pipeline.go
pkg/config/config.go
pkg/defaults/defaults.go
www/docs/customization/upx.md
www/mkdocs.yml

this adds a new root-level `upx` config, so users can pack their binaries with upx :)

feat: native upx support

---

.goreleaser.yaml
main.go

fix: pass tree state as ldflag

---

go.mod
go.sum
internal/artifact/artifact.go
internal/builders/golang/build_test.go
internal/client/gitea.go
internal/client/github.go
internal/client/gitlab.go
internal/exec/exec.go
internal/gio/copy.go
internal/http/http.go
internal/pipe/artifactory/artifactory_test.go
internal/pipe/before/before.go
internal/pipe/blob/upload.go
internal/pipe/docker/api.go
internal/pipe/reportsizes/reportsizes.go
internal/pipe/sbom/sbom.go
internal/pipe/scoop/scoop.go
internal/pipe/sign/sign.go
internal/pipe/upload/upload_test.go
internal/shell/shell.go

- log keys will be ordered as intended instead of sorted
- paths always relative to cwd

feat: improve output

---

cmd/check.go
cmd/check_test.go

This will be more useful for goreleaser pro than for oss, but I thought it might worth it having it in both versions.

feat: allow to goreleaser check multiple files

---

www/docs/customization/builds.md

Fixes documentation for the "prebuilt binaries" section of the docs

Fixes for prebuilt binaries docs

---

internal/archivefiles/archivefiles.go

refs https://github.com/orgs/goreleaser/discussions/3991

fix: warn when no match on archive files

---

internal/pipe/docker/docker.go
internal/pipe/docker/docker_test.go
internal/pipe/docker/manifest.go
www/docs/customization/docker.md
www/docs/customization/docker_manifest.md

feat: allow to template dockers.skip_push and docker_manifests.skip_push

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go

The lintian files were being written for every format, whether they were a deb or not.
Since package name and arches are the same, and packaging runs in parallel, it could happen that one goroutine is reading while the other is writing, as we were guaranteeing uniquenes based on package name and arch only.
This makes it only creates the lintian files when format is deb, so this shouldn't happen anymore.
It also goes one step further by using the actual format in the filepath instead of hard-coding "deb".
This also still supports tmux.
closes #4024

fix(nfpm): write too long when writing the lintian file

---

internal/client/github.go
internal/client/github_test.go

before doing anything, check the `/rate_limits` API... if we have less than 100 remaining, wait for the reset timer.
closes #4028

feat(github): avoid rate limits

---

internal/pipe/nix/nix.go
internal/pipe/nix/nix_test.go
internal/pipe/nix/testdata/TestRunPipe/minimal_build.nix.golden
internal/pipe/nix/testdata/TestRunPipe/minimal_publish.nix.golden
internal/pipe/nix/testdata/TestRunPipe/open-pr_build.nix.golden
internal/pipe/nix/testdata/TestRunPipe/open-pr_publish.nix.golden
internal/pipe/nix/testdata/TestRunPipe/partial_build.nix.golden
internal/pipe/nix/testdata/TestRunPipe/partial_publish.nix.golden
internal/pipe/nix/testdata/TestRunPipe/skip-upload-auto_build.nix.golden
internal/pipe/nix/testdata/TestRunPipe/skip-upload_build.nix.golden
internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
internal/pipe/nix/testdata/TestRunPipe/unibin_build.nix.golden
internal/pipe/nix/testdata/TestRunPipe/unibin_publish.nix.golden
internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_build.nix.golden
internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_publish.nix.golden
internal/pipe/nix/tmpl.nix

feat(nix): support armv6l and armv7l

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature.yaml

chore: fix issue templates

---

internal/pipe/upx/upx.go
internal/pipe/upx/upx_test.go
pkg/config/config.go
www/docs/customization/upx.md

feat(upx): allow to filter by goos, goarch, goarm, goamd64

---

internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go
internal/pipe/scoop/testdata/TestRunPipePullRequest.json.golden
www/docs/customization/scoop.md

make `scoops.description` and `scoops.homepage` templateable as well.

feat(scoop): allow to template description and homepage

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go
pkg/config/config.go
www/docs/deprecations.md

service has been available for a long time as well.
closes #3990

fix: deprecate brews.plist

---

internal/exec/exec.go
internal/exec/exec_test.go
internal/http/http.go
internal/http/http_test.go
internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go
internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
internal/pipe/snapcraft/snapcraft.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
pkg/config/config.go
www/docs/customization/templates.md
www/docs/deprecations.md

since this will be a late, big release, let's remove the deprecated stuff that expired

feat: remove deprecated replacements

---

Taskfile.yml
scripts/pages/build.sh
www/docker/Dockerfile
www/docs/customization/homebrew.md
www/docs/customization/krew.md
www/docs/customization/nix.md
www/docs/customization/scoop.md
www/docs/includes/repository.md
www/mkdocs.yml

I was really tired of copying and pasting that over and over again and keeping it all in sync...

docs: include markdown plugin

---

www/docs/customization/homebrew.md
www/docs/customization/krew.md
www/docs/customization/nix.md
www/docs/customization/scoop.md
www/docs/includes/prs.md

add another include with information about PRs, to be included everywhere `repository.md` is included, too.

docs: add more info about opening prs

---

internal/client/client.go
internal/client/git.go
internal/client/git_test.go

extracted from #4081
a little bit of a better impl than there, actually...

feat: make git client support creating multiple files in a single commit

---

internal/pipe/artifactory/artifactory_test.go
internal/pipe/upload/upload_test.go

improved test check
extracted from #3795

test: ECONNREFUSED

---

internal/pipe/build/build_test.go
internal/pipe/docker/docker.go
internal/pipe/sign/sign_test.go
internal/pipe/universalbinary/universalbinary_test.go

test: improve executable not found checks

---

internal/pipe/checksums/checksums_test.go
internal/pipe/gomod/gomod_proxy_test.go

 test: syscall.EACCES and os.ErrNoExist

---

internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go
pkg/config/config.go
www/docs/customization/changelog.md

closes https://github.com/goreleaser/goreleaser/issues/4111
refs https://github.com/orgs/goreleaser/discussions/4110
recreated #4115

feat: changelog.include

---

internal/pipe/env/env_test.go
internal/pipe/metadata/metadata_test.go
pkg/archive/tar/tar_test.go
pkg/archive/targz/targz_test.go
pkg/archive/tarxz/tarxz_test.go
pkg/archive/zip/zip_test.go

test: improve more tests

---

internal/pipe/aur/aur.go

using the new multiple files api to have a single commit/push for all files of a package.

feat(aur): single commit per package

---

go.mod
go.sum
internal/client/github.go
internal/client/github_test.go

feat(deps): bump github.com/google/go-github/v53 50.1.0 to 53.2.0

---

internal/pipe/winget/winget.go
internal/pipe/winget/winget_test.go

refactor(winget): minor improvements

---

internal/builders/golang/build.go
internal/gio/chtimes.go
internal/gio/chtimes_test.go
internal/pipe/universalbinary/universalbinary.go

we're repeating this quite a bit

refactor: gio.Chtimes

---

internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go
internal/pipe/scoop/testdata/Test_buildManifest/common.json.golden
internal/pipe/scoop/testdata/Test_buildManifest/gitlab_url_template.json.golden
internal/pipe/scoop/testdata/Test_buildManifest/pre-post-install.json.golden
internal/pipe/scoop/testdata/Test_buildManifest/url_template.json.golden

feat(scoop): support arm64

---

internal/client/client.go
internal/client/mock.go
internal/pipe/winget/winget.go
internal/pipe/winget/winget_test.go

fix(winget): improve commit msgs

---

www/docs/customization/builds.md

docs: fix typo in builds.md

---

.goreleaser.yaml
internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
pkg/config/config.go
www/docs/customization/snapcraft.md

allows to disable a snapcraft configuration based on a template, e.g. if snapshot, nightly, etc

feat(snapcraft): allow to disable

---

.goreleaser.yaml
internal/exec/exec.go
internal/exec/exec_test.go
pkg/config/config.go
www/docs/customization/publishers.md

allows to disable a specific custom publisher based on a template, akin to other pipes.

feat: publishers.disable

---

.golangci.yaml
CONTRIBUTING.md
cmd/util_test.go
go.mod
internal/pipe/gomod/gomod_proxy_test.go
internal/pipe/ko/testdata/app/go.mod

feat: update to go 1.21

---

Dockerfile

Bump cosign to version 2.1.1
...
To use latest and greates features of cosign
...

feat(dependencies): upgrade cosign

---

internal/pipe/docker/docker.go

refs https://github.com/orgs/goreleaser/discussions/4263

feat(docker): retry push if 503

---

internal/pipe/upx/upx.go
internal/pipe/upx/upx_test.go
pkg/config/config.go
www/docs/customization/upx.md

refs https://github.com/orgs/goreleaser/discussions/4268

feat: templates in upx.enabled

---

www/docs/blog/posts/2022-10-17-goreleaser-v1.12.md
www/docs/blog/posts/2022-11-18-goreleaser-v1.13.md
www/docs/cookbooks/set-a-custom-git-tag.md
www/docs/customization/changelog.md
www/docs/pro.md

docs: fix some broken links

---

www/docs/ci/actions.md

action v5 was released the other day

docs: update goreleaser-action

---

internal/git/git.go
internal/pipe/git/errors.go
internal/pipe/git/git.go
internal/pipe/git/git_test.go
www/docs/customization/git.md

also regex is not possible there currenctly, didnt realized it at the time
refs #4255

fix: git.ignore_tags not working

---

internal/client/git.go
internal/client/git_test.go
internal/pipe/brew/brew_test.go
internal/pipe/krew/krew_test.go
internal/pipe/scoop/scoop_test.go
internal/testlib/git.go

refs https://github.com/orgs/goreleaser/discussions/4321

fix: git client should respect specified branch

---

www/docs/customization/jsonschema.md
www/docs/customization/reportsizes.md
www/docs/links.md
www/mkdocs.yml

the sidebar is kinda out of control... too many items... tried to organize it a bit better...
let me know what you think :D

docs: organizing docs a bit better 

---

internal/pipe/release/scm.go

refactor: improve releases/scm.go a bit

---

cmd/build.go
cmd/build_test.go

fix: build --single-target

---

pkg/config/config.go
www/docs/install.md
www/docs/static/run
www/docs/static/schema.json

- if `VERSION` ends with `-pro`, set `DISTRIBUTION` to `pro`
- if `DISTRIBUTION` is `pro`, and `VERSION` does not have the `-pro` suffix, add it
closes #4374

fix: improve run script

---

USERS.md

Adding updatecli.io to the list of users.
cc @olblak

chore: add updatecli.io to USERS.md

---

internal/pipe/aur/aur.go
internal/pipe/aur/aur_test.go
internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go
internal/pipe/nix/nix.go
internal/pipe/nix/nix_test.go
internal/pipe/scoop/scoop.go
internal/pipe/scoop/scoop_test.go
internal/pipe/snapcraft/snapcraft.go
internal/pipe/snapcraft/snapcraft_test.go
internal/pipe/winget/winget.go
internal/pipe/winget/winget_test.go
internal/skips/skips.go

Adding more --skip flags

---

www/docs/customization/snapcraft.md

Updates the link for snap tab completion

docs: update snap link

---

www/docs/includes/repository.md

Typo in documentation
check_boxex > check_boxes
...
...
...

docs: Update repository.md typo in documentation check_boxex > check_boxes

---

cmd/build.go
cmd/build_test.go
cmd/release.go
cmd/release_test.go
pkg/context/context.go

feat: store which action is being taken in the context

---

go.mod
internal/pipe/blob/blob.go
internal/pipe/blob/blob_minio_test.go
internal/pipe/blob/blob_test.go
internal/pipe/blob/upload.go
pkg/config/config.go
www/docs/customization/blob.md
www/docs/deprecations.md

The [files refactor](https://github.com/orgs/goreleaser/discussions/4407) will be bigger than I thought it would, and probably not backwards-compatible...
So, I'm trying to fix most of the issues possible before I start working on that big thing™️. 
Some of them were contributed by users long ago... commits were imported manually and original authors added as co-authors.
This fixes all open issues regarding the Blobs publisher.
- closes #3772
- closes #4332
- closes #4309
- closes #3069
---
**NOTE TO SELF**: rebase instead of squash!!

feat(blob): acl, s3ForcePathStyle, disableSSL, kmskey, content-disposition

---

www/docs/blog/.authors.yml
www/docs/blog/posts/2022-03-26-reproducible-builds.md
www/docs/blog/posts/2022-03-28-supply-chain-sec.md
www/docs/blog/posts/2022-05-22-nightly-actions.md
www/docs/blog/posts/2023-01-10-azure-devops.md
www/docs/blog/posts/2023-01-30-goreleaser-ko.md

refs #3503
importing using `mediumexporter` and fixing up manually what's wrong.

docs(blog): import more posts 

---

internal/pipe/docker/api_docker.go
internal/pipe/docker/docker_test.go

fix(docker): remove --builder=default from default args when use=buildx

---

internal/http/http.go
internal/http/http_test.go

Logs when no artifacts were found, and also allow to publish source archives.
refs https://github.com/orgs/goreleaser/discussions/4585

feat(artifactory): publish source archives too, log when no archives found

---

.golangci.yaml
CONTRIBUTING.md
cmd/util_test.go
internal/pipe/gomod/gomod_proxy_test.go
internal/pipe/ko/testdata/app/go.mod
www/docs/install.md

feat: use go 1.22

---

internal/pipe/universalbinary/universalbinary.go
internal/pipe/universalbinary/universalbinary_test.go
www/docs/customization/universalbinaries.md

fix: better universalbinary message

---

pkg/config/config.go
www/docs/customization/builds.md

fix(build): buildmode: pie

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
www/docs/customization/nfpm.md

feat(nfpm): also allow $NFPM_PASSPHRASE

---

internal/pipe/release/release.go

fix: do not log `release published` if it is a draft

---

internal/client/github.go
pkg/config/config.go
www/docs/customization/release.md

feat: allow to delete existing artifacts in the release

---

internal/artifact/artifact.go
internal/artifact/artifact_test.go
internal/exec/exec.go
internal/exec/exec_test.go
internal/http/http.go
internal/http/http_test.go
internal/pipe/blob/blob_minio_test.go
internal/pipe/blob/upload.go
internal/pipe/metadata/metadata.go
internal/pipe/metadata/metadata_test.go
internal/pipe/release/release.go
internal/pipe/release/release_test.go
internal/pipe/sign/sign.go
internal/pipeline/pipeline.go
pkg/config/config.go
www/docs/customization/artifactory.md
www/docs/customization/publishers.md
www/docs/customization/release.md
www/docs/customization/upload.md

this will create a metadata artifact and allow to add them to the release.
closes #4669
closes #4682

feat: add metadata to the release

---

internal/pipe/gomod/gomod.go
internal/pipe/gomod/gomod_test.go
pkg/config/config.go
www/docs/customization/verifiable_builds.md

closes https://github.com/orgs/goreleaser/discussions/4728

fix: support dir in gomod

---

www/docs/customization/dockerhub.md

Fix typo in dockerhubs example
fix typo
...

Fix typo username in dockerhubs example

---

www/docs/customization/dockerhub.md

Minor edits to the `dockerhub` docs.
Thanks for all your [help getting this going](https://discord.com/channels/890434333251362866/1223342596231925852/1223342596231925852)
I note that you already updated a number of things. Here are just a couple more edits.
Thanks for the great work!

docs: Minor edits to 'dockerhub'

---

internal/pipe/release/release.go
internal/pipe/release/release_test.go

fix(release): publish tag with skip_upload

---

internal/client/github.go

If we're editing an existing release, do not set it to draft.
Closes #4742
Refs #4626

fix(release): only change release draft status on new releases

---

.github/workflows/build.yml
scripts/test.sh

simplify test scripts a bit
- remove tparse
- don't verbose test

build: simplify

---

internal/builders/golang/build_test.go
internal/pipe/sign/testdata/README.md
www/docs/blog/posts/2023-05-05-goreleaser-v1.18.md
www/docs/blog/posts/2023-10-08-slsa-generation-for-your-artifacts.md

chore: fix some comments

---

cmd/release.go

feat(cmd): release --draft

---

internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
www/docs/customization/templates.md

useful for conditionally enable/disable things based on whether an env var is set or not

feat: isEnvSet tmpl function

---

internal/deprecate/deprecate.go
internal/pipe/nfpm/nfpm.go
internal/tmpl/tmpl.go

Reuse strings replace instead of recreation

Optimize strings replacers

---

internal/pipe/winget/template.go
internal/pipe/winget/winget.go

fix: winget paths on windows

---

go.mod
go.sum
internal/pipe/discord/discord.go
internal/pipe/linkedin/linkedin.go
internal/pipe/mastodon/mastodon.go
internal/pipe/mattermost/mattermost.go
internal/pipe/opencollective/opencollective.go
internal/pipe/reddit/reddit.go
internal/pipe/slack/slack.go
internal/pipe/smtp/smtp.go
internal/pipe/teams/teams.go
internal/pipe/telegram/telegram.go
internal/pipe/twitter/twitter.go
internal/pipe/webhook/webhook.go

chore(deps): update env from v9 to v11

---

internal/client/gitea.go
internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go
www/docs/customization/changelog.md

- Add `strings` package import to `gitea.go`
- Implement `Changelog` function in `gitea.go`
- Update `useGitea` constant in `changelog.go`
- Add test for `useGitea` in `changelog_test.go`
- Update `changelog.md` with information about `gitea` customization
ref:
* Server API: https://github.com/go-gitea/gitea/pull/30349
* SDK: https://gitea.com/gitea/go-sdk/pulls/659

feat(gitea): implement `Changelog` function

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go
www/docs/customization/nfpm.md

fix(nfpm): termux platform

---

internal/pipe/brew/templates/macos_packages.rb
internal/pipe/brew/testdata/TestFullFormulae.rb.golden
internal/pipe/brew/testdata/TestFullFormulaeMacOSOnly.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
internal/pipe/brew/testdata/TestRunPipeUniversalBinaryNotReplacing.rb.golden

fix(brew): cpu conditionals

---

.goreleaser.yaml
internal/pipe/snapcraft/snapcraft_test.go

refs #4816
temp disable it from our release, and disable the broken tests

fix: temp disable snapcraft

---

go.mod
pkg/archive/archive.go
pkg/archive/archive_test.go
pkg/archive/tarzst/tarzst.go
pkg/archive/tarzst/tarzst_test.go
www/docs/customization/archive.md

feat(archive): support tar.zst

---

.github/workflows/build.yml
.github/workflows/release.yml
.goreleaser.yaml
internal/pipe/snapcraft/snapcraft_test.go

Reverts goreleaser/goreleaser#4826
for when there's a new snap release!

Revert "fix: temp disable snapcraft"

---

.github/workflows/build.yml
.github/workflows/release.yml

build: use latest snapcraft

---

cmd/root.go
cmd/root_test.go

fix: disable logs on some commands

---

www/docs/customization/winget.md

Update docs for `winget` to show the default past contains the name as well.
...
Current doc (and sample value) don't contain the name and this doesn't match the implementation.
...
https://github.com/goreleaser/goreleaser/blob/a82491afe446295c8756a2c5f46950a11d717aa0/internal/pipe/winget/winget.go#L165
...

Update winget.md path docs

---

cmd/build.go
cmd/build_test.go
cmd/release.go
cmd/release_test.go
cmd/root.go
cmd/root_test.go

feat!: more v2 cleanups

---

internal/static/config.yaml
internal/static/config_test.go

fix: init in v2

---

internal/pipe/blob/upload.go

Closes https://github.com/goreleaser/goreleaser/issues/4920
...
...

Do not upload artifacts if `blobs: ids: []` is set

---

internal/pipe/notary/macos.go
www/docs/customization/notarize.md

feat(notary): allow to sign without notarizing

---

internal/pipe/archive/archive.go
internal/pipe/archive/archive_test.go
internal/skips/skips.go

feat: --skip=archive

---

cmd/build.go
cmd/build_test.go
cmd/util_test.go

feat: build --auto-snapshot

---

internal/pipe/blob/blob.go
internal/pipe/blob/blob_minio_test.go
internal/pipe/blob/upload.go
pkg/config/config.go
www/docs/customization/blob.md

Not happy with the option name tbh... happy to hear suggestions :) 
refs #4921
refs https://github.com/goreleaser/goreleaser/issues/4920

feat(blob): allow to upload only extra_files

---

internal/builders/golang/build.go

feat(build): use GOCACHEPROG if set

---

internal/client/gitlab.go
internal/client/gitlab_test.go

fix(gitlab): better handle CI_JOB_TOKEN and unavailable APIs

---

internal/client/github.go

fix: make latest on drafts

---

www/docs/customization/blob.md

I was looking at this example and looking at the text/template docs, and I got confused.
Turns out there is no `neq` function available.

Update blob.md `neq` -> `ne`

---

www/docs/blog/posts/2024-07-13-v2.1.md

gonna release it in the weekend I think

docs: v2.1 announcement

---

.goreleaser.yaml
cmd/testdata/good.yml
internal/pipe/snapshot/snapshot.go
internal/pipe/snapshot/snapshot_test.go
pkg/config/config.go
www/docs/deprecations.md

feat: rename snapshot.name_template -> snapshot.version_template

---

internal/pipe/defaults/defaults.go
internal/pipe/defaults/defaults_test.go
internal/pipe/dist/dist.go
internal/pipe/dist/dist_test.go
internal/pipeline/pipeline.go
pkg/defaults/defaults.go

feat: when --clean, remove dist before checking git state

---

.github/workflows/build.yml

just to make the status a bit better...

ci: split test and check jobs

---

go.mod
go.sum

sec(deps): update docker/docker and google/go-containerregistry

---

internal/pipe/gomod/gomod_proxy_test.go

not sure if this is the right solution though

test: make test pass on go 1.23

---

.golangci.yaml
CONTRIBUTING.md
cmd/util_test.go
go.mod
internal/pipe/gomod/gomod_proxy_test.go
internal/pipe/ko/testdata/app/go.mod
www/docs/contributing.md
www/docs/install.md

build: go 1.23

---

internal/pipe/build/build.go
internal/pipe/build/build_test.go
pkg/config/config.go
www/docs/customization/builds.md

feat(build): template skip

---

internal/pipe/nix/nix_test.go
internal/pipe/upx/upx_test.go

test: do not fail if missing binaries

---

internal/pipe/blob/blob_minio_test.go
internal/pipe/ko/ko_test.go
internal/pipe/sign/sign_binary_test.go
internal/pipe/sign/sign_test.go
internal/testlib/path.go

test: check if pre-requisites are installed

---

internal/pipe/build/build.go
internal/pipe/build/build_test.go
pkg/config/config.go
www/docs/customization/builds.md

closes https://github.com/goreleaser/goreleaser/issues/5024

feat(build): templateable no_unique_dist_dir

---

cmd/build.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
pkg/context/context.go
www/docs/cmd/goreleaser_build.md
www/docs/customization/templates.md

feat(tmpl): IsSingleTarget

---

www/docs/blog/posts/2024-09-12-v2.3.md

docs: announce v2.3

---

www/docs/blog/posts/2024-09-12-v2.3.md
www/docs/install.md

Corrected some spelling errors in the `www/docs/install.md` and `www/docs/blog/posts/2024-09-12-v2.3.md` .

docs: correct spelling errors in documentation

---

internal/builders/golang/build.go
internal/experimental/exp.go
internal/experimental/exp_test.go
internal/pipe/brew/brew.go
internal/pipe/docker/docker.go
internal/pipe/partial/partial.go
pkg/context/context.go
www/docs/experiments.md
www/mkdocs.yml

Guarded by an environment variable for now.
Closes #5155

feat: default GOARM change to 7

---

internal/pipe/brew/brew.go
internal/pipe/brew/brew_test.go

- Fixes #5191 
- I added a test case, but I don't have a great mechanism to test this fully in a live environment.

brew: Fix Forumla Class Name builder

---

internal/client/gitlab.go
internal/client/gitlab_test.go

this makes it more similar to github's implementation.
should fix #5177

fix(gitlab): improve artifact upload retry

---

internal/builders/buildtarget/targets.go

honestly dunno why we were checking string prefixes there...

refactor: improve buildtarget.List

---

internal/pipe/ko/ko.go
internal/pipe/ko/ko_test.go
pkg/config/config.go
www/docs/customization/ko.md
www/docs/static/schema-pro.json
www/docs/static/schema.json

Add support for the newly added annotations and user options in [ko v0.17.0](https://github.com/ko-build/ko/releases/tag/v0.17.0)

feat(ko): support annotations and user

---

internal/pipe/changelog/changelog.go
internal/pipe/changelog/changelog_test.go

this should help when there is no tags in the repo yet

fix(changelog): fix for no tags

---

internal/client/gitea.go
internal/client/gitea_test.go
internal/client/github.go
internal/client/github_test.go
internal/client/gitlab.go
internal/client/gitlab_test.go
internal/client/mock.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
www/docs/customization/templates.md

fix: URL escape tags in github, gitlab, and gitea

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go
internal/builders/golang/targets.go
internal/pipe/build/build.go
internal/pipe/build/build_test.go
internal/pipe/universalbinary/targets.go
internal/pipe/universalbinary/universalbinary.go
internal/pipe/universalbinary/universalbinary_test.go
internal/testlib/artifacts.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
pkg/build/build.go
pkg/build/build_test.go

This starts laying the foundation for supporting more languages, the first of which will probably be Zig, and then Rust.
I already have a zig prototype working in another branch, just raw dogged it to see if it would work, and since it does, now I'll do it piece by piece but with hopefully slightly better code.

refactor(build): preparing to support multiple languages

---

internal/artifact/artifact.go
internal/builders/golang/build.go
internal/builders/golang/build_test.go
internal/pipe/archive/archive.go
internal/pipe/snapcraft/snapcraft.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go
www/docs/customization/templates.md

This will also come in handy for multiple languages support (#5307).

feat(template): allow to use .Target

---

internal/pipe/webhook/webhook.go
internal/pipe/webhook/webhook_test.go
pkg/config/config.go
www/docs/customization/announce/webhook.md
www/docs/static/schema-pro.json
www/docs/static/schema.json

feat(pipe): implement expected_status_codes for webhooks

---

internal/builders/golang/build.go
internal/builders/golang/build_test.go
internal/builders/rust/build.go
internal/builders/zig/build.go
internal/tmpl/tmpl.go
internal/tmpl/tmpl_test.go

reuse it everywhere.
refs #5327

refactor: flag template processing

---

internal/pipe/docker/docker.go

I mostly see this happening in the CI, sometimes... I think it might be that the server is not fully ready yet?

fix(docker): retry on EOF

---

internal/pipe/ko/ko.go
internal/pipe/ko/ko_test.go
pkg/config/config.go
www/docs/customization/ko.md
www/docs/deprecations.md

- allows to set more than one repository on KOs
- if many are set, build the first one, and use crane to copy to the next ones, preventing multiple builds
closes #5351

feat(ko): support multiple repositories

---

internal/builders/golang/build_test.go
internal/pipe/brew/brew.go
internal/pipe/changelog/changelog_test.go
internal/pipe/changelog/testdata/changes-templated.md
internal/pipe/changelog/testdata/changes.md
internal/pipe/ko/ko.go
internal/pipe/project/project.go
internal/pipe/webhook/webhook.go
internal/pipe/webhook/webhook_test.go

A bunch of cosmetic typo fixes.

chore: fix typos in comments, tests, and variables

---

internal/pipe/brew/templates/linux_packages.rb
internal/pipe/brew/templates/macos_packages.rb
internal/pipe/brew/testdata/TestFullFormulae.rb.golden
internal/pipe/brew/testdata/TestFullFormulaeLinuxOnly.rb.golden
internal/pipe/brew/testdata/TestFullFormulaeMacOSOnly.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
internal/pipe/brew/testdata/TestRunPipeNameTemplate.rb.golden
internal/pipe/brew/testdata/TestRunPipeUniversalBinaryNotReplacing.rb.golden

fix(brew): do not use on_arm and on_intel

---

internal/pipe/archive/archive.go

refs https://github.com/goreleaser/goreleaser/issues/5361#issuecomment-2536424924

fix(archive): improve info messages

---

.goreleaser.yaml
README.md
cmd/root.go
main.go
www/docs/intro.md
www/docs/quick-start.md
www/mkdocs.yml

Using the new "Release engineering, simplified" phrasing everywhere.

feat: changing descriptions everywhere, more docs touches

---

internal/builders/rust/build.go
internal/builders/rust/build_test.go
www/docs/customization/rust-builds.md

fix(rust): better cargo workspaces check

---

internal/client/client_test.go
internal/client/gitea_test.go

- speeds up tests
- avoid breaking on server changes

test(gitea): use fake server

---

internal/pipe/aursources/testdata/TestFullAur.golden
internal/pipe/aursources/tmpl.go

There is a missing new line between `.Sources` and the next section.

fix(aur_sources): missing new line

---

www/docs/customization/rust-builds.md

docs: cargo publish

---

internal/pipe/gomod/gomod_proxy_test.go

this should fix #5409 
I delete my local mod cache and ran the tests, and it seems to be working now.

test: update gomod

---

internal/client/github.go
www/docs/customization/release.md

* Resolves https://github.com/goreleaser/goreleaser/issues/5418

feat(release/gh): allow templates in make_latest

---

www/docs/ci/index.md
www/docs/customization/announce/index.md
www/docs/customization/builds/bun.md
www/docs/customization/builds/deno.md
www/docs/customization/builds/go.md
www/docs/customization/builds/hooks.md
www/docs/customization/builds/index.md
www/docs/customization/builds/rust.md
www/docs/customization/builds/zig.md
www/docs/customization/universalbinaries.md
www/docs/customization/upx.md
www/docs/quick-start.md
www/mkdocs.yml

docs: update docs

---

internal/pipe/notary/macos.go
internal/pipe/notary/macos_test.go
pkg/config/config.go
www/docs/customization/notarize.md

feat(notarize): allows setting signing entitlements

---

internal/client/gitea.go
internal/client/gitea_test.go

fix(gitea): commit with no author

---

www/docs/customization/attestations.md
www/mkdocs.yml

docs: attestations

---

README.md

Go report card badge

---

internal/http/http.go
internal/http/http_test.go
pkg/config/config.go
www/docs/customization/artifactory.md
www/docs/customization/upload.md
www/docs/static/schema-pro.json

feat(http/artifactory): skip configuration

---

.goreleaser-nightly.yaml
cmd/build.go
cmd/config.go
cmd/config_test.go
cmd/healthcheck.go
cmd/release.go
internal/yaml/yaml.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/load.go
www/docs/errors/version.md

feat: allow oss to use pro configurations when --snapshot is set

---

www/docs/customization/docker_sign.md

docs(docker_sign): ${artifact} does not contain the digest

---

Dockerfile

Reverts goreleaser/goreleaser#5527

Revert "chore(deps): bump golang from 1.23.5-alpine to 1.24rc2-alpine"

---

internal/pipe/nfpm/nfpm.go
internal/pipe/nfpm/nfpm_test.go

without this, if any nfpm configuration is skipped, it'll skip the entire thing.
this fixes it.

fix(nfpm): do not skip entire pipeline for one skip

---

internal/pipe/ko/ko.go
internal/pipe/ko/ko_test.go
pkg/config/config.go
www/docs/customization/ko.md

feat: kos.disable

---

www/docs/blog/posts/2024-02-05-goreleaser-v1.24.md
www/docs/blog/posts/2024-04-02-goreleaser-v1.25.md
www/docs/blog/posts/2024-05-11-goreleaser-v1.26.md
www/docs/blog/posts/2024-07-13-v2.1.md
www/docs/blog/posts/2024-08-14-v2.2.md
www/docs/blog/posts/2024-09-12-v2.3.md
www/docs/blog/posts/2024-11-02-v2.4.md
www/docs/blog/posts/2024-12-15-v2.5.md
www/docs/blog/posts/2025-01-21-v2.6.md
www/docs/blog/posts/2025-02-10-v2.7.md
www/docs/blog/posts/2025-03-12-v2.8.md

docs: announce v2.8

---

internal/artifact/artifact.go
internal/artifact/artifact_test.go
internal/pipe/aursources/aursources.go

fix(aur): panic if both aur and aur_sources configured

---

.github/workflows/build.yml
cmd/init.go
cmd/init_test.go
dagger/test.go
internal/builders/poetry/build.go
internal/builders/poetry/build_test.go
internal/builders/poetry/testdata/pyproject.toml
internal/builders/uv/build.go
internal/pyproject/pyproject.go
internal/pyproject/pyproject_test.go
internal/pyproject/testdata/poetry-pyproject.toml
internal/static/config.go
internal/static/config.poetry.yaml
www/docs/customization/builds/index.md
www/docs/customization/builds/poetry.md
www/docs/customization/builds/uv.md

this adds Poetry support to goreleaser.
the implementation is very similar to that of `uv`.

feat: poetry builder

---

.github/workflows/build.yml
internal/pipe/brew/templates/linux_packages.rb
internal/pipe/brew/testdata/TestFullFormulae.rb.golden
internal/pipe/brew/testdata/TestFullFormulaeLinuxOnly.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden

closes https://github.com/orgs/goreleaser/discussions/5736

fix(brew): improve if hardware structures

---

.github/workflows/lint.yml
.golangci.yaml

new golangci-lint version apparently

ci: fix lint

---

internal/builders/bun/build.go
internal/builders/deno/build.go

found while looking into https://github.com/orgs/goreleaser/discussions/5763

fix(bun,deno): duplicated build flags

---

.github/workflows/build.yml

refs https://github.com/ziglang/zig/issues/23977

ci: fix zig action

---

internal/pipe/cask/cask.go
internal/pipe/cask/cask_test.go
internal/pipe/cask/template.go
internal/pipe/cask/templates/additional_url_params.rb
internal/pipe/cask/templates/linux_packages.rb
internal/pipe/cask/templates/macos_packages.rb
pkg/config/config.go
www/docs/customization/homebrew_casks.md

one-shot this quickly so I don't forget about it 
refs https://github.com/goreleaser/goreleaser/pull/5800#discussion_r2120931938
closes #5797

feat(cask): improve URL config

---

go.mod
go.sum
testdata/TestVersion/all_empty.json.golden
testdata/TestVersion/complete.json.golden
testdata/TestVersion/only_version.json.golden
testdata/TestVersion/version,_date,_built_by.json.golden
testdata/TestVersion/version_and_date.json.golden

This update fixes typos in testdata golden files.

chore(deps): update github.com/caarlos0/go-version from 0.2.0 to 0.2.1

---

internal/pipe/semver/semver.go
internal/pipe/semver/semver_test.go

see https://github.com/orgs/goreleaser/discussions/5833

fix(semver): skip=validate allows invalid semver

---

internal/logext/styles.go
internal/logext/styles_test.go
internal/logext/testdata/TestDuration.txt.golden
internal/middleware/logging/logging.go
internal/shell/shell.go

also improves styling of duration logs

feat: log duration of all shell commands

---

cmd/healthcheck.go
cmd/root.go
go.mod
go.sum
internal/deprecate/deprecate_test.go
internal/deprecate/testdata/TestNotice.txt.golden
internal/logext/styles.go
internal/logext/writer_test.go
internal/middleware/logging/logging.go
main.go

upgrading all usage to v2.
v1 is still an indirect dependency of quill.

fix(deps): update to lipgloss/v2

---

www/docs/blog/posts/2025-07-08-v2.11.md
www/docs/customization/aur.md
www/docs/customization/aursources.md
www/docs/customization/cloudsmith.md
www/docs/customization/publishers.md
www/docs/deprecations.md
www/docs/includes/repository.md

prepping v2.11 release announcement for tomorrow 🙏🏻

docs: announce v2.11

---

.goreleaser.yaml
cmd/mcp.go
internal/pipe/cask/cask.go
internal/pipe/cask/template.go
internal/pipe/cask/testdata/TestFullCask.rb.golden
internal/pipe/cask/testdata/TestFullPipe/custom_block.rb.golden
internal/pipe/cask/testdata/TestFullPipe/custom_block_url.rb.golden
internal/pipe/cask/testdata/TestFullPipe/default.rb.golden
internal/pipe/cask/testdata/TestFullPipe/default_gitlab.rb.golden
internal/pipe/cask/testdata/TestFullPipe/git_remote.rb.golden
internal/pipe/cask/testdata/TestFullPipe/many-dependencies-and-conflicts.rb.golden
internal/pipe/cask/testdata/TestFullPipe/open_pr.rb.golden
internal/pipe/cask/testdata/TestFullPipe/uninstall.rb.golden
internal/pipe/cask/testdata/TestFullPipe/url_parameters_curl.rb.golden
internal/pipe/cask/testdata/TestFullPipe/url_parameters_post.rb.golden
internal/pipe/cask/testdata/TestFullPipe/valid_repository_templates.rb.golden
internal/pipe/cask/testdata/TestFullPipe/zap.rb.golden
pkg/config/config.go
www/docs/customization/homebrew_casks.md
www/docs/deprecations.md

refs https://github.com/Homebrew/brew/pull/20499
refs https://github.com/orgs/goreleaser/discussions/5995

fix(cask): conflicts_with formula was deprecated

---

.github/workflows/nightly-oss.yml
.github/workflows/release.yml
internal/pipe/checksums/checksums.go
internal/pipe/dockerdigest/digest.go
internal/pipe/dockerdigest/digest_test.go
internal/pipe/dockerdigest/digests.txt
internal/pipe/publish/publish.go
internal/pipe/publish/publish_test.go
pkg/config/config.go
pkg/defaults/defaults.go
www/docs/customization/attestations.md
www/docs/customization/docker_digests.md
www/mkdocs.yml

closes #4852
refs https://github.com/actions/attest-build-provenance/issues/454

feat(docker): create images digest file for attestation

---

internal/pipe/docker/v2/docker.go
internal/pipe/docker/v2/docker_test.go
pkg/config/config.go
www/docs/customization/dockers_v2.md

feat(docker/v2): support arbitrary flags

---

internal/builders/bun/build_test.go
internal/builders/bun/targets.go
internal/builders/bun/targets.txt

closes https://github.com/orgs/goreleaser/discussions/6014

feat(bun): support more targets

---

.github/dependabot.yml
go.mod
go.sum

dependabot keeps downgrading to beta1 for some reason 🤦🏻

chore(deps): update lipgloss
