- .goreleaser.yaml
- internal/pipe/sign/sign.go
- internal/pipe/sign/sign_docker_test.go
sign may emit a certificate but not a signature, currently if there is no signature it also ignores the certificate options.
Also fixed so all certificates and signatures are always stored within `dist`.
> fix: sign with cert only

- www/docs/ci/circle.md
Hello! First of all thanks for the great tool 👍 It's really helps to deliver binaries as fast and easily as possible! Yesterday I have faced with slight inaccuracy in the CircleCI example config. It causes to failed build. The last command in config produces an error and seems like unnecessary:
```
/bin/bash: goreleaser: command not found
Exited with code exit status 127
```
[CircleCI failed build](https://app.circleci.com/pipelines/github/mocktools/go-smtp-mock/222/workflows/afee5f9c-d1b8-4c21-bdaa-a866a9087cb2/jobs/423)
So, this commit will fix this issue.
> docs(ci): fix circle config example

- www/docs/cookbooks/override-image-name.md
Co-authored-by: Furkan <furkan.turkal@trendyol.com>
Add another section to the Docker's page to tell people how they can override registry and image names within `.goreleaser.yml` file. 
To give information on how they can overcome this issue
...
> docs(docker): add section for overriding hard-coded image name

- .goreleaser.yaml
- Taskfile.yml
has virtually no downloads, and was never really tested...
I think we can have fewer targets, only the most common ones. Should speed up the release a bit and also lower the number of files in the release
wdyt?
> feat: do not release goreleaser for arm6

- www/docs/ci/drone.md
Updates Drone CI integration, which includes:
- simplified and deterministic usage of go-releaser (ie: docker image)
- shows how to build docker images in Drone docker pipeline
> docs: update Drone CI integration

- go.mod
- go.sum
closes #2792
this was fixed in nfpm: https://github.com/goreleaser/nfpm/pull/431
> fix: nfpm empty dirs

- internal/logext/testdata/TestWriter/debug/1.txt.golden
- internal/logext/writer.go
its common for CLIs to log to STDERR, showing those as errors seems a bit too much, changing them to warn for now. We can then evaluate and maybe change all to info if needed
> fix: logext STDERR use warn instead of error

- internal/pipe/sbom/sbom.go
When using the `sbom` config with `binary` artifact it was generating a duplicate list of binaries to generate the sbom and that generate the `artifacts.json` with duplicate entries and that will fail in the release step when trying to upload the files to the GitHub, for example, it tries to push duplicate files and that fail in the GitHub side.
applying this change the list is correct.
> fix: sbom binary filter

- internal/pipe/changelog/changelog.go
Thank you for building goreleaser! While setting it up on https://github.com/pelletier/go-toml/tree/v2, I've noticed that when using the `github-native` changelog setting and publishing releases to GitHub, the resulting release had an odd formatting issue (see below).
The Github changelog generation API returns a pre-formatted changelog. The current implementation prefixes every line of that log with "* ". This operation breaks the formatting.
This change makes goreleaser treat github-native changelog as-is, without trying to modify it.
I tried to write a unit test for this, but couldn't find a good way to both mock the `githubNativeChangeloger` and evaluate the execution of `Pipe.Run`.
Would love to hear your thoughts on that change!
---
Formatting:
> fix: don't format github-native changelog

- www/docs/cookbooks/goreleaser-xx.md
- www/mkdocs.yml
Cookbook that shows how to use GoReleaser with [`goreleaser-xx`](https://github.com/crazy-max/goreleaser-xx#readme) to ease the integration and cross compilation in a Dockerfile.
> docs: goreleaser-xx

- go.mod
- go.sum
env is now dependency-free, and 6.9.1 also has a fix for something we don't use (anonymous inner structs with envPrefix), but anyway, here we go :)
> feat(deps): update github.com/caarlos0/env/v6 from v6.8.0 to v6.9.1

- internal/client/gitlab.go
- pkg/config/config.go
- www/docs/scm/gitlab.md
GitLab's Generic Package Repository allows uploading files
to GitLab, as an alternative to attachments.
Added the flag `use_package_registry` to the `gitlab_urls` config.
When false, the default, it will behave as before.
When true, it will publish the file to the Generic Package Registry.
Either way, the URL is bound to the release the same
Updated `go-gitlab` to version 0.52.2 which has the new
`GenericPackages.PublishPackageFile` function.
----
Fixes #2006.  
I tried to run local tests on it and it was not working (failures with `internal/pipe` and weird assembly output);  however, I think that is unrelated to this PR as I've tested this many times before without issue.  My apologies if this is not the case and the CI fails.
> feat: add support for GitLab Generic Packages

- internal/pipe/universalbinary/universalbinary.go
- internal/pipe/universalbinary/universalbinary_test.go
- pkg/config/config.go
- www/docs/customization/universalbinaries.md
fixes #2759
* behavior still the same if no `ids` is provided
* if `ids` is provided, it will be used to filter, and the resulting universal binary will have the ID set in the `id` field
since before it was not possible to set multiple ids, and the previous behavior will remain, this is not a breaking change IMO
> feat: allow multiple ids on universal binaries

- www/docs/ci/azurepipelines.md
This PR corrects the name of an input from `install-only` to `installOnly`.
> docs: correct installOnly in the documentation

- internal/pipe/announce/announce.go
- internal/pipe/webhook/webhook.go
- internal/pipe/webhook/webhook_test.go
- pkg/config/config.go
- pkg/defaults/defaults.go
- www/docs/customization/announce/webhook.md
- www/mkdocs.yml
fixes #2711 
How to test:
Head over to https://webhook.site/ and get a webhook endpoint.
Add following snippet to your `goreleaser.yaml`
```yaml
announce:
webhook:
enabled: true
check_cert: true
message_template: '{ "message": "{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{.ReleaseURL }}"}'
endpoint_url: "<endpoint>"
```
Lookig for your feedback!
> feat: add generic webhook announcer

- internal/commitauthor/author.go
- internal/commitauthor/author_test.go
- internal/pipe/brew/brew.go
- internal/pipe/gofish/gofish.go
- internal/pipe/krew/krew.go
- internal/pipe/scoop/scoop.go
closes #2761
allow to template commit author everywhere:
- brew
- gofish
- krew
- scoop
created a "central" `commitauthor` package to hold the code for the defaults and templates.
> feat: allow to template commit author

- .github/workflows/docs.yml
If applied, this commit will tidy up some stale paths in the GitHub Actions `docs` workflow.
`.github/workflows/htmltest.yml` no longer exists, and the `www/*` path catches changes to `www/htmltest.yml`.
> chore: remove stale trigger paths

- scripts/pre-commit.sh
`-s` is now implicit, so it actually generates a warning. we can drop that option.
> fix: pre-commit hook

- pkg/config/config.go
- pkg/config/config_array_test.go
fix some new lit issues related to tagliatelle
> fix: lint issues

- www/docs/cookbooks/cgo-and-crosscompiling.md
Signed-off-by: Artur Troian <troian.ap@gmail.com>
> docs(cookbooks): update links to the new goreleaser-cross home

- .goreleaser.yaml
Adding the GoReleaser Image to the new ArtifactHub function https://artifacthub.io/docs/topics/repositories/#container-images-repositories
So far so good, It's just miss two properites:
This PR will add them.
Fixes: #2830
> feat: add goreleaser image to ArtifactHub

- .goreleaser.yaml
Add additional properties for ArtifactHub for #2830
> feat: add additional properties for ArtifactHub

- internal/pipe/metadata/metadata.go
- internal/pipe/metadata/metadata_test.go
- internal/pipe/metadata/testdata/TestRun/metadata.json.golden
- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
- pkg/context/context.go
- pkg/context/context_test.go
- www/docs/customization/templates.md
Expose `{{ .Runtime.Goos }}` and `{{ .Runtime.Goarch }}`
refs  #2829
> feat: expose runtime goos and goarch on templates and metadata

- cmd/man.go
- go.mod
- go.sum
mango's API has changed, and the mango-cobra adapter has been moved into a separate repository. This change bumps mango and adapts goreleaser's code to this API change.
See: https://github.com/muesli/mango/pull/5
> chore: bump mango and adapt to changed API

- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
- internal/pipe/build/build_test.go
- pkg/config/config.go
- www/docs/customization/build.md
refs  #2829
allow to override ldflags et al based on the build target
> feat: allow to override build flags by goos/goarch/etc

- internal/deprecate/deprecate.go
- internal/deprecate/testdata/TestNotice.txt.golden
- internal/deprecate/testdata/TestNoticeCustom.txt.golden
this should prevent concurrent logs from getting the wrong padding, as we wont be messing with the global logger padding anymore
brain dump: maybe worth copying what we actually use from that log library and tune it so we can avoid these kinds of hacks?
> fix: improve deprecate logs

- internal/pipe/nfpm/nfpm.go
- internal/pipe/nfpm/nfpm_test.go
allows to template `nfpms[*].maintainer` field.
> feat: template nfpms.maintainer

- cmd/build.go
- cmd/build_test.go
closes #2685
This would add similar behavior as `go build`, a `-o` flag.
so, when you `goreleaser build --single-target -o foo`, it will save the binary as `foo` (if you have only one build config, otherwise this also needs the `--id` flag).
Hopefully this helps replacing some build tasks on makefiles :)
> feat: allow a --output flag on goreleaser build

- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
if the a file is given, but is empty, leave the changelog empty (although it will be warned).
this makes whitespace-only and empty files have the same behavior.
> fix: make --release-notes flags more deterministic

- internal/pipe/universalbinary/universalbinary.go
- internal/pipe/universalbinary/universalbinary_test.go
- www/docs/customization/universalbinaries.md
This allows the usage of `{{ .Path }}` and `{{ .Name }}` on post templates.  Closes #2890
> feat: allow to use .Path and .Name on universal binary post hooks

- USERS.md
If applied, this commit will update the USERS.md document to add the Conduit website in its correct alphabetical place.
> docs: adds Conduit to USERS.md

- .goreleaser.yaml
- .lintian-overrides
- internal/pipe/nfpm/nfpm.go
- internal/pipe/nfpm/nfpm_test.go
- pkg/config/config.go
- www/docs/customization/nfpm.md
allow to more easily set lintian overrides
> feat: lintian overrides

- internal/pipe/nfpm/nfpm.go
- internal/pipe/nfpm/nfpm_test.go
- www/docs/customization/nfpm.md
`/usr/local/bin` is intended for binaries compiled locally, which is never the case for goreleaser.  
This PR changes the default to `/usr/bin` instead.  
closes #2909
> feat: change default nfpm bindir

- cmd/build.go
- cmd/build_test.go
> fix: do not copy binary by default

- README.md
This PR adds a `Community` section to the README file with badges and links to Discord, Twitter and GitHub discussions.
> docs: add community section in README

- www/docs/cookbooks/using-jfrog-cli-to-publish-to-artifactory.md
- www/mkdocs.yml
The jfrog cli allows storing the artifactory configuration in a configuration file rather than directly in the environment.
This is a refactor of the previous PR I had and closed here:  https://github.com/goreleaser/goreleaser/pull/2854
I have found it easier to configure the jfrog cli to contain my artifactory credentials.
> docs: Add a new cookbook that covers using the jfrog-cli as an alternative to the artifactory publisher to publish to artifactory.

- internal/pipe/git/git.go
- internal/pipe/git/git_test.go
- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
- pkg/context/context.go
- www/docs/customization/templates.md
this adds another template variable, `TagBody`, with the body of the annotated tag/commit message only.  
closes #2920
> feat: annotated tag body

- internal/pipe/aur/aur.go
I had this issue on a repo, and it seems at least one more person had it too: ssh/git complaining that the key is invalid.  
My guess is that gh secret set from a file is now appending a new line - as it worked with the exact same key before, for me at least.  
anyway, if thats it, this pr should fix it. 
closes https://github.com/goreleaser/goreleaser-action/issues/326
> fix: trim spaces from aur private key

- go.mod
- go.sum
- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
- internal/pipe/sbom/sbom.go
- internal/pipe/sbom/sbom_test.go
This PR makes the following adjustments:
- primarily restores the capability to reference binary artifacts when `sbom[].artifact == binary`
- adds the ability to have templates within `sbom[].env` values
- only prepends `dist` config value to paths that relative paths (takes no action on absolute paths)
- decomposes templating code further for the SBOM pipe and surround with more testing
Why make this change? primarily to unlock more workflows when generating SBOMs.
Not all tooling can work with encapsulations of go binaries (zip/tar) and instead need access to the binary directly. Since goreleaser manages creating the binary it is possible to expose the original binary to SBOM tooling even though it may be an encapsulation that is attached to a release (e.g. a zip or tar.gz)
Take for …
> fix: dedupliate cataloging binary artifacts

- go.mod
- go.sum
- internal/artifact/artifact.go
For some reason the set lib was trowing an int overflow  error on snapshot when there are no binary artifacts to sign. 
This list is small, we don't need to worry about allocations et al, so I just switched it for a `map` for now, which seems to fix the issue...
cc @wagoodman 
Refs  #2839 
See https://github.com/goreleaser/goreleaser/runs/5334854323?check_suite_focus=true#step:21:50
> fix: build breaking on windows 386

- internal/pipe/brew/brew.go
- internal/pipe/brew/brew_test.go
- internal/pipe/brew/template.go
- internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/valid_tap_templates.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
- internal/pipe/brew/testdata/TestRunPipeNameTemplate.rb.golden
Currently on a M1 macbook when adding a tap with formulas that only support `amd64` it fails to add the tap. With errors similar to the below. Which prevents new `arm64` users from using the tap.
```
brew tap --force-auto-update cdx/brewtest https://github.com/ryancurrah/brewtest
==> Tapping ryancurrah/brewtest
Cloning into '/opt/homebrew/Library/Taps/ryancurrah/homebrew-brewtest'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 15 (delta 2), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (15/15), done.
Resolving deltas: 100% (2/2), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/ryancurrah/homebrew-brewtest/Formula/rcurrahtest.rb
formulae require at least a URL
Error: …
```
> improvement(pipe/brew): install amd64 binaries when no arm64 binaries present

- go.mod
- pkg/archive/gzip/gzip.go
latest nfpm introduced pgzip for faster gzip compression, we can use it on goreleaser as well
> feat: faster archiving with pgzip

- internal/pipe/nfpm/nfpm.go
- internal/pipe/nfpm/nfpm_test.go
The nfpm pipe was globbing the input list, and then globbing its result
as well. If you add a folder that had a file with, say `[]`, in it, it
would later fail the release upon trying to evaluate that as a glob.
This is probably some faulty nFPM update in which I should have removed
that but didn't.
Either way, this should fix it.
closes #2946
> fix: nfpm globbing multiple times

- internal/pipe/snapcraft/snapcraft.go
- internal/pipe/snapcraft/snapcraft_test.go
- pkg/config/config.go
- www/docs/customization/snapcraft.md
Following up on [this discussion](https://github.com/goreleaser/goreleaser/discussions/2952), this PR adds support for missing Snapcraft app metadata fields. These fields are documented [here](https://snapcraft.io/docs/snapcraft-app-and-service-metadata).
**Note:** Curiously, Snapcraft’s [docs](https://snapcraft.io/docs/snapcraft-app-and-service-metadata) are missing a few fields (for example `aliases` and `bus-mode`) that are mentioned in Snapcraft’s [JSON schema](https://github.com/snapcore/snapcraft/blob/383c1f1ce48778916a13f361f01d8badd5b9e406/schema/snapcraft.json) definition for their yaml config. Since these fields _are_ actually usable (the tests assert this because they invoke snapcraft, read the resulting `snap.yaml` and compare the contents of the app metadata), I opted to …
> Add missing Snapcraft app metadata fields

- internal/builders/buildtarget/targets.go
- internal/builders/buildtarget/targets_test.go
- internal/pipe/docker/docker.go
- pkg/config/config.go
- www/docs/customization/gomod.md
- www/docs/deprecations.md
- auto ignore darwin/arm64 on go <1.15, check https://goreleaser.com/deprecations/#builds-for-darwinarm64
- `dockers.use_buildx` (do not mix with `dockers.use: buildx`), check https://goreleaser.com/deprecations/#dockersuse_buildx
> feat: remove some deprecated code, go 1.15 support

- internal/pipe/gomod/gomod.go
- internal/pipe/gomod/gomod_test.go
- pkg/config/config.go
- www/docs/customization/gomod.md
this allows to set the -mod flag on the command used to grab the module root package, in case its needed to ignore the vendor folder, force readonly, etc...  
closes #2975
> feat: set -mod on gomod pipe

- .golangci.yaml
Make golangci-link work again since the go 1.18 upgrade
refs https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1072732099
> fix(ci): golangci-lint on go 1.18

- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
- internal/http/http.go
- internal/http/http_test.go
- pkg/config/config.go
- www/docs/customization/artifactory.md
- www/docs/customization/upload.md
The idea is to be able to filter by extension and send each extension to
a different place, if needed.
This also affects the artifactory pipe.
Also updated artifactory docs a bit.
closes https://github.com/goreleaser/goreleaser/issues/1913
> feat: allow to filter by ext on http upload pipe

- internal/pipe/slack/slack.go
- internal/pipe/slack/slack_test.go
- pkg/config/config.go
- pkg/config/config_slack_test.go
- www/docs/customization/announce/slack.md
This feature adds support for specifying richer content in Slack
announcements. We may now specify "blocks" and "attachments" to produce
better-looking announcement messages.
* fixes #2986
The goreleaser configuration only exposes the top-level structures and does not
check the validity of the Slack API internal structures. This way, we do
not inject hard dependencies on changes in the Slack API.
Notice: untyped config parsing introduces a little hack to have yaml and
JSON marshaling working together properly. This hack won't be necessary
with yaml.v3.
How this has been tested?
-------------------------
* Added unit tests for the config parsing
* Added a (skipped) e2e test.
For now, this requires a valid Slack webhook, so I've been able to test this manually.
Signed-off-by: Frederic BIDON …
> feat(announce): added Slack notification options

- internal/pipeline/pipeline.go
Signing might change a file (e.g. gon), so, if sign after we built the brew tap, the checksums won't match.  Moving this around a bit should have no negative side-effects (that I'm aware of, that is), and should fix that issue.  closes #3010
> fix: sign before brew et al

- .github/workflows/docs.yml
- .github/workflows/generate.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Set permissions for GitHub actions

- internal/pipe/nfpm/nfpm.go
- internal/pipe/nfpm/nfpm_test.go
Several goroutines might touch the lintian file inside dist at the same time, which might cause weird errors, namely `archive/tar: write too long`.  
This PR fixes it by namespacing the file to the package name + arch, so one goroutine won't touch the work of the other. 
It also improves some logs and tests.
> fix: nfpm lintian concurrency issue

- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
- pkg/config/config.go
- www/docs/customization/build.md
Added two more options to the builds section: 
- command: allow to override the command being run. E.g. instead of
`go build`, one could run `go test -c` by setting gobinary, command
and flags, respectively. 
- no_main_check: by default, goreleaser will fail if there's no main
function. 
This option allows to disable that check.  This PR effectively make GoReleaser able to release Go test binaries instead of just "regular" binaries.  
Example usage:
closes #3037
> feat: add builds.no_main_check and builds.command

- internal/pipe/build/build.go
- internal/pipe/build/build_test.go
- internal/pipe/universalbinary/universalbinary.go
- internal/pipe/universalbinary/universalbinary_test.go
- www/docs/customization/build.md
- on universal binaries, use the build id instead of the binary name to
create the folder in the dist folder 
- on builds, default the id the to the binary name instead of project
name. The binary name already defaults to the project id if empty, so
this should only prevent having to specify the id + binary name in
some cases.  
closes #3061
> fix: prevent folder collisions in builds and universal binaries

- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
- www/docs/customization/build.md
Adds the ability to tell goreleaser to use the first-class Go ports as targets.  
Closes #3053
> feat: first class build targets

- internal/pipe/docker/docker.go
- www/docs/errors/docker-build.md
- www/mkdocs.yml
Adding an error page with some more info to help debug issues.
> feat: improve docker errors

- www/docs/errors/no-main.md
I changed "you `main.go`" to "your `main.go`"
> Fix typo in www/docs/errors/no-main.md

- internal/deprecate/deprecate.go
- internal/deprecate/deprecate_test.go
- internal/deprecate/testdata/TestWriter.txt.golden
- internal/pipe/nfpm/nfpm.go
- www/docs/deprecations.md
> fix: nfpm deprecation on nfpm check

- internal/git/config.go
- internal/git/config_test.go
- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
- internal/pipe/milestone/milestone.go
- internal/pipe/milestone/milestone_test.go
- internal/pipe/release/release.go
- internal/pipe/release/release_test.go
- pkg/config/config.go
basically allows to use goreleaser against a repo with a git url without both owner and repo name.
closes #3060
closes #3058
> feat: allow git remote urls from non-scm sources

- www/docs/cookbooks/semantic-release.md
The commit will add an example of the use of sematic-release in the documentation (https://github.com/semantic-release/semantic-release).
The solution in the issue https://github.com/goreleaser/goreleaser/issues/910 was not documented.
> docs: add example for semantic-release

- README.md
Hello,
We recently sponsored on open-collective and noticed the readme wasn't automatically updating. 
I figured I would help out and get all the current sponsors on the readme.
Thanks
Add more sponsors to the readme
Sonr sponsored and I noticed it didn't autoupdate. 
...
> Add more sponsors to the readme

- internal/pipe/archive/archive.go
- internal/pipe/archive/archive_meta_test.go
- pkg/config/config.go
- www/docs/customization/archive.md
adds support for creating meta archives
closes #3085
> feat: meta archives

- internal/pipe/archive/archive.go
- internal/pipe/archive/archive_test.go
- pkg/archive/archive.go
- pkg/archive/archive_test.go
Defaulting to tar.gz is probably not a good idea, better error instead.
> refactor: improve archive pipe

- internal/archivefiles/archivefiles.go
- internal/archivefiles/archivefiles_test.go
- internal/pipe/archive/archive.go
- internal/pipe/archive/archive_test.go
> refactor: evaluate archive files in another package

- internal/pipe/docker/docker.go
Otherwise it'll advise the link when its actually just skipping the run...
> fix: better handle docker skip errors

- internal/pipe/brew/brew.go
- internal/pipe/brew/brew_test.go
Resolves: #3116
Change homebrew class generation to match what homebrew expects based on [Homebrew's code](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formulary.rb#L150-L156) for generating class names.
> fix: brew formula class generation when using dots

- internal/builders/buildtarget/targets.go
- internal/builders/buildtarget/targets_test.go
- www/docs/deprecations.md
has been deprecated for almost 1y, fully removing it now.
> feat: removed deprecated windows arm handling on go 1.16

- USERS.md
[Koordinator](https://koordinator.sh/) is a QoS based scheduling system for hybrid orchestration workloads on Kubernetes, bringing workloads the best layout and status. We uses GoReleaser to release containers, packages, and binaries.
So this PR would like to add Koordinator to USERS.md, thanks.
> docs: adds Koordinator to USERS.md

- cmd/release.go
- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
- internal/pipe/docker/manifest.go
- pkg/context/context.go
Allow to skip the entire docker images and manifests builds.
Might be useful for faster local builds et al.
closes #3144
> feat: add --skip-docker

- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
- now, the pushable docker image is still added to the artifact list, so it can be inspected in `dist/artifacts.json`
- `ctx.SkipPublish` is handled by the `publish` pipe
- handle `dockers.skip_push` in the publish phase
> fix: improve docker publish skipping

- www/docs/errors/no-main.md
Minor fix; if you run goreleaser outside the root of the project you'll see the no-main error.
This may be a bug instead, maybe should be done that way.
> docs: no-main error if running outside project root

- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
- internal/pipe/archive/archive.go
- internal/pipe/archive/archive_test.go
- internal/pipe/aur/aur.go
- internal/pipe/brew/brew.go
- internal/pipe/docker/docker.go
- internal/pipe/gofish/gofish.go
- internal/pipe/krew/krew.go
- internal/pipe/nfpm/nfpm_test.go
- internal/pipe/scoop/scoop.go
- internal/pipe/snapcraft/snapcraft.go
- internal/pipe/universalbinary/universalbinary_test.go
- internal/tmpl/tmpl.go
**Backporting from pro**
In the end of the process we store the artifact list as `dist/artifacts.json`. If we want to load this back into a goreleaser context and use them, some pipes that store "complex" data (e.g. their og config) in the `Extra` field of the artifact will fail, as they will be parsed back from json as `map[string]interface{}`.
With this, we can use the new `artifact.Extra`, which will try to cast, and if it fails, convert back to json and re-unmarshal into the correct type.
This is needed for #3174 in the pro distribution and is being backported from it to the OSS distribution to avoid merge conflicts.
> refactor: improve handling of extra fields in artifacts

- internal/pipe/docker/api_docker.go
- internal/pipe/docker/docker_test.go
- www/docs/customization/docker.md
fixes #3187 
Set the buildx builder for building Docker images to the `default` context builder that is backed by BuildKit in the Docker engine. This builder is always available when using buildx through the Docker CLI so should not be an issue for anyone.
Also adds a new section in the documentation in case some users want to use a specific builder.
In a follow-up we could also create a specific builder before building the image that is attached to the project and could be named `goreleaser_buildx_builer_{{.ProjectName}}` for example. This way users could benefit from advanced features not available with the default builder like cache exporters.
> fix: use default builder with buildx

- internal/pipeline/pipeline.go
otherwise, before might not have some template variables, for example,
the project name.
not sure if this will have adverse side effects though, need to think a
bit more about it.
fixes #3196
> fix: run defaults pipe before before pipe

- internal/pipe/release/release.go
- internal/pipe/release/scm.go
- internal/pipe/release/scm_test.go
this will allow to use templates in the release.github/gitea/gitlab owner and name fields.
closes https://github.com/goreleaser/goreleaser/issues/3202
> feat: allow to template release.repo

- .goreleaser.yaml
- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
This changes the changelog grouping feature a bit: it evaluates the
groups in the order they are declared in the config file, but renders
them following their `order` attribute.
This allows to have better filters, for instance, you might want to have
dependabot commits in another section, which does not need a high
priority in the changelog output, but does when evaluating, as it might
share the words with other groups: in goreleaser's case, the `feat`
prefix.
Giving that Go's regex seems to don't allow negative look-aheads (which
would help in this particular case), this seems like a good quality of
life improvement.
> feat: changelog group improvements

- internal/testlib/log.go
Test output is too verbose, this should help by disabling the default logger when testing.
Most tests import testlib, so this might just be enough for all of them.
> fix(ci): less logs in the test output

- cmd/build.go
- cmd/build_test.go
This should be valid and build both build1 and build2 but no other
goreleaser build --id build1 --id build2
Because it's annoying that this feature is missing.
closes #3211
> feat: allow multiple ids to be passed to build

- www/docs/customization/sign.md
`cosign sign` complains with the following error when using `--output`
⨯ release failed after 14.73s error=sign: cosign failed: exit status 1: WARNING: the '--output' flag is deprecated and will be removed in the future. Use '--output-signature'
...
...
...
> docs: use `--output-signature` with cosign sign

- cmd/root.go
- go.mod
- go.sum
- internal/logext/testdata/TestWriter/debug/0.txt.golden
- internal/logext/testdata/TestWriter/debug/1.txt.golden
- internal/logext/writer_test.go
the original caarlos0/log implementation used `PaddingLeft`, which prepend spaces before the color schemes et al - and is probably the right thing to do
but, and there's always a but, it seems like github actions trims whitespaces, which made the indentations not work.
so, moved to printing spaces inside the styled string... what can you do?
this version update also improves the output a bit by giving some extra right padding, which may make the log output a bit more columnar in most cases, and hopefully a bit more readable as well.
refs https://github.com/caarlos0/log/pull/1
special thanks to @muesli for the help!
> fix: improve output on github actions

- internal/middleware/errhandler/error.go
Skip messages are not an error, in fact.
> chore: make skip messages more idiomatic

- internal/pipe/git/git_test.go
- internal/pipe/universalbinary/universalbinary_test.go
- pkg/archive/tar/tar_test.go
- pkg/archive/tarxz/tarxz_test.go
- pkg/archive/zip/zip_test.go
there is too much going on in our test logs, and we have a lot of tests.. so... its too much output to scroll over/read/etc.
Trying to reduce it to the necessary only.
> test: reducing test ouput

- internal/builders/buildtarget/targets.go
- internal/builders/buildtarget/targets_test.go
we dont need to check the go version anymore, so we can remove all this
now.
> refactor(build): remove unused param

- internal/archivefiles/archivefiles.go
- internal/archivefiles/archivefiles_test.go
- www/docs/customization/archive.md
> fix(archive): always strip parent if set

- internal/builders/buildtarget/targets.go
- internal/builders/buildtarget/targets_test.go
go 1.19 supports linux loong64: https://go.dev/doc/go1.19
> feat: support goarch=loong64

- internal/tmpl/tmpl.go
- www/docs/customization/templates.md
Fix https://github.com/goreleaser/goreleaser/issues/3269 by adding the `split` template function for `strings.Split()`
> Add split function

- internal/pipe/snapcraft/snapcraft.go
It seems that the error I get sometimes (#3257) is related to snap push
not being able to work concurrently.
I'm not a 100% sure though, so I'll try this and see how it goes.
If the error still happens, we can ignore the error or retry.
closes #3257
> fix: do not push snaps concurrently

- internal/client/github.go
closes #3044
What happens is that, if the tag is created only locally, it'll create the tag in the remote upon creating the release. The tag still needs to be created locally though!
@bep let me know if that works for you.
> feat: delay github tag creation

- cmd/root.go
- go.mod
- go.sum
This PR releates to #3328 and fix the first part of the doings in the issue
> feat: add fig autocomplete support

- internal/pipe/sourcearchive/source.go
- internal/pipe/sourcearchive/source_test.go
- pkg/config/config.go
- www/docs/customization/source.md
- www/docs/static/schema.json
`--add-file` adds only the `--prefix` joined with the basename of the added file, so, adding a folder like `vendor` would break havoc.
this basically writes our own source archives (which are more compressed) and allows to add an entire folder easily, as well as other mappings as `archives` already supports. 
refs #3102 #2911
> fix: source archive add subfolders

- internal/client/github.go
- internal/client/github_test.go
- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
- pkg/config/config.go
- www/docs/customization/changelog.md
this allows the user to specify the abbrev lenght to use, and will also add the option to omit the commit hash altogether by setting it to -1.
default is doing nothing
closes #3348
> fix: guard changelog commit abbrev behind config

- internal/pipe/release/scm.go
- internal/pipe/release/scm_test.go
> fix: templates in release URLs

- .github/workflows/build.yml
- cmd/config.go
- internal/builders/golang/build_test.go
- internal/exec/exec_mock.go
- internal/gio/safe_test.go
- internal/git/config.go
- internal/logext/writer_test.go
- internal/pipe/archive/archive.go
- internal/pipe/aur/aur.go
- internal/pipe/blob/upload.go
- internal/pipe/env/env.go
- internal/pipe/linkedin/client_test.go
- internal/pipe/mattermost/mattermost_test.go
- internal/pipe/release/release.go
- internal/pipe/webhook/webhook_test.go
- internal/testlib/git.go
- pkg/context/context.go
run semgrep-go ruleguard and semgrep scans
https://github.com/dgryski/semgrep-go
> fix: ruleguard and semgrep scans and fixes

- internal/pipe/release/release.go
very small improvement, but useful nevertheless
> fix: print release url after publishing it

- .goreleaser.yaml
- internal/static/config.go
- www/docs/customization/index.md
- docs on how to specify the schema to the lang server
- add it automatically along with vim modelines to the init config
- added it to our config as well
this should prevent some "out of date" schema issues, as well as mixing tabs with spaces and whatnot when an editorconfig plugin is not installed.
> fix: yaml-lang-server modelines in init config

- Dockerfile
fix for https://github.com/sigstore/cosign/security/advisories/GHSA-8gw7-4j42-w388
> fix: update cosign in docker img to 1.12.0

- cmd/build.go
- cmd/build_test.go
When using specific targets in the config, single target becomes ineffective. This should fix it.  This also removes other build options like gomips, goarm, goamd64, etc, as go will infer them from the current OS.  In theory we should one day support all the GO* flags go build supports.
> fix: build --single-target when using specific targets

- internal/pipe/archive/archive.go
- internal/pipe/archive/archive_test.go
- www/docs/errors/multiple-binaries-archive.md
- www/mkdocs.yml
> fix: binary archive when multiple builds

- .github/workflows/build.yml
- .github/workflows/release.yml
split build & release workflows
> chore: splitting workflows

- .github/workflows/build.yml
- .github/workflows/gitleaks.yml
- .github/workflows/lock.yml
- .github/workflows/milestone.yml
- .github/workflows/release.yml
- only run the build action when actual go files changed
- only run some actions on the main fork to avoid errors
> chore: avoid running actions when not needed/possible

- internal/pipe/nfpm/nfpm.go
- www/docs/customization/nfpm.md
> docs: update nfpm docs

- cmd/release.go
- cmd/release_test.go
> refactory: making merges with pro easier

- pkg/config/config.go
- www/docs/static/schema.json
> fix: client key and cert should not be required

- internal/client/gitlab.go
- internal/client/gitlab_test.go
If applied, this commit will allow for new GitLab clients to use both ci job tokens and plain tokens (for things like brew publishing where the CI_JOB_TOKEN isn't applicable)
This provides a fix for #3399
---
closes #3399
> bugfix: handle mixing of job and normal tokens

- USERS.md
One of the examples of where we use it https://github.com/meroxa/cli/blob/master/.github/workflows/release.yml#L31-L32.
Thank you for such fantastic tool!
> docs: adds Meroxa to USERS.md

- USERS.md
This will add Goldenhand Software to users' list 
I would like to support GoReleaser as a solo contactor
https://www.goldenhandsoftware.co.uk/
Note: I love the announce functionality of GoReleaser and I do think anything other than Slack should be included in GoReleaser PRO. Announce requires a good time of development for change notes to be announced in different integrations. As a developer who do integrations every day, I do think announce section should require PRO (excluding slack and webhook one)
> docs: add Goldenhand Software to users

- www/docs/customization/homebrew.md
This PR fixes one line in the `homebrew` example section.
In the example of the `homebrew` section, the `url_template` value seems to be wrong.
> Fix the `url_template` line of the brew example

- internal/pipe/gomod/gomod.go
- internal/pipe/gomod/gomod_test.go
- www/docs/customization/build.md
- www/docs/customization/verifiable_builds.md
> fix: gomod.env not being used

- internal/middleware/logging/logging.go
Sub-steps of the publish steps do not have the *took:* log, this will fix it.
> fix: log duration of padlog steps

- internal/pipe/telegram/telegram.go
- www/docs/customization/announce/telegram.md
Set MarkdownV2 as parse mode for Telegram announcer.
This allows for additional formatting in the announcement, such as `code` or _italic_ sections. For details, see the official [Telegram Bot API](https://core.telegram.org/bots/api#markdownv2-style).
If someone has the time (not added in this PR), I think it would be great to add a field to the Telegram config for the parse mode. This would allow setting a different parse mode than MarkdownV2, such as HTML.
This fixes #3431.
> feat: MarkdownV2 for Telegram announcer

- www/docs/errors/multiple-tokens.md
> docs: better document multiple tokens error

- cmd/build.go
- cmd/release.go
- cmd/schema.go
refs https://github.com/withfig/autocomplete/pull/1584
cc/ @fedeci - thanks for the pointers :) 
refs #3328
> fix: annotate flags so they complete better

- www/docs/customization/homebrew.md
* Fix `http` with `https`.
Signed-off-by: Gökhan Özeloğlu <gokhan.ozeloglu@deliveryhero.com>
> docs: fix url misspelling

- internal/git/git.go
- internal/git/git_test.go
- internal/pipe/git/git.go
this improves mergeability between pro and oss a bit
> refactor: making it easier to merge with pro

- go.mod
- go.sum
- internal/pipe/nfpm/nfpm.go
This PR upgrades nFPM to v0.20.0, and integrates the new `ConventionalExtension` method to use the correct extension for the packaging format that is being used.
Currently, goreleaser uses the name of the format to determine the extension. This has worked fine, but with the introduction of Archlinux packages, goreleaser has to handle packages with extensions that don't match the name of the format, since Archlinux uses `.pkg.tar.zst` as the extension.
goreleaser/nfpm#546
goreleaser/nfpm#543
>  feat: integrate ConventionalExtension from nfpm v2.20.0 

- www/docs/customization/aur.md
- www/docs/customization/homebrew.md
- www/docs/customization/scoop.md
- www/docs/scm/gitea.md
This PR adds explicit mention of Gitea in the AUR, Homebrew and Scoop sections.
I have tested and tried using Homebrew and Scoop with a Gitea instance, I have not tried the AUR but it should work the same.
> docs: Mention Gitea explicitly

- internal/pipe/defaults/defaults.go
This PR will truncate any trailing slash left by specifying only a Gitea API URL.
Fixes #3487
I have not added any tests for this.
> fix: Trim trailing slash from Gitea URL

- internal/pipeline/pipeline.go
Its not really needed, nor used for anything, and can cause some issues.
fixes #3510
> fix: do not run changelog on goreleaser build

- www/docs/ci/gitlab.md
- www/docs/scm/gitlab.md
add warning about gitlab-ci protected variables for both CI/gitlab and SCM/gitlab. 
Failing to run the pipelines on a protected ref will cause goreleaser to fail with `401: unauthorized` if for example, GITLAB_TOKEN is a protected variable and the CI Job is running on a tag that is not protected.
Add a warning about Gitlab CI and protected variables
To prevent future users from running into issues with protected variables.
[Discord Convo](https://discord.com/channels/890434333251362866/890434334803247126/1038130560293412955)
> docs: update docs to mention gitlab protected vars

- .goreleaser.yaml
- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
- www/docs/customization/changelog.md
Fix the regular expressions used in changelog group processing to valid golang (RE2) regexps. These previously used PCRE character class `\w` which is not supported in RE2 which is what golang regexp uses.
Also document that format matches not just title as some may thing but the format `<abbrev-commit> <title-commit>`.
> fix(changelog): group regexps

- internal/artifact/artifact.go
- internal/builders/golang/build.go
- internal/pipe/archive/archive.go
- internal/pipe/build/build.go
- internal/pipe/build/build_test.go
- pkg/config/config.go
- www/docs/customization/build.md
This PR improves the handling of shared or static libraries by GoReleaser. It uses the default behaviour of the Go compiler by appending the right extension to libraries.
* `.so` and `.a` for Linux shared libraries and static libraries respectively
* `.dylib` and `.a.` on Darwin
* `.dll` and `.lib` on Windows (pre-existent)
It does not add any configuration option to `.goreleaser.yml`, since it leverages the existing `buildmode` flag.
Additionally, this PR takes care of adding the generated header file into the archive.
Personally I would leverage this change to release some software both as a CLI and as a shared library. I believe others who use CGo or need interoperability with Go from other languages could benefit from this.
This was previously discussed in #3497.
I couldn't quite …
> feat: build of shared/static libraries

- internal/pipe/checksums/checksums.go
- internal/pipe/checksums/checksums_test.go
- internal/pipe/docker/docker.go
Following #3540, output artifacts' checksums to the artifact info.
This addition makes it easier to consume the checksums, especially when running from e.g. GitHub Actions.
New tests:
1. Add a check for the checksum in the extra field. 
2. Add a test for every checksum algorithm (to see that it doesn't break for any algo's output).
3. Add a case of a binary and an extra file (to see that the logic doesn't break when there's a mix).
p.s.
While working on that, I noticed that the convention for extra fields is actually to use UpperCamelCase rather than lower. 
I was mistaken because I looked at the subfields of the "DockerConfig" extra field.
I think it's a good idea to fix it quickly, before the next release rolls and it becomes a compatibility issue.
I took the liberty to fix it here as …
> feat: output checksums to artifacts info

- internal/pipe/docker/docker.go
> fix: log when no artifacts are found for docker

- pkg/config/config.go
- www/docs/static/schema.json
this should prevent yamlschema from complaining on some fields that accept an integer or string (goarm) and a bool or string (skip*)
> docs: improve schema

- internal/artifact/artifact.go
- internal/pipe/docker/docker.go
- internal/pipe/sign/sign.go
- internal/pipe/sign/sign_docker.go
- internal/pipe/sign/sign_docker_test.go
- www/docs/customization/docker_sign.md
this drives it home by using the actual images/manifest digests to sign with cosign by default.
the default signing command is changing in this PR, but since `digest` should be always there (if not, the pipeline will fail way earlier), it should be fine.
refs https://github.com/goreleaser/goreleaser/issues/3496
refs https://github.com/goreleaser/goreleaser/pull/3540
> feat: use digest to sign docker images/manifests

- internal/pipe/docker/docker_test.go
- internal/pipe/docker/manifest.go
this use the digests on the manifest creation.
Another PR will add it to signing too.
refs #3496
refs #3540
> feat: use digest on manifests

- go.mod
- go.sum
- internal/pipe/announce/announce.go
- internal/pipe/mastodon/mastodon.go
- internal/pipe/mastodon/mastodon_test.go
- pkg/config/config.go
- pkg/defaults/defaults.go
- www/docs/customization/announce/mastodon.md
- www/mkdocs.yml
This PR adds [mastodon](https://joinmastodon.org/) as an announcement pipeline. 🥳 
Resolves #3566
> feat: add mastodon

- internal/pipe/mastodon/mastodon.go
- internal/pipe/mastodon/mastodon_test.go
- pkg/config/config.go
- www/docs/customization/announce/mastodon.md
> fix: move mastodon server to yaml

- internal/client/github.go
It makes no sense, but I saw it happens some times... the release will be created as a draft, even though there's nothing telling it to do so.
Editing the release later might do the trick, hopefully.
closes #3541
> fix: improve github release code

- .github/workflows/codeql.yml
> fix(ci): codeql use go 1.19

- www/docs/overrides/home.html
> You can verify yourself as the owner of the links in your profile metadata. For that, the linked website must contain a link back to your Mastodon profile. The link back must have a `rel="me"` attribute. The text content of the link does not matter. 
I checked that `display: none;` doesn't affect the verification process, I was able to "verify" a link using a quick test on my own profile.
I'm not convinced this is the _best_ way, but it is _a_ way. On other pages on the site you have a mastodon link, if those were added to the front page they would also suffice (assuming the above criteria are met).
> chore: verify website for mastodon

- go.mod
- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
- www/docs/customization/templates.md
added new `title` template function.
extracted from #3589
> feat: title template function

- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
- www/docs/customization/build.md
ignore invalid environment variables (e.g. no key, no value, or no equal sign)
> fix: validate env templates

- internal/pipe/brew/brew.go
- internal/pipe/brew/brew_test.go
- internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/valid_tap_templates.rb.golden
Should not be needed in most cases, but doesn't hurt to make it work anyway.
closes #3587
> feat(brew): allow to template brew.install

- .goreleaser.yaml
- cmd/init.go
- cmd/testdata/good.yml
- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
- internal/exec/exec.go
- internal/http/http.go
- internal/pipe/archive/archive.go
- internal/pipe/aur/aur.go
- internal/pipe/brew/brew.go
- internal/pipe/chocolatey/chocolatey.go
- internal/pipe/krew/krew.go
- internal/pipe/nfpm/nfpm.go
- internal/pipe/sbom/sbom.go
- internal/pipe/scoop/scoop.go
- internal/pipe/snapcraft/snapcraft.go
- internal/static/config.go
- internal/static/config.yaml
- internal/static/config_test.go
- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
- pkg/config/config.go
- www/docs/customization/archive.md
- www/docs/customization/nfpm.md
- www/docs/customization/snapcraft.md
- www/docs/customization/templates.md
- www/docs/deprecations.md
The replacements thing was always a bit weird, especially on archives.
We can solve that with templates, so, removing I'm deprecating it.
Also did the same on other places that had it the same feature.
Closes #3588
> feat: deprecate replacements

- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
- internal/pipe/build/build.go
- internal/pipe/build/build_test.go
- www/docs/customization/build.md
GoReleaser evolved a lot since the last time I tried to implement this >1 year ago. 
Now its 100% possible, and way simpler to do it!
closes #3580
refs #2583
> feat(build): allow to template env

- internal/pipe/docker/api.go
- internal/pipe/docker/api_docker.go
- internal/pipe/docker/docker_test.go
- internal/pipe/docker/manifest.go
it was missing the digest parsing for the manifest, and there were no tests covering it.
now the tests are there, and so is the fix.
refs #3599
> fix: missing digests on manifests

- internal/artifact/artifact.go
`List()` "materializes" the filters, so its used everywhere... if we have multiple files with the same name there, its likely some filter wasn't enough, or that the user configuration is faulty. Either way, we should warn about it to help prevent release issues (like duplicated assets on github).
> fix: warn if list has multiple files with same name

- internal/client/github.go
this should help when reporting issues to github, especially the magical "failed successfully" error
> fix: log request-id on upload error and release create/update

- pkg/config/config.go
- www/docs/static/schema.json
adds all the options allowed in the `artifacts` field to the schema
> fix: improve schema for signs

- pkg/archive/zip/zip.go
- pkg/archive/zip/zip_test.go
fixes #3584 
When following the reproduction steps in #3584 I now get the following contents for the zip archive:
```
$ goreleaser --snapshot --skip-publish
...
$ (mkdir thezip && cd thezip && unzip ../dist/test_0.0.0-SNAPSHOT-none_darwin_amd64.zip) && ls -lR thezip
Archive:  ../dist/test_0.0.0-SNAPSHOT-none_darwin_amd64.zip
inflating: a/x                     -> ../x 
inflating: a/x2                    -> x 
inflating: x                       
inflating: test                    
finishing deferred symbolic links:
a/x                    -> ../x
a/x2                   -> x
total 1640
drwxr-xr-x  4 orawlings  staff     128 Nov 22 16:19 a
-rwxr-xr-x  1 orawlings  staff  833104 Nov 22 16:19 test
-rw-r--r--  1 orawlings  staff       2 Nov 22 15:32 x
thezip/a:
total 0
lrwxr-xr-x  1 orawlings …
```
> fix: retain symlinks added to zip archives

- internal/pipe/git/git.go
- internal/pipe/git/git_test.go
- pkg/config/config.go
- www/docs/customization/build.md
- www/docs/customization/git.md
- www/mkdocs.yml
> feat: custom tag.sort

- www/docs/customization/docker.md
Fix the wrong `skip_push` to `skip_build` in `docker.md`.
> doc: fix `skip_push` parameter to `skip_build`

- internal/archivefiles/archivefiles.go
- internal/archivefiles/archivefiles_test.go
- pkg/archive/gzip/gzip.go
- pkg/archive/gzip/gzip_test.go
- pkg/archive/tar/tar.go
- pkg/archive/tar/tar_test.go
- pkg/archive/targz/targz_test.go
- pkg/archive/tarxz/tarxz_test.go
- pkg/archive/zip/zip.go
- pkg/archive/zip/zip_test.go
- pkg/config/config.go
- pkg/config/config_archive_files_test.go
- www/docs/customization/archive.md
this allows to template the owner, group and mtime in file infos inside archives.
should help towards reproducible builds!
goes well with #3618
> feat: allow to template archives.files.info

- USERS.md
Just adding Optimus Mine to the users. We've been using GoReleaser from day one and love it! 🙂
> docs: add Optimus Mine to GoReleaser users

- internal/artifact/artifact.go
the warning was too trigger happy, this should fix it.
thanks @ioga for reporting it.
> fix: multiple files with same name warning

- .goreleaser.yaml
- internal/archivefiles/archivefiles.go
- internal/archivefiles/archivefiles_test.go
- internal/pipe/archive/archive.go
- internal/pipe/archive/archive_test.go
- internal/pipe/sourcearchive/source.go
- internal/static/config.yaml
- pkg/config/config.go
- www/docs/customization/archive.md
- www/docs/customization/source.md
- www/docs/deprecations.md
with this patch, a config like:
```yaml
archives:
- format: tar.gz
name_template: >-
{{ .ProjectName }}_
{{- title .Os }}_
{{- if eq .Arch "amd64" }}x86_64
{{- else if eq .Arch "386" }}i386
{{- else }}{{ .Arch }}{{ end }}
{{- if .Arm }}v{{ .Arm }}{{ end }}
rlcp: true
files:
- src: "build/**/*"
dst: .
nfpms:
- package_name: foo
contents:
- src: "build/**/*"
dst: usr/share/foo
formats:
- apk
```
will eval this:
as much as I would like to make this the default, it would be a breaking change, so we really can't do it.
If `dst` is empty, it'll have the same behavior as before (no rlcp), and if `strip_parent` is set, it will also still have the same behavior. Finally, if the format is binary, `rlcp` is ignored too (as it doesn't make sense).
So, this only changes if:
- your format is not …
> feat: better archives relative paths

- go.mod
- go.sum
- internal/middleware/errhandler/error.go
- internal/middleware/errhandler/error_test.go
- internal/pipe/announce/announce.go
- internal/pipe/announce/announce_test.go
- internal/pipe/discord/discord.go
- internal/pipe/discord/discord_test.go
- internal/pipe/linkedin/linkedin.go
- internal/pipe/linkedin/linkedin_test.go
- internal/pipe/mastodon/mastodon.go
- internal/pipe/mastodon/mastodon_test.go
- internal/pipe/mattermost/mattermost.go
- internal/pipe/mattermost/mattermost_test.go
- internal/pipe/reddit/reddit.go
- internal/pipe/reddit/reddit_test.go
- internal/pipe/slack/slack.go
- internal/pipe/slack/slack_test.go
- internal/pipe/smtp/smtp.go
- internal/pipe/teams/teams.go
- internal/pipe/teams/teams_test.go
- internal/pipe/telegram/telegram.go
- internal/pipe/telegram/telegram_test.go
- internal/pipe/twitter/twitter.go
- internal/pipe/twitter/twitter_test.go
- internal/pipe/webhook/webhook.go
- internal/pipe/webhook/webhook_test.go
This prevents one announce failure to skip all other announcers.
The release will still report a failure in the end, but will not fail in the first failure.
Also improved errors messages a little bit.
closes #3663
> fix: only fail announcing phase in the end

- internal/client/github.go
Linked issues will be resolved.
Because the program will no longer have to refer to nil.
- https://github.com/goreleaser/goreleaser/issues/3669
> fix: Check that the variable resp is not nil

- Dockerfile
- www/docs/customization/nfpm.md
/usr/local/bin is for binaries compiled locally, which is not the case in our docker image or in our examples.
> fix: do not put binaries in /usr/local/bin

- www/docs/intro.md
Every other instance I have seen so far uses `.yaml` so, for consistency, let's rename this one?
> docs: rename `.goreleaser.yml` to `.goreleaser.yaml` in intro

- internal/pipe/nfpm/nfpm.go
To help solve this issue
```
apk:
signature:
key_file: "{{ .Env.ABUILD_KEY_NAME }}.rsa"
key_name: "{{ .Env.ABUILD_KEY_NAME }}"
```
Allow that the key_name in apk signature to be templated
The name of the key might not be hardcoded, in a github workflow
...
> feat: allow to template apk keyname

- Taskfile.yml
- cmd/build.go
- cmd/build_test.go
- cmd/release.go
- cmd/release_test.go
- internal/pipe/dist/dist.go
- www/docs/ci/actions.md
- www/docs/ci/codefresh.md
- www/docs/ci/gitlab.md
- www/docs/cmd/goreleaser_build.md
- www/docs/cmd/goreleaser_release.md
- www/docs/cookbooks/override-image-name.md
- www/docs/cookbooks/semantic-release.md
- www/docs/customization/monorepo.md
- www/docs/customization/partial.md
- www/docs/deprecations.md
- www/docs/errors/no-main.md
- www/docs/install.md
- www/docs/quick-start.md
After talking with @perylemke, we realized that probably most people will likely expect it to be called --clean instead of --rm-dist, as its more similar to the popular `make clean` task.
This adds the --clean flag, and make the --rm-dist one deprecated.
> feat: deprecate --rm-dist in favor of new --clean flag

- internal/pipe/nfpm/nfpm.go
- internal/pipe/nfpm/nfpm_test.go
problem was made evident in the last nfpm update... this should fix it.
refs #3715
> fix: only debs should create iphoneos pkgs

- cmd/build.go
- cmd/build_test.go
- cmd/release.go
- cmd/release_test.go
- cmd/root.go
- internal/deprecate/deprecate.go
- internal/pipe/dist/dist.go
- internal/pipe/dist/dist_test.go
- pkg/context/context.go
- improved how we handle `--rm-dist` deprecation so it looks more like other deprecations
- improved deprecation error message a bit as well
> fix: improve handling of --rm-dist deprecation 

- www/docs/customization/changelog.md
Fix a typo in https://goreleaser.com/customization/changelog/
> changelog: fix typo

- www/docs/deprecations.md
Fix the deprecation notice page to reference the correct new flag replacing `--rm-dist`
...
The documentation for this deprecation seems incorrect, and live on the main page.
...
https://goreleaser.com/deprecations/#-rm-dist
...
I used this commit to reference what it was being changed to: https://github.com/goreleaser/goreleaser/commit/4954815ae491b8c81f884660f76323d77218adf1
> Fix deprecation notice for `--rm-dist` -> `--clean`

- Taskfile.yml
our build is too close to the default 30m timeout, this should prevent it from failing, as it [did today](https://github.com/goreleaser/goreleaser/actions/runs/4049530951/jobs/6966004880)
> build: increase release timeout

- internal/pipe/ko/ko.go
- internal/pipe/ko/ko_test.go
- pkg/config/config.go
The commit will add the `bare` option to ko publisher options when set/passed via config `.goreleaser.yaml`.
Currently, even the `bare: true` is set via config,  the option was never passed to `ko` PublisherOptions.
#3742
> fix: honouring ko bare option

- internal/exec/exec_test.go
otherwise we might get warnings like
> warning: GOCOVERDIR not set, no coverage data emitted
> test: fix exec tests on go 1.20

- internal/client/gitlab.go
- internal/client/gitlab_test.go
Hi, I found a bug in the GitLab client that leads to not correctly prepend/append/keep releases notes.
This will use the original `Description`  instead of the pre-rendered `DescriptionHTML`. Furthermore, as `include_html_description` is not enabled, the `DescriptionHTML` field is always empty.
[GitLab documentation](https://docs.gitlab.com/ee/api/releases/index.html#get-a-release-by-a-tag-name)
> fix(gitlab): correctly prepend/append/keep releases notes

- .goreleaser.yaml
> build: do not release for windows arm7

- internal/pipe/aur/aur.go
- internal/pipe/aur/aur_test.go
- www/docs/customization/aur.md
password-protected keys would give path errors, which was simply not right.
> fix: better handle password protected keys

- internal/artifact/artifact.go
- internal/exec/exec.go
- pkg/context/context.go
I have no idea why this never happened before... the lock was ineffective in `artifacts.List`, which should have caused at least some race condition at some point.
Anyway, got it once locally while working on another feature, and couldn't believe my eyes.
Fixed, thank goodness!
> fix: race condition on artifacts.List

- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
Creating the temp dir for docker builds was required back in the day because we symlinked the files, so to avoid different filesystems et al, this was the easier solution.
Since many versions ago, we switched to copying the files instead, which works a lot better.
This also means we don't need the dist check for extra files anymore, as long as we create the temp outside dist.
All that said, this PR does 2 things:
- changes the docker pipe to create the dist in the user's tempdir instead of dist
- removes the dist path check for docker's extra files
closes #3790
closes #3791
> fix: create temp docker outside dist

- .github/workflows/lint.yml
refs https://github.com/golangci/golangci-lint-action/issues/677
> build: fix golangci-lint failing

- internal/pipe/git/git.go
- internal/pipe/git/git_test.go
- pkg/config/config.go
- www/docs/customization/git.md
- www/docs/static/schema-pro.json
- www/docs/static/schema.json
This commit will fix bad version tag sort if there is a prerelease on the same commit as a release tag. Current output is shown below
```
❯ git tag --points-at HEAD --sort=-version:refname --format='%(creatordate)%09%(refname)'
Thu Mar 2 21:38:51 2023 +0300   refs/tags/v1.13.0-rc3
Thu Mar 2 21:38:51 2023 +0300   refs/tags/v1.13.0
```
Test is changed to match current default value so it will fail without this fix.
Default value `-` is set to the one that is described inside [docs](https://goreleaser.com/how-it-works/?h=prerelease#how-it-works), but people are still allowed to change it.
Output with fix applied
```
❯ git -c versionsort.suffix=- tag --points-at HEAD --sort -version:refname --format='%(creatordate)%09%(refname)'
Thu Mar 2 21:38:51 2023 +0300   refs/tags/v1.13.0
Thu Mar 2 …
```
> feat: include prerelease suffix in git

- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
- www/docs/customization/templates.md
allows to use `{{ .IsDraft }}` in templates.
> feat: IsDraft template variable

- internal/pipe/git/git.go
- internal/pipe/sign/sign.go
- internal/pipe/sign/sign_test.go
Fixes issue #3890 by checking the user's git `gpg.program` configuration. If the user didn't set this value it will use the default "gpg", just like before this PR.
No need to add a additional unit test as your existing tests cover it (mostly); however, a comment has been added to that check, informing the reader that the test environment assumes `git config gpg.program` is not be set.
> fix(gpg sign): issue #3890

- internal/pipe/upload/upload_test.go
This fixes a redundant import of `net/http` in `internal/pipe/upload`.
> internal/pipe/upload: fix redundant net/http import

- internal/pipe/env/env.go
- internal/pipe/env/env_test.go
- www/docs/errors/multiple-tokens.md
This would allow to, when multiple tokens are set in the environment, force which one you want to use.
The need for this comes from the fact gitea sets both `GITHUB_TOKEN` and `GITEA_TOKEN`, and doesn't allow to easily disable either.
With this, users can add a `GORELEASER_FORCE_TOKEN=gitea` to force the gitea client to be used.
I'm not sure what's the best name for this env yet, happy to hear suggestions.
Also improved the `env_test.go` file a bit, as it was kinda messy with env vars...
refs https://github.com/orgs/goreleaser/discussions/3900
> feat: allow to forcefully use a token when multiple are set

- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
- internal/pipe/docker/testdata/Dockerfile.wrongbin
its too hard to debug docker build issues... sometimes is just a typo in the binary name, and you might end debugging it for way too long...
this prints the full path to the build context (so, locally at least, you can cd into it) and also all the files available there when the error seems to be one of the "file not found" kind.
Hopefully this helps fixing things easier :)
closes #3912
> feat: add context info to docker build errors

- pkg/config/config.go
- www/docs/static/schema.json
Add `binary` to Archive `format` enum in the JSON schema.
JSON schema validation currently fails on `archives[0].format: binary`:
```
Value is not accepted. Valid values: "tar", "tgz", "tar.gz", "zip", "gz", "tar.xz", "txz".
``` 
Follow up to c41d6de833114f52759e6c6b70349d960a8ae293
> fix(jsonschema): add binary to Archive format enum

- internal/pipe/nfpm/nfpm.go
- internal/pipe/nfpm/nfpm_test.go
Add extension to produced artifacts so that they can be filtered in later steps
Fixes #3933
---
I tried running the tests before raising this, but I get an unrelated error with docker (I get the same error on `main`). I'm not sure about if you value a test specifically around this? If so, lmk and I'll try to add one
> fix(nfpm): Add extension to produced artifacts

- internal/pipe/sourcearchive/source.go
- internal/pipe/sourcearchive/source_test.go
- pkg/archive/zip/zip.go
- pkg/archive/zip/zip_test.go
> fix: source archive not being added when no extra-files

- internal/pipe/sourcearchive/source_test.go
- internal/testlib/archive.go
- pkg/archive/archive_test.go
- pkg/archive/tar/tar.go
- pkg/archive/tar/tar_test.go
This now works for files added to the source archive **after** the `git archive` command is run. During the `git archive`, it seems that the `tar` is still using some format that doesn't support utf-8 by default.
Tomorrow I'll look more into it.
see https://pkg.go.dev/archive/tar#Format
closes #3812
> test: ensure utf-8 sources/archives filenames work properly

- main.go
This might fail on windows/wsl (see https://github.com/uber-go/automaxprocs/issues/65), and its not too bad if it fails, actually, so, let's just warn the error instead of exiting 1
closes #3945
Signed-off-by: Carlos Alexandro Becker <caarlos0@users.noreply.github.com>
> fix: do not fatal on automaxprocs error

- www/docs/customization/artifactory.md
This property can be used to omit the artifact name from the target URL, which indirectly adds support for matrix parameters.
Fixes #3951
> docs(artifactory): Add details on custom_artifact_name

- .goreleaser.yaml
- internal/artifact/artifact.go
- internal/pipe/reportsizes/reportsizes.go
- internal/pipe/reportsizes/reportsizes_test.go
- internal/pipeline/pipeline.go
- pkg/config/config.go
- www/docs/customization/reportsizes.md
- www/mkdocs.yml
This adds a log with the size of the generated binaries/packages/etc in the end of the build process, and also adds it to the artifacts.json
closes #3949
TODO:
> feat: log generated artifact sizes

- internal/pipe/git/git.go
- internal/pipe/git/git_test.go
- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
- pkg/context/context.go
- www/docs/customization/templates.md
will only ever be true on snapshots or when ran with `--skip-validate`. This should be useful as a ldflag, for example.
> feat: IsGitDirty template variable

- cmd/build.go
- cmd/build_test.go
If you run `goreleaser build --single-target` with `universalbinaries[*].replace = true` on a mac, it'll break.
This fixes it by disabling universal binaries when building a single target.
It isn't useful anyway.
Closes #4004
> fix: goreleaser build index out of range

- www/docs/quick-start.md
To make it easier for someone to create a new GitHub Personal Access Token.
> Pre-fill scopes for new Personal Access Token

- internal/archivefiles/archivefiles.go
- internal/pipe/archive/archive.go
- pkg/config/config.go
Adjust the logging of warnings for unmatched globs to only show when the glob is not a default. No warning will be output for the default globs when there are no matching files.
These are defaults, by design, very generic.
We should not warn the user about them not finding anything, as that is their expected behavior most of the time.
> fix(archive): warn only for non-default globs with no matches

- internal/pipe/ko/ko.go
- internal/pipe/ko/ko_test.go
- www/docs/customization/ko.md
Empty tag names will then be filtered out. This allows to have optional tags depending on templates, for example,
`{{if not .Prerelease}}latest{{end}}`, among other use cases.
This already happens in the `dockers` section, and is now implemented in `kos` too.
refs https://github.com/orgs/goreleaser/discussions/4042
> feat(ko): allow to have an empty tag name

- internal/pipe/ko/ko.go
- internal/pipe/ko/ko_test.go
- www/docs/customization/ko.md
add ko-generated manifests to the artifact list, this way they can be signed later.
closes #4027
> feat: allow to sign KO manifests

- internal/pipe/telegram/telegram.go
- internal/pipe/telegram/telegram_test.go
- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
- pkg/config/config.go
- www/docs/customization/announce/telegram.md
- www/docs/customization/templates.md
this allows to choose parse mode between `HTML` and `Markdownv2`, and adds a new template function, `mdv2escape`, to escape the characters according to telegram docs: https://core.telegram.org/bots/api#formatting-options
closes #4021
> feat(telegram): ability to choose msg format, mdv2escape

- cmd/root.go
- internal/git/git.go
- www/docs/ci/codefresh.md
- www/docs/cookbooks/semantic-release.md
- www/docs/customization/release.md
- www/docs/deprecations.md
- deprecates `--debug` in favor of `--verbose` which is clearer 
- improved some debug log outputs
- docs: update documentation to always use the `release` subcommand (when it makes sense)
> feat: improve verbose output

- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
- www/docs/customization/templates.md
You can achieve the same with `{{ with (index .Env "NAME") }}etc`, but this looks cleaner.
refs #4096
> feat: envOrDefault template function

- www/docs/static/run
Primary motivation here is to fix the runner script on Linux arm64; see the first commit. The other two contain some while-at-it cleanups.
> docs: runner script fixes

- www/docs/static/run
Regression in 4b7827829298c2f4a23dfcdc79bd4fcb685ac1bf, .tar.gz twice. Sorry :(
> fix: runner tarball download URL

- www/docs/static/run
Sigh, yet another regression from 4b7827829298c2f4a23dfcdc79bd4fcb685ac1bf. I actually _did_ test already with 10a627c1967a09810473c182d6e1c1dcb8748f33, but for some reason failed to notice the error. Tested better now :/
> fix: runner tarball extract path

- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
this is needed when we run part of the pipeline on windows, and the rest on linux, for example, the split build pro feature.
extracted from https://github.com/goreleaser/goreleaser/pull/3795 
+ added tests for relative path thing
> fix: artifact.Path should filepath.ToSlash

- internal/archivefiles/archivefiles.go
> fix: archives should always use forward slash

- cmd/release.go
- internal/middleware/errhandler/error.go
- internal/pipe/aur/aur.go
- internal/pipe/aur/aur_test.go
- internal/pipe/brew/brew.go
- internal/pipe/brew/brew_test.go
- internal/pipe/chocolatey/chocolatey.go
- internal/pipe/chocolatey/chocolatey_test.go
- internal/pipe/krew/krew.go
- internal/pipe/krew/krew_test.go
- internal/pipe/milestone/milestone.go
- internal/pipe/milestone/milestone_test.go
- internal/pipe/nix/nix.go
- internal/pipe/nix/nix_test.go
- internal/pipe/publish/publish.go
- internal/pipe/publish/publish_test.go
- internal/pipe/scoop/scoop.go
- internal/pipe/scoop/scoop_test.go
- internal/pipe/snapcraft/snapcraft.go
- internal/pipe/snapcraft/snapcraft_test.go
- internal/pipe/winget/winget.go
- internal/pipe/winget/winget_test.go
- internal/pipeline/pipeline.go
- pkg/context/context.go
closes #3989
Basically, when some of these pipes fail, the error will be memorized, and all errors will be thrown in the end.
Meaning: the exit code will still be 1, but it'll not have stopped in the first error.
Thinking of maybe adding a `--fail-fast` flag to disable this behavior as well 🤔
> feat: continue on error

- www/docs/static/run
Behavior of the `EXIT` condition is not consistent between shells with regards to abnormal exits and signals. This cleanup should occur always.
https://austingroupbugs.net/view.php?id=621
> fix: do runner cleanups also on `SIGINT` and `SIGTERM`

- internal/pipe/nfpm/nfpm.go
- pkg/config/config.go
- www/docs/customization/nfpm.md
nfpm was updated, but we never allowed to configure the umask field in goreleaser.
> fix: umask nfpm field

- internal/pipe/snapcraft/snapcraft.go
It will otherwise create the empty fields in the yaml, and snapcraft then complains they are empty and fail.
> fix(snapcraft): title and icon are optional

- cmd/build_test.go
- internal/builders/golang/build_test.go
- internal/pipe/blob/blob_minio_test.go
- internal/pipe/build/build_test.go
- internal/pipe/git/git_test.go
- internal/pipe/slack/slack_test.go
- internal/pipe/snapcraft/snapcraft_test.go
- internal/testlib/path_test.go
- pkg/context/context_test.go
We have been using `t.Setenv` is most of our tests. This PR replaces the remaining `os.Setenv` with `t.Setenv`.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```
> test: use `t.Setenv` to set env vars

- internal/pipe/scoop/scoop.go
- internal/pipe/scoop/scoop_test.go
The check to skip Scoop releases when SCM ones are disabled seems to be the only place where this is happening and in conflict to Brew releases. These two need not be linked as users can configure the `url_template` to point elsewhere.
--- 
Consider the following use case:
```
* goreleaser/my-app.yml
- builds: spec for building a Go binary for my-app
- dockers: spec for packaging my-app in a container and pushing to Artifactory & GCP
- archives: spec for zipping up my-app binary
- artifactories: spec for pushing archives of my-app to a private jfrog artifactory
- brews: spec for publishing my-app through brew on macOS with URLs from artifactory
- scoop: spec for publishing my-app through scoop on Windows with URLs from artifactory
- release: disabled SCM (e.g. GitHub) release
```
Running …
> fix: Scoop releases being skipped via disabled SCM releases

- .goreleaser.yaml
> build(nix): fix goreleaser config path

- internal/archivefiles/archivefiles.go
- internal/pipe/chocolatey/chocolatey.go
- internal/pipe/krew/krew.go
- internal/pipe/krew/krew_test.go
- internal/pipe/nfpm/nfpm.go
- internal/pipe/nix/nix.go
- internal/pipe/scoop/scoop.go
- internal/pipe/snapcraft/snapcraft.go
- internal/pipe/winget/winget.go
- internal/tmpl/tmpl.go
If applied, this commit simplifies the code required to support templated fields in configuration files. This should make it easier to add more templated fields in the future.
As [discussed first on Discord](https://discord.com/channels/890434333251362866/1032457293687685191/1124033219747127316).
> chore: add function to apply template multiple times

- www/docs/deprecations.md
docs: fix yaml formatting on scoop deprecations
right now, the formatting at 
https://goreleaser.com/deprecations#scoop
is slightly broken when you click 'after'
> docs: fix yaml formatting on scoop deprecations

- internal/pipe/docker/docker.go
Delete the temporary directory used for building Docker images.
Leaving the temporary directory leads to wasted disk space.
> fix: Delete temporary dir used for docker build

- CONTRIBUTING.md
This PR fixes the links to Go and Task installation pages.
Official go site is now https://go.dev where the old link was automatically redicting.
Task's website has been changed and the installation procedure is now on its own page.
> docs: fix links

- Dockerfile
As discussed in #4176, this PR adds syft to the Docker image.
As mentioned in #4176, it simplifies CI when SBOM generation is needed.
I tried to test by running `task goreleaser` in my dev environment. The amd64 image has been built properly and syft is available:
```
docker run --rm -it --entrypoint="" goreleaser/goreleaser:v1.19.2-amd64 sh
/go # syft --version
syft 0.84.1
```
However I couldn't test other platforms since I got unrelated errors when it tried to build the arm64 image.
> feat: adds syft to docker image

- internal/pipe/docker/api.go
This is causing issues when trying to run tests in Dagger.
ref: https://github.com/goreleaser/goreleaser/pull/4186#discussion_r1262977616
Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>
> ci: append envs when calling docker instead of overriding

- internal/client/github.go
- pkg/config/config.go
- www/docs/customization/release.md
This commit adds a `make_latest` boolean to the release configuration,
to allow signaling to GitHub if the release should be marked as latest.
Albeit being a boolean, the internal Go type is a string to allow
to distinguish an empty string (default behavior: `true`) from an
explicit `false`.
For more information around the GitHub API field, see
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
I did not include the `legacy` option, to not adopt something which
appears to be scheduled for removal in the future.
In addition, I opted for `make_latest` over `latest` because the
option is only available for GitHub. Which keeps the latter key
reserved for e.g. future use of a config option which is used across
Git providers.
Fixes #4159
> Support `make_latest` for GitHub release

- go.mod
- internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.installer.yaml.golden
- internal/pipe/winget/winget.go
- internal/pipe/winget/winget_test.go
If an archive filename contains `/` characters, they can sneak into Winget's `RelativeFilePath`.
In this PR, I make sure that `RelativeFilePath` only uses `\` directory separators.
> fix(winget): replace forward slashes in Winget `RelativeFilePath`

- main.go
Remove the comment about WSL failing to set max procs as this was fixed by v1.5.3 of automaxprocs.
> chore: remove comment about WSL failure

- www/docs/deprecations.md
`index` should be `bucket` for scoop
> Fix deprecations notice about `scoops.bucket`

- cmd/config.go
- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
- internal/deprecate/deprecate.go
- internal/deprecate/testdata/TestNotice.txt.golden
- internal/deprecate/testdata/TestNoticeCustom.txt.golden
- internal/logext/styles.go
- internal/pipe/env/env.go
- improves deprecation warning styles a bit so they caught the readers eye faster and are easier to read 
- warns if the user uses `builds.target` in conjunction with other options which are ignored in that case
- improved env output
- improved no configuration found warning
some of the changes:
> feat: improve output

- .goreleaser.yaml
- internal/pipe/brew/brew.go
- internal/pipe/brew/brew_test.go
- internal/pipe/brew/testdata/TestRunPipeBinaryRelease.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
- internal/pipe/brew/testdata/TestRunPipePullRequest.rb.golden
- pkg/config/config.go
- www/docs/customization/homebrew.md
Allows to add manpages and shell completion installs without overriding the default bin.install.
> feat(brew): extra_install

- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
- internal/pipe/docker/testdata/Dockerfile.multiple
`docker` packaging does not honor the path structure defined in builds/binary
it copies all binaries to temp docker build folder
this PR fixes the behavior and make it same as `archive` 
for example
```
builds:
- id: xxx 
binary: plugins/xxx
```
before:
```
/tmp/goreleaserdocker2210262014/xxx
```
after:
```
/tmp/goreleaserdocker2210262014/plugins/xxx
```
> make docker build stage files same as archive

- internal/pipe/snapshot/snapshot.go
- internal/pipeline/pipeline.go
Otherwise .Version will be wrong.
closes #4247
> fix: snapshot should run before before hooks

- internal/client/github.go
- internal/client/github_test.go
if the base branch is empty, it'll try to fetch the default branch, which would fail if base repo name/owner are also empty.
the default behavior when base owner/name are missing is to using head's, so I changed it do that before trying to get the default branch, which should fix the issue.
> fix: failing when pull_request.base is empty

- internal/builders/buildtarget/targets.go
- internal/builders/buildtarget/targets_test.go
`wasip1` is a valid `GOOS` value in the upcoming go 1.21.
> feat: support WASI

- internal/client/client.go
- internal/client/client_test.go
- internal/pipe/aur/aur.go
- internal/pipe/brew/brew.go
- internal/pipe/chocolatey/chocolatey.go
- internal/pipe/krew/krew.go
- internal/pipe/nix/nix.go
- internal/pipe/release/release.go
- internal/pipe/release/release_test.go
- internal/pipe/scoop/scoop.go
- internal/pipe/winget/winget.go
Currently, GoReleaser will assume you're running against github, gitea or gitlab.
You could set `release.disable: true`, but it would still set and try to use some defaults that could break things up.
Now, if you disable the release, goreleaser will not set these defaults. It'll also hard error in some cases in which it would happily produce invalid resources before, namely, if `release.disable` is set, and, for example, `brews.url_template` is empty (in which case it would try to use the one from the release, usually github).
closes #4208
> feat: allow goreleaser to run in gerrit, soft-serve and others

- internal/pipe/snapcraft/snapcraft.go
- internal/pipe/snapcraft/snapcraft_test.go
the publish pipe, which runs all publishers, already skips all publishers if skip publish is set, so this check is not needed here.
> fix(snapcrafts): skip publish is check by publish pipe

- internal/pipe/chocolatey/chocolatey.go
- internal/pipe/chocolatey/chocolatey_test.go
the publish pipe, which runs all publishers, already skips all publishers if skip publish is set, so this check is not needed here.
> fix(chocolatey): skip publish is check by publish pipe

- internal/pipe/custompublishers/custompublishers.go
- internal/pipe/custompublishers/custompublishers_test.go
the publish pipe, which runs all publishers, already skips all publishers if skip publish is set, so this check is not needed here.
> fix(custom_publishers): skip publish is check by publish pipe

- internal/pipe/gomod/gomod.go
The gomod pipe will skip if the Go version does not support modules.
I tried to use goreleaser to build a project with Go v1.8.7 and it failed on `loading go mod information` step. The Go version used doesn't support `go list -m`.
The build failed with the following error:
```
• loading go mod information
⨯ release failed after 0s                          error=failed to get module path: exit status 2: flag provided but not defined: -m
usage: list [-e] [-f format] [-json] [build flags] [packages]
List lists the packages named by the import paths, one per line.
...
```
...
> feat: skip gomod pipe when Go does not support modules

- internal/pipe/sbom/sbom.go
Adds windows-specific `LOCALAPPDATA` to the list of passed through environment variables.  
closes #4290
> fix(sbom): Add LOCALAPPDATA to passthroughEnvVars

- www/docs/install.md
Fix link to homebrew formula on `install` page
> docs: fix link to homebrew formula on `install` page

- .gitignore
- internal/pipe/chocolatey/chocolatey.go
- internal/pipe/chocolatey/chocolatey_test.go
- www/docs/customization/chocolatey.md
tested this on a fake repo, and it seems to fix the problem...
seems like choco does not like when the path has `/` in it, so passing it through `filepath.Clean` fixes it.
also improved tests a bit, and made a small docs fix.
closes https://github.com/goreleaser/goreleaser/issues/4292
> fix: chocolatey push failing 

- internal/pipe/sbom/sbom.go
- pkg/config/config.go
the paths of the artifacts always use forward slashes, and the logic to handle the relative path stuff inside the sbom pipe did not account for that.
running the paths through `filepath.Clean` beforehand fixes it.
also improved yamlschema a little bit :) 
closes #4289
> fix(sbom): syft might fail on windows

- cmd/release.go
- internal/skips/skips.go
- internal/skips/skips_test.go
this will log everything that's being skipped in the beginning of the release process.
also added some tests to `skips`
> fix(skips): print all steps that will be skipped

- internal/tmpl/tmpl.go
We can use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` to avoid unnecessary `[]byte` conversions and reduce allocations. A one-line change for free performance gain.
Benchmark:
```go
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := envOnlyRe.Match([]byte("{{ .Env.FOO }}")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := envOnlyRe.MatchString("{{ .Env.FOO }}"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/goreleaser/goreleaser/internal/tmpl cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 4320873	       381.2 ns/op	      16 B/op	       1 allocs/op
BenchmarkMatchString-16    	 5973543	       203.9 ns/op …
```
> refactor(tmpl): avoid unnecessary byte/string conversion

- SECURITY.md
- internal/pipe/project/project.go
- internal/pipe/project/project_test.go
the release's defaults run before the project's does, so, usually the github/gitlab/gitea names are set.
however, in some cases, the release's defaults might be skipped, in which case they'll be empty.
this breaks things like `goreleaser changelog`, especially on non-go repositories.
this pr tries to extract the project name from the git remote url in the project's defaulter.
it might be possible now to move it to run before the release defaulter, even.
> fix: decouple project_name guessing from the release pipe

- internal/pipe/nix/testdata/TestRunPipe/deps_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/deps_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/extra-install_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/extra-install_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/minimal_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/minimal_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/open-pr_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/open-pr_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/partial_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/partial_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/skip-upload-auto_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/skip-upload_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip_publish.nix.golden
- internal/pipe/nix/tmpl.nix
As GoReleaser focuses on binary packages wrapped in Nix, it is important to mark their right source provenance, i.e. binary native code.
It came up in https://github.com/dagger/nix/pull/4.
If applied, this commit will mark every package built via GoReleaser for Nix with a binary source provenance, which is what GoReleaser does.
This change was made because it is impossible to know about the source provenance if the tooling template does not encompass it and downstreams won't apply it after an upgrade.
https://github.com/dagger/nix/pull/4
> feat(nix): mark all Nix packages with the right source provenance

- .goreleaser.yaml
- internal/static/config.yaml
- pkg/config/config.go
- pkg/config/config_test.go
this should make it easier later on when we have v2, as goreleaser will refuse to run with the wrong version in the configuration.
no version will still work on v1 though, its more to avoid running fils with `version: 2` later, and avoid files with no version or `version: 1` from running on v2.
> feat: version in the yaml file

- internal/pipe/gomod/gomod_proxy.go
- internal/pipe/gomod/gomod_proxy_test.go
- internal/pipeline/pipeline.go
> feat: check if go.mod has replace directives

- internal/pipe/gomod/gomod.go
- internal/pipe/gomod/gomod_test.go
- www/docs/customization/verifiable_builds.md
> fix: properly handle multi-module projects with a go.work file

- CONTRIBUTING.md
A test failed as I didn't had upx installed:
```
--- FAIL: TestRun (0.58s)
upx_test.go:119: 
Error Trace:    /home/cipri/git/goreleaser/internal/pipe/upx/upx_test.go:119
Error:          Received unexpected error:
upx not found in PATH
Test:           TestRun
FAIL
```
...
...
...
> docs: update CONTRIBUTING.md add upx as optional prerequesite

- internal/pipe/linkedin/client.go
- internal/pipe/linkedin/client_test.go
Closes #4421 
I chose to keep `getProfileID` as `getProfileIDLegacy` and use it as a fallback if `getProfileSub` fails because of permission scope.
In this way, it's not a breaking change because one that has only a deprecated permissions such as `r_liteprofile` will still be able to hit `v2/me`
this logic is encapsulated in the new function `getProfileURN`, that resolves the user identifier and returns it formatted as a URN
> fix: linkedin announce api changes

- internal/pipe/ko/ko.go
- internal/pipe/ko/ko_test.go
- www/docs/customization/ko.md
> feat: validate ko's main path

- internal/pipe/sbom/sbom.go
- internal/pipe/sbom/sbom_test.go
- www/docs/customization/sbom.md
refs https://github.com/orgs/goreleaser/discussions/4425
> SBOM improvements

- internal/pipe/brew/brew.go
In a `brews` section, goreleaser will fail when using `format: tar.xz` even though homebrew supports installing binaries bundled in a `.tar.xz` archive.
I use `.tar.xz` instead of `.tar.gz` and would like goreleaser to support this when used in conjunction with `brews` sections.
With this patch, I created a test [homebrew formulae](https://github.com/jftuga/homebrew-tap/blob/main/awswho.rb) and successfully installed it under macOS.
> fix: allow homebrew to use tar.xz format

- USERS.md
- www/docs/customization/blob.md
I corected documentation for upload blobs to azure Storage Service from [used library](https://github.com/google/go-cloud/blob/53ccd8db26a14fd2a40bfcb28af1a1ceba4663f4/blob/azureblob/azureblob.go#L30).
> docs(azblob): correct auth to Azure storage service

- cmd/build.go
- cmd/build_test.go
- internal/pipe/build/build.go
- internal/pipe/build/filter.go
- internal/pipe/build/filter_test.go
- internal/pipe/partial/partial.go
- internal/pipe/partial/partial_test.go
- internal/pipeline/pipeline.go
- internal/testctx/testctx.go
- pkg/context/context.go
- www/docs/contributing.md
> feat: improve --single-target

- www/docs/quick-start.md
Calling `goreleaser release --skip-publish` as according to the [dry run documentation](https://goreleaser.com/quick-start/?h=dry+run#release-flags) gives the following deprecation warning
```
• DEPRECATED: --skip-publish was deprecated in favor of --skip=publish, check https://goreleaser.com/deprecations#-skip for more details
```
This updates the documentation
> docs: update deprecated `--skip-publish` release flag

- www/docs/customization/changelog.md
Removed the duplicate GoReleaser Pro entry from the changelog.
https://github.com/goreleaser/goreleaser/blob/fdf73bda9e8f3223969b26856b3e976352dfa40b/www/docs/customization/changelog.md?plain=1#L81-L84
> docs: Removed the duplicate GoReleaser Pro entry

- internal/client/github.go
- internal/client/github_test.go
github api is eventually consistent... so, we might ask for the branch, it might say it does't exist, and when we try and create it, it might error because it already exists.
this should avoid breaking it
> fix(github): do not fail branch creation if it already exists

- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
when building a go test without the `-c` flag like so:
```yaml
builds:
- command: test
binary: env.test
dir: ./internal/builders/golang
no_main_check: true
```
will result in the error: `exit status 1: fork/exec : exec format error`
adding the -c flags when not present in the flags
adding unit test
https://github.com/goreleaser/goreleaser/issues/4462
> fix: add -c flags when building go test

- internal/pipe/brew/brew_test.go
- internal/pipe/brew/template.go
- internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
- pkg/config/config.go
- www/docs/customization/homebrew.md
- www/docs/static/schema.json
> feat(homebrew): add os to dependency

- www/docs/customization/builds.md
This change updates broken links to the old Go wiki to point to the new location.
> chore: update the link to the go wiki page on first-class ports

- pkg/config/config.go
- www/docs/static/schema.json
> fix(winget): improve schema

- www/docs/ci/actions.md
I've changed the GitHub Action workflow code example to be more inline with the code example on the GitHub repository:
1. https://goreleaser.com/ci/actions/#workflow
2. https://github.com/goreleaser/goreleaser-action?tab=readme-ov-file#workflow
This is done by four commits for better code/git diff:
1. https://github.com/goreleaser/goreleaser/commit/7f6d9eefffe1607e9cc778f10c12c5f491b95b62 Changed the GitHub action workflow from `actions/checkout@v3` to `actions/checkout@v4`.
Copying from the code example on the GitHub repository `goreleaser/goreleaser-action`:
1.  https://github.com/goreleaser/goreleaser/commit/effc880f3d220f16e6acd2f4fe0a1aa28f4b1994 The `name` items 
2. https://github.com/goreleaser/goreleaser/commit/9d7fc2949eb3eb35d6a71f2733b29ee8ea121070 The comments
3. …
> docs: GitHub Actions code example

- internal/semerrgroup/sem.go
- internal/semerrgroup/sem_test.go
log all skip reasons instead of only one, using a multierror.Error to merge them all.
refs https://github.com/orgs/goreleaser/discussions/4469
> fix: improve skip details

- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
- internal/pipe/archive/archive_test.go
refs #4513
this does not prevent the `dist` filepath to have spaces in it, although that's likely less of an issue, but it will remove the spaces from artifact's names.
Ideally, we could add a `tmpl.ApplyTrim` (or similar) that applies and trim spaces, and use it everywhere it makes sense (which is likely a lot of places).
Doing it on regular `Apply` might break things like release footers/headers, which usually rely on empty lines (although maybe its easier to treat those cases differently then).
Anyway, still thinking about it. Opinions are welcome :)
> fix: prevent having whitespaces in artifact names

- internal/pipe/chocolatey/chocolatey.go
- internal/pipe/chocolatey/chocolatey_test.go
- internal/skips/skips.go
If applied, this commit will add `chocolately` as a pipe that can be skipped. 
As Chocolately is only available on Windows machines (and [Linux machines with some effort](https://github.com/twpayne/chezmoi/blob/ff3deb9007ca4cf25e17b1c8665cb8f72fcaeaf9/.github/workflows/main.yml#L167-L171)), it's useful to be able to skip this pipe if you don't have a machine with Chocolately installed.
> feat: --skip=chocolately

- www/docs/install.md
👋 This commit updates links to nightly releases in the installation docs to match [the reference links](https://github.com/goreleaser/goreleaser/blob/29f30b623ef8f0a19607afab22b3f3a2f9f68172/www/docs/install.md?plain=1#L421-L422).
Section in the docs: https://goreleaser.com/install/#manually_1
> docs: fix typo in link to nightly release installations

- www/README.md
This PR adds a few notes on installing mkdocs and the extensions needed to run the documentation locally. The list of extensions was added to until build errors went away and the site was served successfully!
> docs: add instructions for setting up local documentation

- internal/pipe/nix/nix.go
- internal/pipe/nix/nix_test.go
- internal/pipe/nix/template.go
- internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_publish.nix.golden
- internal/pipe/nix/tmpl.nix
If `archives.[*].wrap_in_directory` is set, it'll create a folder inside the archive file, usually something like `app_goos_goarch`.
In those cases, the root of the archive is not constant, so we create a `sourceRootMap` and use it instead.
In cases where the `sourceRoot` is constant, the generated derivation will be the same.
refs https://github.com/orgs/goreleaser/discussions/4549
> fix(nix): sourceRoot when using archives.wrap_in_directory

- internal/pipe/slack/slack.go
- internal/pipe/slack/slack_test.go
As noted in #4556, when we're using a double quote, for use with a
template variable or function, we receive a template parse error as the
value needs to be unquoted.
This provides a slightly hacky solution which is to unquote any quoted
quotes.
Closes #4556.
> Fix: Allow using double quotes for templates in Slack notifications

- internal/http/http.go
From the Go specification [^1]:
> "3. If the map is nil, the number of iterations is 0."
Therefore, it is not required to do a nil check for the map before the loop.
[^1]: https://go.dev/ref/spec#For_range
> refactor(http): remove redundant `nil` check

- USERS.md
Found that the GitHub Code Search syntax did not work (anymore).
**Before**
_https://github.com/search?q=filename%3Agoreleaser+language%3Ayaml+path%3A%2F_
**After**
_https://github.com/search?q=path%3A%2Fgoreleaser.*+language%3Ayaml&type=code_
> chore: Updated the GitHub Code Search syntax

- internal/pipe/nix/nix.go
- internal/pipe/nix/testdata/TestBinInstallFormats/darwin-only-deps.golden
- internal/pipe/nix/testdata/TestBinInstallFormats/linux-only-deps.golden
- internal/pipe/nix/testdata/TestBinInstallFormats/mixed-deps.golden
- internal/pipe/nix/testdata/TestRunPipe/deps_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/deps_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/extra-install_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/extra-install_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/minimal_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/minimal_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/open-pr_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/open-pr_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/partial_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/partial_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/skip-upload-auto_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/skip-upload_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip-and-tar_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip-and-tar_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip_publish.nix.golden
- internal/pipe/nix/tmpl.nix
- use stdenvNoCC instead of pkgs.stdenvNoCC
- always include stdenvNoCC, even if no deps
- use stdenvNoCC.is(Darwin/Linux) instead of stdenv's
refs #4358
refs 003a8815
> fix(nix): improve generated derivations

- internal/git/config.go
- internal/git/config_test.go
If applied this change will allow goreleaser to handle relative remotes when attempting to parse a repo URL from git.
To fix the error that I recently came across while trying to test my goreleaser configuration:
```
% goreleaser check
• checking                                 path=
⨯ configuration is invalid                 error=invalid scm url: .
⨯ .goreleaser.yml                                  error=configuration is invalid: invalid scm url: .
⨯ command failed                                   error=1 out of 1 configuration file(s) have issues
```
This change happened while on a branch doing some development. As part of that development I needed to test a change to my goreleaser config.
My git config at the time looked like (repo obfuscated):
```
% cat .git/config
[core] …
```
> fix(config): handle relative git repos

- internal/pipe/nfpm/nfpm.go
- internal/pipe/nfpm/nfpm_test.go
- pkg/config/config.go
- www/docs/customization/nfpm.md
- www/docs/static/schema.json
This adds `nfpm.libdirs` to allow to set where to put libraries built, as well as include them in the search for artifacts when building the package.
closes #4346
---
PS: I'm not sure about the default dirs, let me know what you think!
> feat(nfpm): support libraries

- internal/pipe/brew/brew.go
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
Fix the order in which brew artifacts are sorted.
* The order occasionally switches, which results in a larger diff: https://github.com/confluentinc/homebrew-tap/pull/41
* The artifacts are already grouped by OS before `lessFnFor()` is called, so `list[i].OS > list[j].OS` always evaluates to `false` and the order remains unchanged. This PR removes that statement.
* It looks like a `map` is used earlier, while filtering the artifacts, which might explain why the order occasionally switches.
* Update the remaining statement in `lessFnFor()` to actually use `<` as the function suggests.
> Fix sort order of brew artifacts

- .golangci.yaml
- internal/pipe/before/before_test.go
- internal/pipe/sign/sign_test.go
This PR fixes cleanup in `TestMain` for `before` and `sign` tests, where`defer` is not called after `os.Exit`. This is [a common gotcha](https://gobyexample.com/exit) in Go, as `os.Exit` does not respect `defer` statements.
Additionally, the PR enables `gocritic` linter with [`exitAfterDefer` check](https://go-critic.com/overview.html#exitafterdefer) to prevent introducing this bug in the future.
> test(pipe): fix tests cleanup

- www/docs/ci/actions.md
This commit updates the GitHub Actions GoReleaser example by upgrading setup-go from version 4 to version 5. Additionally, it includes cleanup of the tables to address linting issues that flagged them as "incorrect".
I updated the setup-go version in the GitHub Actions GoReleaser example because right after I committed the exampled dependabot flagged the old version as outdated and suggested an update. I figured it'd be simple to just bump up the version to keep things current.
...
> docs: bump setup-go version

- .github/workflows/lint.yml
- .golangci.yaml
- cmd/build.go
- cmd/docs.go
- cmd/healthcheck.go
- cmd/man.go
- cmd/schema.go
- internal/artifact/artifact_test.go
- internal/client/gitlab.go
- internal/gio/safe_test.go
- internal/http/http_test.go
- internal/middleware/errhandler/error_test.go
- internal/middleware/logging/logging_test.go
- internal/pipe/chocolatey/chocolatey_test.go
- internal/pipe/docker/docker_test.go
- internal/pipe/gomod/gomod_proxy_test.go
- internal/pipe/ko/ko.go
- internal/pipe/linkedin/client_test.go
- internal/pipe/milestone/milestone.go
The PR fixes lint issues, pins `golangci-lint` to `v1.56.2`, disables `only-new-issues`, and enables `fail-on-issues` in the lint workflow. After this, all new lint issues will fail CI.
The full log of fixed lint issues:
```sh
❯ golangci-lint run
cmd/docs.go:24:14: unused-parameter: parameter 'cmd' seems to be unused, consider removing or renaming it as _ (revive)
RunE: func(cmd *cobra.Command, args []string) error {
^
cmd/man.go:26:14: unused-parameter: parameter 'cmd' seems to be unused, consider removing or renaming it as _ (revive)
RunE: func(cmd *cobra.Command, args []string) error {
^
cmd/healthcheck.go:36:14: unused-parameter: parameter 'cmd' seems to be unused, consider removing or renaming it as _ (revive)
RunE: func(cmd *cobra.Command, args []string) error {
^ …
```
> chore: fix all existing lint issues

- internal/client/client.go
- internal/client/gitea.go
- internal/client/github.go
- internal/client/gitlab.go
- internal/client/mock.go
- internal/pipe/release/release.go
- internal/pipe/release/release_test.go
- www/docs/customization/release.md
Previously end-users would see missing artifacts if trying to use latest version while artifacts are being uploaded.
This currently applies only to GitHub releases. GitLab does not support drafts, and I don't dare to make the change for Gitea since I don't use it (and can't test easily).
> feat(pipe/release): Mark GitHub releases as non-draft only after all artifacts are uploaded.

- internal/builders/golang/build_test.go
- internal/client/git_test.go
- internal/git/git_test.go
- internal/pipe/archive/archive_test.go
- internal/pipe/artifactory/artifactory_test.go
- internal/pipe/before/before_test.go
- internal/pipe/build/build_test.go
- internal/pipe/docker/docker_test.go
- internal/pipe/env/env_test.go
- internal/pipe/git/git_test.go
- internal/pipe/ko/ko_test.go
- internal/pipe/pipe_test.go
- internal/pipe/sbom/sbom_test.go
- internal/pipe/semver/semver_test.go
- internal/pipe/sign/sign_test.go
- internal/pipe/snapcraft/snapcraft_test.go
- internal/pipe/universalbinary/universalbinary_test.go
- internal/pipe/upload/upload_test.go
The PR refactors tests:
- change two lines `require.Error + require.Contains` with one `require.ErrorContains`;
- change `require.Error + require.Equal` with `require.EqualError`.
> test: simplify error asserts with require.ErrorContains

- www/docs/customization/archive.md
- www/docs/customization/aur.md
- www/docs/customization/blob.md
- www/docs/customization/builds.md
- www/docs/customization/changelog.md
- www/docs/customization/checksum.md
- www/docs/customization/docker.md
- www/docs/customization/docker_sign.md
- www/docs/customization/git.md
- www/docs/customization/metadata.md
- www/docs/customization/nfpm.md
- www/docs/customization/publishers.md
- www/docs/customization/release.md
- www/docs/customization/snapcraft.md
- www/docs/customization/source.md
- www/docs/customization/universalbinaries.md
- www/docs/customization/winget.md
- www/docs/includes/repository.md
I have sorted the GoReleaser configuration YAML code examples as follows:
```yaml
```
> DOCS: Sort the GoReleaser configuration YAML code examples

- internal/middleware/middleware.go
- internal/pipe/winget/winget.go
> chore: remove repetitive words

- www/docs/blog/posts/2022-03-28-supply-chain-sec.md
The PR replaces `[Carlos A. Becker](undefined)` with `[Carlos A. Becker](https://caarlos0.dev/)` on page https://goreleaser.com/blog/supply-chain-security/#conclusion.
> docs(blog): fix broken link

- internal/client/git.go
- internal/pipe/aur/aur.go
- internal/pipe/aur/aur_test.go
- using the sha256 of the git url as repo name so we avoid race conditions 
- actually made the git client have a global lock so it doesn't step over itself
closes #4679
> fix(aur): allow to have multiple AUR configs pointing to the same repo

- internal/client/git.go
This PR adds retry logic to the process of cloning a git repository.
Currently, it retries only if the output of the git clone command contains the string `Connection reset`.
Probably, there are more cases where retry is reasonable, but I'm not sure what they are.
The number of retries is hardcoded to 10 with increasing delay between retries — in the same way as it is done in #4265, which served me as an example.
The initial use case is described in #4724.
> feat(git): retry git clone on retriable error

- www/docs/customization/builds.md
> fix(docs): update default for `build.id` attribute

- internal/pipe/archive/archive.go
- internal/pipe/archive/archive_test.go
- pkg/config/config.go
- www/docs/customization/archive.md
> feat(archives): format override to 'none' to skip certain goos

- www/docs/static/run
The changes are minimal and the benefit is quite nice – this script can now be used to install GoReleaser on e.g. Alpine Linux without `bash`.
`shellcheck run` and `shfmt run` both report no warnings/errors.
> Convert `run` install script to pure POSIX sh

- www/docs/static/run
I'm sorry, but my previous PR #4736 contained a mistake and the script wasn't truly POSIX compliant.
With this PR I fix that mistake.
See relevant shellcheck warning: https://www.shellcheck.net/wiki/SC3010
> fix `run` not being truly POSIX-compliant

- www/docs/deprecations.md
The Before part  should be "folder"
> docs: fix deprecation typos

- cmd/check.go
This trivial PR fixes a minor cosmetic issue in the `check` command.
Before this fix, GoReleaser would not show the auto-detected config path under check when no args are provided:
```
$ goreleaser check
• checking                                 path=
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
After this check, GoReleaser correctly shows any auto-detected config paths:
```
$ goreleaser check
• checking                                 path=.goreleaser.yaml
• 1 configuration file(s) validated
• thanks for using goreleaser!
```
> fix: use correct path variable for logging in check command

- internal/pipe/webhook/webhook.go
Corrects typo in the value of the `UserAgentHeaderValue` constant.
> fix: typo in User-Agent header value

- www/docs/blog/posts/2022-02-05-cloud-native-storage.md
- www/docs/blog/posts/2022-02-20-azure-devops.md
- www/docs/blog/posts/2023-05-05-goreleaser-v1.18.md
- www/docs/blog/posts/2023-10-08-slsa-generation-for-your-artifacts.md
- www/docs/customization/artifactory.md
- www/docs/errors/docker-build.md
This PR corrects grammar mistakes in documentation:
- artefacts -> artifacts
- Dockefile -> Dockerfile
- compliation -> compilation
- gorleaser -> goreleaser
- repositores -> repositories
- succesfull -> successful
> docs: fix typos

- www/docs/customization/chocolatey.md
Adds missing description for the `package_source_url` option when building Chocolatey packages.
This option is present in the config and nuspec:
- https://github.com/goreleaser/goreleaser/blob/826438b86584ba27c055186bfb544c20646bf667/pkg/config/config.go#L1428
- https://github.com/goreleaser/goreleaser/blob/826438b86584ba27c055186bfb544c20646bf667/internal/pipe/chocolatey/nuspec.go#L25
See also https://docs.chocolatey.org/en-us/guides/create/create-config-package#creating-a-configuration-package and https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0040#reasoning.
> docs: description for chocolateys.package_source_url

- www/docs/errors/dirty.md
Change `--skip-validate` in a doc file to `--skip=validate`.
Running the command with `--skip-validate` produces the following warning:
>   • DEPRECATED: --skip-validate was deprecated in favor of --skip=validate, check https://goreleaser.com/deprecations#-skip for more details
> Update dirty.md deprecated syntax

- internal/pipe/sbom/sbom.go
- internal/pipe/sbom/sbom_test.go
- www/docs/customization/sbom.md
- add the file type in the end of the sbom generated file 
- fix wrong value attribution in the doc example
> Update SBOM generation to add .json as file type

- internal/pipe/telegram/telegram.go
- www/docs/customization/announce/telegram.md
This pull request fix case when ProjectName contains any not escaped symbols
> Add mdv2escape for ProjectName in default telegram message template

- internal/builders/golang/build.go
if the output is not empty, log it with info.
this prevents potentially hiding warnings et al.
on successful builds usually the output is empty anyway.
closes #4782
> feat: always log build output

- cmd/build.go
I just improved the verbiage of the `build -p` switch:
from: `Amount tasks to run concurrently (default: number of CPUs)`
to: `Number of tasks to run concurrently (default: number of CPUs)`
> improve -p help message

- internal/client/config.go
- internal/client/github.go
- internal/client/gitlab.go
- internal/client/gitlab_test.go
**Depends on #4792**
This adds support for opening pull requests on brew, krew, nix, scoop
and winget changes with Gitlab.
> feat(gitlab): Allow PRs to be created

- internal/client/client.go
- internal/client/gitea.go
- internal/client/gitea_test.go
- internal/client/github.go
- internal/client/github_test.go
- internal/client/gitlab.go
- internal/client/gitlab_test.go
- internal/client/mock.go
- internal/client/testdata/github/compare.json
- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
- pkg/config/config.go
- pkg/defaults/defaults.go
- www/docs/customization/changelog.md
This allows to use templates for commit messages in the changelog when using `github`, `gitea`, or `gitlab` as the changelog implementation.
closes #4800
> feat(changelog): custom commit format

- go.mod
- go.sum
- internal/pipe/telegram/telegram.go
- internal/pipe/telegram/telegram_test.go
- www/docs/customization/announce/telegram.md
Hi, there is another fix of default message. I tried this message, now everything works
> Fix telegram default message

- internal/pipe/brew/templates/linux_packages.rb
- internal/pipe/brew/templates/macos_packages.rb
- internal/pipe/brew/testdata/TestFullFormulae.rb.golden
- internal/pipe/brew/testdata/TestFullFormulaeLinuxOnly.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
- internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
- internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
- internal/pipe/brew/testdata/TestRunPipeNameTemplate.rb.golden
- www/docs/customization/homebrew.md
...
Brew linter says that old constructions can't be used in case of submitting to brew-core
...
> feat: migrate to new homebrew constuctions (on_arm, on_intel)

- internal/pipe/blob/blob.go
- internal/pipe/blob/blob_test.go
- www/docs/customization/blob.md
This change would allow users to disable the `Content-Disposition` header that is set for blob storage operations. The application will continue to set a default value for `Content-Disposition` of `attachment; filename={{.Filename}}` if no value was provided by the user. However, with this change, users can now specifically disable this header by setting the value to "-" in the configuration.
We feel this would be a nice solution for this issue: https://github.com/Homebrew/brew/issues/15604
> blob: permit skipping the configuration of the Content-Disposition header

- .golangci.yaml
- internal/pipe/blob/blob_minio_test.go
- internal/pipe/discord/discord.go
This PR fixes possible resource leaks by adding a statement that closes a response body.
From the [documentation](https://pkg.go.dev/net/http):
> The caller must close the response body when finished with it
Also, see this [article](https://golang50shad.es/index.html#close_http_resp_body) for a deep dive into the problem.
> fix: close HTTP resp body to prevent resource leak

- .github/workflows/lint.yml
- .golangci.yaml
- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
- internal/exec/exec.go
- internal/http/http.go
- internal/pipe/archive/archive.go
- internal/pipe/artifactory/artifactory.go
- internal/pipe/blob/blob.go
- internal/pipe/blob/upload.go
- internal/pipe/build/build.go
- internal/pipe/checksums/checksums.go
- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
- internal/pipe/docker/manifest.go
- internal/pipe/ko/ko_test.go
- internal/pipe/nfpm/nfpm.go
- internal/pipe/release/body_test.go
- internal/pipe/release/release.go
- internal/pipe/scoop/scoop_test.go
- internal/pipe/snapcraft/snapcraft.go
- internal/pipe/universalbinary/universalbinary.go
- internal/pipe/upload/upload.go
- internal/pipe/upx/upx.go
- internal/semerrgroup/sem_test.go
- internal/tmpl/tmpl_test.go
- main_test.go
- pkg/archive/archive_test.go
The PR cleans up unnecessary loop variable copying and enables the [`copyloopvar`](https://golangci-lint.run/usage/linters/#copyloopvar) linter for detecting this redundant variable copying.
After the project upgraded to Go version 1.22 in #4779, copying variables inside a `for` loop became unnecessary. See this [blog post](https://go.dev/blog/loopvar-preview) for a detailed explanation.
The `copyloopvar` linter is only available from `golangci-lint` v1.57 onwards, so we also need to update this tool.
> refactor: remove unneeded in Go 1.22 loop var copy

- CONTRIBUTING.md
- internal/builders/buildtarget/targets.go
- internal/builders/golang/build_test.go
- www/docs/contributing.md
- www/docs/cookbooks/using-main.version.md
- www/docs/customization/builds.md
- www/docs/customization/templates.md
The PR updates the links in the docs, replacing the old `golang.org` with the new `go.dev`.
> docs: update old Go website links

- .gitignore
I noticed this while working on https://github.com/goreleaser/goreleaser/pull/4858.
> chore: fix exe typo in .gitignore

- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
this prevents printing `go: downloading` on go builds in case the mods weren't previously downloaded...
> fix(build): do not print 'go: downloading' bits of go build output

- www/docs/ci/actions.md
According to https://github.com/goreleaser/goreleaser-action?tab=readme-ov-file#workflow, there is a typo `varsion` -> `version`
> fix(docs): version typo

- www/docs/blog/posts/2024-06-04-goreleaser-v2.md
Added the missing deprecation notices deep link to v2 section.
> If you keep up with the [deprecation notices][notices], it's likely you don't need to do anything.
_<https://goreleaser.com/blog/goreleaser-v2/#upgrading>_
> docs: added the missing deprecation notices deep link to v2 section

- internal/pipe/nfpm/nfpm.go
- internal/pipe/nfpm/nfpm_test.go
This adds `arm` support for termux (arch needs to be called `arm` as well).
---
Ok this drove me nuts, but I think I've got it working now: https://github.com/carapace-sh/carapace-bin/releases/tag/v1.0.3
1.  First of all most of the `android` targets need `CGO_ENABLED=1`.
2. Then there's the need for a [patched  runtime](https://github.com/carapace-sh/go/tree/master/termux) due to the `/data/data/com.termux/files` prefix (adopted from the [golang package](https://github.com/termux/termux-packages/tree/master/packages/golang)).
3. Two builds so that for termux the patched `gobinary` can be used. Then add a `termux` suffix to the archives for clarity.
```yaml
builds:
- id: default
env:
- CGO_ENABLED=0
goos:
- linux
- windows
- darwin
main: ./cmd/carapace
binary: carapace
tags:
- release
- …
```
> feat(nfpm): support arm in termux

- pkg/archive/archive.go
- pkg/archive/archive_test.go
- www/docs/customization/archive.md
See <https://lists.gnu.org/archive/html/info-gnu/2019-01/msg00001.html>:
> When '-a' option is in effect, zstd compression is selected if the
> destination archive name ends in '.zst' or '.tzst'.
> feat(archive): support `.tzst` suffix

- internal/pipe/chocolatey/chocolatey.go
- www/docs/customization/chocolatey.md
This PR allows `chocolateys.copyright` to be templated, and provides `ctx.ReleaseNotes` as `.Changelog`.
Allowing templates for the copyright will enable, for example:
```yaml
chocolateys:
- ...
copyright: Copyright (c) 1970-{{ .Now.Format "2006" }} Foo Bar
...
```
Without this change:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
<metadata>
...
<copyright>Copyright (c) 1970-{{ .Now.Format &#34;2006&#34; }} Foo Bar</copyright>
...
</metadata>
...
</package>
```
With this change:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
<metadata>
...
<copyright>Copyright (c) 1970-2024 Foo Bar</copyright>
...
</metadata>
...
</package>
```
--- …
> feat(chocolatey): allow template in copyright, provide ctx.ReleaseNotes

- www/docs/customization/notarize.md
Changes the documentation to reflect a Developer ID _Application_ certificate being required to notarize a binary as opposed to a Developer ID _Installer_ certificate.
Without this, a cryptic `x509: unhandled critical extension` error will be thrown from quill.
Related: https://github.com/anchore/quill/issues/431
> docs(notarize): use a Application cert not an Installer cert

- internal/client/gitea.go
- internal/client/gitea_test.go
- internal/client/gitlab.go
- internal/client/gitlab_test.go
- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
Some changelogers were always returning the short sha instead of the full one, so setting an abbrev had no effect.
This fixes these changelogers, which should now always return the full sha.
Note that github usually still shortens the SHAs rendered in markdown, so the changes might not even be visible in most cases.
closes #4829
> fix: actually respect changelog.abbrev

- www/docs/customization/notarize.md
With the current example build fails with:
> notarize: macos: template: failed to apply "{{ isEnvSet \"MACOS_SIGN_P12 }}": unterminated quoted string
> Fixed missing closing quote

- www/docs/ci/gitlab.md
`only` keyword in `.gitlab-ci.yml` is now deprecated.
c.f. https://docs.gitlab.com/ee/ci/yaml/#only--except
So I migrated because GitLab now recommends using `rules:if`
c.f. https://docs.gitlab.com/ee/ci/jobs/job_rules.html#run-jobs-only-in-specific-pipeline-types
> docs: Fix deprecation keyword in `.gitlab-ci.yml`

- .github/workflows/build.yml
- .github/workflows/release.yml
- internal/pipe/snapcraft/snapcraft.go
- internal/semerrgroup/sem.go
- internal/semerrgroup/sem_test.go
this bug comes and goes every couple of versions it seems.
this will change the snapcraft implementation to run the first item without concurrency, so all needed shared directories can be created without issues, and then grows the limit of the wait group so the other ones can run in parallel.
I haven't tested this yet, but I think it'll work.
refs https://github.com/goreleaser/goreleaser/issues/1715 refs https://bugs.launchpad.net/snapcraft/+bug/1889741
> fix: snapcraft temporary directory + concurrency

- Dockerfile
Reverts goreleaser/goreleaser#4970
closes #4992
>  chore(deps): bump golang to 1.22.5-alpine

- internal/client/gitlab.go
Fix the GitLab upload URL.
Gitlab changed upload URLs from 
`https://gitlab.com/{user}/{repo}/uploads/{hash}/file.ext` to `https://gitlab.com/-/project/{projectID}/uploads/{hash}/file.ext`.
To avoid future issues like this the PR https://github.com/xanzy/go-gitlab/pull/1968 was created upstream which adds the `full_path` field to `go-gitlab` which this PR uses. 
Fixes https://github.com/goreleaser/goreleaser/issues/4974
> fix(gitlab): release file URL broken

- www/docs/ci/actions.md
Simple PR to edit the docs for GitHub actions to use GoReleaser `"~> v2"`, as v2 is now the default for `goreleaser init` and the GoReleaser GitHub action.
> docs: use "~> v2" in GitHub actions docs

- .goreleaser.yaml
If applied, this commit will fix the self-check failure reported in https://github.com/goreleaser/goreleaser/issues/5086#issue-2471620837.
tl;dr goreleaser v2.2 switched from `snapshot.name_template` to `snapshot.version_template`. This PR updates goreleaser's own config to use the new variable.
> chore: use snapshot.version_template in own config

- .goreleaser.yaml
before:
```sh
$ tar tvzf dist/goreleaser_Linux_x86_64.tar.gz                                  
-rw-rw-r-- twp/twp        1085 2024-08-17 09:19 LICENSE.md
-rw-rw-r-- twp/twp       12982 2024-08-17 09:19 README.md
-rw-rw-r-- twp/twp       11975 2024-08-17 18:10 completions/goreleaser.bash
-rw-rw-r-- twp/twp       10061 2024-08-17 18:10 completions/goreleaser.fish
-rw-rw-r-- twp/twp        7892 2024-08-17 18:10 completions/goreleaser.zsh
-rw-rw-r-- twp/twp        1594 2024-08-17 18:10 manpages/goreleaser.1.gz
-rwxrwxr-x root/root  66003096 2024-08-16 19:49 goreleaser
```
after this change:
```sh
$ tar tvf dist/goreleaser_Linux_arm64.tar.gz
-rw-r--r-- root/root      1085 2024-08-18 15:36 LICENSE.md
-rw-r--r-- root/root     12982 2024-08-18 15:36 README.md
-rw-r--r-- root/root     11975 …
```
> build: constant archive files owner, group, and mtime

- internal/pipe/blob/blob_minio_test.go
This happened locally, doesn't seem to happen in the CI though.
Probably related to the Docker version.
> build: fix port error with dockertest on blob_minio_test.go

- Dockerfile
goreleaser currently uses `cosign` `v2.1.1`, this change switches it to `v2.4.0`.
While there may be other useful updates, I'd like this update to workaround a bug which I'm experiencing: https://github.com/sigstore/cosign/issues/3614#issuecomment-2012521670, and which is solved by upgrading the `cosign` version.
> chore(deps): upgrade cosign to 2.4.0

- internal/client/github.go
When trying to release an artifact to github and it fails, I observed the following stacktrace:
```
• publishing
• scm releases
• releasing                                    tag=v1.11.0 repo=my-github-repo
• could not check rate limits, hoping for the best...
• could not check rate limits, hoping for the best...
• took: 1m40s
• took: 1m40s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe28b72]
goroutine 55 [running]:
github.com/goreleaser/goreleaser/v2/internal/client.(*githubClient).createOrUpdateRelease(0xc0001b24c8, 0xc0002c5108, 0xc000b478, {0xc00039ed00, 0x80e})
github.com/goreleaser/goreleaser/v2@v2.2.0/internal/client/github.go:454 +0x3b2 …
```
> fix: Handle error on failed release (github)

- internal/builders/golang/build_test.go
- internal/client/gitea_test.go
- internal/client/github_test.go
- internal/client/gitlab_test.go
- internal/pipe/blob/blob_test.go
- internal/pipe/mattermost/mattermost_test.go
- internal/pipe/webhook/webhook_test.go
If applied, this commit will fix the current linter errors, which are currently causing all Github Actions to fail.
See, for example, the latest `main` run: https://github.com/goreleaser/goreleaser/actions/runs/10607661596/job/29400451251.
> chore: fix linter errors

- cmd/build.go
- internal/pipe/build/filter.go
- internal/pipe/build/filter_test.go
- internal/pipe/partial/partial.go
- internal/pipe/partial/partial_test.go
make them more precise, as its currently only taking GOOS/GOARCH into account, and we can do more.
closes #5112
> fix: build --single-target filters

- internal/pipe/ko/ko.go
- internal/pipe/ko/ko_test.go
- internal/pipeline/pipeline.go
- www/docs/customization/ko.md
this makes ko run on snapshot builds, too.
the image will be `goreleaser.ko.local:[your tags]`, not sure if we can change this, seems like we can't.
also fixed a small doc error around it, as well as added a new test to cover this.
closes #4683
> feat(ko): snapshot builds

- internal/builders/golang/build.go
- internal/pipe/build/build.go
- internal/pipe/build/build_test.go
This commit fixes the automatic extension when building the wasip1_wasm target.
Additionally, in future Go versions, support will be added for generating c-shared WASM binaries. https://github.com/golang/go/issues/65199
Therefore, this PR corrects the extension in the build process and removes the .h file from the release when c-shared is enabled and the target is WASM.
> fix(build,release): c-shared build and release when target is wasm

- www/docs/ci/actions.md
Just adding documentation for using cosign with GitHub's OIDC in CI.
I spent 4 hours looking through goreleaser and GitHub's docs before I finally discovered I was missing the `id-token: write` permission in my workflow file.
This PR serves to just include the `id-token: write` scope in the `CI -> (GH) actions` section of the docs to hopefully save other devs the trouble 🤣
I also considered adding this to docs for the other CI providers, but I am not too familiar on the OIDC side of things; might be worth considering for the team?
Cheers
---
Been using goreleaser for one of my [oss projects](https://github.com/caffeine-addictt/waku) recently and it's been great! Just wanted to contribute something back, keep up the great work! :>
> docs: Add GH Actions OIDC permission docs

- internal/pipe/sign/sign.go
- internal/pipe/sign/sign_binary_test.go
The presence of an artifact field in the `signature` or `certificate` template field caused a silent failure in the template when re-applied after the external signing process was called.
This was due to the artifact being presence in the template context before the signing process, but not after. An error here was also ignored.
The fix supplies the artifact to the template context, and also allows a template failure to
fail the overall process.
As far as I can tell, this change aligns behaviour to match existing documentation.
Fixes #5147
> fix: signature template failed silently after signing process completed

- internal/pipe/chocolatey/template.go
When submitting a new project to chocolatey using goreleaser, a reviewer told me that a line in the template is incorrect:
> since that is not a valid parameter to the Install-ChocolateyZipPackage function: https://docs.chocolatey.org/en-us/create/functions/install-chocolateyzippackage/
This PR aims to correct that by removing the line from the template as requested
> fix: remove filetype exe from chocolatey template

- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
This commit removes the unnecessary slice copy in `sortEntries`, and replaces `sort.Slice` [^1] with the new `slices.SortFunc` [^2].
As recommended by the Go documentation, `slices.SortFunc` is generally faster because it uses generic, whereas `sort.Slice` relies on reflection, which incurs additional allocations
The benchmark result from the newly added `Benchmark_sortEntries` show approximately a 64% performance improvement.
Benchmark result:
```
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
_sortEntries/asc-16    16.458µ ± 1%   5.958µ ± 1%  -63.80% (p=0.000 n=10)
_sortEntries/desc-16   17.675µ ± 1%   6.020µ ± 0%  -65.94% (p=0.000 n=10)
geomean                 17.06µ        5.989µ       -64.89%
│   old.txt    │ …
```
> perf(changelog): improve changelog sort performance

- internal/client/github_test.go
- internal/client/gitlab_test.go
- internal/testlib/archive.go
This PR adds missing `file.Close()` calls in tests. All files that are opened using `os.Open` should be closed after finishing reading.
> test: add missing file.Close() calls

- Dockerfile
This changes the Dockerfile to pull the cosign container image from GHCR instead of Google Cloud. This helps the Sigstore team manage their cloud spend (as GHCR is provided for free and Google Cloud Artifact Registry is not).
Note the container hash does not change and images are posted to both locations upon cosign's release process.
> point to GHCR instead of GCR for cosign container

- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
This is a bug that occurs randomly under a very specific condition.
Not sure how long this bug has been around. I first noticed it in the failed Dagger test job in https://github.com/goreleaser/goreleaser/pull/5161 after the `TestGroup` unit test was updated to use regex matching https://github.com/goreleaser/goreleaser/pull/5161#discussion_r1781302054.
Log: https://github.com/goreleaser/goreleaser/actions/runs/11108665571/job/30862144417#step:4:680
```
--- FAIL: TestGroup (0.23s)
changelog_test.go:843: 
Error Trace:	/src/internal/pipe/changelog/changelog_test.go:843
Error:      	Expect "## Changelog
* a77c0b89a457ee6a78447f6c9113b79cf4dce8ce feat: added that thing
* 3e2908a87e5fdfdbd5efaad013c0b2d196c64c40 bug: Merge pull request #999 from goreleaser/some-branch
* …
```
> fix(changelog): fix random order of first commit in first release

- internal/tmpl/tmpl.go
- internal/tmpl/tmpl_test.go
this is just to prevent some gotchas when using `templ` internally.
> fix: tmpl always copy before modifying

- internal/testctx/testctx.go
The PR corrects a typo in the parameter of the `testctxt.WithCommit` function.
> fix: typo in testctx.WithConfig parameter

- internal/pipe/sourcearchive/source.go
- pkg/archive/archive.go
- pkg/archive/archive_test.go
- pkg/archive/tar/tar.go
- pkg/archive/tar/tar_test.go
- pkg/archive/targz/targz.go
- pkg/archive/zip/zip.go
This PR renames `Copying` functions in the `archive` package to `Copy` because it is a more common method name.
> refactor: rename archive.Copying to archive.Copy

- internal/builders/golang/build.go
- pkg/config/config.go
Since Go386 now has a default value, existing configurations no longer match 386 builds (d583861e0606f2bb9e97c0d0e28f9b82df6a187a).
Since we used to need to write goamd64=1 to match _amd64 builds, I added new opts to fix that. (If you think you need to set some default for override, that would be even better)
> fix: build override

- www/docs/errors/resource-not-accessible-by-integration.md
This pull request updates the documentation to reflect changes in the `goreleaser-action` version and modifies the `.goreleaser.yaml` configuration for better clarity.
Documentation updates:
* [`www/docs/errors/resource-not-accessible-by-integration.md`](diffhunk://#diff-165fd8d8fb477ae98173556cce7fbd52eb9c5fca03b713c7c8d59bc96e46fe50L32-R32): Updated the `goreleaser-action` version from `v4` to `v6` in the workflow file examples. [[1]](diffhunk://#diff-165fd8d8fb477ae98173556cce7fbd52eb9c5fca03b713c7c8d59bc96e46fe50L32-R32) [[2]](diffhunk://#diff-165fd8d8fb477ae98173556cce7fbd52eb9c5fca03b713c7c8d59bc96e46fe50L49-R49)
Configuration changes:
* [`www/docs/errors/resource-not-accessible-by-integration.md`](diffhunk://#diff-165fd8d8fb477ae98173556cce7fbd52eb9c5fca03b713c7c8d59bc96e46fe50L63-R …
> Update deprecated config documentation

- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
the `/compare` api doesn't allow to omit the previous reference, nor to use a git commit, so, if `previous tag` is empty, we're now defaulting to the git changelog implementation, which should resolve the problem.
closes #5240
> fix(changelog): first release default to git changelogger 

- internal/builders/golang/build_test.go
- internal/client/gitlab_test.go
- internal/pipe/blob/upload.go
- internal/pipe/sign/sign_test.go
- internal/pipeline/pipeline.go
- pkg/config/config.go
The PR correct grammar mistakes in Go comments and tests.
> docs: fix typos in comments

- pkg/config/config.go
- www/docs/static/schema-pro.json
- www/docs/static/schema.json
The PR corrects grammar mistake in the property name for `OpenCollective` in the JSON schema.
> fix: typo in JSON property for OpenCollective announce

- internal/pipe/slack/slack_test.go
- pkg/config/config_slack_test.go
The PR refactors tests by removing redundant `require.Error` statements that are followed by `require.ErrorContains`. `require.ErrorContains` will fail if `err` is `nil`, so `require.Error` is not needed.
> test: remove redundant require.Error

- internal/exec/exec_mock_test.go
- internal/pipe/before/before_test.go
- internal/pipe/blob/blob_minio_test.go
- internal/pipe/env/env_test.go
- internal/pipe/sign/sign_test.go
This PR simplifies tests by removing redundant `os.Exit` calls in `TestMain` functions. 
As of Go 1.15, we do not need to call `os.Exit(m.Run())` explicitly, as value returned by `m.Run()` is stored into unexported field of `m` and go test executable is smart enough to automatically call `os.Exit(retValue)` when `TestMain` returns. See golang/go#34129.
> test: remove redundant os.Exit in TestMain

- pkg/config/config.go
- www/docs/static/schema-pro.json
- www/docs/static/schema.json
Currently, the JSONSchema defines the type of `umask` as an `integer` because the type is inherited from `fs.FileMode` (`uint32`).
https://github.com/goreleaser/goreleaser/blob/a7721dc1fed1168b71a06384d6a8136f9bae31ff/www/docs/static/schema.json#L1830-L1832
https://github.com/goreleaser/goreleaser/blob/a7721dc1fed1168b71a06384d6a8136f9bae31ff/pkg/config/config.go#L948
The documentation says octal values (`0o002`) can be used.
https://github.com/goreleaser/goreleaser/blob/a7721dc1fed1168b71a06384d6a8136f9bae31ff/www/docs/customization/nfpm.md?plain=1#L79-L80
But as this value contains a letter (`o`), so this field becomes a `string` and the JSON validation fails.
This PR adds a struct tag on the field `Umask` to allow `integer` and `string`.
I generated the JSONSchema by using the …
> fix(jsonschema): add custom JSONSchema type to umask

- .golangci.yaml
- internal/pipe/linkedin/client.go
- internal/pipe/linkedin/client_test.go
- internal/pipe/linkedin/linkedin.go
- internal/pipe/webhook/webhook.go
This PR adds using `context.Context` in HTTP requests. Changes are similar to #5232.
Additionally, it enables `noctx` to automatically detect missing context:
```
internal/pipe/webhook/webhook.go:85:29: should rewrite http.NewRequestWithContext or add (*Request).WithContext (noctx)
internal/pipe/linkedin/client.go:68:27: (*net/http.Client).Get must not be called (noctx)
internal/pipe/linkedin/client.go:101:27: (*net/http.Client).Get must not be called (noctx)
internal/pipe/linkedin/client.go:172:28: (*net/http.Client).Post must not be called (noctx)
```
> feat: pass context.Context to HTTP requests

- .github/workflows/lint.yml
- cmd/root.go
- internal/archivefiles/archivefiles.go
- internal/git/config_test.go
This PR updates the version of golangci-lint to the latest [v1.62](https://github.com/golangci/golangci-lint/releases/tag/v1.62.0) and fixes appeared lint issues:
```
❯ golangci-lint run
internal/archivefiles/archivefiles.go:144:2: redefines-builtin-id: redefinition of the built-in function min (revive)
var min int
^
internal/archivefiles/archivefiles.go:146:3: redefines-builtin-id: redefinition of the built-in function min (revive)
min = len(b)
^
internal/archivefiles/archivefiles.go:148:3: redefines-builtin-id: redefinition of the built-in function min (revive)
min = len(a)
^
cmd/root.go:152:29: redefines-builtin-id: redefinition of the built-in type rune (revive)
func timedRunE(verb string, rune func(cmd *cobra.Command, args []string) error) func(cmd *cobra.Command, args []string) …
```
> build: update golangci-lint to v1.62

- internal/pipe/aur/aur.go
Follows https://github.com/goreleaser/goreleaser/pull/4695, remove dead code about armv6.
> chore(aur): remove dead code about armv6

- .golangci.yaml
- cmd/build.go
- cmd/check.go
- cmd/healthcheck.go
- internal/client/client.go
- internal/client/git.go
- internal/client/gitlab.go
- internal/git/config.go
- internal/pipe/archive/archive.go
- internal/pipe/blob/blob.go
- internal/pipe/blob/upload.go
- internal/pipe/brew/brew.go
- internal/pipe/docker/docker.go
- internal/pipe/krew/krew.go
- internal/pipe/linkedin/client.go
- internal/pipe/nix/nix.go
- internal/pipe/project/project.go
- internal/pipe/sbom/sbom.go
- internal/pipe/scoop/scoop.go
- internal/pipe/smtp/smtp.go
- internal/pipe/snapcraft/snapcraft.go
- internal/pipe/snapshot/snapshot.go
- internal/pipe/winget/winget.go
The PR replaces usages of `fmt.Errorf` with `errors.New` for creating errors. Enables `perfsprint` linter to prevent future regressions.
> refactor: replace fmt.Errorf with errors.New for consistency

- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
this will use the default value for GOMIPS, GOARM, GO386, and etc in build overrides if they are not specified.
> fix(build): overrides without specifying goarm64 et al

- .goreleaser.yaml
this will affect goreleaser packages themselves.
go was already optional, as people might install it from source, and so are now zig and rust.
> feat: add rustup and zig to packages optional dependencies

- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
- internal/builders/rust/build.go
- internal/builders/rust/build_test.go
- internal/builders/zig/build.go
- internal/builders/zig/build_test.go
- pkg/build/build.go
- pkg/build/build_test.go
- pkg/healthcheck/healthcheck.go
- pkg/healthcheck/healthcheck_test.go
this handles `goreleaser healthcheck` taking into account the builders being used.
> feat: handle healthcheck for builders

- internal/builders/rust/build.go
- internal/builders/rust/build_test.go
- internal/builders/zig/build.go
- internal/builders/zig/build_test.go
- internal/static/config.rust.yaml
- internal/static/config.zig.yaml
- remove `--release` from the default build cmd in rust, add it as a default flag (thus it can be overridden)
- also added `--release` to the generated config for rust
- did the same with `-Doptimize=ReleaseSafe` for zig
> feat: --release and -Doptimize=ReleaseSafe for rust and zig

- internal/builders/buildtarget/targets_test.go
- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
- internal/builders/rust/build.go
- internal/builders/rust/build_test.go
- internal/builders/zig/build.go
- internal/builders/zig/build_test.go
- internal/pipe/build/build.go
- pkg/config/config.go
- www/docs/customization/builds.md
- www/docs/customization/rust-builds.md
- www/docs/customization/zig-builds.md
- www/docs/deprecations.md
This should better accommodate other languages, as it makes no sense to set `gobinary` for rust or zig.
refs #5327
> feat: rename builds.*.gobinary to builds.*.tool

- internal/client/github.go
- internal/client/github_test.go
- internal/client/testdata/github/releases.json
- pkg/config/config.go
- www/docs/customization/release.md
The PR allows setting a `release.use_existing_draft` config option to use an existing draft release instead of creating a new release.
Our release process creates a draft PR before calling GoReleaser. While we can delete an old draft and create a new one, it would be nice to keep the existing draft PR and use that instead of creating a new one.
> feat(release): allow using existing draft release

- internal/archivefiles/archivefiles.go
- internal/exec/exec_mock.go
- internal/pipe/aur/aur.go
- internal/pipe/aursources/aursources.go
- internal/pipe/brew/brew.go
- internal/pipe/checksums/checksums.go
- internal/pipe/docker/docker.go
- internal/pipe/docker/manifest.go
- internal/pipe/krew/krew.go
- internal/pipe/sbom/sbom_test.go
- internal/pipe/sign/sign_test.go
- internal/skips/skips.go
The PR replaces using `sort` with `slices` package. It's because the latter is slightly faster and easier to use.
`sort.Strings(wantFiles)` is removed because `require.ElementsMatch(tb, wantFiles, gotFiles)` compares slices, ignoring the order of the elements.
See https://go-review.googlesource.com/c/go/+/626038
> refactor: change from sort functions to slices functions

- pkg/config/config.go
The PR corrects the tag name for the `Webhook.ExpectedStatusCodes` in the `config` package.
> fix: typo in the YAML tag for Webhook.ExpectedStatusCodes

- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
- internal/pipe/docker/manifest.go
- internal/pipe/docker/manifest_test.go
The PR simplifies `validateManifester` and `validateImager` functions. Also, adds tests to prove that refactoring doesn't break anything.
> refactor: simplify validateImager, validateManifester

- cmd/init.go
- cmd/init_test.go
- cmd/root.go
- internal/builders/rust/build.go
- internal/builders/zig/build.go
- adds common rust/cargo-zigbuild/zig folders/files to .gitignore on init
- improves log output a little bit
- avoid repeating "you are using the experimental Foo builder"
> fix(rust,zig): improve init, experimental warn

- internal/builders/golang/build.go
- internal/pipe/build/build.go
- internal/pipe/build/filter.go
- internal/pipe/build/filter_test.go
- internal/pipe/partial/partial.go
- internal/pipe/partial/partial_test.go
- pkg/build/build.go
- removed duplicate handling of default _extra bit of Go targets
- allow to set `TARGET` (esp for other builders)
> fix: improve goreleaser build --single-target

- www/docs/customization/builds.md
Update documentation links.
This doc: https://go.dev/doc/install/source#environment
is about compiling go from source.
This doc https://pkg.go.dev/cmd/go#hdr-Environment_variables
is about go tool (including `go build`).
I feel like the latter is more likely to stay up to date. 
E.g. goamd64 is not documented in the former, and is documented in the latter.
Also, add extra links for relevant build flags documentation.
> Update documentation links

- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
rust also doesn't set goamd64 and guarm in the artifacts, it should.
> fix(rust): artifact filter when builder is rust

- internal/pipe/release/scm_test.go
If the repo is not set then the repo owner is set to the user's name. The tests assume that this username is `goreleaser`, which is not true for most users. This PR removes the assumption that the username is `goreleaser`.
If applied, this commit will help goreleaser's tests pass on other people's machines.
This change being made so I can run goreleaser's tests successfully on my machine, so I can be confident that any failing tests in future PRs that I propose are due to any changes that I made in the PR.
Refs https://github.com/goreleaser/goreleaser/pull/3412.
> fix: don't assume username in tests

- .github/workflows/build.yml
- .goreleaser.yaml
- cmd/init.go
- flake.nix
- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
- internal/builders/deno/build.go
- internal/builders/deno/build_test.go
- internal/builders/deno/targets.go
- internal/builders/deno/targets.txt
- internal/pipe/build/build.go
- internal/static/config.deno.yaml
- internal/static/config.go
- internal/static/config_test.go
- pkg/config/config.go
- pkg/healthcheck/healthcheck_test.go
- www/docs/cookbooks/builds-complex-envs.md
- www/docs/customization/builds/bun.md
- www/docs/customization/builds/deno.md
- www/docs/customization/builds/go.md
- www/docs/customization/builds/index.md
- www/docs/customization/builds/poetry.md
- www/docs/customization/builds/python.md
- www/docs/customization/builds/rust.md
- www/docs/customization/builds/uv.md
- www/docs/customization/builds/zig.md
- www/mkdocs.yml
TODO: docs, more test
we should also document/test [bun publish](https://bun.sh/docs/cli/publish) and [deno publish](https://docs.deno.com/runtime/reference/cli/publish/) as custom release scripts (like we did with cargo)
now that we have more builders, maybe also worth improving the artifact filtering thing so we don't have to add all langs there
would also be good to have a "skeleton" implementation somewhere to make it faster and less error-prone 
finally, a guide of all the other unrelated changes would be good (tests, init, CI, imports, etc)
> feat(build): adds deno support

- pkg/build/build.go
- pkg/build/fail.go
- pkg/build/fail_test.go
this improves error handling when `builds.builder` is invalid.
currently it simply throws a nil pointer deference error.
it also fixes locking the map when reading it as well
> fix: do not return nil if builder is invalid

- .goreleaser.yaml
I think this is probably better so it doesn't install too many things if users forget `--no-install-recommends` or whatever
wdyt?
> ci(nfpm): suggest builders instead of recommends

- cmd/init_test.go
- internal/builders/golang/build_test.go
- internal/client/gitlab.go
- internal/client/gitlab_test.go
- internal/pipe/checksums/checksums_test.go
- internal/pipe/env/env_test.go
- internal/pipe/gomod/gomod_proxy.go
- internal/pipe/gomod/gomod_proxy_test.go
this should help speed up the build times of goreleaser, as well as making them less-reliable on external dependencies.
tests now use https://github.com/goreleaser/test-mod instead of goreleaser codebase itself, which should also be faster to build/clone/etc.
refs #5409 as well
> test: improve speed, work on clean system

- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
- internal/pipe/nix/nix.go
- internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_publish.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip_build.nix.golden
- internal/pipe/nix/testdata/TestRunPipe/zip_publish.nix.golden
- internal/shell/shell_test.go
this is an alternative implementation of #5440.
I think this is better, actually. We don't really need to care about the builder, if goamd64 is not set in the artifact, we can safely assume it's not a go build.
this is also simpler and less error-prone.
closes #5440 
closes #5439
> fix: target filter byamd64 and byarm

- cmd/build.go
- internal/pipe/partial/partial.go
- internal/pipe/partial/partial_test.go
This works with Go already, but not with other languages. This PR adds a best-effort thingy to try to figure it out, based on common target patterns and names.
This should allow users to run `goreleaser build --single-target` with any language supported by goreleaser on most machines!
> fix: build --single-target infer target from runtime

- internal/builders/buildtarget/targets.go
- internal/builders/buildtarget/targets_test.go
closes #5444
it seems that it'll be in go 1.24... I think its fine to merge it earlier?
> feat(build): support solaris/sparc and solaris/sparc64 in golang builder

- go.mod
- go.sum
- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
- internal/pipe/docker/manifest.go
If you have a typo in the `docker_manifests` setup, the error ends up not being too helpful.
This improves it a little by using levenshtein distances to figure out if it might have been a typo, and suggesting it.
It should not affect the behavior of how things work, besides the warning change.
Had the idea while helping @rs, so thanks for that 🙏🏻
> feat(docker): suggest image if not found

- internal/pipe/blob/blob_minio_test.go
- internal/pipe/docker/docker_test.go
- internal/pipe/ko/ko_test.go
- internal/shell/shell_test.go
- internal/testlib/docker.go
specially when running locally.
- better checking for docker: check its running, not merely in path
- for some reason `touch` from a `sh` from `go` doesn't not exist even though it totally do exist on my machine? anyway fixing it to `/usr/bin/touch` seems to fix it? May need to look into that in other OSes as well...
> test: improve stability of some tests

- .github/workflows/build.yml
- internal/builders/rust/build_test.go
- internal/testlib/path.go
Windows is failing some times, probably the version of something... to avoid it, gonna try to build only for the current runtime platform.
> test: avoid cross-compile in test

- internal/builders/bun/build.go
- internal/builders/common/common.go
- internal/builders/common/common_test.go
- internal/builders/deno/build.go
- internal/builders/golang/build.go
- internal/builders/golang/build_test.go
- internal/builders/rust/build.go
- internal/builders/zig/build.go
- internal/testlib/artifacts.go
it was being ignored since a refactor in #5403
closes #5491
> fix(go): build env overrides

- .golangci.yaml
- internal/client/client_test.go
- internal/pipe/sign/sign_test.go
This PR refactors tests to use [`math/rand/v2`](https://go.dev/blog/randv2) instead of `math/rand`.
> refactor: use math/rand/v2

- cmd/build.go
Passing the empty string as an extension is a functional no-op, but causes actual problems: https://github.com/spf13/cobra/pull/2228
Remove marking the flag as taking filename altogether, as there's no need to do that; cobra comments doing so as a mistake: https://github.com/spf13/cobra/blob/41b26ec8bb59dfba580f722201bf371c4f5703dd/completions.go#L387-L390
Leave MarkFlagFilename in comments so it's clear it's not inadvertently left out.
> fix(build): --output completion usage

- cmd/init_test.go
- internal/static/config.bun.yaml
- internal/static/config.deno.yaml
- internal/static/config.rust.yaml
- internal/static/config.yaml
- internal/static/config.zig.yaml
I noticed the default example config files were specifying `format` instead of `formats` so I fixed that and added a test to ensure this issue never happens again.
The test checks the default configuration files for deprecated fields.
> fix(init): prevent init from creating config files with deprecated fields

- www/docs/customization/binary_sign.md
Add missing link in the `binary_sign.md` file.
> docs: add link to cosign site

- www/docs/customization/ko.md
The key `kos.repository` has been deprecated in 2.5.
<https://goreleaser.com/deprecations/#kosrepository>
Replaced by `kos.repositories`, which is a list of strings instead of a string.
But it is still mentioned in this document as a valid example. 
<https://goreleaser.com/customization/ko/>
> docs: Replace deprecated key kos.repository

- internal/pipe/docker/manifest.go
Fixes a small typo in a warning message
> Fix typo in manifest.go

- www/docs/customization/templates.md
Set the correct redirect link name for the `contains` description for the Functions description in the `Name Templates` article.
The description for the `contains` func should point to the `Contains` func documentation, not `ToLower`.
Article link:
- https://goreleaser.com/customization/templates/#functions
> docs: correct redirect link for the `Name Templates` article

- .golangci.yaml
- internal/packagejson/packagejson.go
The PR fixes package comment for `packagejson` and enables `revive.package-comments` to detect this issue in the future.
> fix: package comment for packagejson

- internal/client/client.go
- internal/pipe/changelog/changelog.go
- internal/pipe/changelog/changelog_test.go
- internal/pipe/changelog/testdata/TestIssue5595/abbrev-sha.md.golden
- internal/pipe/changelog/testdata/TestIssue5595/no-sha.md.golden
- pkg/config/config.go
- www/docs/customization/changelog.md
The git changeloger now uses a custom format that yields a JSON, which we later parse.
With this, I refactored most of how the changelog works, and now abbrev, filtering, sorting, and grouping, are all done with structured data instead of plain strings.
This allows to:
- properly handle commit abbrevs when using custom formats
- customize format when using 'use: git`, including adding author name and email 
- properly handle filters when the format doesn't have a leading SHA 
closes #5595
> feat(changelog): allow to use format when using the git changeloger

- internal/pipe/archive/archive.go
- internal/pipe/archive/archive_test.go
On windows, files have no executable bits.
We read the file permissions on disk to decide its permissions inside the archives - this means that, on windows, the binaries will not have the executable bit when unextracted.
This sets the build file info mode to 0o755 by default, which should resolve this issue.
This was also fixed at some point in time in the past, but apparently regressed. Now that we test on windows as well, this shouldn't happen again.
closes #5632
> fix(archive): make sure binaries are executable

- internal/pipe/sign/sign.go
defers to only try to get gpg program from git config when/if needed
> perf: improve default gpg path detection

- .golangci.yaml
- cmd/init_test.go
- cmd/util_test.go
- internal/git/config_test.go
- internal/git/git_test.go
- internal/http/http_test.go
- internal/pipe/build/build_test.go
- internal/pipe/linkedin/client_test.go
- internal/testlib/git.go
- internal/testlib/mktemp.go
This PR enables [`usetesting`](https://golangci-lint.run/usage/linters/#usetesting) linter and fixes up lint issues.
> test: simplify tests with usetesting linter

- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
- internal/pipe/archive/archive.go
- internal/pipe/archive/archive_test.go
- internal/pipe/aur/aur.go
- internal/pipe/aursources/aursources.go
- internal/pipe/brew/brew.go
- internal/pipe/brew/brew_test.go
- internal/pipe/checksums/checksums_test.go
- internal/pipe/chocolatey/chocolatey.go
- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
- internal/pipe/krew/krew.go
- internal/pipe/nfpm/nfpm_test.go
- internal/pipe/nix/nix.go
- internal/pipe/reportsizes/reportsizes_test.go
- internal/pipe/scoop/scoop.go
- internal/pipe/scoop/scoop_test.go
- internal/pipe/scoop/testdata/TestRunPipePullRequest.json.golden
- internal/pipe/scoop/testdata/Test_doRun/git_remote.json.golden
- internal/pipe/scoop/testdata/Test_doRun/valid_public_github.json.golden
- internal/pipe/snapcraft/snapcraft.go
- internal/pipe/universalbinary/universalbinary_test.go
- internal/pipe/winget/winget.go
- internal/tmpl/tmpl.go
- a lot of places `ExtraOr` is being used we actually expect the key to be there
- similarly, the previous `Extra` behavior was kind of the same of `ExtraOr` in some situations
This PR:
- improves `ExtraOr` by only returning `or` if the key doesn't exist, and panics if it cannot be cast into the expected type - which is the intended usage
- removes the `Extra` function
- adds a `MustExtra` function which panics if the key doesn't exist, or if it cannot be cast to the expected type
> refactor: ExtraOr, MustExtra

- internal/pipe/upx/testdata/fakeupx
- internal/pipe/upx/testdata/fakeupx.bat
- internal/pipe/upx/upx.go
- internal/pipe/upx/upx_test.go
- www/docs/static/schema-pro.json
closes #5719
- the actual skips were not being run inside the skip-aware context
- improved tests so we actually check it ran for all the binaries we want
- make tests faster by avoiding running `upx` for real and `go build`
> fix: upx properly handle skips

- cmd/build.go
- cmd/release.go
I think 30m is not enough for most big-enough projects these days, especially considering Rust builds are slower.
IMHO it's fine to increase to 1hr.
> fix: increase default timeout

- www/docs/customization/sbom.md
https://github.com/ossf/sbom-everywhere/blob/main/reference/sbom_naming.md#consistent-naming-conventions
> docs: use recommended SPDX SBOM filename in example

- cmd/init.go
- cmd/init_test.go
This PR fixes two issues with the `goreleaser init` command when modifying `.gitignore` files:
1. When a `.gitignore` file contains CRLF line endings, the command would incorrectly add duplicate `dist/` entries
2. When a `.gitignore` file doesn't end with a newline, the new entries would be appended on the same line, causing incorrect formatting
> fix(init): handle CRLF line endings in gitignore

- .github/workflows/codeql.yml
- internal/pipe/ko/ko.go
- internal/pipe/ko/ko_test.go
- pkg/config/config.go
- www/docs/customization/ko.md
- www/docs/static/schema-pro.json
- www/docs/static/schema.json
If applied, this commit will make the localDomain for `ko` builds configurable and add tests for the new configuration option.
This change allows users to specify a custom localDomain for ko builds, increasing flexibility for local image publishing scenarios.
https://ko.build/configuration/#local-publishing-options
closes https://github.com/orgs/goreleaser/discussions/5808
> feat(ko): allow configuration of local domain to allow publishing to other local registries (e.g. kind)

- internal/pipe/docker/manifest.go
- internal/pipe/docker/manifest_test.go
Skips empty strings of the given `image_templates` from the `docker_manifests` section after evaluation.
This allows usage of conditionals for some of the filtered `dockers` builds (e.g. by `ids`), such as:
```yaml
builds:
- id: amd_build
goos:
- linux
goarch:
- amd64
- id: arm_build
goos:
- linux
goarch:
- arm64
skip: >-
{{ if skip }}{{ true }}{{ else }}false{{ end }}
dockers:
- image_templates:
- repo/image:tag-amd64
ids:
- amd_build
use: buildx
build_flag_templates:
- --platform=linux/amd64
- image_templates:
- repo/image:tag-arm64
ids:
- arm_build
goarch: arm64
use: buildx
build_flag_templates:
- --platform=linux/arm64/v8
docker_manifests:
- name_template: "repo/image:tag"
image_templates:
- "repo/image:tag-amd64"
- >- 
{{ if skip }}{{""}}{{ else }}repo/image:tag-arm64{{ end }}
``` …
> fix: skip empty image_templates in docker_manifests

- .golangci.yaml
- internal/artifact/artifact.go
- internal/artifact/artifact_test.go
`revive.modifies-value-receiver` reports that `artifact.Checksum` doesn't set the `artifact.Extra` field due to the use of a value receiver in:
```go
func (a Artifact) Checksum(algorithm string) (string, error)
```
Golangci-lint output:
```console
$ golangci-lint run
internal/artifact/artifact.go:359:3: modifies-value-receiver: suspicious assignment to a by-value method receiver (revive)
a.Extra = make(Extras)
^
1 issues:
* revive: 1
```
I believe this is a bug. If it’s not, we can remove the following lines (added in #4707), since they have no effect on the original `Artifact`:
```go
if a.Extra == nil {
a.Extra = make(Extras)
}
a.Extra[ExtraChecksum] = fmt.Sprintf("%s:%s", algorithm, check)
```
> fix: artifact.Checksum should set artifact.Extra field

- internal/builders/rust/build.go
- internal/builders/rust/build_test.go
- internal/builders/rust/targets.go
The `GroupByPlatform()` method used in archives already considers the `Abi` extra field.
For some reason, in the Rust builder, it was being called environment instead.
Changed it to `Abi` so it works the same as Zig et al.
Also updated the tests.
With this patch, the reproducible works as expected:
```console
• building binaries
• building                                       binary=dist/archive-bug-mre_x86_64-unknown-linux-gnu/archive-bug-mre
• cargo zigbuild
output=
│    Compiling archive-bug-mre v0.1.0 (/private/tmp/archive-bug-mre)
│     Finished `release` profile [optimized] target(s) in 1.52s
• building                                       binary=dist/archive-bug-mre_x86_64-unknown-linux-musl/archive-bug-mre
• cargo zigbuild
output=
│    Compiling archive-bug-mre v0.1.0 …
```
> fix(rust): properly group binaries by platform

- internal/pipe/nix/nix.go
- internal/pipe/nix/nix_test.go
currently, it would give a warning when running goreleaser hc, but wouldn't actually fail the check, as the pipe was being skipped if nix-hash wasn't available.
this fixes it, so it checks on run instead.
> fix(nix): improve nix-hash check

- internal/pipe/cask/template.go
- internal/pipe/cask/testdata/TestFullPipe/uninstall.rb.golden
- internal/pipe/cask/testdata/TestFullPipe/zap.rb.golden
Fixes improper string quoting in Homebrew cask `zap` arrays to ensure valid Ruby syntax in generated cask files.
Previously, installing a cask with a `zap` stanza would result in an error due to unquoted strings.
GoReleaser config (valid YAML):
```yaml
zap:
trash:
- "~/.moley/config.yml"
```
Generated cask (invalid Ruby):
```ruby
zap trash: [
~/.moley/config.yml,
]
```
This results in a syntax error when running:
```sh
brew install --cask moley.rb
```
Error:
```sh
➜  mole git:(main) ✗ brew install --cask moley.rb
Warning: Cask 'moley' is unreadable: /Users/kilianhoupeurt/Documents/git/mole/mole/moley.rb:36: syntax errors found
34 |
35 |   zap trash: [
> 36 |       ~/.moley/config.yml,
|               ^~~~~~~ unknown regexp options - cfg
37 |     ],
48 |
```
The fix updates the `groupToS` …
> fix(cask): invalid string quoting in uninstall/zap arrays

- internal/builders/bun/build_test.go
- internal/builders/deno/build_test.go
- internal/builders/golang/build_test.go
- internal/builders/poetry/build_test.go
- internal/builders/rust/build_test.go
- internal/builders/uv/build_test.go
- internal/builders/zig/build_test.go
- internal/pipe/blob/blob_minio_test.go
- internal/pipe/docker/docker_test.go
- internal/pipe/git/git_test.go
- internal/pipe/gomod/gomod_proxy_test.go
- internal/pipe/gomod/gomod_test.go
- internal/pipe/nix/nix.go
- internal/pipe/nix/nix_test.go
- internal/pipe/project/project.go
- internal/pipe/project/project_test.go
- internal/pipe/sign/sign_test.go
- internal/pipe/universalbinary/universalbinary_test.go
- internal/pipe/upx/upx_test.go
- internal/testlib/docker.go
- internal/testlib/git.go
fixed some `exec.Command` calls to pass the context within.
> fix: exec.CommandContext

- .goreleaser.yaml
will add a header to every release linking to the announcement.
> ci: link announcement in the release notes

- internal/pipe/brew/brew.go
- internal/pipe/brew/brew_test.go
it's not too easy to remove/switch this, and if someone runs `goreleaser check` in their CI, this will make it fail.
eventually we could add a better mechanism for this, but since this is a one-off thing for now, added a warning for it.
> fix: make brews deprecation "soft"

- internal/shell/shell.go
- internal/shell/shell_test.go
it might happen that the string is templated, but it evals to empty, in which case shell was panicking.
this should fix it
https://github.com/orgs/goreleaser/discussions/5928
> fix(shell): prevent panic on empty commands

- internal/client/gitlab.go
- internal/client/gitlab_test.go
GitHub PR opener sets our footer, gitlab's was missing that.
> fix(gitlab): missing PR footer

- internal/builders/golang/targets.go
- internal/builders/golang/targets_test.go
- add the concept of experimental and broken targets
- added openbsd/riscv64 as an experimental target (added in go1.23)
- moved windows/arm into the broken target list (marked in go1.25, will be removed in go1.27)
- added `rva23u64` to `GORISCV64` (added in go1.26)
closes https://github.com/orgs/goreleaser/discussions/5939
> feat(golang): update allowed targets

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/generate.yml
- .github/workflows/lint.yml
- .github/workflows/nightly-oss.yml
- .github/workflows/release.yml
- go.mod
this prevents breaking CI when a new Go version is out.
> ci: use go-version-file

- go.mod
- go.sum
- internal/client/git.go
- internal/pipe/docker/api_docker.go
- internal/pipe/docker/docker.go
- internal/pipe/docker/docker_test.go
- internal/pipe/docker/manifest.go
- internal/pipe/release/release.go
- internal/pipe/release/release_test.go
- pkg/config/config.go
- www/docs/customization/docker.md
- www/docs/customization/docker_manifest.md
- adds avast/retry in favor of our manual retries here and there
- makes retries configurable for docker images and manifests
- use retries in docker manifest create and push
closes #5967
fixes #5853
> feat: retry docker manifest, retry configurations

- go.mod
- go.sum
Reverts goreleaser/goreleaser#6035
see: https://github.com/ulikunitz/xz/issues/62
> Revert "chore(deps): bump github.com/ulikunitz/xz from 0.5.13 to 0.5.14 in the go_modules group"

- www/docs/install.md
Fedora: Move the OSS/Pro exclude config to the repo config That way it works even with yum update later on
**If applied, this commit will...**
Provide a better outcome for people using goreleaser on Fedora (like me)
The install instructions are not optimal and I keep getting goreleaser-pro installed when I do yum update
> Fedora move exclude to repo config
