.gitignore, config/config.go, config/config_test.go
From https://www.reddit.com/r/golang/comments/5l3i9b/deliver_go_binaries_as_fast_and_easy_as_possible/dbss8t5/
This PR introduces expansion of the default files to add code in `config.go`'s `fix()` function.
The original rationale behind this change is to allow the tool to recognise and use the alternative spelling of 'Licence' that Real English ™️ uses. The scope has crept a little in that the original implementation would bail when no licence was included.
I have also expanded the testing of this method; it had happy-path'd file selection a tad.
=> Alt licence

pipeline/compress/compress.go
Commit https://github.com/goreleaser/releaser/commit/40de5c5c644d69c3d33a6d0cf16e539a0f40423b introduces a regression (see comment) whereby
the tarball is closed before data is completely written, thus breaking the release package.
Verified by building the package, running the package and then:
```bash
$ tar vvxf dist/release_Darwin_x86_64.tar.gz
x LICENSE.md
x README.md
x release
```
This PR is a response to https://github.com/goreleaser/releaser/issues/40
=> Reorder `defer`'d closers

pipeline/brew/brew.go, pipeline/brew/brew_test.go, sha256sum/sha256.go
- drop linuxbrew support
- drop i386 macs support
- add sha256 (to avoid warnings)
- remove useless `head` statement
closes #50
=> improve brew formulae

README.md
Feel free to improve on what I'm trying to say here.
I just think it's worth mentioning that you need to create a Git tag first to use GoReleaser.
=> Mention Git tags. Closes #68.

goreleaser.yml
it will probably not work on windows anyway (e.g.: calling `git` instead of `git.exe`).
The get/latest script also won't work on Windows.
For me, we can assume that this don't work and that's it...
=> stop building goreleaser.exe

goreleaser.yml
It calls the `git` binary to get tags and logs. I think it's valid to add git as a dependency since now it is supported.
=> brew depends on git

main.go, pipeline/archive/archive.go, pipeline/brew/brew.go, pipeline/brew/brew_test.go, pipeline/build/build.go, pipeline/cleaner.go, pipeline/defaults/defaults.go, pipeline/env/env.go, pipeline/git/git.go, pipeline/release/release.go, pipeline/repos/repos.go, pipeline/repos/repos_test.go, pipeline/source/source.go
This should help with #72.
As you can see from the commits I also fixed another small bug and included it here.
To clean up `git stash` and `git checkout` I added a new interface `Cleaner`. 
Please let me know if you have suggestions for a better solution.
=> Always use latest tag as source

.travis.yml, README.md, config/config.go, context/context.go, goreleaser.yml, main.go, pipeline/brew/brew.go, pipeline/brew/brew_test.go, pipeline/build/build.go, pipeline/fpm/fpm.go, pipeline/git/git.go, pipeline/release/release.go
- we were using the tag as version, neither brew nor fpm really liked that. Now goreleaser removes the `v` prefix from the tag name and uses that as version for both cases
- added support for calling fpm (only dependencies optional supported for now)
What do you guys think?
Agree with the API? Once we agree, I'll update the docs!
closes #10
=> added fpm support

README.md, config/config.go, pipeline/brew/brew.go, pipeline/brew/brew_test.go
I need a plist field in one of my go projects and I did not want to give up on goreleaser :)  So I drafted a PR to discuss how to better add the feature. 
It's already working as it is but I'm not sure this is the right direction. A couple of notes:
- Wherever I added fields to structs I felt the need to reorder the fields alphabetically and put an empty line between groups (I would group the fields by type). But that's probably too personal and I'm not sure you'd like that.
- I changed the tests very little because I'm not sure you'd like to have more there. The rest of the brew tests follow the same approach.
I've tried the branch [here](https://github.com/lucapette/homebrew-tap/blob/master/tracker.rb) and it works fine.
This project gets better every time I use it. Thank you so much …
=> First implementation of plist field for brew formulae

checksum/checksum_test.go, pipeline/checksums/checksums.go, pipeline/checksums/checksums_test.go
Rewrote some file creation logic in a simpler way.
It was first done like that because I was using the `os.O_EXCL` flag, which is not needed anymore.
=> simplified code

main.go
no reason running it on full cycle only.
=> checksum pipe can run on the no-release mode

pipeline/checksums/checksums.go, pipeline/checksums/checksums_test.go
Proposal for #176 
This way, a user can download all archives and a single checksum file and do:
```sh
$ sha256sum -c test_checksums.txt
test_linux_64bits.tar.gz: OK
test_linux_64bits.deb: OK
test_macOS_64bits.tar.gz: OK
```
Example release: https://github.com/caarlos0/test/releases/tag/v2.0.1
=> better checksums

README.md, config/config.go, pipeline/fpm/fpm.go
This is needed to create a proper debian control file, but will also be used for the .rpm packages.
I did not find any easy way to add a unit test for this, but I have tested it myself and verified that the debian control file looks fine.
=> Add fpm options

pipeline/fpm/fpm_test.go
right now we only pass the args, and, since we have fpm installed, if it does not break, we assume it's right.
We may make this code more testable in the future though.
=> add more fpm tests

README.md, config/config.go, pipeline/archive/archive.go, pipeline/archive/archive_test.go
The syntax looks like:
```yml
build:
goos:
- linux
- darwin
- windows
archive:
format: tar.gz
format_overrides:
- goos: windows
format: zip
```
I ran it against goreleaser itself, the output was:
```console
~/Code/Go/src/github.com/goreleaser/goreleaser master*
❯ go run ./cmd/goreleaser/main.go --skip-validate --skip-publish
Running goreleaser dev
Setting defaults
Getting and validating git state
-> Skipped validations because --skip-validate is set
Loading environment variables
-> Skipped validations because --skip-validate is set
Building binaries
-> Building dist/goreleaser_Linux_x86_64/goreleaser
-> Building dist/goreleaser_Linux_i386/goreleaser
-> Building dist/goreleaser_Darwin_i386/goreleaser
-> Building dist/goreleaser_Darwin_x86_64/goreleaser
-> Building …
```
=> Added archive format overrides support

README.md, client/client.go, client/github.go, config/config.go, goreleaser.yml, pipeline/brew/brew.go, pipeline/brew/brew_test.go, pipeline/fpm/fpm.go, pipeline/fpm/fpm_test.go, pipeline/release/release_test.go
brew was discovering homepage and description from the github repository info, which was not documented at all and there were no way of overriding that. So, I added those settings, and also remove the `options` from `fpm` section, they all lay in the root now.
Also renamed `fpm.url` to `fpm.homepage`.
@bep this may impact you, I'm not doing it in a backwards compatible way because probably no one is using it yet :P
=> make brew and fpm config more alike

.travis.yml, Makefile, goreleaser.yml, goreleaserlib/goreleaser.go, goreleaserlib/goreleaser_test.go, main.go
Move `main.go` file to top level and move Go library to `goreleaserlib` package.
This organisation would allow GoReleaser to be installable via `go get` and at the same time make the functionality usable from Go via the `goreleaserlib`.
Calling the package `goreleaserlib` instead of just `goreleaser` allow the default behaviour of `go build` to still create a binary called `goreleaser`.
=> make goreleaser installable via go get #205

README.md, config/config.go, context/context.go, goreleaserlib/goreleaser.go, main.go, pipeline/defaults/defaults.go, pipeline/env/env.go, pipeline/env/env_test.go, pipeline/git/git.go, pipeline/git/git_test.go
This adds a new `--snapshot` flag in order to allow no-tag releases. In addition, the snapshot name can be configured with the `snapshot_name_template` top-level setting within the goreleaser.yml file.
Relates to #222
=> Add snapshot builds

goreleaser.yml
Possible fix for #225 
I saw [Hugo](https://github.com/spf13/hugo/blob/master/goreleaser.yml#L4) uses this option and the Hugo release works on Alpine Linux.
But I don't think Hugo is release from Travis CI.
The only way to test this, is by making it part of a tag and let it run on Travis. 
Could also create a new repository to try this out.
But before trying this, @caarlos0, maybe you have any idea?
=> Use external, static linking.

Gopkg.lock, Makefile, README.md, goreleaser.yml, internal/ext/ext.go, internal/ext/ext_test.go, pipeline/archive/archive.go, pipeline/archive/archive_test.go, pipeline/archive/tar/tar.go, pipeline/archive/tar/tar_test.go, pipeline/archive/zip/zip.go, pipeline/archive/zip/zip_test.go, pipeline/build/build.go, pipeline/build/name.go, pipeline/build/name_test.go, pipeline/defaults/defaults.go, pipeline/defaults/defaults_test.go
refs #229 
- now, the `defaults` pipe won't search for files anymore, but would set the default globs into  `config.archive.files`
- the archive pipe will then iterate over `config.archive.files` and deal with all of them as globs
- removed an unneeded read dir from the archive pipe, which required moving `extFor` function to another pkg
It should work for:
- `*.ext`
- `blah*`
- `folder/*`
- `folder/**/*`
It doesn't work, however, for `folder` only, because the archive impls require files instead of folders. We may change this in the future.
This seems to be more robust than the previous solution, not sure if ideal though. Feedback appreciated!
=> support globs on archive.files

pipeline/build/build.go, pipeline/build/target.go
Looks like
```
~/Code/Go/src/github.com/goreleaser/goreleaser master* 12s
❯ go run main.go --skip-validate --skip-publish
Running goreleaser dev
Setting defaults
Getting and validating git state
-> Skipped validations because --skip-validate is set
Loading environment variables
-> GITHUB_TOKEN not validated because publishing has been disabled
Building binaries
-> Skipped invalid build target: darwin/arm6
-> Skipped invalid build target: darwin/arm64
-> Skipped invalid build target: windows/arm6
-> Skipped invalid build target: windows/arm64
-> Building dist/goreleaser_Linux_i386/goreleaser
-> Building dist/goreleaser_Linux_x86_64/goreleaser
-> Building dist/goreleaser_Linux_armv6/goreleaser
-> Building dist/goreleaser_Linux_arm64/goreleaser
^Csignal: interrupt
```
closes #252
=> pretty target string

pipeline/build/target_test.go, pipeline/build/valid_os.go
closes https://github.com/goreleaser/goreleaser/issues/255
=> allow linux ppc64 and ppc64le builds, as well openbsd arm

pipeline/git/git.go
to ensure output is always readable no matter what configuration a user has set (cc #268)
=> Use git status --porcelain

internal/archiveformat/format.go, internal/archiveformat/format_test.go, pipeline/archive/archive.go, pipeline/archive/archive_test.go, pipeline/brew/brew.go, pipeline/brew/brew_test.go
There was a `TODO this can be broken by format_overrides`.
Fixed and also improved the brew pipe test coverage.
=> archive format overrides could break brew formula

pipeline/release/body.go, pipeline/release/body_test.go
closes https://github.com/goreleaser/goreleaser/issues/245
@goreleaser only work in some places apparently, this should work everywhere!
=> improved link to goreleaser

.goreleaser.yml, Gopkg.lock, Gopkg.toml, config/config.go, config/config_test.go, config/testdata/invalid_config.yml, goreleaserlib/goreleaser.go, goreleaserlib/goreleaser_test.go
added a `XXX` map field in each config struct matching all non previously matched fields.
this `XXX` map should always be empty.
Kind of ugly but works. Inspired by prometheus/alertmanager 🍺 
closes #290
=> Config validation

CONTRIBUTING.md, Gopkg.lock, Gopkg.toml, goreleaserlib/goreleaser_test.go, internal/buildtarget/targets.go, internal/buildtarget/targets_test.go, pipeline/git/git_test.go
- fpm is required to pass tests.
- apex/log package needs to be available.
- gpgSign git option needs to be disabled for test repo.
This is an issue when a developer has set gpgSign to true in
their global .gitconfig file.
https://github.com/goreleaser/goreleaser/pull/294 needs to be merged first.
=> Update contributing guide and fix local tests.

pipeline/git/git_test.go
this error can't happen on normal circumstances.
Adding more asserts to guarantee that.
refs #300
=> ensuring #300 doesnt happen

README.md
The comments for `plist` and `test` got mixed up, so I fixed it.
=> Fix config comments in README

config/config.go, config/config_test.go, config/testdata/invalid.yml, pipeline/snapcraft/snapcraft.go, pipeline/snapcraft/snapcraft_test.go
I noticed that the final artifact was in a subfolder inside dist, different from the other pipes, so I change that. (see https://travis-ci.org/goreleaser/goreleaser/builds/260157591#L891)
I also dealt with a possible error while linking files.
Finally, I passed gometalinter again on the code (disabled on build because it always time out on travis for some reason) and fixed the things it complained about 👍 
cc/ @elopio
=> small improvements

README.md, config/config.go, pipeline/fpm/fpm.go, pipeline/fpm/fpm_test.go, pipeline/fpm/testdata/testfile.txt
This adds a way to add arbitrary extra files or dirs to fpm packages:
```
fpm:
files:
"scripts/etc/init.d/": "/etc/init.d"
```
=> Add fpm path mappings

pipeline/fpm/fpm.go, pipeline/snapcraft/snapcraft.go, pipeline/snapcraft/snapcraft_test.go
- following the same template of the other logs: `skipping because X`
- improved validation of snapcraft pipe
=> improved logs

context/context.go, goreleaserlib/goreleaser.go, internal/buildtarget/targets.go, internal/testlib/skip.go, internal/testlib/skip_test.go, pipeline/brew/brew.go, pipeline/brew/brew_test.go, pipeline/cleandist/dist.go, pipeline/env/env.go, pipeline/env/env_test.go, pipeline/fpm/fpm.go, pipeline/fpm/fpm_test.go, pipeline/git/git.go, pipeline/git/git_test.go, pipeline/pipe.go, pipeline/pipe_test.go, pipeline/release/release.go, pipeline/release/release_test.go, pipeline/snapcraft/snapcraft.go, pipeline/snapcraft/snapcraft_test.go
- skipping a pipe is now an error type
- improved some logs
- improved snapcraft test coverage
=> skip pipe as an error type and improved output

internal/linux/arch.go, internal/linux/arch_test.go, pipeline/fpm/fpm.go, pipeline/snapcraft/snapcraft.go
seems right now:
```
root@4bdeb544b41c:/tmp/dist# dpkg -i goreleaser_Linux_armv6.deb
(Reading database ... 10301 files and directories currently installed.)
Preparing to unpack goreleaser_Linux_armv6.deb ...
Unpacking goreleaser (0.30.0) over (0.30.0) ...
Setting up goreleaser (0.30.0) ...
root@4bdeb544b41c:/tmp/dist# goreleaser -h
NAME:
goreleaser - Deliver Go binaries as fast and easily as possible
USAGE:
goreleaser [global options] command [command options] [arguments...]
VERSION:
0.30.0, commit 42446c807989f83b98f4fa11a41b728eb0b38661, built at 2017-08-27T16:10:05Z
COMMANDS:
init, i  generate .goreleaser.yml
help, h  Shows a list of commands or help for one command
GLOBAL OPTIONS:
--config FILE, --file FILE, -c FILE, -f FILE  Load configuration from FILE (default: ".goreleaser.yml") …
```
=> fixed arm .deb

pipeline/snapcraft/snapcraft.go
it bugs me that the names are different:
I was trying to solve it the wrong way on #329, this one is the right way :)
closes #322
=> padronizing snapcraft packages name

config/config.go, docs/120-homebrew.md, internal/client/github.go, pipeline/defaults/defaults.go, pipeline/defaults/defaults_test.go
Default author name and email can be set in config file.
Close #292.
I think it is most flexible if we allow the user to set the commit author in the config file instead 
of guessing a correct value.
In most cases users won't care so I left the old default values.
In other cases I think the logged in user is not the best guess since organizations mostly rather specify a separate email to indicate that this commit was made by a bot, not a human.
I hope I didn't forget to update any relevant code.
And I am not completely sure I put it in the best place in the config file - open to suggestions here.
- New feature (non-breaking change which adds functionality)
- I have updated the documentation accordingly.
- I have updated the tests to cover my changes.
=> Add config field to overwrite brew commit author

docs/115-release.md
I added an example to the docs of the `--release-notes` flag to make the usage more clear (see #284).
The example is an realistic use case and might help others to generate their own changelog.
=> docs: Add example for --release-notes flag

CONTRIBUTING.md
Explain contributors how to craft useful commit messages.
We also use https://gitcop.com/ to enforce the formatting.
Closes #377
=> docs: Add commit message guidelines to CONTRIBUTING.md

CONTRIBUTING.md
Docker is also a required dev dependency to make the tests pass.
Also see #379
=> docs: Add Docker as dependency in CONTRIBUTING.md

config/config.go, docs/060-archive.md, pipeline/archive/archive.go, pipeline/archive/archive_test.go
The field is optional. When set to true, files in archive are wrapped
in a directory, which has the same name as the archive itself.
Tests have also been extended to cover this.
Closes #251
If you think another name for the option is more clear or we need further customization, please let me know.
=> feat: Add archive config 'wrap_in_directory'

config/config.go, docs/115-release.md, internal/client/github.go, pipeline/release/release.go
Add an config option to `release` section to set a release at not ready
for production.
Closes #384
- New feature (non-breaking change which adds functionality)
- I have updated the documentation accordingly.
=> feat: Add prerelease option

.travis.yml, pipeline/docker/docker_test.go
Makes it not necessary to be logged in the in the docker registry for
the tests to work by using a local registry.
Fixes #379
=> fix: docker tests should not depend on the main docker registry

config/config.go, config/config_test.go, pipeline/defaults/defaults.go, pipeline/defaults/defaults_test.go, pipeline/defaults/remote.go, pipeline/defaults/remote_test.go, pipeline/git/git.go
Improved the error handling in git code,
mostly in the defaults pipe. The idea is to
output better error messages, hopefully avoiding
confusion on "whats wrong".
refs #356
=> refactor: improved git error handling

internal/git/git.go, internal/git/git_test.go, pipeline/defaults/remote.go
We were checking for a .git folder, which would break in cases
where goreleaser is running from a subfolder of a monorepo, for example.
Check https://github.com/goreleaser/goreleaser/commit/529af6fe72a391207ab25ef6ca7676eaf4c45954#commitcomment-25011738
Closes #402 #403
=> fix: detect if current folder is a subfolder of a parent git repo

config/config.go, docs/115-release.md, pipeline/changelog/changelog.go, pipeline/changelog/changelog_test.go
We can now add:
```yaml
changelog:
sort: asc
```
to group together our commits by prefix or just to sort them...
Closes #284
=> feat: added sorting support to the changelog pipe

pipeline/fpm/fpm.go
FPM would randomly fail to build deb and rpm packages. It apparently
happens because fpm (or some tool it uses) shares state between runs
(possibly by overriding files that are going inside the archive).
The error `file changed as we read it` was happening, which is a `tar`
error.
I don't know how to fix this, but, in order to make goreleaser more
stable, I'll disable the concurrency here for now.
closes #333
=> fix: fpm fails randomly

config/config.go, config/config_test.go, config/testdata/invalid_config.yml
If the user configures the changelog section with an invalid key, show
an error.
=> feat: validate changelog config for invalid fields

pipeline/fpm/fpm.go, pipeline/fpm/fpm_test.go
- fixed the previous issue with random failures
- make fpm respect the --parallelism setting
I had 
```
while true; do
go test -v ./pipeline/fpm/... || break
done
```
running for 15min and the issue didn't happened 🎉
=> Enabled parallelism again in fpm pile

config/config.go, docs/100-fpm.md, pipeline/defaults/defaults.go, pipeline/fpm/fpm.go
Some packagers may want to put binaries in a location other than
/usr/local/bin. This allows one to override the destination for
binaries when using fpm, using the `fpm.bindir` config key.
=> feat: Allow overriding fpm destination for binaries

context/context.go, goreleaserlib/goreleaser.go, pipeline/fpm/fpm.go, pipeline/fpm/fpm_test.go
Only enable fpm's debug mode when goreleaser is in debug as well.
Also wrapping the error when fpm fails.
=> feat: improved fpm output

.gitignore, pipeline/build/build.go, pipeline/build/build_test.go
Breaks the release if the package being built doesnt
have a main function.
Also improved error handling in the build pipe.
Closes #415
=> feat: break if main package doesnt have a main func

checksum/checksum.go, internal/git/git.go, pipeline/build/build.go, pipeline/checksums/checksums.go, pipeline/docker/docker.go, pipeline/fpm/fpm.go, pipeline/release/body.go, pipeline/snapcraft/snapcraft.go
GAS started to break on file/folder permissions
and executing things with variables.
closes #422
=> chore: fixed/ignore lint issues

docs/000-introduction.md, docs/040-project.md, docs/050-build.md, pipeline/build/ldflags.go, pipeline/build/ldflags_test.go
Supports passing environment variables to ldflags by using .Env.VARNAME.
Closes #426
=> feat: support environment variables on ldflags

context/context.go, docs/130-docker.md, pipeline/build/ldflags.go, pipeline/build/ldflags_test.go, pipeline/docker/docker.go, pipeline/docker/docker_test.go
* fix `loadEnv()` function to split env vars only into two pars
* move env vars into `context.Context`
* add env var support for Docker `tag_template`
=> feat: env vars for Docker tag_template

pipeline/changelog/changelog.go
Ensure that the git log output is not decorated. Otherwise, the format
changes and the tests fail.
Fixes #439
=> fix: do not decorate git log output

.travis.yml
Docs are using master instead of gh-pages.
refs #378
=> chore: push docs to master

README.md
It was showing the last build, which may be from 
a broken PR.
=> docs: fixed master build status badge on readme

context/context.go, context/context_test.go, pipeline/brew/brew.go, pipeline/brew/brew_test.go, pipeline/release/body.go, pipeline/release/body_test.go, pipeline/release/testdata/release1.txt
It never worked, because the brew pipe is the last
to run.
Either way, it is not a really useful thing to
have I think.
yeah, I'm literally fixing a bug by removing the feature 🎉
=> fix: remove brew taps listing from release notes

.gitignore, goreleaserlib/goreleaser.go, pipeline/defaults/defaults.go, pipeline/dist/dist.go, pipeline/dist/dist_test.go, pipeline/effectiveconfig/config.go, pipeline/effectiveconfig/config_test.go, pipeline/finalconfig/finalconfig.go
Writes the actual config file (with defaults
merged, etc) into the dist folder.
Can be useful for debug purposes.
refs #419
=> feat: write the effective config to ./dist

docs/070-checksum.md, pipeline/checksums/name.go
Allow env vars for the checksum name_template.
=> feat: allow env vars for checksum name_template

pipeline/brew/brew.go, pipeline/brew/brew_test.go
refs #501 
next step would be disable the push only.
=> feat: write formula to dist

goreleaserlib/goreleaser.go
When release notes are added via the --release-notes
and we run in debug mode, a message "custom release notes ..."
is logged. This message had a typo.
=> fix: Typo in debug message for custom release notes

internal/buildtarget/buildtarget.go
The buildtarget contained a typo. This fixes it.
=> fix: Typo in buildtarget

internal/builders/golang/build.go, internal/builders/golang/build_test.go
When adding a line `main: siren/main.go` to the yaml config, but `siren` is an executable resulted in a segfault:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7ca59a]
...
```
The reason is that the error returned from `stat()` is a `not a directory`, but the code only checked for `IsNotExists`. This PR changes the check to check for any error.
It also simplifies the error because the error got very weird in the "not a directory" case. This was the original:
```
⨯ release failed after 0.01s error=could not open foo/such.go: stat foo/such.go: no such file or directory
```
With this PR it is:
```
⨯ release failed after 0.01s error=stat foo/such.go: no such file or directory
```
* [x, but see note] …
=> fix: Fix segfault by catching all stat errors

.travis.yml, pipeline/snapcraft/snapcraft.go
```
DEPRECATED: Use of the 'snap' command with a directory has been deprecated in favour of the 'pack' command.
```
=> fix: snapcraft snap deprecated

pipeline/brew/template.go, pipeline/brew/testdata/run_pipe.rb.golden, pipeline/brew/testdata/run_pipe_download_strategy.rb.golden, pipeline/brew/testdata/run_pipe_enterprise.rb.golden, pipeline/brew/testdata/test.rb.golden
brew recently deprecated the use of `<<-EOS.undent` in favor of `<<~EOS` (cf. https://github.com/Homebrew/brew/pull/3694/files#diff-d667e35be86b1a2b5d1f95ff39b4a878R3). This PR updates the brew template and test files to use the new syntax.
=> fix: update brew template to use tilde heredoc syntax

internal/client/client.go, internal/client/github.go, pipeline/brew/brew.go, pipeline/brew/brew_test.go, pipeline/release/release_test.go
The GitHub implementation of CreateFile implicitly uses HomeBrew data.
Added parameters for CommitAuthor and Repo so the call site can specify
these parameters based on the context.
This is only a very minor code change that the Scoop feature (and possible other future features that rely on pushing arbitrary files to arbitrary repos).
=> refactor: Changed Client.CreateFile to be more generic

internal/client/github.go
Just a little something I noticed during #547 and #546 - the current code results in calls to `UpdateFile` even if `err != nil` still.
Changed the branching after the `GetContents` call to *first* check for
a non-404 error (internal failure of some sort) and then proceed to
check the status to determine whether to `CreateFile` or `UpdateFile`.
=> fix: Silent failure caused by branching logic

pipeline/build/build.go, pipeline/build/build_test.go
found while debugging #540 
instead of hardcoding the path, we can use the `$PWD` environment variable, for example, and it should work.
Not sure if this is a feature or a bugfix, will treat it like a feat :D
=> feat: expand env on build envs

docs/050-build.md, pipeline/build/build.go, pipeline/build/build_test.go
I added support for using the Go template engine with the binary
property. This is needed for generating binaries that include
the current version number in their file name. For example
`terraform-provider-NAME_vX.Y.Z`.
=> feat: Adds template support to binary property

.goreleaser.yml, Gopkg.lock, Gopkg.toml, config/config.go, docs/100-nfpm.md, docs/990-deprecations.md, goreleaserlib/goreleaser.go, pipeline/defaults/defaults.go, pipeline/nfpm/nfpm.go, pipeline/nfpm/nfpm_test.go, pipeline/nfpm/testdata/testfile.txt
the idea is to replace fpm with goreleaser/nfpm.
nfpm is an implementation of deb/rpm packaging that uses pure go when possible (depends on rpmbuild, unfortunately), and we can use it as a lib instead of calling a 3rd party binary.
this will hopefully increases the reliability of the entire pipeline.
not sure if the new `nfpm` field is the right thing to do or if we just replace the whole thing.
=> feat: nfpm support

config/config.go, docs/020-environment.md, pipeline/git/git.go, pipeline/git/git_test.go
Add a git configuration to control to either use long commit hashes
(current default) or use the short version with only the first 7
characters of the hash.
See #578
=> feat: Configuration to use short git hashes

pipeline/archive/archive.go, pipeline/archive/archive_test.go
Fix the problem in case
```yaml
archive:
format_overrides:
- goos: windows
format: binary
```
released file was archive (`archive.format`) and name have extension `.binary`
e.g. https://github.com/avast/stor-client/releases/tag/2.1.2
now is possible use `binary` format in `format`overrides` section
=> fix: archive.format_overrides section supports binary format correctly

pipeline/brew/brew.go, pipeline/brew/brew_test.go
The #597 added support for customizing the final Brew formula name.
The generated *.rb file still were using the project name as
class name and installing with custom name didn't work.
Fixed the issue by using the `name` field as an input for
building the class name, which defaults to project name
if no name given.
=> fix: Fix Brew formula class name when using custom name

docs/123-release.md, internal/client/name.go, internal/client/name_test.go
This PR adds a template function to be used in the release title. It allows for specifying the release date as part of the title.
=> Provide time template func to release name template

config/config.go, docs/045-hooks.md, main.go, pipeline/before/before.go, pipeline/before/before_test.go
This PR adds a new pipeline step to run additional hooks (in my case: `make clean`) before the build starts.
=> feat: Add cleanup pipeline

pipeline/brew/brew.go, pipeline/brew/brew_test.go, pipeline/brew/template.go, pipeline/brew/testdata/build_from_source.rb.golden, pipeline/brew/testdata/custom_download_strategy.rb.golden, pipeline/brew/testdata/default.rb.golden, pipeline/brew/testdata/github_enterprise_url.rb.golden, pipeline/brew/testdata/test.rb.golden
Pull request #625 made some changes to the way that caveats are included in Homebrew formulae. Previously, the string value of the caveats config field was included directly into the formula. Now, surrounding whitespace is trimmed, it is split by line, and the lines are included into the formula with some leading whitespace for readability reasons. That's all sensible, but this leads to an unintended problem: if `cfg.Caveats` is the empty string (as will be the case if it's not present in the config file), `split()` will return a slice containing the empty string. This is considered truthy by the template processor, resulting in it including the caveats section with a blank line. We deal with this by adding a check in `split()` for this scenario and returning an empty slice instead. …
=> Improve generated Homebrew formulae caveats

Gopkg.lock, pipeline/nfpm/nfpm.go, pipeline/nfpm/nfpm_test.go
Call `nfpm.Validate` before packaging to ensure config is about right.
This is because users reported on slack that their build was failing due to missing `homepage` config (which is not necessary, fixed on underlying nfpm impl).
=> fix: added nfpm validations

internal/linux/arch.go, internal/linux/arch_test.go
Previously when creating deb package for ARMv6 and ARMv7 the
architecture information were invalid in the generated package.
For example ARMv6 package got armhf architecture which is not right.
According to https://wiki.debian.org/ArmHardFloatPort,
armel is armv4t, armv5, armv6 and armhf is armv7 so updated
to use correct architecture.
Fixes https://github.com/goreleaser/nfpm/issues/32
=> fix: Use right architecture for ARM packages

internal/client/github.go
If applied, this commit will create a new tag if it does not already exist in the remote repository. If the tag already exists, the provided target commitish will not be used. This will not impact users following the existing workflow (tag, push, release).
This commit allows the user to perform `git tag v1.0.0 && goreleaser` without pushing the tags to the remote repository. The git account used for compiling the code may not have different permissions than the token used to create the release. Also, currently `git tag v1.0.0 && goreleaser` without the tags pushed will run successfully but create an invalid release pointing to the latest master commit.
One caveat, this change has no effect if a short hash is used. 
From the GitHub docs [:](https://developer.github.com/v3/repos/releases/) …
=> feat: Create new tags for GitHub release

config/config.go, docs/050-build.md, internal/builders/golang/build.go, internal/builders/golang/build_test.go
This adds support for templated `asmflags` and `gcflags` fields to the config file to match the `ldflags` field. While less often useful than the `ldflags` field, these fields are sometimes useful, especially when set to `all=-trimpath={{.Env.GOPATH}}`.
Resolves #638.
=> feat: Add asmflags and gcflags fields

config/config.go, docs/100-linux-packages.md, pipeline/nfpm/nfpm.go, pipeline/nfpm/nfpm_test.go
Support per-format NFPM overrides (as recently implemented in NFPM),
plus a pair or Goreleaser specific overrides, for "Replacements"
and "NameTemplate" (to address #640).
This keeps backward compatibility with existing config files:
settings at the root of the nfpm config section will still work as
previously (which is also useful to define common/shared settings
that we don't want to override anyway).
See #640
=> feat: Support per-format NFPM overrides

Gopkg.lock
=> chore: bump deps

www/content/environment.md
In the default golang builders ldflags three flags are set:
`main.version`, `main.commit` and `main.date`.
See https://github.com/goreleaser/goreleaser/blob/master/internal/builders/golang/build.go#L48
In the environment docs, only the `main.version` is mentioned.
goreleaser itself uses `main.date` and `main.commit` also.
=> docs: Add main.commit and main.date to environment section

pipeline/defaults/defaults_test.go
`assert.NotEmpty()` appears to have been used here as if it would check multiple arguments. [In actuality][docs], it checks the second argument and, if it determines that it is empty, fails the test with an error message containing all subsequent arguments. This changes the test to call `assert.NotEmpty()` multiple times.
Feel free to close this PR without merging if I am mistaken as to the intent of the code in question.
[docs]: https://godoc.org/github.com/stretchr/testify/assert#NotEmpty
=> test: Use multiple calls to assert.NotEmpty()

config/config.go, config/config_array_test.go, internal/builders/golang/build.go, internal/builders/golang/build_test.go, pipeline/build/build_test.go, www/content/build.md
This allows users to specify different sets of compiler, assembler, and/or linker flags for different packages. It also makes it possible to specify generic flags that contain spaces. It does this while maintaining compatibility with the old format of the fields in question by up-converting bare strings into single-element lists.
Resolves #668
=> feat: Convert flag fields into lists

README.md
If applied, this commit will remove a broken link to the docs (https://github.com/goreleaser/goreleaser/blob/master/docs) on the README.
The `docs` folder seems to have moved and hence the link is broken. [This](https://github.com/goreleaser/goreleaser.github.io) is the best I could find and it isn't ideal to be in the README.
=> fix: Remove broken documentation link

pipeline/docker/docker.go, pipeline/docker/docker_test.go
closes #673
instead of deleting - which may cause problems due to parallelism, I decided to link to `dockerfile.seed`, so we can have whatever number of links with the same origin at any given time.
docker build was already expecting this, so it was an easy change.
also added a test case.
=> fix: allow multiple images with the same dockerfile

context/context.go, main.go, pipeline/pipeline.go, pipeline/sign/sign.go, pipeline/sign/sign_test.go
This change adds a new flag `--skip-sign` which has the same effect as
```yml
sign:
artifacts:
none
```
I'd love to run `goreleaser` from Travis but don't want to give them my GPG key
=> main: add --skip-sign flag

Makefile, internal/builders/golang/build.go, internal/builders/golang/targets.go, pipeline/brew/brew.go, pipeline/checksums/checksums.go, pipeline/docker/docker.go, pipeline/release/body.go, pipeline/scoop/scoop.go, pipeline/scoop/scoop_test.go, pipeline/sign/sign.go
fix: temporary hack for golang/go#21387
for some reason it won't fail on my machine... dunno why.
=> fix: travis build

Gopkg.lock, internal/git/git.go
Right now, if git fails, it doesn't matter if debug is enabled, because it won't print both stdout and stderr.
=> fix: show git error on debug

pipeline/docker/docker.go, pipeline/docker/docker_test.go
improved the case in which a docker image may be declared but have no binaries matching it (which can really happen) and the case of a binary + goos + goarch + goarm combination matching more than one binary (can't happen right now).
Later it will just warn on the first case and do things wrong on the second, now it will error in both cases.
=> fix: improve docker error handling

config/config.go, pipeline/s3/s3.go, pipeline/s3/s3_test.go, www/content/s3.md
Hi there!
By default, goreleaser uploads archives to s3 as private files. So I add option `acl` to s3 configuration which let upload an archive as a public file.
=> feat: add acl option for s3

pipeline/s3/s3.go
closes #731 
uses the chained credential provider to get either from the config file or from env.
=> feat: s3: credentials from env as well

config/config.go, internal/tmpl/tmpl.go, pipeline/brew/brew.go, pipeline/brew/brew_test.go, pipeline/brew/template.go, www/content/homebrew.md, www/content/templates.md
Hi there!
`goreleaser` can publish archives to s3, but can't use s3-links in `brew` formulas. This solution fixes that.
=> feat: add s3 as an option to use in a brew formula

www/content/ci.md
Since support for CircleCI 1.0 will end on August 31, 2018, the documentation needs to be updated with CircleCI 2.0. Since I have just recently added `goreleaser` to my own package, I'm sharing the config I used, based on the discussion in #350.
The configuration is kept to the bare minimum needed to run `gorelease` on a tag push. I excluded other steps such as setting up dependencies, which should be on per project basis.
=> docs: Update doc for CircleCI 2.0

internal/tmpl/tmpl.go, pipeline/brew/brew_test.go
Fix two smalls typos that are avoiding a full 100% on Go Report Card
https://goreportcard.com/report/github.com/goreleaser/goreleaser#golint
https://goreportcard.com/report/github.com/goreleaser/goreleaser#misspell
=> fix: typos

pkg/archive/zip/zip.go
Redo of https://github.com/goreleaser/archive/pull/6
Hi, @caarlos0. We've had a regression here. This actually breaks zip files on macs here. When they are not compressed, it gives out a Bad ZIP file error when unzipping. That and they are 4 times as big :)
=> Zip files were no longer being compressed

internal/pipeline/snapcraft/snapcraft.go, internal/pipeline/snapcraft/snapcraft_test.go, www/content/snapcraft.md
Hi there!
I have a snap, the name of which differs from the name of the binary build. So, I propose to use the snap name as the app name instead of the name of the binary build.
=> feat: Add default command for snapcraft

internal/pipeline/snapcraft/snapcraft.go, internal/pipeline/snapcraft/snapcraft_test.go
Hi there!
In my previous PR #749 I've added the default command for snapcraft pipeline. But I only copy the command without additional metadata. That solution doesn't work if we have additional metadata like `plugs`.
=> feat: copy all app metadata to default command

internal/pipeline/scoop/scoop.go, internal/pipeline/scoop/scoop_test.go, internal/pipeline/scoop/testdata/test_buildmanifest_url_template.json.golden, pkg/config/config.go, www/content/scoop.md
Hi there!
I've added `url_template` to the scoop pipeline, as for [homebrew](https://github.com/goreleaser/goreleaser/pull/735).
=> feat: Add url template to scoop pipeline

Dockerfile, www/content/introduction.md
closes https://github.com/goreleaser/goreleaser/issues/606
I gave up trying to put everything inside the docker image, put only the basics - which is more than we had before. Should already be an improvement.
Will leave it as-is for now.
=> fix: better dockerfile

internal/http/http.go, internal/http/http_test.go, www/content/artifactory.md, www/content/put.md
If applied, this commit will allow to get http username (used from "artifactory" and "put" pipelines) from env var if not configured in goreleaser configuration.
This change is useful to avoid committing to vcs the username in goreleaser configuration file when it needs to change based on the actual user which will run goreleaser to upload files.
=> feat: Allow to get http username from env

internal/http/http.go, internal/http/http_test.go, internal/pipeline/artifactory/artifactory.go, internal/pipeline/put/put.go
This PR removes the requirement for HTTP servers to return a Location header when are used as targets for publishing artifacts with the Put and Artifactory pipelines.
This is needed because Nexus repository server doesn't include a Location header on responses of PUT requests.
This change doesn't lose any functionality since the location wasn't used at all before the patch.
=> fix: remove location header requirement on http put responses

internal/pipeline/scoop/scoop.go, internal/pipeline/scoop/scoop_test.go, internal/pipeline/scoop/testdata/test_buildmanifest.json.golden, internal/pipeline/scoop/testdata/test_buildmanifest_url_template.json.golden, www/content/scoop.md
Hi there!
When I install an application via scoop I always see the warning:
> Warning: No hash in manifest...
So, I've added the hash key to the scoop manifest.
=> feat: add hash to scoop manifest

www/content/release.md
The docs for `release` show that the `sort` field should a member of `filter`, which is incorrect syntax.
=> docs: Fix misplaced 'sort' for release

www/content/ci.md
The main point of this PR is to remove the CI instructions for CircleCI 1.0.
Last month, CircleCI 1.0 [has been EOL'd](https://circleci.com/blog/sunsetting-1-0/). It doesn't work anymore for new projects, you have to use 2.0. Thus these instructions are useless now and should be removed.
Lastly, while I was in this file, I made some grammar corrections on lines 10 and 12.
- software is its own plural
- Travis CI is their correct name
Thanks!
=> Removed EOL'd CircleCI 1.0 instructions.

Gopkg.lock, internal/tmpl/tmpl.go
If applied, this commit will imports `github.com/Masterminds/semver` instead of `github.com/masterminds/semver`. This fixes case-sensitive collisions when other repos are also importing it but with a different report path.
`github.com/Masterminds/semver` seems to prefer the uppercase-leading one, see the usages in its readme.
https://raw.githubusercontent.com/Masterminds/semver/master/README.md
=> fix github.com/Masterminds/semver import path

www/content/introduction.md
Repro:
- Open https://goreleaser.com/ in Chrome or Firefox
- Click on "customize" in the second paragraph
Expected:
- The page jumps to "Customization"
Actual:
- The page doesn't change because no matching `name` or `id` is found
=> fix customization link

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, pkg/config/config.go, www/content/docker.md
This adds support for building docker images with build flags through templates.
See #813
As an example, given this `.goreleaser.yml`
```yaml
dockers:
-
binary: mybinary
image: myuser/myimage
build_flag_templates:
- "--label=org.label-schema.schema-version=1.0"
- "--label=org.label-schema.version={{.Version}}"
- "--label=org.label-schema.name={{.ProjectName}}"
```
It will execute the following command:
```bash
docker build -t myuser/myimage . \
--label=org.label-schema.schema-version=1.0 \
--label=org.label-schema.version=1.6.4 \
--label=org.label-schema.name=mybinary"
```
=> feat: Add support for docker build flags

main.go
adding some examples of commonly used hooks.
=> fix: improve goreleaser init

Dockerfile
image now uses go 1.11 and do not installs recommended packages...
=> fix: docker: go1.11 and no-install-recommends

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, www/content/docker.md
Docker image names can now have template variables in them. This is super helpful for use cases where we want to reuse the same `.goreleaser.yml` file for all our builds so they all follow the same conventions.
Because convention > configuration
=> feat: image names can ontain template variables

internal/pipe/archive/archive.go, internal/pipe/build/build.go
- add the `archive` field to subsequent logs
- log the number of binaries in a platform group
- warn if user has more than 1 build setup - while it is OK to have, most of the times its a type on the yaml file :/ 
refs https://github.com/goreleaser/goreleaser/issues/836
=> improved logs related to archive and multiple builds

internal/pipe/publish/publish.go
Docker image names were not being added to the release notes
because the Github release step was happening earlier in the
pipeline than the docker release itself (so no artifacts had
been added to the context). This patch re-orders the pipeline
and adds a comment to warn against this happening again.
Fixes: #846
=> fix: Bring back docker release notes

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go
We can `docker build` repeating the `-t` flag, so we can build + tag on a single run, avoiding the need to call docker tag later.
=> fix: docker: build several tags

Gopkg.lock, Gopkg.toml
github.com/mitchellh/go-homedir has a stable release version now. Using master causes dep to be unable to solve for a suitable version when goreleaser is depended on in other projects which also (transiently) depend on the released version. This fixes that, and brings API stability guarantees.
=> bump: go-homedir to stable version

Dockerfile, Dockerfile.cgo
Added a CGO-capable Goreleaser image to repo and cleaned up layers
in exisitng Dockerfile.
Layers are ordered in a way to minimize breaking of the cache. Additional
Docker key fingerprint checking has been added to ensure that we get the
key we are expecting from Docker website.
https://github.com/goreleaser/goreleaser/issues/795
=> Add cgo image and cleanup existing dockerfile

Dockerfile, Dockerfile.cgo
This should significantly reduce the image size of the Docker images
needed to use Goreleaser
```
Current:
goreleaser        1.15GB 
goreleaser-cgo    1.15GB
Alpine-based:
goreleaser        595MB
goreleaser-cgo    741MB
```
Resolves #882
I didn't have a big enough project to test everything that goreleaser supports in this manner but the medium-size one seems to work fine.
PS: `mercurial` is added since `go mod download` is supposed to support mercurial-backed plugins which some k8s go plugins use.
=> Converted current docker images to Alpine

internal/client/github.go, internal/pipe/release/release.go, internal/pipe/release/release_test.go, pkg/config/config.go, pkg/context/context.go, www/content/release.md
This PR addresses #667 
It's not complete yet but with a draft for the implementation.
The changes enable `goreleaser` to automatically mark a release as a pre release when the tag contains an indicator for it. A tag that would lead to a pre release would be `0.0.1-rc1`. The requirement is basically that `-` followed by 1+ characters is present.
This can probably be tweaked and hardened a bit. I'm open for suggestions!
I'm also not 100% sure yet if this is the best location for the code.
`ctx.Config.Release.Prerelease` is not accessed anywhere else so the choice where to put the code is basically free. But since we change the datatype from `bool` to `string` and `Context` does not have a member for `Prerelease` we would have to carry the variable around otherwise.
So either we check quite …
=> Add check if tag contains indicator for pre release

internal/pipe/release/release.go
If applied, this commit will fix a log message. At the moment, I see in the output of `goreleaser` I see:
```
• SETTING DEFAULTS 
• Invalid value %!s(MISSING) for prerelease. Should be auto, true or false
```
The `%!s(MISSING)` indicates a missing argument to (in this case) `log.Warnf`.
As I do not set `prerelease` in my config, it is also likely that the default value of `prerelease` is not being set correctly. Alternatively, if `prerelease` is empty is should perhaps be treated the same as `auto`.
=> fix: pass missing arg to log.Warnf

scripts/entrypoint.sh, www/content/install.md
Allows pushing docker containers to a private docker registry.
When creating a docker image tagged for a private docker registry the [goreleaser docker container](https://hub.docker.com/r/goreleaser/goreleaser/) can optionally be configured to use a private docker registry by setting the `DOCKER_REGISTRY` command line environment variable.
This will allow you to, for example, push images to a `gitlab` docker registry.
=> feat: Allows pushing to private docker registry

.travis.yml, internal/pipe/git/git.go, internal/pipe/git/git_test.go, internal/pipe/snapcraft/snapcraft.go, internal/pipe/snapshot/snapshot.go, internal/pipe/snapshot/snapshot_test.go, internal/pipeline/pipeline.go, www/content/snapshots.md
Make sure there is always a `ctx.Version` when snapshotting.
if `config.snapshot.name_template` was empty, the default was being set after the template (which was empty) was already evaluated, leaving the user with an empty `ctx.Version`.
For some reason, snapcraft just now started to complain about that.
=> fix: snapshot version handling

internal/client/github.go, internal/pipe/put/put.go
=> fix: retry upload

internal/client/github.go, internal/pipe/put/put.go, internal/pipe/release/release.go, internal/pipe/release/release_test.go
current implementation on the client does not work well, as well its not the best place to do it, since we'll need to re-implement it on other clients when needed.
moved impl to the release pipe itself, also adding better tests for it.
refs #900
=> better retry upload

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go, internal/pipe/brew/template.go, internal/pipe/brew/testdata/custom_block.rb.golden, internal/pipe/brew/testdata/test.rb.golden, pkg/config/config.go, www/content/homebrew.md
This allow authors to specify things such as devel, head and more.
I'm proposing this change so we can let users run projects from master.
See https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#advanced-formula-tricks for details.
=> feat: add custom_block to brew formula generation

internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go, internal/pipe/scoop/testdata/test_buildmanifest.json.golden, internal/pipe/scoop/testdata/test_buildmanifest_url_template.json.golden
now it should be able to support multiple builds and therefore multiple binaries.
refs https://github.com/goreleaser/goreleaser/issues/705
=> fix: support multiple binaries in scoop pipe

internal/pipe/changelog/changelog.go, internal/pipe/changelog/changelog_test.go, pkg/config/config.go
In some cases, changelog or release notes do not need to be compiled for
various reasons.
This commit adds an option to Skip building the changelog.
Fix #888
=> feat: allow skipping changelog generation

internal/pipe/docker/docker_test.go, internal/pipe/git/errors.go, internal/pipe/git/git.go, internal/pipe/git/git_test.go, internal/pipe/release/release.go, internal/pipe/release/release_test.go, internal/pipe/semver/semver.go, internal/pipe/semver/semver_test.go, internal/pipeline/pipeline.go, internal/tmpl/tmpl.go, internal/tmpl/tmpl_test.go, pkg/context/context.go
- get and parse semver in a single place
- semver now is available in the context 
- we may add prerelease to templates too
- simplified some docker checks that happened to fail here for some reason now
- removed extra semver checks
- fixed issue with skip validate and semver ( closes #928 )
=> fix: improved semver parsing

internal/pipe/git/git.go, internal/pipe/snapshot/snapshot_test.go, pkg/config/config.go, www/content/deprecations.md
Removed `git.short_commit` option, it has been deprecated for almost 1 year...
=> clean: removed deprecated git.short_hash option

internal/client/github.go
this shall avoid overriding the release body if the release exists and the body is not empty...
refs #929 
closes #856
=> fix: do not override release notes

internal/middleware/doc.go, internal/middleware/error.go, internal/middleware/error_test.go, internal/middleware/logging.go, internal/middleware/logging_test.go, internal/middleware/middleware.go, internal/middleware/middleware_test.go, internal/pipe/changelog/changelog.go, internal/pipe/changelog/changelog_test.go, internal/pipe/changelog/testdata/changes.md, internal/pipe/defaults/defaults.go, internal/pipe/publish/publish.go, main.go, main_test.go, pkg/context/context.go
- moved changelog file load to the changelog pipe
- created middlewares for common abstractions on `Piper`, `Defaulter` and `Publisher` actions
- other smaller improvements
=> refactor/fix: improved CLI

.goreleaser.yml, www/content/actions.md
closes #938 
I'm pushing `goreleaser/goreleaser:v0.98.0-action` to test this...
=> feat: github actions support

www/content/quick-start.md
If applied, this commit will update the quickstart docs to make a few things clearer
This change is being made to clear up a few things that I struggled with on my first time using GoReleaser.
#946 could potentially have been avoided by making it clearer in the quickstart docs that you can change the format to release just the binaries not in any archive.
=> Make a few things clearer in quickstart docs

internal/git/git.go, internal/testlib/git.go
This change will support parsing the commit hash from GPG-signed commits. It does so by disabling signing output from the `git` CLI using `git -c log.showSignature=false` prior to the git subcommand.
@controlplaneio security policy mandates GPG signed commits, and we'd like to use this tool.
Closes https://github.com/goreleaser/goreleaser/issues/952
=> fix: parse commit hash of GPG signed commit

pkg/archive/archive.go, pkg/archive/archive_test.go, pkg/archive/gzip/gzip.go, pkg/archive/gzip/gzip_test.go, pkg/archive/targz/targz.go, pkg/archive/targz/targz_test.go, pkg/archive/zip/zip_test.go, www/content/archive.md
=> feat: support gzip format

.travis.yml, Dockerfile, Dockerfile.cgo
=> feat: bump to go 1.12

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, internal/pipe/publish/publish_test.go, pkg/config/config.go, www/content/docker.md
If applied, this commit will skip docker pushes on `skip_publish` builds, draft builds and on pre-releases if `skip_push` is set to `auto`
Closes https://github.com/goreleaser/goreleaser/issues/977
I directly followed approach introduced in https://github.com/goreleaser/goreleaser/pull/943
So:
- Change `config.Docker.SkipPush` to `string`
- Respect `skip_publish` setting
- Respect `draft` setting
- Skip `docker push` if `skip_push` is set to `auto` and version is a pre-release
=> ability to skip Docker update for pre-releases (#977)

internal/linux/arch.go
If applied, this commit will allow goreleaser to generate rpm packages for ppc64 and ppc64le targets which include the correct architecture in the SPEC definition.
=> feat: linux compatible arch for ppc64/ppc64le

internal/linux/arch_test.go
If applied, this commit will validate the goarch to linux compatible architectures for the two ppc64 cases.
I didn't notice the go testing framework when I made the first pull
request so these were left out. Not a big deal either way but we might
as well have complete tests.
Related to #987.
=> test: validate arch map for linuxpp64/ppc64le

.goreleaser.yml, Makefile
Use https://gocenter.io as GOPROXY.
Using https://gocenter.io as GOPROXY will speed modules download and will ensure that modules referenced in go.mod are always the same, doesn't matter if some modules get deleted/changed/etc at source e.g. GitHub and etc, they get cached for live at https://gocenter.io  :-)
=> Set GoCenter as GOPROXY to speed up go builds

internal/builders/golang/build.go, internal/builders/golang/build_test.go, internal/pipe/build/build.go, internal/pipe/build/build_test.go, pkg/config/config.go, www/content/build.md
this is the first step to achieve multiple archives: we need to be able to identify builds.
The binary name alone is not a good idea, as the user may have different build configs depending on GOOS for example, so an `ID` field was added.
**This is a breaking change**: if the user has multiple builds with the same binary name the release will now fail.
refs #705
=> feat: build id

internal/pipe/build/build.go, internal/pipe/build/build_test.go, www/content/build.md
closes #1004 
build hooks now inherit global envs and are also templateable
=> feat: templates and inherit global env on build hooks

internal/pipe/sign/sign.go, internal/pipe/sign/sign_test.go
Add support for environment variables
within sign arguments. For e.g. the private key for signing.
Fixes #1009
=> fix: add env expansion within signage

internal/http/http.go, internal/http/http_test.go, www/content/put.md
=> feat: filter PUT by ID

www/content/install.md
This PR simply fixes the snapcraft install command listed on the website.
1. Almost always the user will need to prefix the command with `sudo`.
2. The GoReleaser snap is a classically confined snap which requires the flag `--classic` to install.
=> docs: fix snap install command

internal/pipe/snapcraft/snapcraft.go, internal/pipe/snapcraft/snapcraft_test.go, pkg/config/config.go, www/content/snapcraft.md
If applied, this commit will add support for [snap bash tab completion](https://docs.snapcraft.io/tab-completion-for-snaps).
This change is being made because I would like to use this functionality in chezmoi (https://github.com/twpayne/chezmoi/issues/347). The change to `.goreleaser.yaml` is demonstrated in https://github.com/twpayne/chezmoi/pull/362.
I tested this using a local build of goreleaser to build a chezmoi snap package. It seems to work :)
=> feat: add support for completer in snaps

www/content/blob.md
fixing typos in blob authentication doc.
=> docs: fix typos in blob doc

.travis.yml
should give us rpmbuild 4.12, maybe helps on https://github.com/goreleaser/goreleaser/issues/1033
=> ci: use xenial instead of trusty

internal/pipe/nfpm/nfpm.go
The `epoch` configuration is currently not propagated to nfpm, so setting `epoch` in `nfpms` config section currently has no effect on the epoch of the generated package. 
This can be easily reproduced by adding `epoch: 100` to the `.goreleaser.yml` `nfpms` section in this repo.
**Without this fix:**
```bash
$ rpm -qip dist/goreleaser_amd64.rpm
Name        : goreleaser
Version     : 0.112.1
Release     : 1
Architecture: x86_64
Install Date: (not installed)
Group       : Development/Tools
Size        : 23442528
License     : MIT
Signature   : (none)
Source RPM  : goreleaser-0.112.1-1.src.rpm
Build Date  : Tue 09 Jul 2019 10:53:37 AM CEST
Build Host  : e1-gostelit-alsu001.pnet.ch
Relocations : (not relocatable)
Packager    : Carlos Alexandro Becker <root@carlosbecker.com>
URL         : …
```
=> fix(nfpm): propagate epoch config to nfpm

Makefile
Adds step to Makefile `ci` step that diffs go.mod to help prevent garbage dependencies from getting in the commit.
Example where this could be useful: https://github.com/goreleaser/goreleaser/commit/c338cfb9a1db9922c40fa0149b7ae5c5ad0eabab
=> ci: check for unnecessary packages during CI

Makefile
- due to the `||` go-mod-tidy check will fail silently
=> chore: fix go-mod-tidy silent failure

www/content/docker.md
fix the docs for using environment variables in the `.goreleaser.yml`
I tested as described in the docs but the map does not have a key for `.ENV` but has for `.Env` as the case matters
See context struct:  https://github.com/goreleaser/goreleaser/blob/master/pkg/context/context.go#L55
=> fixes env usage description for docker images

www/content/deprecations.md
https://github.com/goreleaser/goreleaser/blob/31e27e918dbdbec87e95ca4983944d963bb0768c/www/content/deprecations.md#s3
`blobs` is not working. 
```yml
blobs:
-
provider: s3
```
```
$ goreleaser 
• releasing using goreleaser dev...
• loading config file       file=.goreleaser.yml
⨯ release failed after 0.00s error=yaml: unmarshal errors:
line 31: field blobs not found in type config.Project
```
`blob` is working.
https://github.com/goreleaser/goreleaser/blob/31e27e918dbdbec87e95ca4983944d963bb0768c/pkg/config/config.go#L357
=> docs: fix blob typo in deprecations doc

internal/builders/golang/build.go, internal/builders/golang/build_test.go
- fixes a case where ldflags are set as array in config yaml, this causes only last one to apply
Fixes #911
=> fix: ldflags need to be a single string to apply

internal/pipe/blob/blob.go, internal/pipe/blob/blob_test.go, pkg/config/config.go, www/content/blob.md, www/content/deprecations.md
pluralizes `blob` to `blobs` so its more clear that it is a list.
fixes #1094
=> fix: pluralize blob in the config file

internal/semerrgroup/sem.go, internal/semerrgroup/sem_test.go
* Honor total order of methods added to `semerrgroup.Group` when `parallelism == 1`
* `semerrgroup.Group.Go(...)` will block if the number of concurrently executing goroutines in the group is at the maximum. 
This change is being made to so that project authors may include dependencies between build phases by ordering them in their project's `goreleaser.yml`
* https://github.com/goreleaser/goreleaser/issues/1097
=> fix: honor order of functions in semerrgroup w/ parallelism == 1

internal/client/github.go
Is it a bugs?
```go
type A interface {
A()
}
func TestA(t *testing.T) {
var a A
assert.NotEqual(t, nil, &a)
a = nil
assert.NotEqual(t, nil, &a)
}
```
// this test is passed. So this pr is working?
=> fix: &base always not nil

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go, internal/pipe/brew/template.go, internal/pipe/brew/testdata/test.rb.golden
Hi there!
I've added support architecture arm for linuxbrew formulas.
I've used that formula as example https://github.com/Homebrew/linuxbrew-core/blob/c7f81028802006ba26b5e079556d1617b38ca495/Formula/openssl.rb#L58
/cc @caarlos0 @sethkor What do you think about it?
Close #1052
=> feat: support arm for linuxbrew

.github/ISSUE_TEMPLATE/Bug_report.md, go.mod, go.sum, www/content/quick-start.md, www/content/release.md
- update the docs and bug report template that only GitLab versions `11.7+` are supported 
- the docs were updated
- the gitlab sdk was updated to the latest version `go-gitlab v0.19.0`
- will close #1091
=> docs: supported gitlab versions

Dockerfile, Dockerfile.cgo
=> fix: bzr required for some go modules

go.mod, internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go, internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go
... skip brew and scoop pipe if the release section is disabled and give an appropriate error message
- Users were confused because they got misleading error messages like in the liked issue
- We'd rather go further and add this to the `check` method to do a *semantic* validation of the config, but this would be a bigger change.
- #1119
=> fix brew and scoop for disabled release

internal/pipe/brew/brew.go
brew should not do things in parallel as we may hit a race condition on github/gitlab/etc
check #1120 for more details.
closes #1120
=> fix: race condition on brew pipe

internal/pipe/docker/docker.go
Since #1110 the artifacts are passed by reference, causing the previous
code to edit the Artifact in place, _and_ add it to the list.
Fixes: #1133
=> fix: copy into DockerImage Artifact

internal/pipe/brew/brew.go
Without this change, formula is generated without arm support for linux.
See my last post here:
https://github.com/goreleaser/goreleaser/pull/1113
Repo made specifically for testing this (latest tag there is using this commit):
https://github.com/dawidd6/goreleaser-test
---
By the way I see that we can also support i386 architecture for linux in brew pipe as it seems to be simply omitted now, but idk if there is a demand for this.
=> fix: actually support arm

go.mod, go.sum
Allow to build with go1.13 or with go1.11 and go1.12 with GOPROXY enable.
It's more a "workaround"  than a real fix.
The problem need to be fixed by https://github.com/go-gitea/gitea.
Fixes #1132
=> fix: invalid pseudo version for github.com/go-macaron/cors

Dockerfile, Dockerfile.cgo
While working on a GitLab CI setup I was copying the behavior of the Dockerfile and entrypoint.sh, so that I had control over the Go version used in CI, but still use goreleaser. When I was looking at the CI output I noticed there was 303 MB of packages installed when I did `apk add --no-cache bash curl docker git`. The list of packages included `containerd`, `libseccomp`, `docker-engine` and many more that seem unnecessary. When I changed it to `apk add --no-cache bash curl docker-cli git` it reduced this to 97 MB.
I think that's something the goreleaser/goreleaser Docker image can benefit from as well, so here's that same change. If there's a need for a full Docker engine instead of just the CLI, feel free to ignore this pull request.
=> fix: install only docker-cli instead of docker

Makefile, go.mod, go.sum
Updates Makefile to use official GOPROXY (proxy.golang.org) to detects issues in which third party module proxies differ in checksum behavior for broken/invalid packages. In this case the `proxy.golang.org` less permissive than `gocenter.io`.
The issue can easily be reproduced with the following commands:
Works:
```       
$ go clean -modcache
$ GOPROXY=gocenter.io go get code.gitea.io/gitea@v1.10.0-dev.0.20190711052757-a0820e09fbf7
```
Broken:
```
$ go clean -modcache
$ GOPROXY=proxy.golang.org go get code.gitea.io/gitea@v1.10.0-dev.0.20190711052757-a0820e09fbf7
```
=> fix: GOPROXY and dependency issues

Makefile
I just added `https://gocenter.io` as a reserve proxy because `https://proxy.golang.org` may not be available.
Any comments are welcome.
refs  #1155
=> ci: extend GOPROXY list

internal/builders/golang/targets.go, internal/builders/golang/targets_test.go
Add support for additional targets:
GOOS=illumos GOARCH=amd64
GOOS=aix GOARCH=ppc64
GOOS=android GOARCH=386
GOOS=android GOARCH=amd64
GOOS=android GOARCH=arm64
GOOS=plan9 GOARCH=arm
=> feat: support additional GOOS/GOARCH targets

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go
This commit will allow to build package from a snapshot without have a package version of "0.0.0". Instead of using ctx.Git.CurrentTag, it will use ctx.Version. During a release both are the same value (with prefix "v" removed if it exists), so release pipeline stay unchanged.
With this changes, we can build package from snapshot which is useful in our use-case where we built package after each commit to master. We don't want to tag each commit but still want to build usable packages (e.g. with a version - coming from snapshot pipe) and not "0.0.0").
In addition, is allow us to build package with version that does not match SemVer (like 19.06.27.084010 which is the date + time converted to a version).
The package version i'm talking is the one set in package metadata, not just filename. …
=> feat: Use Version instead of Git tag to for .deb/.rpm

internal/semerrgroup/sem.go, internal/semerrgroup/sem_test.go
added a `skipAwareGroup` to `semerrgroup` pkg, which decorates a `Group` adding the ability to proceed even with a `pipe.SkipErr` and returning the first skip err OR another error in case it happens.
refs #1053
=> fix: skip aware semerrgroup

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, internal/pipe/docker/testdata/Dockerfile.false, internal/pipe/docker/testdata/Dockerfile.true
=> fix: docker: skip push skips other builds

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go
prevent setting `docker.files` to `.` or something inside `./dist`, hence not allowing "infinite path loops"
closes #1117
=> fix: reject docker.files as . or inside dist

go.sum, internal/pipe/git/git.go, internal/pipe/git/git_test.go
prints the `git diff` output when the branch is dirty, helping debug things on CI (maybe)
closes #1005
=> feat: git diff when dirty

internal/pipe/git/git.go, internal/pipe/git/git_test.go
Possible fix of https://github.com/goreleaser/goreleaser/issues/1163
=> fix: getTag return incorrect tag, if we have more than 1 tag for 1 commit

.golangci.yml, Makefile
This commit adds  a configuration for `golangci-lint` to not need to add a bunch of cli parameters.
closes #1185
=> ci: add golangci-lint configuration file

go.sum, internal/pipe/git/git.go, internal/pipe/git/git_test.go
`git diff` does not work when we have untracked files.
=> Revert "feat: git diff when dirty (#1178)"

www/content/actions.md
We will get the following error without it: `error=missing GITHUB_TOKEN, GITLAB_TOKEN and GITEA_TOKEN`, and the release action will be failed.
=> docs: add GITHUB_TOKEN env to github action file

www/content/ci.md
Updating the CircleCI example.
1. We now have config v2.1 so using that for the example.
2. The workflow name was changed to main as that's more common than one called "release". Which is also confusing since the job is called the same thing.
3. Updated the version of Go to the latest (because why not).
4. Placed the workflow section first.
5. Added a comment explaining what the filters are doing.
=> docs: Update CircleCI example

internal/tmpl/tmpl.go, internal/tmpl/tmpl_test.go, www/content/templates.md
This commit introduces a set of functions from the `strings` package to the templates.
It might be useful to modify the available template predefined variables.
In my case, the version format we use for tags is not compatible with docker tag format so I needed to modify it a bit
=> feat: add basic string function to template

internal/artifact/artifact.go, internal/artifact/artifact_test.go, internal/pipe/sign/sign.go, internal/pipe/sign/sign_test.go, pkg/config/config.go, www/content/sign.md
ads the hability to filter by id on the sign pipe.
with this, the user can have multiple build configs, say, one specifically for macos, then one archive config specifically for it, and finally a sign config for it, signing it with `gon`, so it macOS won't complain when the user tries to run it.
refs https://github.com/goreleaser/goreleaser/issues/1227
=> feat: filter by id on sign pipe

internal/pipe/build/build.go, internal/pipe/build/build_test.go
This PR modifies the default extension of windows that are build using the flag `-buildmode=c-shared` and `-buildmode=c-archive` from `.exe` to `.dll` and `.lib`, respectively.
Even though go allows other non-`.exe` build modes (archive, shared, pie and plugin), these are not supported in windows.
More info about build modes: https://golang.org/cmd/go/#hdr-Build_modes
This commit is based on this issue:
#1221
=> feat: Add support for c-shared and c-archive build modes in windows

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go, pkg/config/config.go, www/content/deprecations.md, www/content/nfpm.md
- adds `package_name` field to nfpm
- adds `file_name_template` to nfpm, deprecates `name_template`
closes #1238
=> feat(nfpm): allow to change package name

main.go
it was always erroring due to missing `dist` default.
fixed to use the defaults pipe instead of what I was originally doing
=> fix: goreleaser check

internal/pipe/snapshot/snapshot.go, internal/pipe/snapshot/snapshot_test.go, www/content/snapshots.md
both deb and rpm requires that the version is somewhat semantic, so this is a way to make that work as expected.
closes https://github.com/goreleaser/goreleaser/issues/1236
=> feat: change default snapshot version template

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go
The user might provide another `url_template`.
This is not ideal, but I guess its OK for now.
closes https://github.com/goreleaser/goreleaser/issues/1237
=> fix: brew: do not really depends on release

www/content/build.md
Change the default ldflags template that is displayed in the build docs to
show that the default sets `main.commit` to `Commit` instead of
`ShortCommit`.
The docs state that the default ldflags includes the ShortCommit but in
reality the code uses the longer Commit value instead. This behavior has
existed since the defaults were introduced ~3 years ago in commit
4af2cb0 so even if short commit was the intended behavior, after 3 years
of it working this way we should probably just update the docs to reflect
the actual default.
Fixes #1264
=> docs: fix default ldflag template

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, pkg/config/config.go, www/content/docker.md
Tested it with a config like this, worked like a charm:
```yaml
builds:
- id: build1
binary: foo
env:
- CGO_ENABLED=0
main: ./main.go
goos:
- darwin
goarch:
- amd64
- id: build2
binary: foo
env:
- CGO_ENABLED=0
main: ./foo/main.go
goos:
- linux
goarch:
- amd64
dockers:
- image_templates:
- caarlos0/foo
binaries:
- foo
builds:
- build2
dockerfile: Dockerfile.foo
```
closes #1241
=> feat: docker builds filter

internal/pipe/blob/blob_minio_test.go, internal/pipe/blob/blob_test.go, internal/pipe/blob/openbucket.go, pkg/config/config.go, www/content/blob.md
added blob region and disableSSL configs.
closes #1278
=> feat: added blob.region and blob.disableSSL

internal/http/http.go, internal/http/http_test.go, internal/pipe/archive/archive.go, internal/pipe/artifactory/artifactory_test.go, internal/pipe/defaults/defaults_test.go, internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go, internal/pipe/upload/upload_test.go, pkg/config/config.go, www/content/deprecations.md
removed singular `archive` config in favor of its plural form, `archives`.
=> feat: remove singular archive config

internal/builders/golang/build.go, internal/builders/golang/build_test.go, internal/pipe/build/build.go, internal/pipe/build/build_test.go, pkg/config/config.go, www/content/build.md
This will enable using GoReleaser in multi-language projects where Go code (and `go.mod`/`go.sum`) is not in project's root directory.
An example of such project is [Oasis Core](https://github.com/oasislabs/oasis-core) (where we are planning on using GoReleaser to do releases).
=> feat: specify (sub)directory with go code when building

www/content/actions.md
- use actions/checkout@v2
- unshallow
refs https://github.com/goreleaser/goreleaser-action/issues/69
=> docs: unshallow on github actions

.travis.yml
fixed the CI pipeline
we needed trusty because we needed sudo to install snapcraft... turns out there is now a package for it on apt, so, no need for any of that anymore... 
plus, upgraded infrastructure!
🚀
=> fix(ci): install snapcraft

www/content/homebrew.md
This just updates the Hombrew documentation to reference the official managed list of download strategies. Making this change as I was bit by the example provided. 
Referenced by this issue https://github.com/goreleaser/goreleaser/issues/967
=> docs: remove reference to deprecated download strategy

.goreleaser.yml, www/content/docker.md
Add the flag `--pull` to the `goreleaser` releaser process itself as well as the Docker documentation.
By default, docker won't refresh the images when performing a `docker build`, thus when building new releases, it might reuse an old base image, e.g. `alpine:3` (in my case) or `golang:1.13-alpine` in this case.
=> docs: invite people to use docker --pull

internal/pipe/sign/sign.go, internal/pipe/sign/sign_test.go, pkg/config/config.go, pkg/context/context.go, www/content/sign.md
- adds `id` config to the sign pipe
- fixes an issue with concurrent map access on `ctx.Env`
closes #1317
=> feat(sign): id, concurrent map

internal/pipe/git/git.go
With older versions of git (such as 1.8.x which I have to use for reasons), the `-q` switch is invalid, which results in this error message:
```
• releasing using goreleaser 0.124.1...
• loading config file       file=.goreleaser.yml
• RUNNING BEFORE HOOKS     
• LOADING ENVIRONMENT VARIABLES
• GETTING AND VALIDATING GIT STATE
⨯ release failed after 0.01s error=couldn't get current commit: fatal: unrecognized argument: -q
```
Using the longer form `--quiet` works on both newer and older versions of git.
=> fix: Use long git arg for quiet

go.mod, go.sum
update gitea client lib
changelog: https://gitea.com/gitea/go-sdk/releases
=> chore(deps): bump code.gitea.io/sdk/gitea from untaged to 0.11.0

internal/pipe/changelog/changelog.go, internal/pipe/changelog/changelog_test.go, internal/pipe/git/git.go, internal/pipe/git/git_test.go, www/content/build.md, www/content/environment.md, www/content/release.md
This patch detects CI environments and uses the available tag information when
collecting the git tag.
This resolves issues where one commit has multiple tags.
Closes #1163
Closes #1311
=> Use CI environment variables to figure out tag

internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go, pkg/config/config.go
Expose a new config option for `scoop`, `skip_upload`, that behaves like `brew.skip_upload`
We make heavy use of prereleases over at https://github.com/cli/cli and have come to rely on the
brew pipeline's `skip_upload` setting to avoid shipping prereleases. We were surprised that the
scoop pipeline didn't seem to support a similar feature, so this PR adds it. Please let me know if
there is existing support for this that I just missed!
[the existing brew feature](https://github.com/goreleaser/goreleaser/blob/479798126ea3d066f11fbd9ab67c21aa057ce204/internal/pipe/brew/brew.go#L157)
=> feat: add ability to skip uploads for prereleases

internal/pipe/snapcraft/snapcraft.go, internal/pipe/snapcraft/snapcraft_test.go
=> fix: snap autocompletions

.goreleaser.yml, internal/static/config.go, www/content/build.md, www/content/env.md, www/content/hooks.md
Recommend using `go mod download` rather than `go mod tidy` for fetching
dependencies. The `tidy` function is used to update things and chagnes
the dependency graph. Using the `download` function avoids any changes.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> fix: Use go mod download

www/content/quick-start.md
The docs for `--snapshot` in the quick start are confusing, especially since they mention Github releases and `--snapshot` doesn't create releases at all.
=> docs: Clarify usage of --snapshot in quick start

internal/pipe/project/project.go, internal/pipe/project/project_test.go, www/content/project.md
When a GitLab release is configured, the project name will default to the repository name, if not set explicitly. This is already the behaviour with GitHub releases.
This should fix https://github.com/goreleaser/goreleaser/issues/1337.
=> fix: infer project name from GitLab/Gitea release

internal/pipe/snapcraft/snapcraft.go, internal/pipe/snapcraft/snapcraft_test.go
fixes #1365
do not push snaps if skip-publish is set
=> fix: snapcraft: do not push when skip publish

internal/http/http.go, internal/http/http_test.go, internal/pipe/artifactory/artifactory_test.go, internal/pipe/upload/upload_test.go, www/content/upload.md
Use the standard template package on the http upload pipe.
This way, users can have more fields available on the template, as for instance, the `Os` or `Arch`.
refs #1357
=> fix: http.target template

internal/pipe/project/project.go, internal/pipe/project/project_test.go
if we can't get the project name from the release settings, fail the whole thing, as things will eventually get broken anyway.
closes #1367
=> fix: fail if cant guess project name

internal/pipe/blob/blob.go, internal/pipe/blob/blob_test.go, internal/pipe/sign/sign.go, internal/pipe/sign/sign_test.go, pkg/config/config.go, www/content/deprecations.md
you should now use blobs and signs instead.
=> feat: remove deprecated blob and sign

internal/client/client.go, internal/client/gitea.go, internal/client/github.go, internal/client/gitlab.go, internal/pipe/release/release.go, internal/pipe/release/release_test.go
=> fix: do not retry upload if file already exists

internal/builders/golang/build.go, internal/builders/golang/build_test.go, internal/pipe/archive/archive.go, internal/pipe/archive/archive_test.go, internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go
closes https://github.com/goreleaser/goreleaser/issues/1398
3 things:
1. make archive pipe work when `build.binary` is a path
2. `artifact.extra[binary]` should not have the path to the binary, just its name...
3. scoop pipe was using the `artifact.extra[binary]` field instead of just `artifact.name`
=> fix: build.binary and artifact.extra.binary

www/content/upload.md
Change the HTTP upload example to include the `name` key.
I banged my head on it for a while when trying to upload to Nexus using archive, then binary. Apparently it wants to use GET for some reasons.
#1404
=> docs: a name key is required

pkg/archive/gzip/gzip.go, pkg/archive/targz/targz.go, pkg/archive/zip/zip.go
I have read the CONTRIBUTING guide.
If applied, this commit will use maximum compression levels for gzip and zip archives instead of the default compression level.
This change will speed up uploading archive files created by goreleaser to GitHub and also consume less disk space.
=> feat: use maximum compression for gzip and zip archives

internal/pipe/build/build.go, internal/pipe/build/build_test.go, internal/pipe/checksums/checksums.go, internal/pipe/checksums/checksums_test.go, pkg/config/config.go, www/content/build.md
This PR introduces the `skip` option to the build configuration. That is mainly relevant for a library project which would need the changelog generation and creating the release, but not the building step.
With this feature, also simple library projects can benefit from `goreleaser`. 
Configuration example for a library project:
```yaml
project_name: mylib-go
build:
skip: true
release:
github:
prerelease: auto
```
Fixes #981
=> feat: build.skip option, support for library projects

internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go
Since v1.30.X the scoop manifest `bin` field always ends with `exe.exe`.
Check out the official goreleaser scoop-bucket [commit](https://github.com/goreleaser/scoop-bucket/commit/e820896a5ef81374aa05e5e8c109b1542d659c89). 
The cause is [this](https://github.com/goreleaser/goreleaser/commit/fa608c302efac346ea198f193a5d284bafa63fce#diff-01ec4399097caf1adca54769f5d1e7c9R199) change. `Artifact.Name` already contains an extension.
=> fix: scoop binary names

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go
refs #1425
basically, we don't need to fail at that time if the token is not there... it will still fail on publish time if at that time there is none.
for now, while building the brew file, assume github unless a gitlab token is provided, this should prevent failures on snapshot mode when no token is available.
=> fix: brew no token

internal/pipe/build/build.go, internal/pipe/build/build_test.go
This helps in situations where hook couldn't run at all, e.g. because of insufficient permissions.
Previously such failure would only be reported as empty stdout/stderr output - this allows exposure of the real root cause.
This PR is currently part of https://github.com/goreleaser/goreleaser/pull/1414 but I think the change is small enough in scope it could be merged separately and the PR can then be rebased.
=> feat(pipe/build): Report hook error in addition to stdout

internal/pipe/build/build_test.go
Despite the comment in code I don't believe there is anything Travis-specific about the nature of the failure. I managed to reproduce (and fix) the failure locally on my MacOS.
All tests share the same environment (hence variable namespace too) and setting & reading the same variables has lead to race conditions which can be fixed by using different variables in each test.
=> test: Allow tests to run in parallel without failing

internal/builders/golang/build_test.go, internal/pipe/build/build.go, internal/pipe/build/build_test.go, internal/tmpl/tmpl.go, pkg/config/config.go, pkg/config/config_build_hook_test.go, www/content/build.md, www/content/templates.md
This is an early prototype of a solution for #1328 to solicit early feedback.
```yml
builds:
-
env:
- CGO_ENABLED=0
targets:
- darwin_amd64
- windows_386
- windows_amd64
after:
all:
hooks:
- zip ./signable_binaries.zip {{ range .Builds }} {{ .Path }}{{ end }}
- echo "Signing every eligible binary..."
- cmd: ./codesign.sh
env:
- ZIP_FILE={{ .ProjectName }}_{{ .Version }}_{{ .Target }}.zip
each:
default_dir: "{{ .Path }}"
hooks:
- upx {{ .Name }}
```
--- 
I would be happy to add some tests, perhaps some more logging and docs if we agree on the rough direction.
=> feat(pipe/build): Add support for flexible build hooks

go.mod, go.sum, internal/pipe/before/before.go, internal/pipe/before/before_test.go, internal/pipe/build/build.go, internal/pipe/build/build_test.go
closes #1375
better command-aware hooks (both on build and before steps).
=> feat: better shellwords on hooks

.goreleaser.yml, .travis.yml, internal/deprecate/deprecate.go, internal/deprecate/deprecate_test.go, internal/pipe/nfpm/nfpm.go, internal/pipe/upload/upload.go, main.go, main_test.go, pkg/context/context.go, www/content/ci.md
- instruct to run `goreleaser check` on CI
- actually fail if deprecated properties are being used
- warn in the end of a release as well if deprecated properties are being used
closes https://github.com/goreleaser/goreleaser/issues/1289
=> feat: improve check command

www/content/archive.md
This is a follow up to my last PR, which I should have previously included. It adds `tar.xz` to the www content.
=> docs: add tar.xz to www content

internal/pipe/snapshot/snapshot.go
Small and relatively insignificant change, but the correct spelling is
with two "t's"
=> fix: correct the spelling of "snapshotting"

internal/pipe/snapcraft/snapcraft.go
This is a proposal fix for #1448. Fixes the issue for us, and relevant tests pass. This should probably be tested as well, but I cannot add a relevant unit test.
Given that the tests pass, it should not break existing behaviour either. Yet, if you think a more elaborate solution is required, feel free to close this.
Change snap app metadata command generation, using app name instead of binary name.
Snap packages with multiple apps are not built correctly.
Closes #1448
=> fix: snap package apps with multiple binaries

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go, internal/pipe/upload/upload.go, pkg/config/config.go, www/content/deprecations.md
- removed the deprecated `puts` pipe from config (replaced with `uploads`)
- removed the deprecated `nfpm.file_name_template` option in favor of `nfpms.file_name_template`
- updated deprecations page, also adding the versions in which something was removed
=> feat: remove deprecated nfpm options and puts

internal/pipe/archive/archive.go, internal/pipe/archive/archive_test.go, internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go, internal/pipe/scoop/testdata/test_buildmanifest_wrap.json.golden
takes into account `wrap_in_directory` when building the scoop manifest.
closes #1447
=> fix: scoop wrap_in_directory

internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go, pkg/config/config.go, www/content/scoop.md
Without this change, users unable to control the resulting commit message of the
scoop update.  In some environments this may present an issue with commit
linters that require a specific commit message format in order to build proper
change logs and make decisions.  Here we include a Scoop config option to use a
format string provided by the user during the commit.
resolves: https://github.com/goreleaser/goreleaser/issues/1468
=> feat(scoop): provide config option to change commit message

internal/pipe/sign/sign.go, internal/pipe/sign/sign_test.go, www/content/sign.md
allow to use templates in `signs.args`
=> feat: allow to template signs.args

internal/artifact/artifact.go, internal/artifact/artifact_test.go, internal/exec/exec.go, internal/exec/exec_mock.go, internal/exec/exec_mock_test.go, internal/exec/exec_test.go, internal/logext/writer.go, internal/pipe/custompublishers/custompublishers.go, internal/pipe/publish/publish.go, internal/tmpl/tmpl.go, internal/tmpl/tmpl_test.go, pkg/config/config.go, www/content/publishers.md, www/content/templates.md
Closes #1460
This is functionally mostly ready and it has a decent test coverage too.
It's worth noting that `env` has no inheritance of variables (unlike existing hooks), which has some tradeoffs:
- some essential variables like `TMPDIR` or `PATH` may be expected and required by the executables that are launched
- any sensitive variables remain scoped to GoReleaser and don't leak by default
We could perhaps pass through some safe variables like the ones mentioned above, to balance the negative effect of this?
```yml
publishers:
-
name: "custom"
ids:
- foo
- bar
checksum: true
signature: true
dir: "/utils"
cmd: custom-publisher.sh -product={{ .ProjectName }} -version={{ .Version }} {{ .ArtifactPath }}
env:
- API_TOKEN=secret-token
```
=> feat: Add support for custom publishers

internal/pipe/docker/docker.go
improved error output, as it may be confusing when there's more than one image being built...
=> fix: improve docker logs and errors

cmd/build.go, cmd/build_test.go, cmd/release.go, cmd/root.go, internal/pipe/build/build.go, internal/pipe/env/env.go, internal/pipeline/pipeline.go, pkg/context/context.go, www/docs/quick-start.md
This PR implements new `build` command per discussion in #1469 and aims to prevent the sprawl of `skip-*` flags in the main `release` command.
This also potentially paves way for a future similar command, like `archive/package` as discussed in #1446 but that should be IMO discussed separately.
Closes #1469
=> feat: Add build command

internal/pipe/blob/upload.go
closes https://github.com/goreleaser/goreleaser/issues/1510
should use `path.Join` for URLs instead of `filepath.Join`.
=> fix: blob: filepath on url

www/htmltest.yml
this always fails with 503 because it requires auth... ignore it.
=> fix(ci): htmltest failing checks

.goreleaser.yml
closes https://github.com/goreleaser/goreleaser/discussions/1484
=> fix: include go as a dependency of the brew tap

.github/workflows/build.yml
```
--- FAIL: TestRunPipe/multiple_images_with_same_extra_file (0.05s)
docker_test.go:73: 
Error Trace:	docker_test.go:73
docker_test.go:619
Error:      	Received unexpected error:
link testdata/Dockerfile /tmp/dockertest722218777/dist/goreleaserdocker676008868/Dockerfile: invalid cross-device link
failed to link dockerfile
github.com/goreleaser/goreleaser/internal/pipe/docker.process
```
> https://github.com/goreleaser/goreleaser/runs/698224308#step:8:40
Since virtual environment `ubuntu-18.04` (20200518.1), `/home/runner/work` is on another partition `/dev/sdb1`, so rename or link returns this kind of error.
To workaround this, override `TMPDIR` env var with `/home/runner/work/_temp/tmp`
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.4G     0  3.4G   0% …
```
=> fix(ci): Fix invalid cross-device link

go.mod, go.sum, internal/client/gitea.go
Migrate gitea client sdk
for more info look at https://gitea.com/gitea/go-sdk/src/branch/master/docs/migrate-v0.11-to-v0.12.md
and for the changelog at https://gitea.com/gitea/go-sdk/releases
=> chore(deps): bump code.gitea.io/sdk/gitea from v0.11.3 to v0.12.0

Dockerfile, Dockerfile.cgo
closes https://github.com/goreleaser/goreleaser/issues/1526
also removes `rpm` which is not required anymore.
=> fix: cgo docker image

.goreleaser.yml
having in mind #1542, maybe we should add `golang` as a dependency of the rpm and deb packages as well?
tested on both ubuntu and fedora (latests) and it works, although by default ubuntu install golang 1.10 and fedora golang 1.13 (but I think if any other package provides `golang` it will work as well).
what are your thoughts on this?
=> fix: include golang as a dependency of deb/rpms

internal/tmpl/tmpl.go, pkg/context/context.go, www/docs/customization/templates.md
Closes #1549 
--- 
I formatted the table via https://www.tablesgenerator.com/markdown_tables but I wish it was a bit easier to modify these tables manually without having to use any external tools/services.
We could make it easier by using the default left-side text-aligning, which I think would be also easier to read when rendered. That's something to discuss in a separate PR, where we could sweep all the tables at once and discuss whether it's a good idea.
=> feat: Expose semver for snapshots

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go
Will replace `@` for `AT` in brew formulae name.
Allow for Brew versioned releases (eg: foo@1). See how [awscli](https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli.rb#L1) and [awscli@1](https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli%401.rb#L1) do it.
- Fixes https://github.com/goreleaser/goreleaser/issues/1537
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli.rb#L1
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli%401.rb#L1
=> fix: Brew versioned formulae now supported

www/docs/ci/actions.md, www/docs/customization/build.md, www/docs/customization/templates.md
This patch formats all existing markdown tables in docs in a way that aligns cell content to left, as opposed to the centre (in most cases). This in turn makes it easier for anyone without any markdown generators to edit the source and getting the spacing right.
=> docs: Format markdown tables

Dockerfile, Dockerfile.cgo
seems like the newer alpine doesn't have `bzr` in their repos anymore...
```
~/Code/goreleaser/goreleaser alpine 1m 6s
λ docker run -it --rm alpine:3.12 sh
Unable to find image 'alpine:3.12' locally
3.12: Pulling from library/alpine
df20fa9351a1: Pull complete
Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:3.12
/ # apk add -U bzr
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
bzr (missing):
required by: world[bzr]
/ # apk search bzr
bzr-zsh-completion-5.8-r1
bzrtp-4.3.1-r0
bzrtp-dev-4.3.1-r0
/ #
~/Code/goreleaser/goreleaser alpine* 48s
λ
```
not sure if we can do …
=> fix: docker images: bzr

www/docs/customization/docker.md
Fix bug in [the documentation](https://goreleaser.com/customization/docker/#applying-docker-build-flags)
=> docs: remove incorrect quotes

scripts/entrypoint.sh
Instead of passing the password using the `-p` arg which is deprecated, we now use `--password-stdin` which is recommended.
Solves the following warning:
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
```
=> fix: docker login using password stdin

Dockerfile
This patch adds make to the docker image. The cgo one should already have it via `build-base`.
For projects that have a Makefile, it'd be nice to be able to use the goreleaser docker image to build the project.
Refs https://gitlab.com/gitlab-org/pubsubbeat/-/merge_requests/47.
=> feat: Install make into docker image

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go, pkg/config/config.go, www/docs/customization/nfpm.md
Allows to use "meta" package in NFPM: packages without binaries
Related to https://github.com/goreleaser/goreleaser/discussions/1612
=> feat: add nfpm meta mackages

internal/pipe/blob/upload.go
Currently if uploading a file to Google Cloud Storage the filename contains the path when downloading e.g. `bucket/path/to/file.ext` will download as `path_to_file.ext`.
Setting the `Content-Disposition` metadata on upload ensures the filename we have locally is what it's called when downloading from GCS.
=> fix: use correct filename for GCS downloads

internal/client/client.go, internal/client/config.go, internal/client/gitea.go, internal/client/gitea_test.go, internal/client/github.go, internal/client/github_test.go, internal/client/gitlab.go, internal/client/gitlab_test.go, internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go, internal/pipe/release/release_test.go, internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go, internal/tmpl/tmpl.go, internal/tmpl/tmpl_test.go, pkg/config/config.go, www/docs/customization/homebrew.md, www/docs/customization/scoop.md
Closes #1643
--- 
This introduces a new config options for Homebrew and Scoop as mentioned in #1643 - allowing the use of dedicated tokens when publishing to a Homebrew tap or Scoop bucket.
Most of the implementation is hopefully self-explanatory, or the comments in code explain it.
It's worth pointing out that this introduces a new precedent of a limited/enforced templating, scoped to just environment variables, mostly to prevent people from hard-coding tokens in the config, which this new option would otherwise allow. I'm open to alternative ideas on how to solve this problem though.
```yaml
brews:
-
tap:
owner: repo-owner
name: homebrew-tap
token: {{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}
scoop:
bucket:
owner: user
name: scoop-bucket
token: {{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}
```
=> feat: support custom tokens in Homebrew & Scoop

www/docs/customization/homebrew.md, www/docs/customization/scoop.md
Quotes are apparently necessary, otherwise the example leads to the following error:
```
• releasing...
• loading config file       file=.goreleaser.yml
⨯ release failed after 0.00s error=yaml: unmarshal errors:
line 59: cannot unmarshal !!map into string
```
=> docs: add missing quotes around templating syntax

internal/client/client.go, internal/client/gitea.go, internal/client/github.go, internal/client/gitlab.go, internal/git/config.go, internal/git/config_test.go, internal/git/git_test.go, internal/pipe/brew/brew_test.go, internal/pipe/milestone/doc.go, internal/pipe/milestone/milestone.go, internal/pipe/milestone/milestone_test.go, internal/pipe/publish/publish.go, internal/pipe/release/release.go, internal/pipe/release/release_test.go, internal/pipe/scoop/scoop_test.go, pkg/config/config.go, pkg/defaults/defaults.go, www/docs/customization/milestone.md, www/mkdocs.yml
Closes #1415
---
Enables configuration to automatically close milestones matching the tag name (or any configurable name template) at the end of the publishing pipeline with GitHub, GitLab, and Gitea. In its simplest form:
```yaml
milestones:
- close: true
```
Will close the milestone title matching the release tag after all publishing has occurred.
=> feat: support closing milestones

www/docs/quick-start.md
Improve the quick-start documentation to reflect that `.goreleaser.yml` needs to be checked into the source control. See - https://github.com/goreleaser/goreleaser/discussions/1666
=> docs: Update quick-start.md

www/docs/customization/docker.md
Signed-off-by: Jeremy Gustie <jeremy@gustie.com>
If applied, this commit will change the example labels in the Docker documentation to match the OCI recommendations.
The `org.label-schema.name` label became `org.opencontainers.image.title` ([Annotations](https://github.com/opencontainers/image-spec/blob/master/annotations.md)).
=> docs: fix OCI annotation example

internal/pipe/snapcraft/snapcraft.go, internal/pipe/snapcraft/snapcraft_test.go
Closes #1678
Do not fail on `os.Link` errors if `os.IsExist(err)`
- Loop through the completer scripts separately and only once.
- Keep track of files that have been linked already and do not try to link again.
=> fix: Completer script link errors for snapcraft

internal/static/config.go, internal/static/config_test.go
=> fix: Fix indent of yaml generated by `init`

www/docs/ci/gitlab.md
docker run command has not the option `--pull`
here's the `docker run` [documentation](https://docs.docker.com/engine/reference/run/)
=> remove --pull option from docker run

internal/pipeline/pipeline.go
This change allows us to use all the template variables in the named templates in the before hook.
Issue: GH-1710
=> feat(pipeline): change the pipeline order to support additional template variables

.github/workflows/docs.yml, www/htmltest.yml
it defaults headers to `Range: bytes=0-0`, which some providers may not support.
changing to `0-10` seems to yield a 206 on the providers I tested.
=> fix(ci): htmltest failing with 416 on some sites

internal/git/git.go, internal/git/git_test.go, internal/testlib/git.go
should avoid issues like https://github.com/goreleaser/goreleaser/issues/1734, although I'm not sure how to reproduce it (and therefore write a test for it).
=> fix: ignore git warnings

CONTRIBUTING.md, www/docs/customization/release.md, www/docs/customization/scoop.md, www/docs/deprecations.md, www/docs/install.md, www/docs/quick-start.md
so users can copy without worrying about the `$` prefix.
=> docs: make commands copy-paste friendly

internal/pipe/blob/blob_minio_test.go
If applied, this commit will update the version of the minio container used during the pipe/blob tests.
While working on #1775 I discovered that I could not get the pipe/blob tests to pass locally even on master. The apparent cause was a failure of the test_upload container to start at all. (Note: I'm on macOs 10.15.6) I was able to determine that minio failed on start up with this output:
```
You are running an older version of MinIO released 1 year ago
Update: docker pull minio/minio:RELEASE.2020-08-27T05-16-20Z
ERROR Unable to initialize config system: Unexpected error, please report this issue at https://github.com/minio/minio/issues.
```
I could not determine the specific cause other than it had something to do with the `testdata/data` directory (minio would work just fine unless the …
=> fix:make minio based tests run locally again.

internal/builders/golang/build.go, internal/builders/golang/build_test.go, pkg/config/config.go, www/docs/customization/build.md
If applied, this commit will add a `gobinary` option to the build config allowing specification of specific go binaries to use during a build.
The change is being made because it was listed in #1235 as requested.
See: #1235 for further details.
=> feat: Add `gobinary` option to build configs.

internal/artifact/artifact.go
Existing implementation seemed to rely on implicit case fallthrough, which doesn't exist in Go. Moving default return to default case helps catch this error in the future, as it will cause a "missing return" compile error.
=> fix: artifact string method switch statement

cmd/root.go, cmd/root_test.go
Allow help commands like:
```bash
goreleaser help
goreleaser help check
```
When you run: `goreleaser help` it should output help and not run `releaser`.
Thanks.
=> fix: allow help command

internal/pipe/brew/brew.go
Disambiguate a confusing warning message
The warning `optimistically guessing `brew[%d].installs`, double check` made me thinks of a hidden `installs` option (note the final "s"). Thanks god, it's just a typo, the existing and documented option is `install` (without the "s")
=> fix: typo on warning log

cmd/completion.go, cmd/completion_test.go, cmd/root.go
If applied, this commit will add shell autocompletion to `goreleaser` for bash/zsh. Can also add some documentation if there is a suggested place.
See documented issue #1858 
**Provide links to any relevant tickets, URLs or other resources**
Closes #1858
=> feat: Add Shell Autocompletion to goreleaser for bash and zsh

cmd/completion.go, cmd/completion_test.go, cmd/root.go, cmd/root_test.go
refs #1858 #1859
- added fish as well
- allow `__complete` as well (used for fish completions at least)
=> feat: add fish completion

www/docs/customization/templates.md
Change the documentation to reflect reality. Currently the documentation says .ArtifactPath is relative, not absolute.
The issue was raised in #1867 and this should fix the documentation.
=> docs: .ArtifactPath is the absolute path, not the relative one.

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go
This patch ensures that there are no duplicate `bin.install` statements added to the homebrew formula. It resolves several upstream issues including https://github.com/ory/homebrew-kratos/issues/1 and others.
Closes https://github.com/ory/homebrew-kratos/issues/1
=> fix: ensure uniqueness of brew's bin.install

go.mod, go.sum
=> chore(deps): update nfpm

.gitignore, .goreleaser.yml, scripts/completions.sh
not sure if there's a better way of doing this... but this should work...
=> fix: install completions with homebrew

internal/builders/golang/build.go, internal/builders/golang/build_test.go, internal/builders/golang/targets.go, internal/builders/golang/targets_test.go, internal/pipe/build/build.go, internal/pipe/build/build_test.go, pkg/build/build.go, pkg/build/build_test.go
=> feat: validate goos, goarch, goarm and gomips

internal/client/gitea.go, internal/client/github.go, internal/client/gitlab.go, internal/http/http.go
=> feat: use proxy from environment

internal/pipe/nfpm/nfpm.go, pkg/config/config.go, www/docs/customization/nfpm.md
port new nfpm options into goreleaser.
=> feat: nfpm rpm.summary and nfpm.ghost_files

cmd/build.go, cmd/check.go, cmd/completion.go, cmd/init.go, cmd/release.go, cmd/root.go
setting arg counts and added long description to completions command.
=> fix: improve completions

internal/builders/golang/build.go, internal/builders/golang/build_test.go
=> fix: dont fail if there is a .go directory

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go, internal/pipe/brew/template.go, internal/pipe/brew/testdata/binary_overridden.rb.golden, internal/pipe/brew/testdata/custom_block.rb.golden, internal/pipe/brew/testdata/custom_download_strategy.rb.golden, internal/pipe/brew/testdata/custom_require.rb.golden, internal/pipe/brew/testdata/default.rb.golden, internal/pipe/brew/testdata/default_gitlab.rb.golden, internal/pipe/brew/testdata/foo_is_bar.rb.golden, internal/pipe/brew/testdata/multiple_armv5.rb.golden, internal/pipe/brew/testdata/multiple_armv6.rb.golden, internal/pipe/brew/testdata/multiple_armv7.rb.golden, internal/pipe/brew/testdata/test.rb.golden, internal/pipe/brew/testdata/test_linux_only.rb.golden, www/docs/customization/homebrew.md
- rename some template fields 
- changing the ifs to avoid empty if statements
- adding `depends_on :linux` if only linux URLs
closes #1893
maybe helps with #1804
=> fix: improving URLs on linuxbrew

www/docs/cookbooks/debconf-templates.md, www/docs/customization/nfpm.md, www/mkdocs.yml
As promised [here](https://github.com/goreleaser/goreleaser/pull/1849#issuecomment-723122060) :smiley:.
I completed deb package in [our project](https://github.com/ethersphere/bee/pull/962) so I could wrap this up.
Change inside `www/docs/customization/nfpm.md` is to match [nfpm docs](https://goreleaser.com/customization/nfpm/).
=> add debconf-templates cookbook

internal/pipe/git/git.go, internal/pipe/git/git_test.go, internal/tmpl/tmpl.go, internal/tmpl/tmpl_test.go, pkg/context/context.go, www/docs/customization/templates.md
Add a `.Branch` field to the text templates populated by the current git
branch.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> feat: add support for git branch in templates

www/docs/customization/archive.md, www/docs/customization/blob.md, www/docs/customization/build.md, www/docs/customization/checksum.md, www/docs/customization/docker.md, www/docs/customization/homebrew.md, www/docs/customization/hooks.md, www/docs/customization/milestone.md, www/docs/customization/nfpm.md, www/docs/customization/publishers.md, www/docs/customization/release.md, www/docs/customization/snapcraft.md, www/docs/customization/snapshots.md, www/docs/customization/source.md, www/docs/customization/upload.md, www/docs/limitations/semver.md
I suspect this is something about the mkdocs template, but I'm not familiar enough, and this is easy.
Explanation:
Following any of these links, the resulting page reads just fine, but the navigation sidebar is lacking part of the expected path, resulting in links that are invalid.
If applied, this commit will fix some internal links, which appear to work, but result in a navigation sidebar with incorrect links.
This change is being made because I couldn't (fairly quickly) figure out where else an appropriate change might be made -- in the mkdocs config or in an upstream project.
=> docs: fixing internal links that result in a broken navigation sidebar

internal/client/client_test.go, internal/client/gitea.go, internal/client/gitea_test.go, internal/pipe/defaults/defaults.go, internal/pipe/defaults/defaults_test.go, pkg/config/config.go, www/docs/environment.md
implement for brew and scoop support for Gitea-hosted repos
=> feat:  Gitea client add create file function

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go
Closes #1916. The problem was that the default Dockerfile name isn't taken into account if there are several lines in the matrix.
Thanks for this great project.
=> fix: prevent error if "dockerfile" isn't set

internal/pipe/changelog/changelog.go
This will trim any superfluous newlines from the Changelog. In particular, if you don't have a `ReleaseHeader` set, the file will not start with two empty new-lines, but instead directly begin with `## Changelog`.
=> fix: don't append empty header/footer to changelog

internal/pipe/changelog/changelog.go, internal/pipe/changelog/changelog_test.go
This ensures the Changelog ends with a trailing newline, regardless of a footer being set.
Also added tests to verify this behavior.
=> fix: ensure Changelog ends on a newline

.goreleaser.yml, internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go, internal/pipe/brew/template.go, internal/pipe/brew/testdata/custom_block.rb.golden, internal/pipe/brew/testdata/custom_download_strategy.rb.golden, internal/pipe/brew/testdata/custom_require.rb.golden, internal/pipe/brew/testdata/default.rb.golden, internal/pipe/brew/testdata/default_gitlab.rb.golden, internal/pipe/brew/testdata/multiple_armv5.rb.golden, internal/pipe/brew/testdata/multiple_armv6.rb.golden, internal/pipe/brew/testdata/multiple_armv7.rb.golden, internal/pipe/brew/testdata/test.rb.golden, pkg/config/config.go, www/docs/customization/homebrew.md
This PR resolves the issues described in #1908. I want to split this into two commits:
1. Add the license field (optional). If no SPDX license identifier is set, the field won't be present in the generated Formula.
2. Get rid of the whitespaces in otherwise empty lines.
Figuring the first one out was easy but I kinda struggle with the whitespaces. Really never thought that was the hard part... but gotemplates 🤦
=> feat: make generated brew formulas `brew audit` compatible (#1908)

cmd/root.go
While investigating https://github.com/spf13/cobra/issues/1279, I noticed that turning off descriptions does not currently work for goreleaser.  And that this could impact bash completion if `ValidArgsFunction` is to eventually be used.
The `__completeNoDesc` command is used by bash to request completion without any descriptions.  It is an alias for the `__complete` command. It must be properly supported for `cobra.Command.ValidArgsFunction` to work with bash completion.
You can test this change by turning off descriptions for Fish completion at this line by changing `true` to `false`:
https://github.com/goreleaser/goreleaser/blob/c0119436136826241bb1a926a65d526f9ae417ce/cmd/completion.go#L57
Then without this PR, fish completion will be broken.
This test is representative because `bash` …
=> Support __completeNoDesc hidden command

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go
Currently the following command will fail:
```
goreleaser release --snapshot --rm-dist --skip-sign
⨯ release failed after 4.74s error=nfpm failed: signing error: armored detach sign: reading PGP key file: open /tmp/key.gpg: no such file or directory
```
If I do not want to sign the packages with the `--skip-sign` flag (just want to build the rpm,debs etc...)  the command should not fail when there is no signing key available.
I am not sure if the fix is in the correct place :man_shrugging: Maybe there is a better way to do it.
=> fix: nfpm signing error with `--skip-sign` when gpg key is not found

cmd/testdata/good.yml, internal/static/config.go, www/docs/customization/archive.md, www/docs/customization/build.md, www/docs/customization/docker_manifest.md, www/docs/customization/env.md, www/docs/customization/sign.md, www/docs/deprecations.md, www/docs/quick-start.md
Since multiple filenames for the config file are allowed, we find several different usages of the file names in the docs:
- .goreleaser.yml
- goreleaser.yml
- .goreleaser.yaml
- goreleaser.yaml
I find that using a single filename in the docs is more intuitive for new users. Hence I replaced all occurrences of the filename with `.goreleaser.yml`.
Feel free to request changes for individual occurrences of the file name.
=> docs: unify naming of .goreleaser.yml file

.github/workflows/build.yml, cmd/build.go, cmd/build_test.go, cmd/release.go, cmd/release_test.go, internal/git/git.go, internal/git/git_test.go, internal/pipe/git/errors.go, internal/pipe/git/git.go, internal/pipe/git/git_test.go, www/docs/customization/snapshots.md
Introduce a new flag for build/release commands called `--snapshot-auto`. This new flag will detect if Git is in dirty state and create a snapshot if so. Footprint in the project is pretty minimal to avoid unattended regressions for the current implementation of snapshot.
The purpose of this new flag is for CI and automation to avoid specific conditions like:
https://github.com/goreleaser/goreleaser/blob/9423da1b607b26916664cb26016811b54359e46c/.github/workflows/build.yml#L85-L89
I am open to any suggestion or alternative proposal.
Could also partially fix #1324 (see the comment https://github.com/goreleaser/goreleaser/issues/1324#issuecomment-634189064)
=> feat: allow automatic snapshot on dirty state

.github/workflows/build.yml, cmd/build.go, cmd/build_test.go, cmd/release.go, cmd/release_test.go, internal/git/git.go, internal/git/git_test.go, internal/pipe/git/errors.go, internal/pipe/git/git.go, internal/pipe/git/git_test.go, www/docs/customization/snapshots.md
Reverts goreleaser/goreleaser#1958. Needs to be handled in git pipe, we don't have enough context in cmd.
=> Revert "feat: allow automatic snapshot on dirty state"

www/docs/customization/release.md
Adds a link to changie an alternative changelog generator.
Changie uses goreleaser for releases so it is, at least a little, tested.
Not sure if anything else was needed for doc changes.
=> docs: add changie to changelog generators

.goreleaser.yml
- we don't need the `latest-$arch` imgs as it handled by the manifest
- the v0.X imgs are never used anyway, removing
We'll now only have `latest` and `v0.x.y` images.
=> feat: simplify docker images

internal/builders/golang/build_test.go, internal/pipe/archive/archive_test.go, internal/pipe/brew/brew_test.go, internal/pipe/checksums/checksums_test.go, internal/pipe/docker/docker_test.go, internal/pipe/env/env_test.go, internal/pipe/sign/sign_test.go, internal/tmpl/tmpl_test.go
very error-prone, as we can see in some tests, we were using `t` instead of `tt` later on, making the `go test` output be wrong, basically.
=> refactor: use t instead of tt

internal/http/http.go, internal/http/http_test.go, pkg/config/config.go, www/docs/customization/upload.md
This commit will add an additional field to elements under `uploads:`, allowing the user to specify custom headers for the `PUT` (or other mode) request.
GitLab has a Generic Packages Repository which allows uploads using various auth methods, one being the CI job token. However, it must be specified not as basic authentication but rather as a custom header, namely `JOB-TOKEN: $CI_JOB_TOKEN`. This change supports specifying that header as well as any other headers required by various upload destinations.
See also: https://docs.gitlab.com/ee/user/packages/generic_packages/index.html#publish-a-generic-package-by-using-cicd
=> feat(http): support custom headers in http upload

internal/http/http.go, internal/http/http_test.go, www/docs/customization/upload.md
If applied, this commit will allow the user to employ template expressions in the values of `uploads.custom_headers` map values, e.g.:
```yaml
uploads:
- name: gitlab
mode: binary
target: "{{ .Env.CI_API_V4_URL }}/projects/{{ .Env.CI_PROJECT_ID }}/packages/generic/{{ .ProjectName }}/{{ .Version }}/"
username: gitlab-ci-token
method: PUT
custom_headers:
JOB-TOKEN: "{{ .Env.CI_JOB_TOKEN }}"
PRIVATE-TOKEN: "{{ .Env.GITLAB_TOKEN }}"
```
Prior to this change, only literal expressions were supported, and so my docs example in #2002 was actually not functioning.
=> feat(http): resolve custom header template expressions

internal/builders/golang/targets.go, internal/builders/golang/targets_test.go
=> feat: compile to riscv64

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go, internal/pipe/defaults/defaults_test.go
This was a long time TODO that should probably be removed anyway.
In the specific case of using templates in the `builds.binary` field, even if we evaluate it at defaults time, the formula wouldn't work when using multiple platforms, so it would have to be customized anyway.
This simplifies things by removing one complicated, probably wrong default (hence the warning) in favor of a simple probably wrong default (which will still have the warning).
All things considered I think this should be ok.
closes https://github.com/goreleaser/goreleaser/issues/2029
see #2021
see #1936
=> fix: brew default install when using templates in the binary name

internal/pipe/snapcraft/snapcraft.go
As per deprecation message from snapcraft [here](https://github.com/achannarasappa/ticker/runs/1859510333?check_suite_focus=true#step:7:150), the `push` command has been replaced by the `upload` command.
=> fix: update snapcraft command from 'push' to 'upload'

internal/pipe/brew/template.go, internal/pipe/brew/testdata/custom_block.rb.golden, internal/pipe/brew/testdata/custom_download_strategy.rb.golden, internal/pipe/brew/testdata/custom_require.rb.golden, internal/pipe/brew/testdata/default.rb.golden, internal/pipe/brew/testdata/default_gitlab.rb.golden, internal/pipe/brew/testdata/foo_is_bar.rb.golden, internal/pipe/brew/testdata/multiple_armv5.rb.golden, internal/pipe/brew/testdata/multiple_armv6.rb.golden, internal/pipe/brew/testdata/multiple_armv7.rb.golden, internal/pipe/brew/testdata/test.rb.golden
since now there are both amd64 and arm64 downloads for macs, I think its better to guard the amd64 download with a "if intel" check...
=> fix: brew: check cpu

www/docs/cookbooks/blog-posts.md
Added reference to a blog post that explains how to publish deb/rpm packages with Fury.io
It enables goreleaser users to push deb/rpm packages built with goreleaser to be automatically published via publicly-reachable yum/apt repository which Fury provides for free.
=> docs: added ref to a blog post explaining how to publish deb/rpm packages to apt/yum repos

.goreleaser.yml
See - [Sunset on May 1st: Bintray, JCenter, GoCenter, and ChartCenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).
=> chore(ci): stop using gocenter.io

internal/testlib/git.go
some users might setup `git` locally to default to main, which would cause the tests to fail...
this pr sets the branch to git init so it works regardless of user config.
=> test: use main as git branch for tests

internal/deprecate/deprecate.go, internal/deprecate/deprecate_test.go, internal/deprecate/testdata/output.txt.golden, internal/deprecate/testdata/output_custom.txt.golden, internal/pipe/semver/semver.go, internal/pipe/semver/semver_test.go, www/docs/deprecations.md
closes #2081
make skipping semver checks deprecated, so we can remove those ifs soon.
=> fix: log semver errors when snapshot

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go
This commit will let windows users to validate nfpm configuration successfully
When validating nfpm configuration windows paths separators ("\\\\") were removed by goreleaser/fileglob. info.Contents source and destination were modified using filepath.ToSlash(). This changes does not impact non-windows users.
Related issue: https://github.com/goreleaser/goreleaser/issues/2068
Edit: other packages tests still fail but they are related to os-specific behaviors, internal/pipe/nfpm now succeeds.
=> fix: nfpm config validation

www/docs/customization/scoop.md
Scoop supports `skip_upload`, just like Brew, but it was missing in the docs.
=> docs: Add info on skip_upload to scoop 

internal/pipe/snapcraft/snapcraft.go, internal/pipe/snapcraft/snapcraft_test.go, pkg/config/config.go, www/docs/customization/snapcraft.md
**If applied, this commit will...**
Goreleaser will support snapcraft layout.
bind to #2106 
I am a goreleaser user.
I use goreleaser to build my own application: [meepo](https://github.com/PeerXu/meepo).
When try to build snap with strict confinement, service can not read configure files in isolated environment.
I figure out how to solve the problem, it should be use `layout`, for mapping files to sandbox.
But goreleaser not support snapcraft layout now, so I want it support the feature.
**# Provide links to any relevant tickets, URLs or other resources**
[Use layout](https://snapcraft.io/docs/snap-layouts)
=> feat: support snapcraft layout

internal/tmpl/tmpl.go, internal/tmpl/tmpl_test.go, www/docs/customization/templates.md
This allows templates to trim prefixes. Particularly useful for removing the v prefix from versions.
`.Version` for a release has the v prefix stripped. I would expect the same for the snapshot. From https://goreleaser.com/customization/templates/:
> the version being released (v prefix stripped),
> or {{ .Tag }}-SNAPSHOT-{{ .ShortCommit }} in case of snapshot release
At present, any other templates where I use `.Version` but need to re-add the v prefix (because it might be relevant in a URL for example) ends up having a double prefix e.g. `vv0.5.4-SNAPSHOT-0b768c4`.
`trimprefix` would be useful in this case so that users can trim prefixes in their custom templates.
See the discussion for some context: [should tag in snapshot's default .Version have a v prefix …
=> Add trimprefix function to template package

www/docs/ci/gitlab.md
Docker-in-Docker is overkill for simple binary and archive release purposes and the more verbose configuration for it is intimidating for it to be the only example of using GoReleaser in GitLab CI.
This commit adds an example `.gitlab-ci.yml` and some additional explanation on the general GitLab CI process, as I stumbled onto some quirks that were hard to find documentation on while implementing GoReleaser into my own CI pipeline.
=> docs: expand GitLab CI examples

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go
docker manifests exepcted to be pushed on draft.
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>
=> fix: docker manifest on draft release

internal/builders/golang/build.go, internal/pipe/build/build_test.go, www/docs/customization/build.md
default to hardfloat, as in `go build`.
an empty gomips was causing goreleaser to fail validation as well.
closes https://github.com/goreleaser/goreleaser/discussions/2105
=> fix: default gomips

internal/pipe/docker/docker_test.go, internal/pipe/docker/manifest.go, internal/pipe/docker/testdata/Dockerfile.dummy
- the problem seems to be the `--amend` flag, so, remove it
- without the amend, it might fail if the manifest already existed locally, so, remove it first
TODO:
closes https://github.com/goreleaser/goreleaser/issues/2127
=> fix: wrong docker manifest on latest

go.mod, go.sum
Gitlab.com has some changed (bug?) recently that returns 500 internal server error if the filename contains "/".
Update go-gitlab dependency to get the workaround from upstream: https://github.com/xanzy/go-gitlab/pull/1113.
> If applied, this commit will...
Fix the uploading error for Gitlab.com.
> Why is this change being made?
To update go-gitlab dependency to get the workaround from upstream.
> Provide links to any relevant tickets, URLs or other resources
* https://github.com/xanzy/go-gitlab/pull/1113
=> fix: update go-gitlab to fix upload file issue

internal/pipe/artifactory/artifactory.go, internal/pipe/artifactory/artifactory_test.go
=> fix: artifactory checksum header

internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go
Fixes #2171, see issue for details.
=> fix: ignore non-arm64/386 builds when building Scoop manifest

internal/pipe/gomod/gomod.go, internal/pipe/gomod/gomod_test.go, www/docs/customization/build.md, www/docs/customization/gomod.md
refs https://github.com/go-task/task/pull/462#issuecomment-821886239
having `build.main` point to a `main.go` file, for example, instead of package would break things. 
trying to guess the package by removing the last element of the path if it ends with `.go`, also throwing a warning when that happens.
=> fix: handle build.main being a go file when using gomod.proxy

internal/client/github.go
If the discussion category name is not specified in the config file, do not send it in to the request
This is a quick fix, and possibly it would be better to make `DiscussionCategoryName` a pointer.
Fixes #2181
=> Do not send an empty discussion category name

cmd/build.go, cmd/build_test.go
a rather simple way to implement a "single target build" approach.
- `goreleaser build --single-target`: builds only `runtime`'s `GOOS`/`GOARCH`
- `GOOS=linux GOARCH=darwin goreleaser build --single-target`: builds for specified `GOOS`/`GOARCH` environment variables
- `goreleaser build --single-target --id foo`: builds only `runtime`'s `GOOS`/`GOARCH` and build id `foo`
Cool things about this:
- no need to mess with anything but the command line
- known interface (GOOS/GOARCH envs)
Notes:
- if `--id` is passed but we have either 0 (default config) or 1 build configs, it is ignored (but warns)
What do you think?
--
closes https://github.com/goreleaser/goreleaser/pull/1987
closes https://github.com/goreleaser/goreleaser/issues/1852
closes https://github.com/goreleaser/goreleaser/pull/2032
=> feat: build single target and/or build id

www/docs/ci/actions.md
This is to encourage use of reduced scope of the token by taking advantage of recently announced changes: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
=> docs: document required GitHub Actions token privileges

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go
This fixes an issues that causes builds to still try to release to brew
even though the `--skip-publish` flag was passed
=> fix: skip releasing to brew when skipping publishing

www/docs/customization/docker.md
Fixes typo in docker tags section
Fix typos in the docs.
Cleaning up syntax/phrasing that was used in the docker tags section of the docs.
=> docs: fixed typo

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go
I was trying to create two formulas per release. One signifying the latest and
another with the version explicitly: formula.rb and formula@v0.0.0.rb
The filenames are fine but the formula name for the explicit version
was created as FormulaATv0.0.0 which isn't valid Ruby.
Looking at the function history I couldn't find why underscores were being replaced
since underscores are valid for Ruby identifiers. I opted to replace dots in a formula with
underscores
- https://github.com/goreleaser/goreleaser/commit/1399a396036ea246522a4cbae7aef376d6dbbda2
- https://ruby-doc.org/docs/ruby-doc-bundle/Manual/man-1.4/syntax.html#ident
=> fix: allow underscores in formula name

www/docs/customization/nfpm.md
field `name_template` not found in type config.NFPMOverridables, but it's `file_name_template` found.
=> docs: fix config field

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go, internal/pipe/nfpm/testdata/testfile-386.txt, internal/pipe/nfpm/testdata/testfile-amd64.txt, www/docs/customization/nfpm.md
Hi,
this will fix #1637. It adds support for name templates in NFPM content declarations.
E.g.:
```
nfpms:
- id: publish
...
bindir: /usr/bin
formats:
- deb
- rpm
contents:
- src: bin/foo-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}/*
dst: /usr/bin/foo/
```
=> feat: add support for name templates to NFPM contents

.github/workflows/build.yml
Use the official [docker/login-action](https://github.com/docker/login-action) to login against [Docker Hub](https://github.com/docker/login-action#docker-hub) and [GHCR](https://github.com/docker/login-action#github-container-registry).
[Container registry now supports GITHUB_TOKEN](https://github.blog/changelog/2021-03-24-packages-container-registry-now-supports-github_token/) so no need to use a PAT anymore :)
You may need to manage write and read access of GitHub Actions for repositories in the container settings:
=> fix(ci): use official login action and switch to github secret for ghcr

internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go
This change makes the scoop pipe write out the manifest before the skip conditions.
By writing the manifest before the skip section of the pipe, you can do dry runs of the scoop pipeline. This is how the brew pipe does it.
Example behavior before change:
```
...
• homebrew tap formula
• writing                   formula=dist/app.rb
• pipe skipped              error=brew.skip_upload is set
• scoop manifests  
• pipe skipped              error=scoop.skip_upload is true
...
```
After
``` 
...
• homebrew tap formula
• writing                   formula=dist/app.rb
• pipe skipped              error=brew.skip_upload is set
• scoop manifests  
• writing                   manifest=app.json
• pipe skipped              error=scoop.skip_upload is true
...
```
=> feat: Scoop pipe - Write the manifest before skips, like Brew pipe.

cmd/release.go, cmd/release_test.go, internal/pipe/pipe.go, internal/pipe/twitter/twitter.go, internal/pipe/twitter/twitter_test.go, pkg/context/context.go, www/docs/cmd/goreleaser_release.md
adds --skip-announce flag and also skips announcing on --skip-publish and --snapshot
refs #2248
=> feat: --skip-announce

.goreleaser.yml
- go should be optional, as it can be installed in other ways
- git is actually required
=> fix(ci): brew dependencies

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go, www/docs/customization/nfpm.md, www/docs/deprecations.md
allow to template contents.dst
should make the [goreleaser pro includes feature](https://goreleaser.com/customization/includes/) even better, e.g. https://raw.githubusercontent.com/caarlos0/.goreleaserfiles/main/package_with_completions.yml , but will probably also be useful for other usecases.
=> feat(nfpm): allow to template contents.dst

internal/pipe/release/body.go, internal/pipe/release/body_test.go, internal/pipe/release/testdata/TestDescribeBody.golden, internal/pipe/release/testdata/TestDescribeBodyWithDockerManifest.golden, internal/pipe/release/testdata/TestDescribeBodyWithHeaderAndFooter.golden
I was thinking... does it makes sense to add the `:latest` docker images to the release notes? After all, **it will be wrong** eventually anyway...
I'm thinking... maybe its better if we just don't print those imgs there?
wdyt?
=> feat: remove :latest imgs from release notes

internal/builders/golang/build.go, internal/builders/golang/build_test.go
`-ldflags` and `-tags` are not repeatable, so mentioning them again with a zero value actually sets them to 0.
This should fix it
closes #2300
refs #2268 
refs #2262
=> fix:  empty build.tags and build.ldflags

.goreleaser.yml, cmd/root.go, internal/pipe/docker/api.go, internal/pipe/docker/api_docker.go, internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, internal/pipe/docker/manifest.go, pkg/config/config.go, www/docs/customization/docker.md, www/docs/deprecations.md
refs #1902
started to extract an api for the docker and docker_manifest pipes, for now with only their current docker implementations.
this will evolve to support `podman` and maybe `buildah` as well.
=> refactor: preparing for other docker implementations

internal/pipe/docker/api.go, internal/pipe/docker/api_docker.go, internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, internal/pipe/docker/manifest.go, internal/pipe/docker/testdata/Dockerfile.arch, pkg/config/config.go
some needed refactories to support multiple docker/manifests backend implementations (which will land on [goreleaser pro](https://goreleaser.com/pro) first)
=> refactor(docker): preparing for multiple backends

internal/pipe/release/body.go, internal/pipe/release/body_test.go, internal/pipe/release/testdata/TestDescribeBodyWithHeaderAndFooter.golden
A continuation of #2267 - the header and footer in release configuration
can be templated as well to support more use cases like attaching
published docker image information(without using docker pipe).
=> pipe/release: template header and footer

internal/client/gitlab.go
This commit fixes releases on gitlab.com.
Currently, new releases are not working, because the API returns `404` for non-existing releases, which causes goreleaser to throw an error and fail.
See also #2334 for more info.
Let me know what you think, thanks a lot!
=> fix: new gitlab releases throwing 404 due to API change #2334

scripts/get-releases.sh
got an email from vercel saying we used all our quota this month (actually, 3x more).
My bet is the releases json file, which is kinda big:
```sh
❯ du -hs *.json
492K	releases-pro.json
12M	releases.json
```
It has all the releases content, but we just use the `tag_name` on our action cc/ @crazy-max 
Changed a bit, and now:
```sh
❯ du -hs www/docs/static/*.json
4.0K    www/docs/static/releases-pro.json
12K    www/docs/static/releases.json
```
will merge this asap to prevent being blocked... please let me know if this breaks anything I'm not expecting.
=> feat: smaller releases.json

cmd/init.go, cmd/init_test.go
If applied, this commit will inject an extra leading newline when patching `.gitignore`, so that it works properly on existing `.gitignore` files that do not have trailing newlines (#2349)
Per #2349, the current way breaks `.gitignore` files without a trailing newline.
closes #2349
=> fix: gitignore patching needs leading newline (#2349)

internal/pipe/snapcraft/snapcraft.go, internal/pipe/snapcraft/snapcraft_test.go, pkg/config/config.go, www/docs/customization/snapcraft.md
By default, snap store manage "edge", "beta", "candidate" and "stable".
Default to all this channels when package is in grade stable. But only on
"edge" and "beta" for grade "devel".
This fix this TODO: https://github.com/goreleaser/goreleaser/blob/bf19dc1079887d31e58065771bb069953b1704d6/internal/pipe/snapcraft/snapcraft.go#L342
=> feat(snapcraft): manage channel upload

.goreleaser.yml, cmd/testdata/good.yml, internal/pipe/git/git.go, internal/pipe/snapshot/snapshot.go, internal/pipe/snapshot/snapshot_test.go, internal/static/config.go, internal/tmpl/tmpl.go, internal/tmpl/tmpl_test.go, www/docs/customization/snapshots.md, www/docs/customization/templates.md
revives https://github.com/goreleaser/goreleaser/pull/1457 adding some new template functions:
- incpatch
- incminor
- incmajor
and change the `goreleaser init`  generated config snapshot name to `{{ incpatch .Tag }}-next`
refs https://github.com/goreleaser/goreleaser/issues/2355
=> feat: inc parts of semver, change snapshot default name

internal/gio/copy.go, internal/gio/copy_test.go, internal/gio/hash.go, internal/gio/testdata/somefile.txt, internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, internal/pipe/snapcraft/snapcraft.go, internal/pipe/snapcraft/snapcraft_test.go
since we are now copying instead of hard-linking the files on the snapcraft pipe, let's do the same for the docker pipe.
This also means we can deduplicate some code!
refs #2358
=> fix: copying file on docker pkg instead of hard linking

internal/builders/golang/build.go, internal/exec/exec.go, internal/exec/exec_test.go, internal/pipe/docker/api.go, internal/pipe/docker/api_docker.go, internal/pipe/sign/sign.go, internal/pipe/snapcraft/snapcraft.go
improved output when a `exec.Command` fails, adding its output to the error
=> fix: return an err with stdout/err when a command failed

internal/pipe/git/git.go, internal/pipe/git/git_test.go
When the `HEAD` commit has multiple tags, they are sorted in order to select the latest so that it can be released. However, the existing sort would not work if there were multiple commits across a Wednesday and a Thursday.
For example, here is our commit with multiple tags. Printing out the `creatordate` and `refname` to demonstrate the issue.
```
git tag --points-at HEAD --format='%(creatordate)%09%(refname)'
Wed Jul 28 07:13:19 2021 +0000  refs/tags/v0.0.183
Thu Jul 29 13:31:07 2021 +0000  refs/tags/v0.0.184
Thu Jul 29 13:38:42 2021 +0000  refs/tags/v0.0.185
Thu Jul 29 13:57:44 2021 +0000  refs/tags/v0.0.186
```
When using the existing sort the `creatordate` field was targeted and reversed. Alphabetically Thursday comes before Wednesday, so that is reversed and the Wednesday release …
=> fix: sort tags by version not day of the week

internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go
Don't skip the pipeline altogether but write
out the manifest.json file as the homebrew
pipeline does, only skip committing to the repo.
closes #2374
=> fix: make scoop write .json when --skip-publish

internal/builders/golang/build.go, internal/builders/golang/build_test.go, internal/pipe/gomod/gomod.go, internal/pipe/gomod/gomod_test.go, pkg/config/config.go
we can't check for the `main` function in the actual proxied module, but we can at least check the code which, in theory, is the module being proxied.
this should avoid bad releases as I did for fork-cleaner, which was basically empty.
What happens now is that the `gomod` pipe overrides `Main` and `Dir` as before, but set the original values to `UnproxiedMain` and `UnproxiedDir`, and then the `build` pipe checks the main on the unproxied properties when they exist.
=> fix: main check when using gomod.proxy 

internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, pkg/config/config.go, www/docs/deprecations.md
removed some deprecated options from the `dockers` config
=> feat: remove deprecated docker options

internal/exec/exec.go, internal/exec/exec_test.go, internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, internal/pipe/docker/manifest.go, pkg/config/config.go, www/docs/customization/docker.md, www/docs/customization/docker_manifest.md
=> feat: add id to dockers and docker_manifests

internal/builders/golang/build.go, internal/builders/golang/targets.go, internal/builders/golang/targets_test.go, www/docs/deprecations.md
closes #2404
closes #2405
simpler alternative to impl made in #2405. We will eventually remove those, so no need to go all fancy
=> feat: support windows/arm64

internal/builders/golang/build.go, internal/builders/golang/build_test.go, internal/builders/golang/targets.go, internal/pipe/build/build_test.go
Currently, the `goVersion` function is run without any directory set. This is problematic when a build uses the `dir` config in combination with the `gobinary` config. When `gobinary` is a relative path (like a script in the current repository), goVersion silently fails, returning an empty string.
This commit refactors `goVersion` to execute the command with `Dir` set to the `build.Dir`, in addition to now returning an error, so that issues may be bubbled up in the build log, rather than silently failing.
It also adds a new helper function to facilitate running `goVersion` by creating a temporary executable that outputs a given `version` string. This function is only currently used by `TestWithDefaults`.
=> fix: Run 'go version' command in build.Dir

.goreleaser.yml, cmd/testdata/good.yml, internal/pipe/snapshot/snapshot.go, internal/pipe/snapshot/snapshot_test.go, internal/static/config.go, www/docs/customization/snapshots.md, www/docs/customization/templates.md
This commit will change the default- and the init-template that is used for `snapshot.name_template`. If applied, this commit will prevent situations as described in #2415 for new projects and projects that don't overwrite `snapshot.name_template`.
The change is necessary to remove an odity:
In regular mode, `.Version` removes the `v` from the most recent git tag (e.g. `v1.2.3` becomes `1.2.3`). In snapshot mode however, what is defined as `snapshot.name_template` becomes the value of `.Version`. And before this commit `snapshot.name_template` is defined as a value that does not remove the `v` prefix.
This did lead to the following odd situation, given the most recent git tag is `v1.2.3`:
```
Regular Mode:  .Version =                            '1.2.3'
Snapshot Mode: .Version = …
```
=> fix: Change the init- and default-template for `snapshot.name_template`

internal/builders/golang/build_test.go, internal/builders/golang/targets.go
if the `build.dir` doesn't exist, ignore it while checking the go version.
IMHO, its unlikely that the before hook of a build will create a folder and set a go wrapper in there... 
For now I think we can just ignore the dir if we fail to stat it.
cc/ @jorng  
closes #2434
=> fix: build dir that dont exist yet

pkg/archive/targz/targz.go, pkg/archive/targz/targz_test.go, pkg/archive/tarxz/tarxz.go, pkg/archive/tarxz/tarxz_test.go, pkg/archive/testdata/link.txt, pkg/archive/zip/zip.go, pkg/archive/zip/zip_test.go
closes #2430
support symlinks inside tar.gz, tar.xz and zip files.
probably not perfect, but good enough for now.
=> feat: support links inside archives

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go, www/docs/customization/nfpm.md
=> feat: templateable nfpm key files

internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go, internal/pipe/scoop/scoop.go, pkg/config/config.go, www/docs/customization/homebrew.md
=> feat: allow to template brew message

internal/pipe/git/git.go, internal/pipe/git/git_test.go
Fix #2456 
to avid showing user information in the message template if someone uses the {{ .GitURL }} within these templates.
=> fix: clean user information from remote url if it contains username and token

internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go, www/docs/customization/nfpm.md
In NFPM configuration, allow the `Bindir` to also be templated.
I'm creating a _nagios plugin_ . Those are deployed in the `/usr/lib/nagios/plugins` directory on `i386` arch. And in `/usr/lib64/nagios/plugins` on `amd64` arch.
I wasn't able to achieve such behavior with RPM generation without this patch.
With this patch applied, one can use the following configuation:
```yaml
nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
[...]
bindir: '/usr/lib{{ if ne .Arch "386" }}64{{ end }}/nagios/plugins'
[...]
```
closes #2460
=> feat: Add support for templating NFPM bindir 

internal/client/gitea.go, internal/client/gitea_test.go, internal/client/github.go, internal/client/github_test.go, internal/client/gitlab.go, internal/client/gitlab_test.go, internal/pipe/defaults/defaults.go, internal/pipe/defaults/defaults_test.go, www/docs/scm/gitea.md, www/docs/scm/github.md, www/docs/scm/gitlab.md
Thank you for this really well polished project and the hard work put into it 🙌 
Background
---
When a git repository is hosted in multiple GitLab instances the
`.goreleaser.yml` needs to take in consideration both APIs endpoints. At
the moment it defaults to GitLab.com and you can override it with
`gitlab_urls` however this forces you to only support 1 GitLab instance.
We need this for
https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/14122
where we have a tool that is developed on GitLab.com but then mirrored
to an internal GitLab instance since we need it to operate GitLab.com
even when it's down.
Solution
---
Support templates like `{{ .Env.CI_SERVER_URL }}` for the
`gitlab_urls`, `github_urls`  and `gitea_urls` so it can use environment
variables and the same …
=> feat: support templates for scm urls

internal/client/gitlab.go, internal/client/gitlab_test.go
Background
---
In 5bcfa9042d0efd419b660a3b63c815a13d919e30 the condition was changed to
that it can support the new status code returned by GitLab. However, the
condition is now checked `resp != nil` and not `resp == nil` which causes
the condition not to trigger when the resp is nil and only returns an
error. We can reproduce this issue by running
`TestGitLabCreateReleaseUknownHost` test added in this commit.
Solution
---
If we look at other error handling
https://github.com/goreleaser/goreleaser/blob/91a8abb2e6c5915d93866cb19be6b67db4a193f4/internal/client/gitlab.go#L106
we can see that we check if the `resp` is nil as well before continuing.
Added tests for the following use cases:
- When there is an error and no response was returned.
- When there is a 403 or 404 error so we expect to …
=> fix: panic on gitlab create release

internal/pipe/docker/api_buildpack.go, internal/pipe/docker/api_buildpack_test.go, internal/pipe/docker/api_docker.go, internal/pipe/docker/docker.go, internal/pipe/docker/docker_test.go, www/docs/customization/docker.md
Greetings.
We (w/@developer-guy and @Dentrax ) are trying to add **buildpacks** support to **goreleaser**. With this feature, users won't have to use a Dockerfile to build and publish an image.
This gives us `Dockerfile`less usage of goreleaser. This PR fixes #2450 
- [Buildpacks](https://buildpacks.io/)
- [GCR Builder](https://github.com/GoogleCloudPlatform/buildpacks)
Notes:
- Buildpacks has several builder options but maybe we can use `gcr.io/buildpacks/builder:v1` if not any builder specified.
Todo
=> feat(docker): add buildpacks support

internal/builders/buildtarget/targets.go, internal/builders/buildtarget/targets_test.go, internal/builders/golang/build.go, internal/builders/golang/build_test.go, internal/pipe/build/build.go, internal/pipe/build/build_test.go, internal/tmpl/tmpl.go, pkg/build/build.go, pkg/config/config.go
prepare the build api for future features:
- move matrix gen to another pkg
- merge target stuff with build opts
- renamed `builds.lang` to `builds.builder`
=> refactor: improve build

www/docs/customization/docker_sign.md
this is a small doc fix to update the documentation and use the  `COSIGN_PWD` instead of `GPG_PASSWORD` since it defaults to use `cosign`
=> docs: fix environment variable to be COSIGN_PWD

.github/workflows/build.yml
update cosign installer action to 1.2.0
Please hold until this is merged and we make a release: https://github.com/sigstore/cosign-installer/pull/25
/assing @caarlos0
=> update cosign installer action to 1.2.0

go.mod, go.sum, internal/pipe/announce/announce.go, internal/pipe/smtp/smtp.go, pkg/config/config.go, pkg/defaults/defaults.go, www/docs/customization/announce.md
fix #2479 
to add SMTP support to the announces
https://www.loginradius.com/blog/async/sending-emails-with-golang/
=> feat: add SMTP support to the announces

Dockerfile
sometimes releasing may take a while. when running it in docker `Ctrl-C` is not passed properly to the goreleaser process.
[why tini](https://github.com/krallin/tini/issues/8)
=> feat(docker): install tini to handle Ctrl+C

internal/client/client.go, internal/client/client_test.go, internal/pipe/brew/brew.go, internal/pipe/env/env.go, internal/pipe/env/env_test.go
fixes  #2514
not really sure why it happens on some projects and not in others... but anyway, this should fix it...
the problem is that it might not have the `token type` set when running, which then was returning a nil client... this will now error and also always default to github token type if none was provided.
also some refactory to reuse some code on the client instantiation.
=> fix: brew/scoop panic

internal/pipe/defaults/defaults.go
our defaults have many side effects... one example being the project name is inferred from the release config... 
until v0.179.0, the defaults ran anyway, but on 0.180 they wont in some cases, which may lead to errors.
until we figure this out, lets remove the conditional skipping from the defaults
closes #2520
=> fix: do not skip any defaults

internal/git/config.go, internal/git/config_test.go
This PR will fix parsing of the git URL format that is used by gitlab-ci runners, for example:
```
https://gitlab-ci-token:SOME_TOKEN@gitlab.yourcompany.com/goreleaser/goreleaser.git
```
The URL style above works correctly in v0.179.0, but not v0.180.0, I believe because of the following PR:
https://github.com/goreleaser/goreleaser/pull/2474/files
Thanks, for the consideration, and for the awesome project in general!
=> fix: bug in handling gitlab-ci style urls

internal/client/github.go
=> fix: regression on nil pointer check

www/docs/scm/gitlab.md
The url for the gitlab's CI integration seems to be outdated.
=> docs: Fix invalid personal access token URL

www/htmltest.yml, www/mkdocs.yml
Added the md file from mattermost announce feat (#253) to the website data.
FYI: @cpanato
=> fix: docs: Missing mattermost docs on website

internal/client/client.go, internal/pipe/brew/brew.go, internal/pipe/brew/brew_test.go, internal/pipe/gofish/gofish.go, internal/pipe/gofish/gofish_test.go, internal/pipe/scoop/scoop.go, internal/pipe/scoop/scoop_test.go
there's no client impl returning that error anymore, so we might as well remove it and the checks for it.
=> refactor: remove unused not impl error

internal/pipe/brew/brew.go
This is a minor fix to add support for templates in the Homebrew tap owner field.
Our use case for this was to get the owner field from environment variables
=> feat: add template support for homebrew tap owner

.github/workflows/build.yml, CONTRIBUTING.md, Taskfile.yml
As discussed in private, this PR is a proposal to replace the Makefile with Task: https://taskfile.dev/
- Added a `Taskfile.yml`
- Changed CI to use it instead of Make
- Updated CONTRIBUTING documentation
I didn't delete the Makefile yet because some contributors may be used to it. It's your choice to delete it some day or not.
```bash
$ task --list
task: Available tasks for this project:
* build: 	Build the binary
* ci: 		Run all the tests and code checks
* cover: 	Run all the tests and opens the coverage report
* dev: 		Setup pre-commit
* docs:build: 	Build documentation
* docs:serve: 	Start documentation server
* fmt: 		gofmt and goimports all go files
* imgs: 	Download and resize images
* setup: 	Install dependencies
* test: 	Run tests
* todo: 	Show to-do items per file
```
=> feat: Replace Make with Task

Taskfile.yml
Hi,
i love `task` and I am happy to see #2557 is used in goreleaser.
This PR just changes the debs of the CI task because of:
```
Dependencies run in parallel, so dependencies of a task shouldn’t depend one another. If you want to force tasks to run serially take a look at the Calling Another Task section below.
```
https://taskfile.dev/#/usage?id=task-dependencies
and introduced the default task. So i can just call `task`
Hope its okay for you 😄
=> fix: taskfile: rewerite task order of ci and add default taks

.github/workflows/build.yml
according to [this](https://github.com/mvdan/github-actions-golang), this seems like a good idea to speed up tests/builds a bit
wdyt?
=> chore(ci): cache go-build results on github actions

USERS.md
Overview
---
This PR will add Ministry of Justice in the UK to the list of proud users of this tool. Using goreleaser dramatically  improves release time/velocity of our developers, which in turn improves the experience of the British public using digital justice tools and services.
Keep up the great work!
=> docs: Add Ministry of Justice UK to list of users

internal/pipe/sourcearchive/source.go, internal/pipe/sourcearchive/source_test.go, pkg/config/config.go, www/docs/customization/source.md
If applied, this change will add a `prefix_template` option to the source archive pipe. This allows the generated tarball to use a subdirectory for all files in the archive, as described in [`git-archive`](https://git-scm.com/docs/git-archive).
Currently, archives generated by the source archive step do not use a prefix, whereas traditionally the prefix of `{{ .ProjectName }}-{{ .Version }}/` is used. See https://github.com/twpayne/chezmoi/issues/1576.
The default prefix is none, to maintain compatibility for existing users.
=> feat(source): add prefix_template option

USERS.md
This adds a reference for [IRON](https://github.com/iron-security) which uses goreleaser for their Go projects.
=> chore: add iron security ref

internal/pipe/release/release.go
- renamed pipe to `scm release` to match our docs menu https://goreleaser.com/scm/github/
- avoid unneeded extra blocks
- fix bug that could happen when using gitea and gitlab + `ctx.Config.Release.Prerelease`
=> refactor: improve release defaults

internal/pipe/git/git.go, internal/pipe/mattermost/mattermost.go, internal/pipe/mattermost/mattermost_test.go, internal/pipe/reddit/reddit.go, internal/pipe/reddit/reddit_test.go, internal/pipe/slack/slack.go, internal/pipe/smtp/smtp.go, internal/pipe/teams/teams.go, internal/pipe/telegram/telegram.go, internal/pipe/twitter/twitter.go, internal/tmpl/tmpl.go, pkg/context/context.go
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
Co-authored-by: Erkan Zileli <erkan.zileli@trendyol.com>
Fixes #2625 
to support message templating while announcing for supported git providers such as GitHub, GitLab, Gitea
=> feat: add message template support for git providers

.goreleaser.yml, internal/pipe/nfpm/nfpm.go, internal/pipe/nfpm/nfpm_test.go, www/docs/customization/nfpm.md, www/docs/customization/templates.md
adds a new template variable on nfpm config with the result of [`ConventionalFileName`](https://github.com/goreleaser/nfpm/blob/v2.8.0/nfpm.go#L100) of each packager.
=> feat: nfpm conventional file name

Dockerfile
we are planning to use the goreleaser image in the release pipeline for some projects in `sigstore` but that image is lacking the `cosign` tool to sign the blobs and images.
Instead of download every time during the release process, it might be good to have that already present in the image 😄 
If this gets merged and when we release cosign v1.3.0 which will include the tool for arm65 then we update this to include for the arm64 image as well
If you do not agree feel free to close this PR.
thanks!
=> feat: add cosign tool in the goreleaser image

internal/artifact/artifact_test.go, internal/client/gitea_test.go, internal/gio/copy_test.go, internal/pipe/archive/archive_test.go, internal/pipe/brew/brew_test.go, internal/pipe/checksums/checksums_test.go, internal/pipe/docker/docker.go, internal/pipe/env/env_test.go, internal/pipe/mattermost/mattermost.go, internal/pipe/mattermost/mattermost_test.go, internal/pipe/nfpm/nfpm_test.go, pkg/config/config_test.go
`io/ioutil` is deprecated so i replaced it according to https://golang.org/doc/go1.16#ioutil
=> refactor: use os and io packages instead of io/ioutil

internal/pipe/sign/sign.go, internal/pipe/sign/sign_test.go, www/docs/customization/docker_sign.md, www/docs/customization/sign.md
Previously, `artifactName` would give you a path in the root of the repository, and `artifact` would lead to double-dist (`dist/dist/foo.pem`).
This PR ensures that filename and path are always correct.
This also removes from docs some sections that are not useful and/or should not be used.
refs  #2662
=> fix: ensure certificate is always within dist

internal/pipe/dist/dist.go
When using a custom distribution directory goreleaser outputs the commands/information using the default distribution directory `./dist`
This PR updates the strings to use the custom name if that is set, to avoid any confusion for the user when reading the logs
=> chore: update strings when using a custom distribution directory

Taskfile.yml
removing the `-s` flag since it's been removed in [`gofumpt v0.2.0`](https://github.com/mvdan/gofumpt/blob/master/CHANGELOG.md#020---2021-11-10)
=> chore: avoid task error on fmt

internal/pipe/changelog/changelog.go, internal/pipe/changelog/changelog_test.go, pkg/config/config.go, www/docs/customization/changelog.md
Fixes #2669 request from @blacktop
The implementation could look like this:
The example is in a test repo, with no commits so dont wonder in looks blant. And the `use` is set to `git` so no userids. You can change this if you want. So it looks like this:
I tried to follow the [guidance](https://www.conventionalcommits.org/en/v1.0.0/) from @aalmiray and sorted the commits in features, Bug fixes and Others. 
You need to follow the conventional commits rules `<type>[optional scope]: <description>` to end in the right group. `feat:` goes to `Features`, `fix:` goes to `Bug Fixes`, etc.
You can activate the grouping feature via the flag `group: true` in the `changlog` block of the goreleaser config.
Looking for your feedback!
=> feat: CHANGELOG categories

internal/pipe/changelog/changelog.go, internal/pipe/changelog/changelog_test.go
Made a few changes here:
- commits are now list items (someone asked this, I always wanted to do this, don't see why not as it looks better)
- refactor some code from #2670
- compile each regex only once
- rename method
- check if regex is valid and error otherwise
- also added a test for this
cc/ @dirien 
-------
```
* 81c53073a4d4b638cec836ccb6cee78052695b3a: feat(ci): add cosign public key to releases (#2636) (@erkanzileli)
* a94e28b77c40d0ff483f618e77d2defdc637e54f: feat(deps): bump golang from 1.17.2-alpine to 1.17.3-alpine (#2632) (@dependabot[bot])
* 1e718d2db0a612fe79e25292889c9ca10a97e563: Revert "fix: armv7 on linux is usually armv7l" (@caarlos0)
* c958e4cc5e18073116881a7dd79355ca9197871a: fix: changelog is too long (#2661) (@dirien)
* 048557efdb35d87f628ff1206ebff48b44229075: …
```
=> feat: make each changelog commit a list item

.goreleaser.yml, internal/pipe/changelog/changelog.go, internal/pipe/changelog/changelog_test.go, internal/pipe/git/git.go, internal/pipe/git/git_test.go, internal/tmpl/tmpl.go, internal/tmpl/tmpl_test.go, pkg/context/context.go, www/docs/customization/templates.md
Previous tag will be available as a template field. It will be empty if there are no previous tag (e.g. first ever release of a repo).
Changelog still works by using the first commit on those cases (as it already does today).
=> feat: allow to use .PreviousTag on templates

internal/pipe/git/git.go, internal/pipe/git/git_test.go, internal/tmpl/tmpl.go, pkg/context/context.go, www/docs/customization/templates.md
If applied, this commit will make `git describe --dirty --tags --always` available under the `context.GitInfo` as `Summary` and ultimately available in template replacements as `.Summary`
This change is being made because the above commands output is very useful as an alternative for build outputs.
This command when run on a tagged commit will return just the tag, when run on any other commit, it will provide `TAG-N-COMMIT` where N is the number of commits since last tag, and commit is the short commit id.
I would be happy to rename this to any other field that makes more sense, I prefer the `TAG-N-COMMIT` vs `TAG-SNAPSHOT-COMMIT` format, this just allows options. With further search and replace, you can change the `-` to `.` or `+`, depending on your semver desires.
Simple
```yaml …
```
=> feat: add git summary support (aka git describe --dirty --tags --always)

internal/git/config.go, internal/git/config_test.go
closes #2704
there's a test covering the exact example commented in this else branch, and it still passes after it is removed.
Also added more tests to increase test coverage a bit.
=> fix: git url with port

cmd/build.go, internal/artifact/artifact.go, internal/artifact/artifact_test.go, internal/golden/golden.go, internal/pipe/artifacts/artifacts.go, internal/pipe/artifacts/artifacts_test.go, internal/pipe/artifacts/testdata/TestArtifacts.json.golden, internal/pipeline/pipeline.go
=> feat: store artifact list into dist/artifacts.json

pkg/config/config.go
=> fix: jsonschema build ignore casing

www/docs/quick-start.md
after testing, this is what I found
not sure this is the exact way we should write this but it's a start
add additional test to the quickstart docs
as I am a security minded person, and the goreleaser doesn't state what permissions are required, I thought it would be wise to write in the quickstart docs
=> docs(quickstart): minimum github_token perms

internal/pipe/git/git.go, internal/pipe/git/git_test.go, internal/testlib/git.go, internal/tmpl/tmpl.go, internal/tmpl/tmpl_test.go, pkg/context/context.go, www/docs/customization/templates.md
this adds a new template field, `.Subject`, which will contain the annotated tag message if tag is annotated, or the message of the commit it points to.
This can be used on `release.name_template`, for example 🤘
closes #2726
=> feat: get annotated tag message

internal/logext/writer.go, internal/pipe/sign/sign.go, pkg/config/config.go, www/docs/customization/docker_sign.md, www/docs/customization/sign.md
by default, when signing, output is only shown when goreleaser is running in debug mode.
this adds a config that allows to always log the output... so if you use, say, cosign with their oidc (which will print an URL you'll need to visit to auth), you won't need to run with `--debug` anymore.
=> feat: allow to always log signing output

pkg/config/config.go, www/docs/static/schema.json
In the JSON schema, the `keep-existing` value [was missing](https://github.com/goreleaser/goreleaser/blob/167d95e67fe0266fd75bc5dffc949f5db550dc73/www/docs/static/schema.json#L1716) for `ReleaseNotesMode`.
```
"mode": {
"enum": [
"append",
"prepend",
"replace"
],
"type": "string",
"default": "keep-existing"
}
```
I fixed a typo in the struct tags and rebuilt the schema (`task schema:generate`). This adds `keep-existing` in the enum.
Note: [`schema-pro.json`](https://github.com/goreleaser/goreleaser/blob/167d95e67fe0266fd75bc5dffc949f5db550dc73/www/docs/static/schema-pro.json#L1884) is also affected, but I don't know how it is generated.
=> Fix JSON schema for ReleaseNotesMode

internal/artifact/artifact.go, internal/artifact/artifact_test.go, internal/artifact/testdata/TestMarshalJSON.json.golden, internal/pipe/scoop/scoop_test.go
since type is an int, 0 is ignored, so we need to start at 1
=> fix: artifacts.json when type is archive

internal/logext/writer.go
we are actually changing the padding of the default logger... this should improve log output a bit.
=> fix: logext shouldnt mess with default logger
